### PR TITLE
Add new fingerprint for Avatto ZDMS16-1

### PR DESCRIPTION
**Pull request by RoelVB**
This PR adds a new fingerprint for the Avatto ZDMS16-1.

Fixes https://github.com/Koenkk/zigbee2mqtt/issues/24946, https://github.com/Koenkk/zigbee2mqtt/issues/24822

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by curtash** [comment]
Please can `_TZE204_2cyb66xl` be added too. Sorry I would do it myself but I'm not sure how...

I've just received the exact same AVATTO 1ch dimmer with another fingerprint, I've successfully tested it using a local converter. 

This is the local converter that I'm using currently:

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const utils = require('zigbee-herdsman-converters/lib/utils');


const definition = {
	fingerprint: tuya.fingerprint('TS0601', ['_TZE204_5cuocqty', '_TZE204_nqqylykc', '_TZE204_2cyb66xl']),
	model: 'ZDMS16-1',
    vendor: 'AVATTO',
    description: 'Zigbee 1 channel Dimmer CURTIS',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    configure: tuya.configureMagicPacket,
    exposes: [
        tuya.exposes.lightBrightnessWithMinMax(),
        tuya.exposes.countdown(),
        tuya.exposes.switchType(),
        e.power_on_behavior().withAccess(ea.STATE_SET),
    ],
    meta: {
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverter.onOff, {skip: tuya.skip.stateOnAndBrightnessPresent}],
            [2, 'brightness', tuya.valueConverter.scale0_254to0_1000],
            [3, 'min_brightness', tuya.valueConverter.scale0_254to0_1000],
            [4, 'switch_type', tuya.valueConverter.switchType2],
            [5, 'max_brightness', tuya.valueConverter.scale0_254to0_1000],
            [6, 'countdown', tuya.valueConverter.countdown],
            [14, 'power_on_behavior', tuya.valueConverter.powerOnBehaviorEnum],
        ],
    },
};

module.exports = `definition;
```

**Comment by Koenkk** [comment]
@curtash added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by curtash** [comment]
Perfect, thanks very much.

**Comment by mrmaximas** [comment]
@curtash hi! is it really impossible to read the state of the dimmer?

**Comment by MalibuBanane** [comment]
I recieved a Avatto ZDMS16-1 today and it isn't recoginiced properly in my homeassisant zigbee2mqtt addon.

The Zigbee Manufacturer seems now to be: _TZE284_nqqylykc

**Pull request merged**
