### PR TITLE
Update ledvance.js

### PR DESCRIPTION
**Pull request by dhanukapulkit**
Added the new B40 E14 and PAR16 50 dimmable lamps with the correct indentions

### CODE REVIEW

**Comment by dhanukapulkit** [comment]
How can i remove this indenting errors? i checked a lot but it still shows the errors with ci.

**Comment by Koenkk** [comment]
Can you allow me edit access? If not then copy paste the following:

```js
    {
        zigbeeModel: ['B40 DIM T'],
        model: '4058075729063',
        vendor: 'LEDVANCE',
        description: 'SMART+ Classic B40 E14 dimmable white',
        extend: extend.ledvance.light_onoff_brightness(),
        ota: ota.ledvance,
    },
    {
        zigbeeModel: ['PAR16 DIM T'],
        model: '4058075729148',
        vendor: 'LEDVANCE',
        description: 'SMART+ Spot PAR16 50 GU10 dimmable white',
        extend: extend.ledvance.light_onoff_brightness(),
        ota: ota.ledvance,
    },
    {
        zigbeeModel: ['P40 DIM T'],
        model: '4058075729100',
        vendor: 'LEDVANCE',
        description: 'SMART+ Classic P40 E14 dimmable white',
        extend: extend.ledvance.light_onoff_brightness(),
        ota: ota.ledvance,
    },
```

Note to self; after this merge https://github.com/Koenkk/zigbee2mqtt.io/pull/1553

**Comment by dhanukapulkit** [comment]
You have the editing access, but i also copy pasted the same. But still the ci failed :(
image

**Comment by dhanukapulkit** [comment]
Now the indentions are implemented correctly and it should work.

**Comment by Koenkk** [comment]
great, thanks!

**Pull request merged**
