### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by xsp1989**
fix bug

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `ZB-RS485.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by xsp1989** [comment]
Thank you very much. I have submitted the picture last time, but the model does not correspond to the picture, resulting in the wrong product picture being displayed.

**Comment by Koenkk** [comment]
Could you then make a new PR to fix this?

**Comment by xsp1989** [comment]
> Could you then make a new PR to fix this?

Do I need to submit a PR again at [https://github.com/Koenkk/zigbee2mqtt.io](https://github.com/Koenkk/zigbee2mqtt.io)  ？
I changed the model RS485 to ZB-RS485, but the RS485 is displayed on https://www.zigbee2mqtt.io/devices/RS485.html instead of the ZB-RS485.png I submitted. 

This is the PR I submitted ZB-RS485.png：
https://github.com/Koenkk/zigbee2mqtt.io/commit/65879aa23446c7d7efc8d704bbe1fc0eaac94dcc#diff-638a8f72c86f4fa138e9d177873254dc39c546aac9180e8d115f2251e5a3c74d

How should I fix this bug?

**Comment by Koenkk** [comment]
Ah it's correct already, thanks!

**Comment by xsp1989** [comment]
> Ah it's correct already, thanks!

Thank you very much for your help, but there are still some problems. I have displayed the correct device in Z2M, but when I click on the device model, the page does not exist. When searching through the manufacturer easyiot, it still shows RS485 instead of ZB-RS485.

This is a wrong model link:
https://www.zigbee2mqtt.io/devices/RS485.html
This is a correct model link, but the corresponding device page cannot be found：
https://www.zigbee2mqtt.io/devices/ZB-RS485.html#easyiot-zb-rs485

**Comment by Koenkk** [comment]
That will be fixed with the next z2m release, the change of this PR is not in the z2m release yet.

**Pull request merged**
