### PR TITLE
Support OTA for Legrand 067771, 067772

### PR DESCRIPTION
**Pull request by EXP-Carthage**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by SilentT-FR** [comment]
Hi @agsola i thinks its a same error we have with powersocket
the zigbee stack version was not the same onfile detection by the nodejsscript

https://github.com/Koenkk/zigbee-OTA/issues/328

and legrand as be aware about the problem : https://developer.legrand.com/forums/topic/nlc-firmware-version/#post-9734

**Comment by SilentT-FR** [comment]
In fact its was already upgraded and to the last firmware

Just Z2M have fetched on your device report version 0 and on the update file a version 1
so its install the version 1 on your product, 

but after the upgrade the device report 2 

Like 1 and 2 was two number and 2 is upper than 1, so after OTA upgrade Z2M want to verify new OTA update and failed because 2 is upper than 1

yes its complicated

**Comment by SilentT-FR** [comment]
you can see my complete test here
i have the same issue but with NLP and NLC product

https://github.com/Koenkk/zigbee2mqtt/issues/17709#issuecomment-1588148332

**Comment by SilentT-FR** [comment]
its same devices ? you can precise the legrand device number of it ?

**Comment by SilentT-FR** [comment]
and on "state" tab the 

```
    "update": {
        "installed_version": 4867071,
        "latest_version": 5128707,
        "state": "available"
    },
```

**Comment by SilentT-FR** [comment]
For the updated one in 46 can you report the  
    "update": {
        "installed_version": 3490307,
is it for Legrand to prevent a non corresponding version between zstack and filename/onfile

for the second one you have this error : 
Error 2023-07-01 21:46:48Update of 'XXXXX' failed (Device didn't respond to OTA request)

For me 2 option/opinion

Reboot them electricaly or if you can reapair it

Or but i cant be sure, it can be updated because it have a very old version and not on firmware minimum required to accept v70

**Comment by SilentT-FR** [comment]
> even physically pressing the device to be "aware"

yes good technique

**Comment by Laxilef** [comment]
Hi
On firmware 0034 the same problem (Device didn't respond to OTA request), devices are not updated

**Comment by TRuHa83** [comment]
I have seen that they have given OTA support to Legrand devices, wonderful!

I have already updated two devices but I have a third, much older that does not give me the option to update. Would it be possible to force the update?
Attached image

Screenshot_20230711_190436

As you can see devices 5 and 6 are updated to 0046 but device 7 gives a very rare version and does not give me the option to update.

Any ideas?

**Comment by SilentT-FR** [comment]
I think very old version yeah, 
going to state of your product and verify this things

```
    "update": {
        "installed_version": 3490307,
        "latest_version": 4604419,
        "state": "available"
    },
```
but you can test to fork this file https://github.com/Koenkk/zigbee-OTA/blob/master/index.json and modify the line corresponding to your product 
i thinks this one https://github.com/Koenkk/zigbee-OTA/blob/1032e892cb6b60423069fa8f9d3a839b4c9a017d/index.json#L2698

to make a number upper than you have installed_version and say to z2m to use your file in settings

**Comment by SilentT-FR** [comment]
@Laxilef @agsola version v72 is out, i prepare the pull request, 🤞 if its work with its

**Comment by SilentT-FR** [comment]
https://static.developer.legrand.com/files/2023/05/1021-000e-00464203-NLF.zip 🤦

**Comment by TRuHa83** [comment]
> I think very old version yeah, going to state of your product and verify this things
> 
> ```
>     "update": {
>         "installed_version": 3490307,
>         "latest_version": 4604419,
>         "state": "available"
>     },
> ```
> 
> but you can test to fork this file https://github.com/Koenkk/zigbee-OTA/blob/master/index.json and modify the line corresponding to your product i thinks this one https://github.com/Koenkk/zigbee-OTA/blob/1032e892cb6b60423069fa8f9d3a839b4c9a017d/index.json#L2698
> 
> to make a number upper than you have installed_version and say to z2m to use your file in settings

I have been doing tests as you have told me, which now shows me the following error.

`2023-07-11 23:01:14 Update of 'switch_salon' failed (File version mismatch)`

I understand that yours would be to be able to force a firmware to be loaded regardless of the version.

This is the current version of the device.
```
"update": {
        "installed_version": 54532608,
        "latest_version": 4604419,
        "state": "idle"
    },
```

**Comment by SilentT-FR** [comment]
hmmm z2m verify the file version i thinks we can bypass it

**Comment by SilentT-FR** [comment]
067773,067774 => I make PR for z2m support OTA, because yes we have the firmware file
certainly a mistake of me

for the 067776 => i already make possible
https://github.com/Koenkk/zigbee-herdsman-converters/pull/5936/files#diff-a810ad77a161d2ba313b432723c2463b8474fba942e347409b7dc387de893554R141

**Comment by SilentT-FR** [comment]
🤞  for the 067773,067774 ;)

**Comment by SilentT-FR** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/5963 Done

**Comment by TRuHa83** [comment]
> hmmm z2m verify the file version i thinks we can bypass it 

Hello, do you know how I could update my devices with firmware that is too obsolete? 🤔

**Pull request merged**
