### PR TITLE
LELLKI WK36 Plug EU with Power Monitor

### PR DESCRIPTION
**Pull request by DavidFFerreira**
LELLKI WK36 Plug EU with Power Monitor

### CODE REVIEW

**Comment by DavidFFerreira** [comment]
@Koenkk  can u help me? cannot figure it out the error lol

**Comment by Koenkk** [comment]
Can we merge this with https://github.com/Koenkk/zigbee-herdsman-converters/blob/b1131b9b46f15ca30613a938536c23f3e4c8208e/devices/tuya.js#L1430 ?

**Comment by DavidFFerreira** [comment]
> Can we merge this with
> 
> https://github.com/Koenkk/zigbee-herdsman-converters/blob/b1131b9b46f15ca30613a938536c23f3e4c8208e/devices/tuya.js#L1430
> 
> ?

the device have LELLKI and WK36 identified all over, can we do a separate thing?

**Comment by smulle48** [comment]
No reason to reinvent the wheel. It's just another tuna white label :-)

https://ae01.alicdn.com/kf/H5d078d9315544e99939ec719a2c01191o/LELLKI-Tuya-Smart-Life-Plug-16A-EU-Zigbee-Socket-Outlet-Timer-Power-Monitor-With-Google-Assistant.jpg_Q90.jpg

**Pull request closed without merging**
