### PR TITLE
chore(master): release 19.56.0

### PR DESCRIPTION
**Pull request by Koenkk**
:robot: I have created a release *beep* *boop*
---

### Features

* **add:** QAT42Z3, QAT42Z1, QAT42Z2, QARZ1DC, QARZDC1LR, QARZ2LR, QARZ3LR, QARZ4LR, QAT42Z1H, QAT42Z2H, QAT42Z3H, QAT44Z6H, QAT44Z4H, QADZ1, QADZ2 ([#7610](https://github.com/Koenkk/zigbee-herdsman-converters/issues/7610)) ([d21ed6a](https://github.com/Koenkk/zigbee-herdsman-converters/commit/d21ed6a222be5e82334211929568969525ad8d0f))
* Enable modern OTA for BTH-RM & minor cleanup ([#7633](https://github.com/Koenkk/zigbee-herdsman-converters/issues/7633)) ([53def67](https://github.com/Koenkk/zigbee-herdsman-converters/commit/53def671536f9ba0289e99d2dece68c03ada645b))

### Bug Fixes

* Add "off" fan mode for Inovelli ([#7641](https://github.com/Koenkk/zigbee-herdsman-converters/issues/7641)) ([00d8880](https://github.com/Koenkk/zigbee-herdsman-converters/commit/00d8880d0f46bc82b4f6b7c9be20f7371da8eaf0))
* Fixes for TICMeter ([#7640](https://github.com/Koenkk/zigbee-herdsman-converters/issues/7640)) ([40fa490](https://github.com/Koenkk/zigbee-herdsman-converters/commit/40fa490bbc9eb2114506806f87f0611d85c52ad9))
* Improve support of Sunricher ZG2858A ([#7637](https://github.com/Koenkk/zigbee-herdsman-converters/issues/7637)) ([6fbad86](https://github.com/Koenkk/zigbee-herdsman-converters/commit/6fbad86bf3270b0fb79577a644dcb77dabc785bc))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by Koenkk** [comment]
:robot: Release is at https://github.com/Koenkk/zigbee-herdsman-converters/releases/tag/v19.56.0 :sunflower:

**Comment by queroautomacao** [comment]
Testing qa.ts definitions but it does not work, devices are not supported, or supported by different tuya.ts definition. Is there something I am missing to use the definitions? Testing dev branch in docker container.

**Comment by Koenkk** [comment]
What zigbee herdsman converters version shows in the z2m frontend?

**Comment by queroautomacao** [comment]
> What zigbee herdsman converters version shows in the z2m frontend?

Frontend version
0.7.2
19.56.0
0.50.0

**Pull request merged**
