### PR TITLE
feat: support for PO-BOCO-ELEC

### PR DESCRIPTION
**Pull request by Applelo**
Add support for [PO-BOCO-ELEC device](https://powernity.fr/wp-content/uploads/2024/11/PO-BOCO-ELEC_NOTICE_V04.pdf), a power wire device controlling heater.
The same device is available with [Xanlite](https://www.xanlite-store.com/fr/thermostats/1877-boitier-de-pilotage-connecte-pour-radiateur-electrique-systeme-thermostats-connectes-3700619439334.html) trademark but I don't know the fingerprint.

Tuya datapoints:  https://docs.google.com/spreadsheets/d/1-eYgSqdD2n82m-0-rMAVLv9gOyj_rSVTCMnZdgPtNOo/edit?usp=sharing

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by lsadauskas** [comment]
Hello. I think that there is a confusion. [PO-BOCO-ELEC device](https://powernity.fr/wp-content/uploads/2024/11/PO-BOCO-ELEC_NOTICE_V04.pdf) is a controller, while https://github.com/Koenkk/zigbee-herdsman-converters/issues/8245 is a thermostat. I tried to implement the connection but this is what the logs say: 

warning 2025-01-25 11:08:11z2m: Device '0xa4c138ffaf83c819' with Zigbee model 'TS0601' and manufacturer name '_TZE284_tbgecldg' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by Applelo** [comment]
I didn't have the valve thermostat so yeah this implement the PO-BOCO-ELEC and not the KZTETHEAU device.

**Comment by reguiny** [comment]
Here is the convertor for the trv valve:-

const exposes = require('zigbee-herdsman-converters/lib/exposes.js');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya.js');
const localValueConverter = {
   divideBy2: tuya.valueConverterBasic.divideBy(2)}


const definition = {

  fingerprint: [
      {
          modelID: 'TS0601',
          manufacturerName: '_TZE284_tbgecldg',
      },
  ],
  model: 'TS0601_thermostat',
  vendor: 'Powernity',
  description: 'Radiator valve with thermostat',
      whiteLabel: [
          { vendor: 'POWERNITY', model: 'KZTETHEAU' },
      ],
  fromZigbee: [tuya.fz.datapoints],
  toZigbee: [tuya.tz.datapoints],
  onEvent: tuya.onEventSetTime, // Add this if you are getting no converter for 'commandMcuSyncTime'
  configure: tuya.configureMagicPacket,
  exposes: [
          e
              .climate()
              .withPreset(['auto', 'manual', 'holiday'])
              .withLocalTemperature(ea.STATE)
              .withSetpoint('current_heating_setpoint', 0, 29.5, 0.5, ea.STATE_SET)
              .withLocalTemperatureCalibration(-9, 9, 0.1, ea.STATE_SET),
          e.comfort_temperature().withValueMin(5).withValueMax(30),
          e.eco_temperature().withValueMin(5).withValueMax(30),
          e.holiday_temperature().withValueMin(0).withValueMax(30),
          e.window_detection(),
          e.open_window_temperature().withValueMin(5).withValueMax(25),
          exposes.numeric('open_window_time').withValueMin(0).withValueMax(60).withUnit('m'),
          e.binary('boost_heating', ea.STATE_SET, 'ON', 'OFF'),
                ...tuya.exposes.scheduleAllDays(ea.STATE, 'HH:MM/C'),
          e.child_lock(),
          e.battery().withUnit('%'),
          tuya.exposes.errorStatus(),
  ],
  meta: {
      tuyaDatapoints: [
      [2, 'preset', tuya.valueConverterBasic.lookup({ auto: tuya.enum(0), manual: tuya.enum(1), holiday: tuya.enum(2)})],
      [16, 'current_heating_setpoint', localValueConverter.divideBy2],
      [24, 'local_temperature', tuya.valueConverter.divideBy10],
      [30, 'child_lock', tuya.valueConverter.lockUnlock],
      [34, 'battery',  tuya.valueConverterBasic.scale(0, 100, 50, 150)],
      [45, 'error_status', tuya.valueConverter.raw],
      [101, 'comfort_temperature', localValueConverter.divideBy2],
      [102, 'eco_temperature', localValueConverter.divideBy2],
      [103, 'holiday_start_stop', tuya.valueConverter.thermostatScheduleDayMultiDP2],
      [104, 'local_temperature_calibration', tuya.valueConverter.localTempCalibration1],
      [105, 'Temperature setting_Auto', localValueConverter.divideBy2],
      [106, 'boost_heating', tuya.valueConverter.onOff],
      [107, 'window_detection', tuya.valueConverter.onOff],
      [109, 'schedule_monday', tuya.valueConverter.thermostatScheduleDayMultiDP2],
      [110, 'schedule_tuesday', tuya.valueConverter.thermostatScheduleDayMultiDP2],
      [111, 'schedule_wednesday', tuya.valueConverter.thermostatScheduleDayMultiDP2],
      [112, 'schedule_thursday', tuya.valueConverter.thermostatScheduleDayMultiDP2],
      [113, 'schedule_friday', tuya.valueConverter.thermostatScheduleDayMultiDP2],
      [114, 'schedule_saturday', tuya.valueConverter.thermostatScheduleDayMultiDP2],
      [115, 'schedule_sunday', tuya.valueConverter.thermostatScheduleDayMultiDP2],
      [116, 'open_window_temperature', localValueConverter.divideBy2],
      [117, 'open_window_time', tuya.valueConverter.raw],
      [118, 'boost_time', tuya.valueConverter.countdown],   
      [119, 'holiday_temperature', tuya.valueConverter.divideBy10],
  
  ],      
  },
  extend: [
      // A preferred new way of extending functionality.
  ],

};

module.exports = definition;

**Comment by gbrunois** [comment]
I created a pull request here for the valve (PO-THCO-EAU), without the schedules : https://github.com/Koenkk/zigbee-herdsman-converters/pull/8729

**Comment by Samt43** [comment]
@Applelo @Koenkk : I just submitted a PR : https://github.com/Koenkk/zigbee-herdsman-converters/pull/11532 for Xanlite fingerprint

**Comment by Samt43** [comment]
@Applelo : Xanlite sensor is now handled on dev channel it's great ! I had a question concerning your integration : 
What does [Auto mode (enum)](https://www.zigbee2mqtt.io/devices/PO-BOCO-ELEC.html#auto-mode-enum) do ? For me changing this enum value do not have any effect.

I'm currently trying to manage the temperature using a thermostat in HA, but i seems to a=use thermostat i will need to create a switch ON (Confort) / OFF (antifrost) in some way...

**Comment by Applelo** [comment]
@Samt43 You can look into my tuya datapoints I have made (https://docs.google.com/spreadsheets/d/1-eYgSqdD2n82m-0-rMAVLv9gOyj_rSVTCMnZdgPtNOo/edit?usp=sharing). It relies on dates available (one entry for one day of the week). I have decode the payload (you can look into the other sheet available)

**Pull request merged**
