### PR TITLE
Fix MULTI-ZIG-SW

### PR DESCRIPTION
**Pull request by mortenmoulder**
I am no longer using input 1, but rather 2, 3, 4, and 5. This is because the device resets itself if input 1 is being held down for 10+ seconds.

### CODE REVIEW

**Comment by mortenmoulder** [comment]
`Duplicate zigbee model MULTI-ZIG-SW` fails because I am updating the definition. The product is not out yet, so nobody but me will experience any issues.

`Exposes access matches toZigbee` not sure what this means. I simply updated the name in Z2M so they look like this:
image

`Check if all exposes have a color temp range` doesn't look like this error is mine.

**Comment by Koenkk** [comment]
The keys of `multi_zig_sw_switch_type` should be updated (`switch_type_1`, `switch_type_2`)

**Comment by mortenmoulder** [comment]
@Koenkk Done. Thanks.

I'm having a hard time testing the stuff I modify in custom_devices_diy.ts. When I build the file and get the compiled .js files, Z2M cannot use that file as a custom converter. So I have to copy stuff bath and forth into my own .js file, and remove the TypeScript stuff from it.

Is there a guide to getting `npm run build` files to work with Z2M as custom converters?

**Comment by Koenkk** [comment]
Great, currently there is no guide but maybe we can support `ts` external converters in the future.

**Pull request merged**
