### PR TITLE
Tuya active reports

### PR DESCRIPTION
**Pull request by drzony**
Companion for https://github.com/Koenkk/zigbee-herdsman/pull/337

I've updated:
- Fantem ZB003X to use the new type in cluster, waiting for confirmation in: #2071 
- Tuya switches which used a combo of defined and 'raw' message types

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by dsantos21** [comment]
Sorry @drzony, i didn't see your message before!

Heres an example of fantem debug:

zigbee-herdsman-converters:FantemZB003X: Unrecognized DP #110 with data {"status":0,"transid":0,"dp":110,"datatype":2,"fn":0,"data":{"type":"Buffer","data":[0,0,0,100]}}

zigbee-herdsman-converters:FantemZB003X: Unrecognized DP #107 with data {"status":0,"transid":0,"dp":107,"datatype":2,"fn":0,"data":{"type":"Buffer","data":[0,0,0,245]}}

Now I've a lot of these messages!

**Comment by dsantos21** [comment]
Or would it be something like that?

Received Zigbee message from '0xxxxxxxxx', type 'commandActiveStatusReport', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,100],"type":"Buffer"},"datatype":2,"dp":110,"fn":0,"status":0,"transid":0}' from endpoint 1 with groupID 0

**Comment by drzony** [comment]
@dsantos21 Are you on latest dev, do you have any custom changes? The unrecognized messages seem like a bug, since those DPs are defined in code.

**Comment by drzony** [comment]
@dsantos21 Fauond a bug, after the merge everything should be OK.

**Comment by dsantos21** [comment]
I'm using the latest release, 1.18.2. Please, let me know if i can help!

**Comment by drzony** [comment]
@dsantos21 after #2442 is merged you can try it out by using dev branch: https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html
After this the `Unrecognized DP` messages should be gone and the device should fully work

**Comment by dsantos21** [comment]
Ok, no problem! Motion, tamper and lux still works . As far as I can tell it seems to affect only temperature and humidity. 

What is this change about? :) a new way to read tuya data clusters? Just out of curiosity.

**Comment by drzony** [comment]
The change we are commenting adds a new cluster type (probably Tuya changed something and now a different ID is used to send data), before this ZB003X used "raw" cluster type (which was in fact has the same format as old "getCommand" but due to changed ID it was not recognized). #2442 fixes a mistyping on my part when implementing above change.

**Comment by dsantos21** [comment]
Thanks! Also, just to let you know: the change proposed in #2442 seems to be working fine!
So far I think that led enable/disable settings is inverted (on is off, off is on), but let me try a little while, could still be something here.

PS: Not sure if that's relevant, but right know there are two variants of Fantem ZB003X. I have both types, minor design change (plastic case). The new version doesn't bundle the USB cable anymore... :/

**Pull request merged**
