### PR TITLE
Add support for AIRAM CTR.U BX

### PR DESCRIPTION
**Pull request by realPy**
Add the support missing remote CTR.U BX.
Additionnal add a hold parameters in CTR U functions to easy implement brightness down and up on Hold.

### CODE REVIEW

**Comment by Koenkk** [comment]
I see the `direction` is already present in the `action` property, why add it another time?

**Comment by realPy** [comment]
When we want use the Hold brigthness, we track the brighness_Hold action.
When we have it we begin to send a payload with "on" and the brightness. The action is override with "on" , then "".
If we want to use the repeat until from homeassistant, we need an attribute that change only twice: One when its Hold, the second when it's release.

**Comment by Koenkk** [comment]
The problem I'm having with this is that the `hold` is persisted, which means that on e.g. a battery report `hold` will also be published. 

Also can you switch to the generic converters? The currently used converters (except `command_on` and `command_off`) are considered legacy. For e.g. `CTR_U_brightness_updown_click` use `command_step`

Note to self after this merge https://github.com/Koenkk/zigbee2mqtt/pull/4467

**Comment by realPy** [comment]
@Koenkk I use generic function and remove the hold parameter

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
