### PR TITLE
Add Shade Control MC-02 cover

### PR DESCRIPTION
**Pull request by adarazs**
Hello Koen,

Here's support for this cover device that I received to try out from its developer. I am using it for a few weeks now and it seems to be working well with this configuration, reporting battery and reacting to commands over Zigbee as it should.

I also submitted relevant documentation at https://github.com/Koenkk/zigbee2mqtt.io/pull/2056

Thank you for this awesome project, I really enjoy using Zigbee2MQTT! :) Let me know if I should fix anything in my PRs.

Best regards,
Attila

### CODE REVIEW

**Comment by adarazs** [comment]
I don't understand the error message in the failed check. Is it relevant to my PR? Can you help me understand it?

**Comment by Koenkk** [comment]
Can you provide a link to the device? (product page)

Note to self; after this merge https://github.com/Koenkk/zigbee2mqtt.io/pull/2056

**Comment by adarazs** [comment]
I have an early unit and the product page for the Zigbee version is not up yet. This is the page for the Bluetooth version: https://www.shade-control.com/products/shade-control-automate-your-roller-blinds (same hardware, different firmware).

We can wait until the page for the zigbee version is up if you prefer, according to the creator it should be done in a week or so.

**Comment by Koenkk** [comment]
I see, thanks!

**Pull request merged**
