### PR TITLE
split impl for revision FW for VES-ZB-SWI-015

### PR DESCRIPTION
**Pull request by devildant**

### CODE REVIEW

**Comment by devildant** [comment]
@chris-1243

**Comment by devildant** [comment]
hello @Koenkk  ,
 I am trying once again to make the change for the sunricher device, without impacting the previous versions of the fw, is this the right method?

However, I don't understand the current error, it doesn't seem to come from my code

**Comment by Koenkk** [comment]
That's the right method indeed.

@martyn-vesternet could you check this?

**Comment by martyn-vesternet** [comment]
I mentioned changing the model name over at https://github.com/Koenkk/zigbee-herdsman-converters/pull/6553 and it was suggested that this would cause code duplication.

Also, I think that the model name is used to match to devices listed on https://www.zigbee2mqtt.io/supported-devices/#v=Vesternet so would they no longer match there?

For this particular device (VES-ZB-SWI-015) it's only the configuration that requires changing depending on the firmware, so something like this might work:

```
{
        fingerprint: [{modelID: 'ON/OFF(2CH)', softwareBuildID: '2.5.3_r2'}, {modelID: 'ON/OFF(2CH)', softwareBuildID: '2.9.2_r3'}],
        model: 'VES-ZB-SWI-015',
        vendor: 'Vesternet',
        description: 'Zigbee 2 channel switch',
        fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering, fz.power_on_behavior, fz.ignore_genOta],
        toZigbee: [tz.on_off, tz.power_on_behavior],
        exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'), e.power(), e.current(),
            e.voltage(), e.energy(), e.power_on_behavior(['off', 'on', 'previous'])],
        whiteLabel: [{vendor: 'Sunricher', model: 'SR-ZG9101SAC-HP-SWITCH-2CH'}],
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2};
        },
        meta: {multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint1 = device.getEndpoint(1);
            const endpoint2 = device.getEndpoint(2);            
            await reporting.bind(endpoint1, coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(endpoint2, coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(endpoint1);
            await reporting.onOff(endpoint2);
            if (device && device.softwareBuildID == '2.9.2_r3') {
                const endpoint11 = device.getEndpoint(11);
                await reporting.bind(endpoint11, coordinatorEndpoint, ['haElectricalMeasurement', 'seMetering']);
                await reporting.readEletricalMeasurementMultiplierDivisors(endpoint11);
                await reporting.activePower(endpoint11);
                await reporting.rmsCurrent(endpoint11, {min: 10, change: 10});
                await reporting.rmsVoltage(endpoint11, {min: 10});
                await reporting.readMeteringMultiplierDivisor(endpoint11);
            }
            else if (device && device.softwareBuildID == '2.9.3_r2') {
                await reporting.bind(endpoint1, coordinatorEndpoint, ['haElectricalMeasurement', 'seMetering']);                
                await reporting.readEletricalMeasurementMultiplierDivisors(endpoint1);
                await reporting.activePower(endpoint1);
                await reporting.rmsCurrent(endpoint1, {min: 10, change: 10});
                await reporting.rmsVoltage(endpoint1, {min: 10});
                await reporting.readMeteringMultiplierDivisor(endpoint1);
                await reporting.currentSummDelivered(endpoint1);
            }
        },
    },
```

This is currently on my todo list for testing, I'm just short on time at the moment unfortunately.

**Comment by martyn-vesternet** [comment]
@devildant there's an external converter at https://github.com/vesternet/zigbee2mqtt-herdsman-converters which should fix this issue now, it should hopefully configure the device correctly during pairing based on its reported firmware version.

It seems to work OK for me on the two versions of test device that I have here, perhaps you can check it on yours?

**Comment by devildant** [comment]
> @devildant there's an external converter at https://github.com/vesternet/zigbee2mqtt-herdsman-converters which should fix this issue now, it should hopefully configure the device correctly during pairing based on its reported firmware version.
> 
> It seems to work OK for me on the two versions of test device that I have here, perhaps you can check it on yours?

Hi,

I don't have time to test at the moment, but I see the code and for me it's OK for 015

**Comment by martyn-vesternet** [comment]
@devildant this PR can be closed since the issue was address in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6991

**Pull request closed without merging**
