### PR TITLE
Add "discovery" mode for Xiaomi ZNCLDJ12LM

### PR DESCRIPTION
**Pull request by VisualGadget**
Add "discovery" mode for Xiaomi ZNCLDJ12LM to calibrate end points. This PR fixes my issue home-assistant/core#37943.

Use case for my solution to calibrate curtains after mains loss (automations.yaml):
```
- alias: Calibrate curtains
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/br_cover/set
      payload: "{'discovery': true}"
  - service: cover.close_cover
    entity_id:
    - cover.br_cover
  - delay:
      seconds: 13
  - service: cover.open_cover
    entity_id:
    - cover.br_cover
```

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks, can you also make a PR for https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/devices/ZNCLDJ12LM.md ?

Out of interest how does this work? Is it a matter of sending this command and the curtain will calibrate itself automatically? (perhaps it should be called `calibrate` instead?)

**Comment by VisualGadget** [comment]
I have doubts about the correct model description. I have a "new" version of ZNCLDJ12LM that reports itself as "Aqara B1 curtain motor (ZNCLDJ12LM) by Xiaomi".

2020-07-24_00h21_38

Physically it looks different:

9fdf3d90-ca73-4170-b9bd-406c08219334

22909371-627a-40ff-82f3-99cd686adbff

There is an optional attachable battery you can barely see on pictures. And curtain has no persistent memory for settings. So when it is used without battery (it's my case) it loses configuration when power is lost. When you put curtain in "discovery" mode it writes down future closed and opend extremal positions. You need to close and open it fully once to finish calibration procedure. So putting curtain to discovery mode is not enough to calibrate it. You see in my automation example all the necessary steps.
Should that hardware be marked as an another version of ZNCLDJ12LM? Unfortunately I don't have original ZNCLDJ12LM. I haven't seen similar complains about calibration for original ZNCLDJ12LM, it may behave differently.

I personally lean more towards "discovery mode" because "calibrate" presumes action in my opinion.

**Comment by Koenkk** [comment]
Discover mode is better indeed, does it look like a ZNCLDJ11LM ? (https://www.zigbee2mqtt.io/devices/ZNCLDJ11LM.html)

Note to self after this merge: https://github.com/Koenkk/zigbee2mqtt.io/pull/352

**Comment by VisualGadget** [comment]
Discover mode is implemented for ZNCLDJ11LM as reset_move option. We can unify options for ZNCLDJ11LM and ZNCLDJ12LM. state, position and reverse_direction are already equal. ZNCLDJ11LM hand_open is the same as ZNCLDJ12LM auto_close. I don't like "auto_close" name because automatic movement starts by hand move. It also may be opening, not closing.  ZNCLDJ11LM reset_move is my ZNCLDJ12LM discovery command.
The final option set for the both curtains is:
reverse_direction
hand_open
reset_move (or reset_limits, discovery, your variant?).

**Comment by Koenkk** [comment]
Sounds good, do you know how the discovery/reset_limits is called in the Xiaomi app? Preferable keep the naming consistent with that.

Instead of 3 separate converters, we can use 1 single converters for both ZNCLDJ11LM and ZNCLDJ12LM, so this replaces (while keeping backwards compatibility):  `ZNCLDJ12LM_options`, `ZNCLDJ11LM_options` and `ZNCLDJ12LM_control`.


```js
xiaomi_curtain_options: {
    key: ['options'],
    convertSet: async (entity, key, value, meta) => {
        const opts = {
            reverse_direction: false,
            hand_open: true,
            reset_limits: false, // TODO how is this called in the Xiaomi app?
            ...value,
        };

        // Legacy names
        if (value.hasOwnProperty('auto_close')) opts.hand_open = value.auto_close;
        if (value.hasOwnProperty('reset_move')) opts.reset_limits = value.reset_move;

        if (meta.mapped.model === 'ZNCLDJ12LM') {
            await entity.write('genBasic', {0xff28: {value: opts.reverse_direction, type: 0x10}}, options.xiaomi);
            await entity.write('genBasic', {0xff29: {value: !opts.auto_close, type: 0x10}}, options.xiaomi);

            if (opts.reset_limits) {
                await entity.write('genBasic', {0xff27: {value: 0x00, type: 0x10}}, options.xiaomi);
            }
        } else if (meta.mapped.model === 'ZNCLDJ11LM') {
            const payload = [
                0x07, 0x00, opts.reset_limits ? 0x01: 0x02, 0x00, opts.reverse_direction ? 0x01: 0x00, 0x04,
                !opts.hand_open ? 0x01: 0x00, 0x12,
            ];

            await entity.write('genBasic', {0x0401: {value: payload, type: 0x42}}, options.xiaomi);

            // hand_open requires a separate request with slightly different payload
            payload[2] = 0x08;
            await entity.write('genBasic', {0x0401: {value: payload, type: 0x42}}, options.xiaomi);
        } else {
            throw new Error(`xiaomi_curtain_options set called for not supported model: ${meta.mapped.model}`);
        }

        return {state: {options: opts}};
    },
    convertGet: async (entity, key, meta) => {
        if (meta.mapped.model === 'ZNCLDJ11LM') {
            await entity.read('genBasic', [0x0401], options.xiaomi);
        } else {
            throw new Error(`xiaomi_curtain_options get called for not supported model: ${meta.mapped.model}`);
        }
    },
},
```

Can you test?

**Comment by VisualGadget** [comment]
Xiaomi called this "Clear the position":
Screenshot_20200725-155835
To test your function I put call to it instead of tz.ZNCLDJ11LM_options and tz.ZNCLDJ12LM_options. All options are working good: reverse_direction, hand_open, reset_limits. I had to remove manually the old auto_close option from \share\zigbee2mqtt\state.json to get rid of it in the log. The only thing I don't like is that the option reset_limits is persistent and keeps True after calibration that makes no sense. Can you remove it from the log?
I don't have ZNCLDJ11LM to test unfortunately.

Also saw additional issues I believe not related to this update:
1. According to the sources I can use "state" to change curtain position. I have error if provide number as position value:
```
zigbee2mqtt:error 2020-07-25 19:11:48: Publish 'set' 'state' to 'br_cover' failed: 'TypeError: value.toLowerCase is not a function'
```
2. I publish the following:
```
topic: zigbee2mqtt/br_cover/set
payload: '{ "position": <X> }'
```
Every position change I have wrong position reports with values 2 and 0:
```
***Send to 0***
zigbee2mqtt:info  2020-07-25 18:56:25: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":2,"running":true,"linkquality":55,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
zigbee2mqtt:info  2020-07-25 18:56:25: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":true,"linkquality":52,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
zigbee2mqtt:info  2020-07-25 18:56:26: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":55,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
zigbee2mqtt:info  2020-07-25 18:56:26: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":55,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
***Send to 10***
zigbee2mqtt:info  2020-07-25 18:57:35: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":2,"running":true,"linkquality":42,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
zigbee2mqtt:info  2020-07-25 18:57:35: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":true,"linkquality":42,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
zigbee2mqtt:info  2020-07-25 18:57:36: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":10,"running":false,"linkquality":44,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
zigbee2mqtt:info  2020-07-25 18:57:36: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":10,"running":false,"linkquality":39,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
***Send to 100***
zigbee2mqtt:info  2020-07-25 18:58:09: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":2,"running":true,"linkquality":49,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
zigbee2mqtt:info  2020-07-25 18:58:09: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":true,"linkquality":49,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
zigbee2mqtt:info  2020-07-25 18:58:09: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":100,"running":false,"linkquality":47,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
zigbee2mqtt:info  2020-07-25 18:58:10: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":100,"running":false,"linkquality":49,"battery":50.5,"options":{"reverse_direction":false,"hand_open":true,"reset_limits":true}}'
***Send to 100 again***
Nothing here
```
Position trackbar in the Home Assistant jumping around because of that. Should I report these issues separately?

**Comment by Koenkk** [comment]
1. yes, with e.g. `zigbee2mqtt/br_cover/set`, `{"state": "open"}` , `{"state": "close"}`
2. can you check if this is fixed now (updated the pr)

**Comment by Koenkk** [comment]
also removed `reset_limits` from the state (you have to remove it from `data/state.json` manually first)

**Comment by VisualGadget** [comment]
1. No more error.
2. Ok. Set position works good. Two reports per move in the log. Positions 0 and 2 works too.
Options are broken. I tried to set hand_open to false:
```
zigbee2mqtt:info  2020-07-26 13:49:11: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":80,"running":false,"linkquality":52,"options":{"reverse_direction":false,"hand_open":true}}'
zigbee2mqtt:info  2020-07-26 13:49:11: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":80,"running":false,"linkquality":52,"options":{"reverse_direction":false,"hand_open":true}}'
***
topic: zigbee2mqtt/br_cover/set/options
payload: "{ 'hand_open': false }"
***
zigbee2mqtt:info  2020-07-26 13:53:45: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":80,"running":false,"linkquality":52,"options":{"0":"{","1":" ","2":"'","3":"h","4":"a","5":"n","6":"d","7":"_","8":"o","9":"p","10":"e","11":"n","12":"'","13":":","14":" ","15":"f","16":"a","17":"l","18":"s","19":"e","20":" ","21":"}","reverse_direction":false,"hand_open":true}}'
```

**Comment by Koenkk** [comment]
Can you post the debug logging of 2 ?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by VisualGadget** [comment]
hand_open option doesn't work due to mistake here: await entity.write('genBasic', {0xff29: {value: !opts.**auto_close**, type: 0x10}}, options.xiaomi); I've change it to **hand_open**.
All options work after that.
2. If I publish
```
topic: zigbee2mqtt/br_cover/set
payload: '{ "options": {"hand_open": false} }'
```
all OK. If I use another format
```
topic: zigbee2mqtt/br_cover/set/options
payload: '{"hand_open": false}'
```
it breaks options in the log.
Log:
```
info  2020-07-27 00:15:33: Logging to console and directory: '/share/zigbee2mqtt/log/2020-07-27.00-15-33' filename: log.txt
info  2020-07-27 00:15:34: Starting zigbee2mqtt version 1.14.2 (commit #unknown)
info  2020-07-27 00:15:34: Starting zigbee-herdsman...
info  2020-07-27 00:15:37: zigbee-herdsman started
info  2020-07-27 00:15:37: Coordinator firmware version: '{"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20190523}}'
info  2020-07-27 00:15:37: Currently 3 devices are joined:
info  2020-07-27 00:15:37: 0x00158d000236631a (0x00158d000236631a): ZNCZ02LM - Xiaomi Mi power plug ZigBee (Router)
info  2020-07-27 00:15:37: pr_cover (0x04cf8cdf3c75576f): ZNCLDJ12LM - Xiaomi Aqara B1 curtain motor  (EndDevice)
info  2020-07-27 00:15:37: br_cover (0x04cf8cdf3c756375): ZNCLDJ12LM - Xiaomi Aqara B1 curtain motor  (EndDevice)
info  2020-07-27 00:15:37: Zigbee: disabling joining new devices.
info  2020-07-27 00:15:37: Connecting to MQTT server at mqtt://core-mosquitto:1883
info  2020-07-27 00:15:40: Connected to MQTT server
info  2020-07-27 00:15:40: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2020-07-27 00:15:40: MQTT publish: topic 'zigbee2mqtt/pr_cover', payload '{"battery":50.5,"linkquality":31,"position":0,"running":false}'
info  2020-07-27 00:15:40: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":70,"running":false,"linkquality":28,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:15:40: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.14.2","commit":"unknown","coordinator":{"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20190523}},"log_level":"info","permit_join":false}'
info  2020-07-27 00:15:40: MQTT publish: topic 'homeassistant/switch/0x00158d000236631a/switch/config', payload '{"payload_off":"OFF","payload_on":"ON","value_template":"{{ value_json.state }}","command_topic":"zigbee2mqtt/0x00158d000236631a/set","state_topic":"zigbee2mqtt/0x00158d000236631a","json_attributes_topic":"zigbee2mqtt/0x00158d000236631a","name":"0x00158d000236631a_switch","unique_id":"0x00158d000236631a_switch_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d000236631a"],"name":"0x00158d000236631a","sw_version":"Zigbee2mqtt 1.14.2","model":"Mi power plug ZigBee (ZNCZ02LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
info  2020-07-27 00:15:40: MQTT publish: topic 'homeassistant/sensor/0x00158d000236631a/power/config', payload '{"unit_of_measurement":"W","icon":"mdi:flash","value_template":"{{ value_json.power }}","state_topic":"zigbee2mqtt/0x00158d000236631a","json_attributes_topic":"zigbee2mqtt/0x00158d000236631a","name":"0x00158d000236631a_power","unique_id":"0x00158d000236631a_power_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d000236631a"],"name":"0x00158d000236631a","sw_version":"Zigbee2mqtt 1.14.2","model":"Mi power plug ZigBee (ZNCZ02LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
info  2020-07-27 00:15:40: MQTT publish: topic 'homeassistant/sensor/0x00158d000236631a/temperature/config', payload '{"unit_of_measurement":"°C","device_class":"temperature","value_template":"{{ value_json.temperature }}","state_topic":"zigbee2mqtt/0x00158d000236631a","json_attributes_topic":"zigbee2mqtt/0x00158d000236631a","name":"0x00158d000236631a_temperature","unique_id":"0x00158d000236631a_temperature_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d000236631a"],"name":"0x00158d000236631a","sw_version":"Zigbee2mqtt 1.14.2","model":"Mi power plug ZigBee (ZNCZ02LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
info  2020-07-27 00:15:40: MQTT publish: topic 'homeassistant/sensor/0x00158d000236631a/consumption/config', payload '{"unit_of_measurement":"kWh","value_template":"{{ value_json.consumption }}","icon":"mdi:flash","state_topic":"zigbee2mqtt/0x00158d000236631a","json_attributes_topic":"zigbee2mqtt/0x00158d000236631a","name":"0x00158d000236631a_consumption","unique_id":"0x00158d000236631a_consumption_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d000236631a"],"name":"0x00158d000236631a","sw_version":"Zigbee2mqtt 1.14.2","model":"Mi power plug ZigBee (ZNCZ02LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
info  2020-07-27 00:15:40: MQTT publish: topic 'homeassistant/sensor/0x00158d000236631a/linkquality/config', payload '{"icon":"mdi:signal","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x00158d000236631a","json_attributes_topic":"zigbee2mqtt/0x00158d000236631a","name":"0x00158d000236631a_linkquality","unique_id":"0x00158d000236631a_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d000236631a"],"name":"0x00158d000236631a","sw_version":"Zigbee2mqtt 1.14.2","model":"Mi power plug ZigBee (ZNCZ02LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
info  2020-07-27 00:15:40: MQTT publish: topic 'homeassistant/cover/0x04cf8cdf3c75576f/cover/config', payload '{"command_topic":"zigbee2mqtt/pr_cover/set","position_topic":"zigbee2mqtt/pr_cover","set_position_topic":"zigbee2mqtt/pr_cover/set","set_position_template":"{ \"position\": {{ position }} }","value_template":"{{ value_json.position }}","json_attributes_topic":"zigbee2mqtt/pr_cover","name":"pr_cover_cover","unique_id":"0x04cf8cdf3c75576f_cover_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c75576f"],"name":"pr_cover","sw_version":"Zigbee2mqtt 1.14.2","model":"Aqara B1 curtain motor  (ZNCLDJ12LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
info  2020-07-27 00:15:40: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c75576f/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/pr_cover","json_attributes_topic":"zigbee2mqtt/pr_cover","name":"pr_cover_battery","unique_id":"0x04cf8cdf3c75576f_battery_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c75576f"],"name":"pr_cover","sw_version":"Zigbee2mqtt 1.14.2","model":"Aqara B1 curtain motor  (ZNCLDJ12LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
info  2020-07-27 00:15:40: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c75576f/linkquality/config', payload '{"icon":"mdi:signal","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/pr_cover","json_attributes_topic":"zigbee2mqtt/pr_cover","name":"pr_cover_linkquality","unique_id":"0x04cf8cdf3c75576f_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c75576f"],"name":"pr_cover","sw_version":"Zigbee2mqtt 1.14.2","model":"Aqara B1 curtain motor  (ZNCLDJ12LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
info  2020-07-27 00:15:40: MQTT publish: topic 'homeassistant/cover/0x04cf8cdf3c756375/cover/config', payload '{"command_topic":"zigbee2mqtt/br_cover/set","position_topic":"zigbee2mqtt/br_cover","set_position_topic":"zigbee2mqtt/br_cover/set","set_position_template":"{ \"position\": {{ position }} }","value_template":"{{ value_json.position }}","json_attributes_topic":"zigbee2mqtt/br_cover","name":"br_cover_cover","unique_id":"0x04cf8cdf3c756375_cover_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c756375"],"name":"br_cover","sw_version":"Zigbee2mqtt 1.14.2","model":"Aqara B1 curtain motor  (ZNCLDJ12LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
info  2020-07-27 00:15:40: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c756375/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/br_cover","json_attributes_topic":"zigbee2mqtt/br_cover","name":"br_cover_battery","unique_id":"0x04cf8cdf3c756375_battery_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c756375"],"name":"br_cover","sw_version":"Zigbee2mqtt 1.14.2","model":"Aqara B1 curtain motor  (ZNCLDJ12LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
info  2020-07-27 00:15:40: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c756375/linkquality/config', payload '{"icon":"mdi:signal","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/br_cover","json_attributes_topic":"zigbee2mqtt/br_cover","name":"br_cover_linkquality","unique_id":"0x04cf8cdf3c756375_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c756375"],"name":"br_cover","sw_version":"Zigbee2mqtt 1.14.2","model":"Aqara B1 curtain motor  (ZNCLDJ12LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
error 2020-07-27 00:15:40: No converter available for 'discovery' (true)
info  2020-07-27 00:15:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"entity_not_found","message":{"friendly_name":"cover.br_cover"}}'
error 2020-07-27 00:15:40: Entity 'cover.br_cover' is unknown
info  2020-07-27 00:15:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"entity_not_found","message":{"friendly_name":"Curtain"}}'
error 2020-07-27 00:15:40: Entity 'Curtain' is unknown
info  2020-07-27 00:18:34: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":53,"running":false,"linkquality":36,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:18:34: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":53,"running":false,"linkquality":36,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:19:44: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":20,"running":false,"linkquality":39,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:19:44: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":20,"running":false,"linkquality":42,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:20:04: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":10,"running":false,"linkquality":36,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:20:04: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":10,"running":false,"linkquality":39,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:20:40: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":10,"running":false,"linkquality":39,"options":{"reverse_direction":false,"hand_open":false},"battery":50.5}'
info  2020-07-27 00:21:06: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":16,"running":false,"linkquality":47,"options":{"reverse_direction":false,"hand_open":false},"battery":50.5}'
info  2020-07-27 00:21:06: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":16,"running":false,"linkquality":42,"options":{"reverse_direction":false,"hand_open":false},"battery":50.5}'
info  2020-07-27 00:21:24: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":16,"running":false,"linkquality":42,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:21:46: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":9,"running":false,"linkquality":31,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:21:48: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":28,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:21:49: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":44,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:22:26: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":44,"options":{"reverse_direction":true,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:22:55: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":90,"running":false,"linkquality":52,"options":{"reverse_direction":true,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:23:05: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":49,"options":{"reverse_direction":true,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:23:05: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":47,"options":{"reverse_direction":true,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:23:08: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":1,"running":true,"linkquality":49,"options":{"reverse_direction":true,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:23:08: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":15,"running":false,"linkquality":44,"options":{"reverse_direction":true,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:23:18: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":99,"running":false,"linkquality":42,"options":{"reverse_direction":true,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:23:18: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":99,"running":false,"linkquality":42,"options":{"reverse_direction":true,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:23:43: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":100,"running":false,"linkquality":57,"options":{"reverse_direction":true,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:23:43: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":100,"running":false,"linkquality":39,"options":{"reverse_direction":true,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:24:01: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":100,"running":false,"linkquality":39,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:24:25: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":100,"running":false,"linkquality":39,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:24:50: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":1,"running":true,"linkquality":34,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:24:50: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":255,"running":false,"linkquality":34,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:25:00: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":255,"running":false,"linkquality":49,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:25:00: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":255,"running":false,"linkquality":47,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:25:02: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":255,"running":false,"linkquality":42,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:25:12: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":47,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:25:12: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":49,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:25:22: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":1,"running":true,"linkquality":44,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:25:22: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":19,"running":false,"linkquality":44,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:25:32: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":99,"running":false,"linkquality":44,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:25:32: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":99,"running":false,"linkquality":52,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:25:34: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":86,"running":false,"linkquality":52,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:26:26: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":1,"running":true,"linkquality":49,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:26:26: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":47,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:26:37: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":100,"running":false,"linkquality":44,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:26:38: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":100,"running":false,"linkquality":47,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:27:14: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":49,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:27:15: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":49,"options":{"reverse_direction":false,"hand_open":true},"battery":50.5}'
info  2020-07-27 00:28:43: MQTT publish: topic 'zigbee2mqtt/br_cover', payload '{"position":0,"running":false,"linkquality":49,"options":{"0":"{","1":"\"","2":"h","3":"a","4":"n","5":"d","6":"_","7":"o","8":"p","9":"e","10":"n","11":"\"","12":":","13":" ","14":"f","15":"a","16":"l","17":"s","18":"e","19":"}","reverse_direction":false,"hand_open":true},"battery":50.5}'

```

**Comment by Koenkk** [comment]
1. updated
2. fixed this in zigbee2mqtt (update to latest dev branch: https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by VisualGadget** [comment]
I've switched to dev. Here is my testing results:
```
topic: zigbee2mqtt/br_cover/set
payload: '{ "options": {"hand_open": false }  }'

topic: zigbee2mqtt/br_cover/set
payload: '{ "options": {"hand_open": false, "reverse_direction": false }  }'
```
OK
```
topic: zigbee2mqtt/br_cover/set/options
payload: '{ "hand_open": true }'

topic: zigbee2mqtt/br_cover/set/options
payload: '{ "hand_open": true, "reverse_direction": true }'
```
OK
```
topic: zigbee2mqtt/br_cover/set/options/hand_open
payload: false
```
Not working.
Is there a place where I can see the latest code snapshot with all the changes from this thread? I'm fishing files one by one now.

**Comment by Koenkk** [comment]
The last thing is not an issue of this pr but of zigbee2mqtt (this second level depth was never intended to work). If the rest is OK I propose to merge this, agree?

**Comment by VisualGadget** [comment]
I agree, let's merge. Thank you for your work.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
