### PR TITLE
_TZE200_a8sdabtg divide battery reported level by 2

### PR DESCRIPTION
**Pull request by mleone87**
Fixes https://github.com/Koenkk/zigbee2mqtt/issues/24120

### CODE REVIEW

**Comment by mleone87** [comment]
@Koenkk let me know if anything else is needed

**Comment by Koenkk** [comment]
Thanks!

**Comment by KipK** [comment]
This commit bring an issue here. Since this update, all my TS0601 now reports 50% battery instead of 100%

**Comment by Koenkk** [comment]
Had to revert this because of https://github.com/Koenkk/zigbee2mqtt/issues/25581

**Pull request merged**
