### PR TITLE
Add fingerprint for HG06338 sold by Lidl CZ

### PR DESCRIPTION
**Pull request by xpavli44**
Adding fingerprint for https://www.zigbee2mqtt.io/devices/HG06338.html sold by Lidl CZ https://www.lidl-shop.cz/SILVERCREST-Zigbee-3-0-Smart-Home-Prodluzovaci-kabel-s-USB/p100306996 so it is recognised. 

More details in https://community.home-assistant.io/t/silvercrest-lidl-smarthome/243561/117?u=xpavli44

### CODE REVIEW

**Comment by xpavli44** [comment]
@Koenkk I am not sure how to get a review on this as I do not see any button for that

BTW I tested it via using custom device.js option in home assistant and it works now

**Comment by Koenkk** [comment]
Looks good, thanks!

**Comment by thibmaek** [comment]
Thanks, I wondered why mine didn't show up. This model code is the same for BE models.

**Comment by Sierek** [comment]
I have the same device purchased from Lidl Poland. When I try to pair, I have exactly the same effect as described by xpavli44 details in [(https://community.home-assistant.io/t/silvercrest-lidl-smarthome/243561/117?u=xpavli44)]

**Comment by xpavli44** [comment]
@Sierek if it is the same problem the just copy&paste what I did. 

1) go to Z2M logs and find what your fingerprint is. Begins with _TZ3000_
2) add it to devices.js file the same way as I did here https://github.com/Koenkk/zigbee-herdsman-converters/pull/1845/files , it is simple, you can edit the file directly here on github

let me know if you need help with that

**Comment by Sierek** [comment]
Thank you for your answer. 

My fingerprint is the same as yours.
The devices.js file on Github is now good for me now. How do I update it in my HA? I have an installation on Proxmox.

**Comment by xpavli44** [comment]
Oh, I see. Either you need to wait two weeks for home assistant addon to be released https://github.com/danielwelch/hassio-zigbee2mqtt and then update in you HA.

Or you can make it use a custom file (the up to date one from github) using instructions here https://github.com/danielwelch/hassio-zigbee2mqtt#adding-support-for-new-devices read the part about Using devices.js override in add-on

**Comment by YankoValski** [comment]
Well spotted @xpavli44 

I also requested to add new finger print from Lidl Ireland
https://github.com/xpavli44/zigbee-herdsman-converters/compare/master...YankoValski:patch-2

**Pull request merged**
