### PR TITLE
adding develco zhot101

### PR DESCRIPTION
**Pull request by sekyHC**
Adding develco zho101 motion sensor support
It reports temperature, illumination, tamper, occupancy, and battery low. 
Battery voltage times out every time I try to configure its reporting

found issue about it:
https://github.com/Koenkk/zigbee2mqtt/issues/4765

### CODE REVIEW

**Comment by Koenkk** [comment]
Did you test if this works? I think `zigbeeModel` should be `ZHOT201`

**Comment by sekyHC** [comment]
I have 101
https://www.manualslib.com/manual/1369563/Develco-Zhot101.html

it is working perfectly in my setup, I use it to trigger the lights and test it multiple times a day :smile_cat:

**Comment by Koenkk** [comment]
Could you provide the data/database.db entry of this device?

**Comment by sekyHC** [comment]
`{"id":28,"type":"EndDevice","ieeeAddr":"0x0015bc001a0043cc","nwkAddr":53411,"manufId":0,"manufName":"Develco Products A/S","powerSource":"Battery","modelId":"ZHOT101 - ZigBee Occupancy, Temperature & Light Sensor","epList":[34,1,35,38,39,40,41],"endpoints":{"1":{"profId":49353,"epId":1,"devId":1,"inClusterList":[2,3,5],"outClusterList":[1],"clusters":{},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0029dc083b","endpointID":1}],"configuredReportings":[],"meta":{}},"34":{"profId":260,"epId":34,"devId":263,"inClusterList":[0,3,1,1030],"outClusterList":[10],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"35":{"profId":260,"epId":35,"devId":1026,"inClusterList":[0,3,1280],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}},"ssIasZone":{"attributes":{"zoneState":0}}},"binds":[{"cluster":1280,"type":"endpoint","deviceIeeeAddress":"0x00124b0029dc083b","endpointID":1}],"configuredReportings":[],"meta":{}},"38":{"profId":260,"epId":38,"devId":770,"inClusterList":[0,3,1,1026],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}},"msTemperatureMeasurement":{"attributes":{"measuredValue":1706}}},"binds":[{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0x00124b0029dc083b","endpointID":1}],"configuredReportings":[{"cluster":1026,"attrId":0,"minRepIntval":60,"maxRepIntval":600,"repChange":100,"manufacturerCode":null}],"meta":{}},"39":{"profId":260,"epId":39,"devId":262,"inClusterList":[0,3,1,1024],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":7200}}},"binds":[{"cluster":1024,"type":"endpoint","deviceIeeeAddress":"0x00124b0029dc083b","endpointID":1}],"configuredReportings":[{"cluster":1024,"attrId":0,"minRepIntval":60,"maxRepIntval":600,"repChange":500,"manufacturerCode":null}],"meta":{}},"40":{"profId":260,"epId":40,"devId":263,"inClusterList":[0,3,1,1030],"outClusterList":[10],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"41":{"profId":260,"epId":41,"devId":263,"inClusterList":[0,3,1,1030],"outClusterList":[10],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}}},"zclVersion":3,"interviewCompleted":false,"meta":{"configured":1433780322},"lastSeen":1700603790398,"defaultSendRequestWhen":"immediate"}
`

**Comment by sjorge** [comment]
You probably also want to add:
```

await develco.configure.read_sw_hw_version(device, logger);

```

To the configure function to grab the develco hw and sw versions.

Based on the manual it looks very similar to the MOSZ-1xx, the voltage is probably not on ep1 but the first ep in the 30's.

**Comment by sekyHC** [comment]
I have tried manually setting up voltage reporting already
on ep1 it times out, but on other endpoints I get UNSUPPORTED_ATTRIBUTE response

I can try again tomorrow

**Comment by sekyHC** [comment]
I have been busy, but after spending a few hours today I gave up.
The original device is connected to my home assistant and is working as intended.
I have another one, but this one is not behaving nicely. Interviewing is failing, it is not responding to any read requests from dev console etc. I tried repairing it multiple time.
The difference from my main network is also that the main network is on TI chip, while this one is on ezsp (efr32mg21)
Since I know for a fact that this has not been produced in a while, we should either merge this config I have, or just completely drop it

**Pull request closed without merging**
