### PR TITLE
Update tuya.ts

### PR DESCRIPTION
**Pull request by dyx052612**
Add Thermostatic radiator valve

### CODE REVIEW

**Comment by Koenkk** [comment]
Everything except the `schedule` is similar to the `TS0601_thermostat_3`.

@vladyspavlov  could you check if the schedule part of this also works for the `TS0601_thermostat_3`? Then we can merge `TS0601_thermostat_3` and `TS0601_thermostat_4`

**Comment by dyx052612** [comment]
Can be applied to TS0601_ Thermostat_ 3, but How to change .md file and schedule 。

**Comment by Koenkk** [comment]
> but How to change .md file and schedule 。

What do you mean by this?

Note to self; after this merge https://github.com/Koenkk/zigbee2mqtt.io/pull/2166

**Comment by dyx052612** [comment]
May I ask when this device can be supported

**Comment by vladyspavlov** [comment]
> @vladyspavlov could you check if the schedule part of this also works for the `TS0601_thermostat_3`? Then we can merge `TS0601_thermostat_3` and `TS0601_thermostat_4`

DPs are the same and looks like it will work. I'll test tomorrow.

**Comment by vladyspavlov** [comment]
@Koenkk tested and it works ok

**Comment by Koenkk** [comment]
perfect, thanks!

**Pull request merged**
