### PR TITLE
essentials smart home thermostat converter

### PR DESCRIPTION
**Pull request by TAKeanice**
I have built this converter for the thermostat I own. Also, it is relevant for https://github.com/Koenkk/zigbee2mqtt/issues/14239 . Please tell me if there are any aspects of how I built this that may have to be changed to make it into the main repository.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks for the PR. Could you refactor this to the new TuYa format? You can find an example here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/f7ca8a893874ee6d68032bf8efd60b31a532338f/devices/tuya.js#L2189

**Comment by TAKeanice** [comment]
Thanks for the feedback, I will try to do it this weekend.

**Comment by TAKeanice** [comment]
I am still committed to this, but need some more time.

**Comment by TAKeanice** [comment]
@Koenkk I think the error in the git checks is not in my changes

**Comment by TAKeanice** [comment]
> @Koenkk I think the error in the github checks is not in my changes

I was wrong, I didn´t know that it is now necessary to return an array of devices from a manufacturer.js file

**Comment by Koenkk** [comment]
Can we harmonise the schedule expose with one of the existing supported TuYa thermostats?

- https://github.com/Koenkk/zigbee-herdsman-converters/blob/4b8c153235b0fef0481efec41d07ad90ce317f61/devices/tuya.js#L2253

- https://github.com/Koenkk/zigbee-herdsman-converters/blob/4b8c153235b0fef0481efec41d07ad90ce317f61/devices/tuya.js#L2159

**Comment by TAKeanice** [comment]
Not sure whether that will provide a benefit, especially if the user is required to type a string in a specific format instead of a composite decomposing the parts of the schedule setpoints. I will take a look whether I can do anything useful with the standard functions. Is there anything I should look at for the effects of a composes definition besides the UI built into Zigbee2Mqtt?

**Comment by Koenkk** [comment]
@TAKeanice the main goal is to unify the TuYa thermostat schedules. It would be great if existing converters could be re-used (to reduce code size and improve maintainability). This is indeed mainly for the UI.

**Comment by TAKeanice** [comment]
Even though the tuya schedules get more harmonized by the string format "HH:MM/Degrees", it's pretty unusable for all home automation tools. It is too easy to mistype and enter invalid values.

I will happily introduce a new function to lib/tuya.js for a schedule using a composite of days with a nested composite of hour, minute and temperature for each setpoint, as for the essentials thermostat. If you wish, I can make that function generic such that it can be used in the tuyaDatapoints definition.

One thing I noted about the tuyaDatapoints definition is that the converter entry in a datapoint does not have a definition for `get`, so refreshing a value manually is not possible as with the former `convertGet`. Is that on purpose or just not finished yet?

**Comment by Koenkk** [comment]
> I will happily introduce a new function to lib/tuya.js for a schedule using a composite of days with a nested composite of hour, minute and temperature for each setpoint, as for the essentials thermostat. If you wish, I can make that function generic such that it can be used in the tuyaDatapoints definition.

That would be great

> One thing I noted about the tuyaDatapoints definition is that the converter entry in a datapoint does not have a definition for get, so refreshing a value manually is not possible as with the former convertGet. Is that on purpose or just not finished yet?

AFAIK the TuYa api does not allow reading.

**Comment by TAKeanice** [comment]
I am going to make the schedule function I used more general and outbid into the main tuya lib for others to use. This should remain open.

**Comment by TAKeanice** [comment]
I just saw #5550 and will see how it affects the plan to introduce a better week schedule for tuya thermostats, as I am still committed to implementing it.

**Pull request closed without merging**
