### PR TITLE
Add support for EDM-1ZAA-EU dimmer

### PR DESCRIPTION
**Pull request by viperet**
Adds support for EDM-1ZAA dimmer by Earda Technologies Co. Ltd
Product link https://www.aliexpress.com/item/1005001505069156.html

### CODE REVIEW

**Comment by Koenkk** [comment]
Can this be merged with: https://github.com/Koenkk/zigbee-herdsman-converters/blob/59c18447c945f5d8ebe95384c217d4cc40504394/devices.js#L1438 ?

**Comment by viperet** [comment]
@Koenkk no, that dimmer uses dp = 515 to set brightness, in this dimmer dp = 515 sets min brightness level and dp = 514 used to set current brightness level. Unless it's possible make code in tz.tuya_dimmer_level be conditional on manufacturerName.

**Comment by Koenkk** [comment]
Yes, use `meta.device.manufacturerName`.

**Comment by viperet** [comment]
@Koenkk done

**Comment by Koenkk** [comment]
Thanks!

**Comment by carriopablo** [comment]
Hi, The switch have a LED indicator blinking constantly after is switched off. Is there any way, or any command to send over Zigbee to configure the switch stop doing this?

**Comment by viperet** [comment]
@carriopablo Sorry, I don't know any way to disable that blinking.

**Comment by carriopablo** [comment]
@viperet are you experiencing the same behavior?

**Comment by viperet** [comment]
@carriopablo yes, when light is off dimmer is slowly blinking (period ~7 sec) with one led, showing last used light level.

**Pull request merged**
