### PR TITLE
Update legacy.ts

### PR DESCRIPTION
**Pull request by VoltickVL**
fix local_temperature _TZE200_5toc8efa

### CODE REVIEW

**Comment by Koenkk** [comment]
This reverts https://github.com/Koenkk/zigbee-herdsman-converters/commit/e12a381e046afaae8935070977166ff76a3d47e0 lets discuss further in https://github.com/Koenkk/zigbee2mqtt/issues/18791

**Comment by VoltickVL** [comment]
> This reverts [e12a381](https://github.com/Koenkk/zigbee-herdsman-converters/commit/e12a381e046afaae8935070977166ff76a3d47e0) lets discuss further in [Koenkk/zigbee2mqtt#18791](https://github.com/Koenkk/zigbee2mqtt/issues/18791)

This fix need. When we have this fix - local temperature work fine. And we need fix for tozigbee section:

> moes_thermostat_current_heating_setpoint: {
> key: ['current_heating_setpoint'],
> convertSet: async (entity, key, value, meta) => {
>     if (value >= 1 && value <= 5) 
>     value = Math.round(value * 10);
>   await sendDataPointValue(entity, dataPoints.moesHeatingSetpoint, value);
> },

But I'm not sure if the code is correct. After that everything will be fine.

**Comment by Koenkk** [comment]
> And we need fix for tozigbee section:

Can you add it to this pr?

**Comment by VoltickVL** [comment]
> > And we need fix for tozigbee section:
> 
> Can you add it to this pr?

I update pr with 2 fix. Plz confirm

**Comment by VoltickVL** [comment]
@Koenkk i need to install Zigbee2MQTT Beta for view change?

**Comment by Koenkk** [comment]
changes are in z2m edge

**Pull request merged**
