### PR TITLE
Convert Sonoff SNZB-02D & SNZB-02P to `modernExtend`

### PR DESCRIPTION
**Pull request by burmistrzak**
Shouldn't have any adverse effects. Hopefully. 🤞

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Pferdebockwurst** [comment]
Do I need to re-pair or reconfigure these after updating?

**Comment by Pferdebockwurst** [comment]
> `genPollCtrl`

Ok thank you, I'll do this too and report back, if there are any problems.

**Comment by sKinyo** [comment]
Was there a need to remove the device specific reporting settings?

Temperature 
from
{min: 30, max: constants.repInterval.MINUTES_5, change: 20}
to generic
{min: '10_SECONDS', max: '1_HOUR', change: 100}

**Comment by satter** [comment]
My SNZB-02P sensor is missing OTA capabilities after the z2m upgrade: https://github.com/Koenkk/zigbee2mqtt/issues/22889

This PR seems to be removing this capability from the device. Is this an intended removal, and is the device not capable of OTA updates?

**Pull request merged**
