### PR TITLE
Add Haozee Tuya Zigbee 3.0 EU Plug 3680W 16A

### PR DESCRIPTION
**Pull request by DJTerentjev**

### CODE REVIEW

**Comment by DJTerentjev** [comment]
Polling required for this device

**Comment by Koenkk** [comment]
Since the description, vendor and model is an (almost) one on one copy I suggest to add this as a whitelabel instead

**Comment by DJTerentjev** [comment]
I didn't make it clear, but this two model don't provide power data without polling. That is why it was separated and poling was added.

**Comment by Koenkk** [comment]
Then add them to `TS011F_plug_3`

**Comment by DJTerentjev** [comment]
You are right. Done.

**Comment by Koenkk** [comment]
Could you provide the data/database.db entry of both devices? I'm interested in the `appVersion`, my current assumption is that:
- appVersion 67: support reporting
- appVersion 69: doesn't support reporting

Could you also check if the devices provides status updates when controlling the switch physically?

**Comment by andysaab** [comment]
> Could you provide the data/database.db entry of both devices? I'm interested in the `appVersion`, my current assumption is that:
> 
> * appVersion 67: support reporting
> * appVersion 69: doesn't support reporting
> 
> Could you also check if the devices provides a `state` update when controlling the switch using the button on it?

I have a same plug with appVersion 68 - doesn't support reporting.

**Comment by Koenkk** [comment]
@andysaab what is the `manufacturerName` of yours?

**Comment by andysaab** [comment]
>

**Comment by Koenkk** [comment]
I mean this (you can find it in the frontend):
Screenshot 2021-11-19 at 20 27 34

**Comment by andysaab** [comment]
> I mean this (you can find it in the frontend): Screenshot 2021-11-19 at 20 27 34

Sorry, I'm from phone :( 
_TZ3000_w0qqde0g
Zigbee Model is a same

**Comment by DJTerentjev** [comment]
@Koenkk I don't owned device, but you are right behavior of device depend of firmware version.  
This video about it this device and update (in Russian): 
https://www.youtube.com/watch?v=PuL00Sr1jiQ
Hope author of video will joint this thread. 
Device with same model and manufacturer required differed converters. 
Is it possible differentiate applicable converter depending of firmware version? 
I have another case. Spot lights Gledopto GL-S-007Z with old version of software doesn't support Default Response, but then Gledopto fix it.

**Comment by Koenkk** [comment]
> Is it possible differentiate applicable converter depending of firmware version?

yes, example:
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3374/files#diff-7ae23d3c13c2d7f7e37106590684c791aba8093f8be813b7c74a4f1484017c3bR974

**Comment by DJTerentjev** [comment]
OK. Got it. Thank you. Let's close this one. Once I have more information I'll create new pull request.

**Pull request closed without merging**
