### PR TITLE
Create and use wire pilot preset + refactoring

### PR DESCRIPTION
**Pull request by esciara**
Related to issue https://github.com/Koenkk/zigbee2mqtt/issues/19943

I separated changes in relevant commits:
- one for NoDon/Adeo devices
- one for Legrand devices
- one that reflects refactoring of NodOn cluster

Sister PR https://github.com/Koenkk/zigbee-herdsman/pull/812

### CODE REVIEW

**Comment by esciara** [comment]
I could not test the Legrand device, so either @FabianMangold @EXP-Carthage could help (I could not mention the others who also wrote/modified part of the code), or we can remove the related commit for the time being.

**Comment by Koenkk** [comment]
Thanks!

**Comment by EXP-Carthage** [comment]
Why change the legrand.js file with data from NodOn devices when they have absolutely nothing in common ?

**Comment by SilentT-FR** [comment]
Of for Legrand devices

**Comment by esciara** [comment]
> Ok for Legrand devices

Thanks for confirming it works!

**Comment by esciara** [comment]
Just wanted to add that now with this change, pilot wire mode is available by default on the dashboard 🎉!

image

**Pull request merged**
