### PR TITLE
Update xiaomi.js

### PR DESCRIPTION
**Pull request by nukusinji**
no need fz.battery
exactly battery level comes fz.aqara_opple.

### CODE REVIEW

**Comment by Otnow** [comment]
```javascript
        fromZigbee: [ ... fz.battery],

        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await endpoint.read('genPowerCfg', ['batteryVoltage']);
        },
```

I [added this code](https://github.com/Koenkk/zigbee-herdsman-converters/pull/4237) and it is needed to initialize the battery value during pairing, so please close your PR, because it degrades functionality and carries no payload.

**Comment by nukusinji** [comment]
> 

I think no need read when pairing. because can get initial battery value when pairing from fz.aqara_opple.

**Comment by Otnow** [comment]
> I think no need read when pairing. because can get initial battery value when pairing from fz.aqara_opple.

Unfortunately, this is not always the case, which is why this additional code has been added, the presence of which does not interfere with the basic functionality at all, but only complements it.

**Comment by nukusinji** [comment]
> 

okay, i close

**Comment by Otnow** [comment]
> okay, i close

Thanks for understanding.

**Pull request closed without merging**
