### PR TITLE
TERNCY Awareness switch, ORVIBO Smart sticker switch

### PR DESCRIPTION
**Pull request by kirovilya**
TERNCY Awareness switch https://ru.aliexpress.com/item/32992813884.html
ORVIBO Smart sticker switch https://ru.aliexpress.com/item/32917905957.html

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks, I changed `orvibo_raw` to `action` to make it more in line with other converters.

**Comment by diplix** [comment]
can confirm, that the orvibo smart sticker switch works as described (buttons 1 through 4). thanks!
i made one more observation: if i press buttons 7 and 8 together for more than 4 seconds, i get
```
[34mzigbee2mqtt:debug[39m 2019-11-06T05:45:22: Received Zigbee message from '0x00124b001d033b3a', type 'attributeReport', cluster 'genBasic', data '{"170":0}' from endpoint 1 with groupID 0
[34mzigbee2mqtt:debug[39m 2019-11-06T05:45:22: Device '0x00124b001d033b3a' announced itself
```
and the red led constantly blinks. i can end the blinking by clicking button 7 or 8 and get a
```
[34mzigbee2mqtt:debug[39m 2019-11-06T05:45:37: Received Zigbee message from '0x00124b001d033b3a', type 'attributeReport', cluster 'genBasic', data '{"170":1}' from endpoint 1 with groupID 0
```
i’m guessing when the sticker blinks red it could be paired with other devices or scenes. i could however make no use of that other than keeping the device awake for pairing or removing.

**Comment by Keeze** [comment]
Hi guys, How can I get the ORVIBO Smart sticker in pairing mode?

Cheers,
Kees

**Comment by kirovilya** [comment]
@Keeze press 5+7 together - led blink red 3 times, then 1, 2, 3, 4 - led start fast blinking - begin pairing

**Comment by Keeze** [comment]
@kirovilya Thanks! Just to be sure:
Number reference is right?
orvibo_c

So press 5+7 together: red led blinks 3 times
Then 1234 in sequence: red+blue led blinks 4 times fast and blue led begins to blink and after some time the blue led turns on a little longer and stops.

 I think I get:

`zigbee2mqtt:error 11/9/2019, 11:25:59 AM Cannot get the Node Descriptor of the Device: 0x00124b0013dc11e0 (Error: Timed out after 10000 ms)`

What does that mean?

**Pull request merged**
