### PR TITLE
Added new updated version of inwall switch

### PR DESCRIPTION
**Pull request by azamat5991**
The device was not reporting correctly the status of the 2nd gang, and after removing the lines everything worked fine

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by azamat5991** [comment]
> Can you provide the data/database.db entry of this device?

{"id":4,"type":"Router","ieeeAddr":"0xbc33acfffe58e443","nwkAddr":59134,"manufId":4633,"manufName":"ORVIBO","powerSource":"Unknown","modelId":"83b9b27d5ffb4830bf35be5b1023623e","epList":[1,2,3,4,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"9":0,"modelId":"83b9b27d5ffb4830bf35be5b1023623e","manufacturerName":"ORVIBO","powerSource":0,"zclVersion":3,"dateCode":"20191119","swBuildId":"0.1.0"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[25],"clusters":{"genOnOff":{"attributes":{"onOff":0}},"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0014dbcea8","endpointID":1}],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":0,"inClusterList":[0,3,23],"outClusterList":[3,6],"clusters":{"genBasic":{"attributes":{}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0014dbcea8","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"dateCode":"20191119","swBuildId":"0.1.0","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1610797863675}

**Comment by azamat5991** [comment]
> Can you provide the data/database.db entry of this device?

`{"id":4,"type":"Router","ieeeAddr":"0xbc33acfffe58e443","nwkAddr":59134,"manufId":4633,"manufName":"ORVIBO","powerSource":"Unknown","modelId":"83b9b27d5ffb4830bf35be5b1023623e","epList":[1,2,3,4,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"9":0,"modelId":"83b9b27d5ffb4830bf35be5b1023623e","manufacturerName":"ORVIBO","powerSource":0,"zclVersion":3,"dateCode":"20191119","swBuildId":"0.1.0"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[25],"clusters":{"genOnOff":{"attributes":{"onOff":0}},"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0014dbcea8","endpointID":1}],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":0,"inClusterList":[0,3,23],"outClusterList":[3,6],"clusters":{"genBasic":{"attributes":{}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0014dbcea8","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"dateCode":"20191119","swBuildId":"0.1.0","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1610797863675} `

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
