### PR TITLE
add EFEKTA_THP and EFEKTA_miniPWS

### PR DESCRIPTION
**Pull request by smartboxchannel**

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you link instructions for both devices on how to build them?

**Comment by smartboxchannel** [comment]
> Can you link instructions for both devices on how to build them?

Сompiled firmware for PWS and miniPWS sensors are on my github ( https://github.com/smartboxchannel/Plant-Watering-Sensor-Zigbee/tree/main/PROJECT%20SOURCE ). To compile these firmware independently for the desired sensor type, you need to select the appropriate defines in the preinclude.h file ( https://github.com/smartboxchannel/Plant-Watering-Sensor-Zigbee/blob/c2a8421c82e26886febe152bb7de561210077fd7/PROJECT%20SOURCE/PWS/Source/preinclude.h#L47 )

There are no instructions for assembling the devices, there are only 10 components and there is a device diagram on the GIT, soldering takes 10 minutes, I don't see the point in the instructions. How to add a device to the network is described in detail in the README ( https://github.com/smartboxchannel/Plant-Watering-Sensor-Zigbee#readme )

If you mean adding information to https://github.com/Koenkk/zigbee2mqtt.io , then it will be added a little later, as soon as the problem with https://github.com/Koenkk/zigbee2mqtt.io/pull/968 , I didn't quite understand what was going on there, either the structure of the description has changed, or someone has already added information about the humidity sensor with an eink

**Comment by smartboxchannel** [comment]
I think something happened with npm test

**Comment by Koenkk** [comment]
@smartboxchannel is there also a page for EFEKTA_THP ?

Please also add a picture for it to https://github.com/Koenkk/zigbee2mqtt.io/pull/970/

**Pull request closed without merging**
