### PR TITLE
Update tuya.ts

### PR DESCRIPTION
**Pull request by RafaelDuncan**
adding support for manufacturerName: '_TZE204_5cuocqty' TS0601
merged with the existing TS0601_dimmer_5

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by RafaelDuncan** [comment]
hello @Koenkk , 

Today I discovered that this dimmer module (_TZE204_5cuocqty' TS0601) also has the function for choosing the "switch type". This way you can indicate whether a toggle or momentary switch is connected. this is comparable to module _TZ3210_3mpwqzuu. Should I submit a change request for this?   otherwise this function cannot be used.

**Comment by RafaelDuncan** [comment]
@Koenkk  did you see request
https://github.com/RafaelDuncan/zigbee-herdsman-converters/commit/3d43ed3cee2606fd4ab517e215ecf9059b4cc7d8

**Comment by RafaelDuncan** [comment]
> @Koenkk did you see request
> [RafaelDuncan@3d43ed3](https://github.com/RafaelDuncan/zigbee-herdsman-converters/commit/3d43ed3cee2606fd4ab517e215ecf9059b4cc7d8)

@Koenkk did you see request
https://github.com/RafaelDuncan/zigbee-herdsman-converters/commit/3d43ed3cee2606fd4ab517e215ecf9059b4cc7d8

**Comment by RafaelDuncan** [comment]
> Yes, but this is not a pull request, can you create it? Alternatively I can add the changes directly.

I don't know if I will be able to do that... otherwise could you make the change yourself?

**Comment by Koenkk** [comment]
Done!

**Comment by RafaelDuncan** [comment]
thank you very much Koenkk

**Pull request merged**
