### PR TITLE
Add support TuYa Curtain Motor TS0601

### PR DESCRIPTION
**Pull request by nukusinji**
TuYa based Curtain motor TS0601 by tuya
product link
https://www.aliexpress.com/item/4000463256008.html?spm=a2g0s.9042311.0.0.5aae4c4dVWxyOg

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by mgrom** [comment]
Could you help me with something @nukusinji  ?
There are more devices with the same model TS0601 for example Tuya radiator thermostat.  Those devices were added to devices.js with "fingerprint" property, so they could be recognized properly. Curtain motor is still with just model. 
The thing is when device is being configured for the first time it's  showing up in home assistant as Curtain monitor (because of model being equal). Then I need to restart zigbee2mqtt service, and after that device is recognized properly - I think it's because of entry in database.db file. 

This is fingerprint for thermostat.
`        fingerprint: [
            {
                type: 'EndDevice', manufacturerID: 4098, manufacturerName: '_TZE200_ckud7u2l', modelID: 'TS0601', powerSource: 'Battery',
                endpoints: [
                    {ID: 1, profileID: 260, deviceID: 81, inputClusters: [0, 4, 5, 61184], outputClusters: [25, 10]},
                ],
            },
        ],`

Could you please paste here entry from your database.db for the tuya courtain motor?

**Comment by nukusinji** [comment]
> Could you help me with something @nukusinji ?
> There are more devices with the same model TS0601 for example Tuya radiator thermostat. Those devices were added to devices.js with "fingerprint" property, so they could be recognized properly. Curtain motor is still with just model.
> The thing is when device is being configured for the first time it's showing up in home assistant as Curtain monitor (because of model being equal). Then I need to restart zigbee2mqtt service, and after that device is recognized properly - I think it's because of entry in database.db file.
> 
> This is fingerprint for thermostat.
> ` fingerprint: [ { type: 'EndDevice', manufacturerID: 4098, manufacturerName: '_TZE200_ckud7u2l', modelID: 'TS0601', powerSource: 'Battery', endpoints: [ {ID: 1, profileID: 260, deviceID: 81, inputClusters: [0, 4, 5, 61184], outputClusters: [25, 10]}, ], }, ],`
> 
> Could you please paste here entry from your database.db for the tuya courtain motor?

Hi
My tuya curtain motor in database.db
{"id":3,"type":"Router","ieeeAddr":"","nwkAddr":51693,"manufId":4098,"manufName":"_TZE200_5zbp6j0u","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,10,4,5,61184],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0005","65506":21,"appVersion":82,"modelId":"TS0601","manufacturerName":"_TZE200_5zbp6j0u","powerSource":1,"zclVersion":3,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[]}},"appVersion":82,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1596558312396}

I think you have to repairing. because Model of tuya_thermostat is TS0601_thermostat in devices.js
but your pairing model is TS0601. If you successful pairing, will changing.

**Comment by mgrom** [comment]
@nukusinji 
Thanks!

Could you please do one more thing for me? I don't want to break your configuration, so be so kind add this to devices.js to your curtain motor:
        fingerprint: [
            {
                type: 'Router', manufacturerID: 4098, manufacturerName: '_TZE200_5zbp6j0u', modelID: 'TS0601', powerSource: 'Mains (single phase)',
                endpoints: [
                    {ID: 1, profileID: 260, deviceID: 81, inputClusters: [0,10,4,5,61184], outputClusters: [25]},
                ],
            },
        ],  

and please check if you are still able to pair successfully device with zigbee network.

Then I'll handle thermostat by myself :)

**Pull request merged**
