### PR TITLE
feat: VOCKQJK11LM allow reading and improve reporting

### PR DESCRIPTION
**Pull request by sjorge**
I got myself a VOCKQJK11LM after another one of my Develco VOC sensors died :(, so here are some improvements:

- support air_quality
- read display_unit and air_quality attribute during configure so the value is populated
- allow reading of temperature, humidity, voc, air_quality and battery.  (this is of course done after the next checkin)
- configure batteryVoltage reporting

Something I still haven't found is how to convert the ppb voc to ug/mg3, the display has the option to chose and the their hub also has it as ug/mg3 which makes sense to compare it to other sensors. 
image

So far I haven't really found any info on the sensor which is a shame. Also not really sure this should be in the Xiaomi vendor file as the actual vendor is lumi and sold under the aqara brand. But that's not a can of worms I want to deal with.

If I do manage to find a spec-sheet for the chip I'll see about converting the value to ug/mg3 (and maybe see if I can somehow have it follow whatever is configured for the display_unit value.

### CODE REVIEW

**Comment by sjorge** [comment]
I think the air_quality converter needs a bit of rework, I only noticed later there is a weird aqaraOppl parser convertor.

**Comment by sjorge** [comment]
Switched to using the aqara_opple fromZigbee converter for parsing air_quality:
```
Zigbee2MQTT:debug 2023-12-15 13:34:06: VOCKQJK11LM: Processed buffer into data {"1":3271,"3":20,"4":5032,"5":6,"6":53,"8":285,"10":43357,"12":1,"100":2029,"101":5589,"102":422,"103":3}
Zigbee2MQTT:debug 2023-12-15 13:34:06: VOCKQJK11LM: unknown key 6 with value 53
Zigbee2MQTT:debug 2023-12-15 13:34:06: VOCKQJK11LM: Processed data into payload {"voltage":3271,"battery":100,"device_temperature":20,"power_outage_count":5,"temperature":20.29,"humidity":55.89}
Zigbee2MQTT:debug 2023-12-15 13:34:06: VOCKQJK11LM: Processed data into payload {"voltage":3271,"battery":100,"device_temperature":20,"power_outage_count":5,"temperature":20.29,"humidity":55.89}
```

**Comment by sjorge** [comment]
The expose data now looks like:
image

And aside from the ppb instead of ug/m3 it's a drop in replacement functionality wise for my old Develco.

**Comment by Koenkk** [comment]
Could you write this to the modernExtend? Modern extend automatically generates the from/toZigbee and exposes, example: https://github.com/Koenkk/zigbee-herdsman-converters/blob/944e9416ef1e99ca5ac4bb454e749b01570ec4e0/src/devices/sonoff.ts#L384

**Comment by sjorge** [comment]
Which ones specifically?

The tz humidity one seems generic enough to have it be were it is now?

The big aqara_opple one seems hard to rewrite.

The tvoc one seems doable, not sure on the display unit one though at first glance it also seems doable but it's also somehow tied into the aqara_opple one.

**Comment by Koenkk** [comment]
- Humidity can go to `modernExtend`
- For the ones using `aqara_opple`, I think an option should be added to the pass the fromZigbee converter to the modernExtend (then the modernExtend will not generate it but use that one instead), e.g. `numeric({fromZigbee: xiaomi.fromZigbee.aqara_opple, .......})`

**Comment by sjorge** [comment]
My first attempt for the tvoc did not go well, I assume I have to use the numeric (hex or decimal) notation and can't use the names (even if they are in the zcl/cluster definition ?

```
        extend: [
            numeric({
                name: 'voc',
                cluster: 'genAnalogInput',
                attribute: 'presentValue',
                description: 'Measured VOC value',
                unit: 'ppb',
            }),
        ],
```

Is what I tried.

**Comment by sjorge** [comment]
OK got the tvoc moved over:
```
debug 2023-12-15 21:51:33: Received MQTT message on 'zigbee2mqtt/airquality/livingroom/get' with data '{"voc":""}'
debug 2023-12-15 21:51:33: Publishing get 'get' 'voc' to 'airquality/livingroom'
debug 2023-12-15 21:51:33: Received Zigbee message from 'airquality/livingroom', type 'readResponse', cluster 'genAnalogInput', data '{"presentValue":64}' from endpoint 1 with groupID 0
info  2023-12-15 21:51:34: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"excellent","battery":100,"device_temperature":20,"display_unit":"ppb_celsius","humidity":52.16,"last_seen":"2023-12-15T20:51:33.918Z","linkquality":80,"power_outage_count":5,"temperature":20.65,"voc":64,"voltage":3237}'
debug 2023-12-15 21:51:34: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'genBasic', data '{"modelId":"lumi.airmonitor.acn01"}' from endpoint 1 with groupID 0
info  2023-12-15 21:51:34: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"excellent","battery":100,"device_temperature":20,"display_unit":"ppb_celsius","humidity":52.16,"last_seen":"2023-12-15T20:51:34.878Z","linkquality":76,"power_outage_count":5,"temperature":20.65,"voc":64,"voltage":3237}'
debug 2023-12-15 21:51:34: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[1,33,165,12,3,40,20,4,33,168,19,5,33,6,0,6,36,3,0,0,0,0,8,33,29,1,10,33,93,169,12,32,1,100,41,22,8,101,33,94,20,102,33,64,0,103,32,1],"type":"Buffer"}}' from endpoint 1 with groupID 0
info  2023-12-15 21:51:35: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"excellent","battery":100,"device_temperature":20,"display_unit":"ppb_celsius","humidity":52.14,"last_seen":"2023-12-15T20:51:34.938Z","linkquality":80,"power_outage_count":5,"temperature":20.7,"voc":64,"voltage":3237}'
```

**Comment by sjorge** [comment]
Also did humidity:

```
debug 2023-12-15 22:06:00: Received MQTT message on 'zigbee2mqtt/airquality/livingroom/get' with data '{"humidity":""}'
debug 2023-12-15 22:06:00: Publishing get 'get' 'humidity' to 'airquality/livingroom'
debug 2023-12-15 22:06:05: Received Zigbee message from 'airquality/livingroom', type 'readResponse', cluster 'msRelativeHumidity', data '{"measuredValue":5009}' from endpoint 1 with groupID 0
info  2023-12-15 22:06:06: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"excellent","battery":100,"device_temperature":22,"display_unit":"ppb_celsius","humidity":50.09,"last_seen":"2023-12-15T21:06:05.851Z","linkquality":43,"power_outage_count":5,"temperature":22.04,"voc":58,"voltage":3237}'
```

@Koenkk  I have a few questions related to this:
- currently it's not possible to disable the convertGet in a modernExtend ? (not that I need it here, but it seems like something we will need elsewhere ?)
- with fz.humidity there was an option to calibration and precision, these don't work anymore now that it is using a modernExtend should I drop the humidity -> modernExtend commit ? As we will lose functionality and it doesn't seem super easy to add it ?

**Comment by sjorge** [comment]
I guess a fromZigbeePassthru would also fix the humidity options if i pass through fz.humidity, I'll look at this tomorrow. Not sure how easy that is. Just though of it in the shower 😅

**Comment by Koenkk** [comment]
> currently it's not possible to disable the convertGet in a modernExtend ? (not that I need it here, but it seems like something we will need elsewhere ?)

We can add it once needed

> with fz.humidity there was an option to calibration and precision, these don't work anymore now that it is using a modernExtend should I drop the humidity -> modernExtend commit ? As we will lose functionality and it doesn't seem super easy to add it ?

The humidity you added can be moved as a preset into `modernExtend.ts`. Additionally we can also pass the options there.

**Comment by Koenkk** [comment]
I just noticed that humidity will also be added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6692/files#diff-47eee2b61258a9d48e4b9104d706a4aeacec2e1baba7d21f34db7d2963357d28R69

**Comment by sjorge** [comment]
> I just noticed that humidity will also be added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6692/files#diff-47eee2b61258a9d48e4b9104d706a4aeacec2e1baba7d21f34db7d2963357d28R69

I can temp pull in the change and drop the commit after that one gets merged, however that one does not pull in the tz.humidity that I added. I can modify the change to do so, but then I still need to add the toZigbee.humidity convertor, or should I add that one directly in modernExtend?

**Comment by sjorge** [comment]
Some things I noticed when pulling in these temperature and humidity modern convertors, the configure function sets them up in a no very good way, min report is 0 max = zcl max, change = 0

**Comment by sjorge** [comment]
Doubling back to the whole aqara_opple function, I think since attribute id 276 and 297 only seem to be for VOCKQJK11LM we can add those to herdman's cluster.ts, that also makes it easy to write a normal extend as we can then use enumLookup for both. I'll open a PR for that.

**Comment by sjorge** [comment]
@Koenkk so after some more poking about it seems (newer) aqara/lumi devices (that that follow the zigbee 3.0 zcl) seem to have some of the data duplicated, e.g. temp, humidity, battery voltage is on there manufacturer specific cluster and available on the standard clusters. Seems a lot of devices are using a mix of both, e.g. most of this devices updates come from the standard clusters via attributeReporting but occasionally they also come (when the button is pressed on the device) via the aqaraOpple cluster.

For non standard stuff like the displayUnit and airQuality they only come in via de aqaraOpple cluster, but it seems reporting can (needs to) be setup for those seperate, I think it makes sense to add all the custom ones to cluster.ts to make it easy to add those via modernExtends, we should probably also slowly move things out of the very big aqara_opple function.

This is getting very big for one PR though I'd like to work on this in smaller PR's depending on how much time we have I propose to split this up in at least:

1. basic improvements
   1.  read displayUnit and airQuality value in configure (after https://github.com/Koenkk/zigbee-herdsman/pull/829 gets merged)
   1. add modernExtend for airQuality
   1. setup reporting for batteryVoltage
1. allow reading of some attrinute + modernExtend for those
   1. move temperature over to modernExtend and allow reading (plus fix the reporting configuration after https://github.com/Koenkk/zigbee-herdsman-converters/pull/6692/files#diff-47eee2b61258a9d48e4b9104d706a4aeacec2e1baba7d21f34db7d2963357d28R69 lands)
   1. move humidity over to modernExtend and allow reading (plus fix the reporting configuration)
1. move battery (voltage) to modernExtend (I think this is going to be a big one, we need to basically create at least 2, one for batteryVoltage that does the reporting and battery type mapping) and one for batteryPercentageRemaining (with the divide/don't divide logic) this should ideally also be applied to all all devices, I got a wide selection of device so I can test this OKish I think)
1. extract device_temperature from aqara_opple function
   1. add deviceTemperature to cluster.ts
   1. create add modernExtend in lib/xiaomi for deviceTemperature
   1. depending on how easy this is, also do tempeature, humidity, ... although I'm not sure we should use these for this device as it also support those over standard ZCL cluster and I prefer to use those as we get reporting control over those.

**Comment by sjorge** [comment]
I had a bit of time so I already started splitting this up in smaller chunks locally.

**Comment by sjorge** [comment]
@Koenkk I've started splitting this out, I'll close this, there is an issue to track progess here https://github.com/Koenkk/zigbee-herdsman-converters/issues/6721

I will open a new PR this weekend for phase 1, just need to figure out how to nicely add optional reporting and reading of the attribute during configure stage to numeric and enumLookup modern extends.

**Comment by Koenkk** [comment]
Sounds good!

**Pull request closed without merging**
