### PR TITLE
Update TS0601 _TZE200_68nvbio9

### PR DESCRIPTION
**Pull request by jracoma**
Adding missing features from existing _TZE200_68nvbio9. 

See [https://github.com/Koenkk/zigbee2mqtt/issues/16981](url)

### CODE REVIEW

**Comment by Koenkk** [comment]
Same note as https://github.com/Koenkk/zigbee2mqtt/issues/16981#issuecomment-1464857866.

I will close https://github.com/Koenkk/zigbee2mqtt/issues/16981 to continue here.

**Comment by jracoma** [comment]
These are the datapoints I pulled from the Tuya IOT platform.
Control/State: 1 - open/stop/close/continuous - Enum
(Set) Curtain Position Setting: 2 - Integer
Current Curtain Position: 3 - Integer
Mode: 4 - night/morning - Enum
Motor Direction (Control Back Mode): 5 - forward/back - Enum
Work State: 7 - opening/closing - Enum
Situation Set: 11 - fully_open/fully_close - Enum (Doesn't work)
Fault: 12 - motor_fault - Label
Battery Percentage: 13 - Integer
Border: 16 - up/down/up_delete/down_delete/remove_top_bottom (all) - Enum
Best Position: 19 - Integer - (Doesn't work)
Click Control: 20 - up/down - Enum

I tried adding datapoint 2 using below:
`[1, 'state', tuya.valueConverterBasic.lookup({ 'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2) })], [2, 'position', tuya.valueConverter.raw],[13, 'battery', tuya.valueConverter.raw] using e.cover_position().setAccess('position', ea.STATE_SET),`

State and battery work but position kept giving this error:
`TypeError: Cannot read properties of undefined (reading '1') at Object.options (/app/data/tuya.js:1788:40) at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17) at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:92:81) at new Controller (/app/lib/controller.ts:84:58) at start (/app/index.js:106:18) Using '/app/data' as data directory /app/data/tuya.js:1788 const dpKey = datapoint[1];`

**Comment by ievgeniip** [comment]
Confirm - it works for me.
Maybe the reverse control don't need to put into exposes section, it works well in the settings(special)

**Comment by Koenkk** [comment]
@jracoma can you provide the full external converter you are using?

**Comment by jracoma** [comment]
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
// const tuya = require('zigbee-herdsman-converters/lib/tuya');
const tuya = require('../../data/tuya');

const dataPointsLocal = {
	battery: 13,
	border: 16,
	clickControl: 20,
};

const fzLocal = {
	ZM16EL: {
		cluster: 'manuSpecificTuya',
		type: ['commandDataReport'],
		options: [exposes.options.invert_cover()],
		convert: (model, msg, publish, options, meta) => {
			const dpValue = tuya.firstDpValue(msg, meta, 'ZM16EL');
			const dp = dpValue.dp;
			const value = tuya.getDataValue(dpValue);

			switch (dp) {
				case tuya.dataPoints.coverPosition: // Started moving to position (triggered from Zigbee)
				case tuya.dataPoints.coverArrived: { // Arrived at position
					const invert = tuya.isCoverInverted(meta.device.manufacturerName) ? !options.invert_cover : options.invert_cover;
					const position = invert ? 100 - (value & 0xff) : value & 0xff;

					if (position > 0 && position <= 100) {
						return { 'position': position, 'state': 'OPEN' };
					} else if (position == 0) {
						return { 'position': position, 'state': 'CLOSE' };
					} else {
						// result.running = running; // Not calibrated yet, no position is available
					}
				}
					break;
				case tuya.dataPoints.state:
					return { 'state': { 'open': 0, 'stop': 1, 'close': 2 }[value] };
					break;
				case tuya.dataPoints.motorDirection:
					return { 'motorDirection': value };
					break;
				case dataPointsLocal.battery:
					return { 'battery': value };
					break;
				case dataPointsLocal.clickControl:
					return { 'clickControl': value };
					break;
				default:
					meta.logger.warn(`Unhandled DP #${dp} for ${meta.device.manufacturerName}:
                    ${JSON.stringify(value)}`);
			}
		}
	},
};

const tzLocal = {
	ZM16EL: {
		key: ['state', 'position', 'border', 'options', 'click_control'],
		options: [exposes.options.invert_cover()],
		convertSet: async (entity, key, value, meta) => {
			switch (key) {
				case 'state':
					await tuya.sendDataPointEnum(entity, tuya.dataPoints.state, { 'open': 0, 'stop': 1, 'close': 2 }[value.toLowerCase()]);
					break;
				case 'position':
					const invert = tuya.isCoverInverted(meta.device.manufacturerName) ? !meta.options.invert_cover : meta.options.invert_cover;
					const position = invert ? 100 - (value & 0xff) : value & 0xff;

					await tuya.sendDataPointValue(entity, tuya.dataPoints.coverPosition, position);
					break;
				case 'border':
					await tuya.sendDataPointEnum(entity, dataPointsLocal.border, { 'up': 0, 'down': 1, 'up_delete': 2, 'down_delete': 3, 'remove_top_bottom': 4 }[value]);
					break;
				case 'options':
					if (value.reverse_direction != undefined) {
						if (value.reverse_direction) {
							meta.logger.info('Motor direction reverse');
							await tuya.sendDataPointEnum(entity, tuya.dataPoints.motorDirection, 1);
						} else {
							meta.logger.info('Motor direction forward');
							await tuya.sendDataPointEnum(entity, tuya.dataPoints.motorDirection, 0);
						}
					}
					break;
				case 'click_control':
					await tuya.sendDataPointEnum(entity, dataPointsLocal.clickControl, { 'up': 0, 'down': 1 }[value]);
					break;
				default:
					meta.logger.warn(`Unhandled key #${key} for ${meta.device.manufacturerName}:
                    ${JSON.stringify(value)}`);
			}
		}
	},
};

const definition = {
	fingerprint: [
		{
			modelID: 'TS0601',
			manufacturerName: '_TZE200_68nvbio9',
		},
	],
	model: 'ZM16EL-03/33',
	vendor: 'Zemismart',
	description: 'Smart tubular motor',
	fromZigbee: [fzLocal.ZM16EL, fz.ignore_basic_report],
	toZigbee: [tzLocal.ZM16EL],
	exposes: [
		e.battery(),
		e.cover_position().setAccess('position', ea.STATE_SET),
		exposes.composite('options', 'options', ea.STATE_SET)
			.withFeature(exposes.binary('reverse_direction', ea.STATE_SET, true, false)
				.withDescription('Reverse the motor direction')),
		exposes.enum('border', ea.STATE_SET, ['up', 'down', 'up_delete', 'down_delete', 'remove_top_bottom']),
		exposes.enum('click_control', ea.STATE_SET, ['up', 'down'])
			.withDescription('Single motor steps'),
	],
};

module.exports = definition;
```

**Comment by jracoma** [comment]
Sorry about that.

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
// const tuya = require('zigbee-herdsman-converters/lib/tuya');
const tuya = require('../../data/tuya');

const definition = {
	fingerprint: [
		{
			modelID: 'TS0601',
			manufacturerName: '_TZE200_68nvbio9',
		},
	],
	model: 'ZM16EL-03/33',
	vendor: 'Zemismart',
	description: 'Smart tubular motor',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime,
    configure: tuya.configureMagicPacket,
	exposes: [
		e.battery(),
		// e.cover_position().setAccess('position', ea.STATE_SET),
		e.cover_position(),
		exposes.composite('options', 'options', ea.STATE_SET)
			.withFeature(exposes.binary('reverse_direction', ea.STATE_SET, true, false)
				.withDescription('Reverse the motor direction')),
		// exposes.enum('border', ea.STATE_SET, ['up', 'down', 'up_delete', 'down_delete', 'remove_top_bottom']),
		// exposes.enum('click_control', ea.STATE_SET, ['up', 'down'])
		// 	.withDescription('Single motor steps'),
    ],
    meta: {
        // All datapoints go in here
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverterBasic.lookup({ 'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2) })],
            // [3, 'coverPosition', tuya.valueConverter.raw]
            // [5, 'options', tuya.valueConverter.trueFalseEnum0]
            [13, 'battery', tuya.valueConverter.raw]
        ],
    },
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Does this converter give the error you mentioned earlier? 

```
TypeError: Cannot read properties of undefined (reading '1') at Object.options (/app/data/tuya.js:1788:40) at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17) at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:92:81) at new Controller (/app/lib/controller.ts:84:58) at start (/app/index.js:106:18) Using '/app/data' as data directory /app/data/tuya.js:1788 const dpKey = datapoint[1];
```

**Comment by jracoma** [comment]
Sorry, I forgot to uncomment the position datapoint.

`[3, 'position', tuya.valueConverter.raw]`

**Comment by Koenkk** [comment]
In your converter it shows `coverPosition` while this should be `position`.

**Comment by jracoma** [comment]
So I've tried position and different combinations of the other datapoints but I'm stuck on that initial TypeError.

```
const definition = {
	fingerprint: [
		{
			modelID: 'TS0601',
			manufacturerName: '_TZE200_68nvbio9',
		},
	],
	model: 'ZM16EL-03/33',
	vendor: 'Zemismart',
	description: 'Smart tubular motor',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime,
    configure: tuya.configureMagicPacket,
	exposes: [
		e.battery(),
		// e.cover_position().setAccess('position', ea.STATE_SET),
        e.cover_position(),
		exposes.composite('options', 'options', ea.STATE_SET)
			.withFeature(exposes.binary('reverse_direction', ea.STATE_SET, true, false)
				.withDescription('Reverse the motor direction')),
		exposes.enum('border', ea.STATE_SET, ['up', 'down', 'up_delete', 'down_delete', 'remove_top_bottom']),
		exposes.enum('click_control', ea.STATE_SET, ['up', 'down'])
            .withDescription('Single motor steps'),
        exposes.enum('motor_fault', ea.STATE_SET, false, true),
    ],
    meta: {
        // All datapoints go in here
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverterBasic.lookup({ 'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2) })],
            [3, 'position', tuya.valueConverter.raw],
            // [5, 'options', tuya.valueConverter.trueFalseEnum0]
            [12, 'motor_fault', tuya.valueConverter.trueFalse1],
            [13, 'battery', tuya.valueConverter.raw],
            [16, 'border', tuya.valueConverterBasic.lookup({ 'up': tuya.enum(0), 'down': tuya.enum(1), 'up_delete': tuya.enum(2), 'down_delete': tuya.enum(3), 'remove_top_bottom': tuya.enum(4) })],
            [20, 'click_control', tuya.valueConverterBasic.lookup({ 'up': tuya.enum(0), 'down': tuya.enum(1) })],
        ],
    },
};
```

**Comment by jracoma** [comment]
So I tried with your code and click_control works. Position works in reporting but not in setting a position. Invert_cover and reverse_direction didn't work. I tried to add the same datapoints to where you added yours but it didn't work.

**Comment by Koenkk** [comment]
Please try with https://gist.github.com/Koenkk/9c2e023277a170e409b7ae622a159d9c

**Comment by Koenkk** [comment]
Do you get an error when setting the position?

**Comment by jracoma** [comment]
So it seems datapoint 2 is to set the position and then datapoint 3 is the curtain reporting current position. When I change it to 2, setting position works but then the position doesn't correctly update and just holds the last set position.

**Comment by Koenkk** [comment]
Updated https://gist.github.com/Koenkk/9c2e023277a170e409b7ae622a159d9c , can you try again?

**Comment by jracoma** [comment]
I've updated it to below and everything works except I am not able to generate a fault to verity that works. Hitting refresh on position does generate this error but it does update when commands are sent.

`Error 2023-03-31 10:44:45No converter available for 'get' 'position' ()`

Also, is it possible to re-add the exposes.options.invert_cover() settings? I see it in devices/tuya.js but not sure if it's a good idea to add for all datapoints.

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
// const tuya = require('zigbee-herdsman-converters/lib/tuya');
const tuya = require('../../data/tuya');

const tzDatapoint = {
    ...tuya.tz.datapoints,
    key: ['state', 'position', 'reverse_direction', 'motor_fault', 'battery', 'border', 'click_control'],
}

const definition = {
	fingerprint: [
		{
			modelID: 'TS0601',
			manufacturerName: '_TZE200_68nvbio9',
		},
	],
	model: 'ZM16EL-03/33',
	vendor: 'Zemismart',
	description: 'Smart tubular motor',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tzDatapoint],
    onEvent: tuya.onEventSetTime,
    configure: tuya.configureMagicPacket,
	exposes: [
		e.battery(),
		e.cover_position(),
		exposes.composite('options', 'options', ea.STATE_SET),
		exposes.enum('reverse_direction', ea.STATE_SET, ['forward', 'back'])
		    .withDescription('Reverse the motor direction'),
		exposes.enum('border', ea.STATE_SET, ['up', 'down', 'up_delete', 'down_delete', 'remove_top_bottom']),
		exposes.enum('click_control', ea.STATE_SET, ['up', 'down'])
		    .withDescription('Single motor steps'),
		exposes.binary('fault_alarm', ea.STATE, true, false),
    ],
    meta: {
        // All datapoints go in here
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverterBasic.lookup({ 'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2) })],
            [2, 'position', tuya.valueConverter.raw],
	        [3, 'position', tuya.valueConverter.raw],
            [5, 'reverse_direction', tuya.valueConverterBasic.lookup({ 'forward': tuya.enum(0), 'back': tuya.enum(1) })],
            [12, 'motor_fault', tuya.valueConverter.trueFalse1],
            [13, 'battery', tuya.valueConverter.raw],
            [16, 'border', tuya.valueConverterBasic.lookup({ 'up': tuya.enum(0), 'down': tuya.enum(1), 'up_delete': tuya.enum(2), 'down_delete': tuya.enum(3), 'remove_top_bottom': tuya.enum(4) })],
            [20, 'click_control', tuya.valueConverterBasic.lookup({ 'up': tuya.enum(0), 'down': tuya.enum(1) })],
        ],
    },
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
- TuYa api doesn't not support reading/refresh, change to `e.cover_position().setAccess('position', ea.STATE_SET),`
- About the invert, doesn't `reverse_direction` do this already? (natively on the device)

**Comment by jracoma** [comment]
Reverse direction does but the invert_cover flips the open/close states. It's not a huge deal, I can handle it specifically in HA.

`Inverts the cover position, false: open=100,close=0, true: open=0,close=100 (default false).`

**Comment by Koenkk** [comment]
I've added this now, update to the latest dev branch (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) and:
- Use: `[2, 'position', tuya.valueConverter.coverPosition],`
- Below `onEvent: tuya.onEventSetTime,` add `options: [exposes.options.invert_cover()],`

**Comment by jracoma** [comment]
Sorry for the delay. I've pulled the dev branch and everything looks good. Thanks for all the help!

**Comment by Koenkk** [comment]
Should be fixed now.

**Comment by jracoma** [comment]
Looks good. Thank you.

**Comment by Koenkk** [comment]
@jracoma can you post the final ext converter?

**Comment by jracoma** [comment]
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
// const tuya = require('zigbee-herdsman-converters/lib/tuya');
const tuya = require('../../data/tuya');

const tzDatapoint = {
    ...tuya.tz.datapoints,
    key: ['state', 'position', 'reverse_direction', 'motor_fault', 'battery', 'border', 'click_control'],
}

const definition = {
	fingerprint: [
		{
			modelID: 'TS0601',
			manufacturerName: '_TZE200_68nvbio9',
		},
	],
	model: 'ZM16EL-03/33',
	vendor: 'Zemismart',
	description: 'Smart tubular motor',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tzDatapoint],
    onEvent: tuya.onEventSetTime,
    options: [exposes.options.invert_cover()],
    configure: tuya.configureMagicPacket,
	exposes: [
	e.battery(),
        e.cover_position(),
	exposes.composite('options', 'options', ea.STATE_SET),
	exposes.enum('reverse_direction', ea.STATE_SET, ['forward', 'back'])
            .withDescription('Reverse the motor direction'),
	exposes.enum('border', ea.STATE_SET, ['up', 'down', 'up_delete', 'down_delete', 'remove_top_bottom']),
	exposes.enum('click_control', ea.STATE_SET, ['up', 'down'])
            .withDescription('Single motor steps'),
        exposes.binary('fault_alarm', ea.STATE, true, false),
    ],
    meta: {
        // All datapoints go in here
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverterBasic.lookup({ 'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2) })],
            [2, 'position', tuya.valueConverter.coverPosition],
            [3, 'position', tuya.valueConverter.raw],
            [5, 'reverse_direction', tuya.valueConverterBasic.lookup({ 'forward': tuya.enum(0), 'back': tuya.enum(1) })],
            [12, 'motor_fault', tuya.valueConverter.trueFalse1],
            [13, 'battery', tuya.valueConverter.raw],
            [16, 'border', tuya.valueConverterBasic.lookup({ 'up': tuya.enum(0), 'down': tuya.enum(1), 'up_delete': tuya.enum(2), 'down_delete': tuya.enum(3), 'remove_top_bottom': tuya.enum(4) })],
            [20, 'click_control', tuya.valueConverterBasic.lookup({ 'up': tuya.enum(0), 'down': tuya.enum(1) })],
        ],
    },
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
