### PR TITLE
Add ringbell cluster for lumi.lock.aq1

### PR DESCRIPTION
**Pull request by SchumyHao**
Signed-off-by: SchumyHao <schumyhaojl@126.com>

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by ulug79** [comment]
this lock model does not have a bell function

**Comment by SchumyHao** [comment]
> this lock model does not have a bell function

Hi friend
This model lock will bell when lock be force removed from out door
I tested this function by dissemble my lock with battery inserted.

**Comment by ulug79** [comment]
Hi,

Now it’s clear, this is an anti-theft alarm.  Thanks for your work.  I have such a model.

**Pull request merged**
