### PR TITLE
Update enbrighten.js

### PR DESCRIPTION
**Pull request by nickctn**
Add support for 43078 In-Wall Switch
https://www.amazon.com/Enbrighten-QuickFit-SimpleWire-Directly-43078/dp/B08Q4F43HT

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by nickctn** [comment]
By any chance, would you know how to get the power monitoring from this device? and also for 43082?

**Comment by nickctn** [comment]
I think this is what you're looking for.  Here's for one of my 43078:
`{"id":12,"type":"Router","ieeeAddr":"0x588e81fffe335523","nwkAddr":20395,"manufId":4388,"manufName":"Jasco Products","powerSource":"Mains (single phase)","modelId":"43078","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,1794,2821],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x000d6f001740aeb2","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}},"2":{"profId":260,"epId":2,"devId":259,"inClusterList":[0,3,2821],"outClusterList":[3,6],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":18,"stackVersion":101,"hwVersion":2,"zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1644940196210,"defaultSendRequestWhen":"immediate"}`

And here's one of my 43082:
`{"id":13,"type":"Router","ieeeAddr":"0x588e81fffe00707d","nwkAddr":9917,"manufId":4388,"manufName":"Jasco Products","powerSource":"Mains (single phase)","modelId":"43082","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,1794,2821],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"43082","manufacturerName":"Jasco Products","powerSource":1,"zclVersion":3,"appVersion":18,"stackVersion":101,"hwVersion":2}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x000d6f001740aeb2","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x000d6f001740aeb2","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}},"2":{"profId":260,"epId":2,"devId":260,"inClusterList":[0,3,2821],"outClusterList":[3,6,8],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":18,"stackVersion":101,"hwVersion":2,"zclVersion":3,"interviewCompleted":true,"meta":{"configured":1461352984},"lastSeen":1644938957639,"defaultSendRequestWhen":"immediate"}`

**Comment by nickctn** [comment]
I think I have it partly figured out.  I have modified my code to this:

> const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
> const tz = require('zigbee-herdsman-converters/converters/toZigbee');
> const exposes = require('zigbee-herdsman-converters/lib/exposes');
> const reporting = require('zigbee-herdsman-converters/lib/reporting');
> const extend = require('zigbee-herdsman-converters/lib/extend');
> const e = exposes.presets;
> module.exports = [
>     {
>         zigbeeModel: ['43078'],
>         model: '43078',
>         vendor: 'Enbrighten',
>         description: 'Zigbee in-wall smart switch',
>         extend: extend.switch(),
>         configure: async (device, coordinatorEndpoint, logger) => {
>             const endpoint = device.getEndpoint(1);
>             await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'seMetering']);
>             await reporting.onOff(endpoint);
>             await reporting.readMeteringMultiplierDivisor(endpoint);
>             await reporting.instantaneousDemand(endpoint);
>         },
>         exposes: [e.switch(), e.power(), e.energy()],
>     },
> ];

Now I can see the power readings in Zigbee2mqtt, but I get this in the logs:

debug Received Zigbee message from 'Entry Hall Light', type 'attributeReport', cluster 'seMetering', data '{"instantaneousDemand":321}' from endpoint 1 with groupID 0
debug No converter available for '43078' with cluster 'seMetering' and type 'attributeReport' and data '{"instantaneousDemand":321}'

**Comment by Koenkk** [comment]
Great, now below `extend: extend.switch(),` add `toZigbee: [...extend.switch().toZigbee, fz.metering],`

**Comment by nickctn** [comment]
So I've done that and restarted a couple of times, but still seeing this in my logs:

```
info MQTT publish: topic 'zigbee2mqtt/Entry Hall Light', payload '{"energy":null,"linkquality":255,"power":24.5,"state":"ON"}'
debug Received Zigbee message from 'Entry Hall Light', type 'attributeReport', cluster 'seMetering', data '{"instantaneousDemand":322}' from endpoint 1 with groupID 0
debug No converter available for '43078' with cluster 'seMetering' and type 'attributeReport' and data '{"instantaneousDemand":322}'
```

The change that I did notice was that I'm now seeing the energy sensors in my dashboard, but they are all null...

**Comment by Koenkk** [comment]
Whoops, `toZigbee: [...extend.switch().toZigbee, fz.metering],` should be `fromZigbee: [...extend.switch().fromZigbee, fz.metering],`

**Comment by nickctn** [comment]
Ok everything seems to work properly now.  I'll make the changes to main code and send another pull request later.

If I want to test to see if these modifications would also work for the 43082, how would I go about that since that model already exists in the enbrighten.js code.

**Comment by Koenkk** [comment]
You can use an external converter (which overrides the zigbee-herdsman-converters definition): https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-adding-converter-s-for-your-device

**Pull request merged**
