### PR TITLE
ledvance-panel-tw-620-ugr19

### PR DESCRIPTION
**Pull request by FlorentBrianFoxcorner**
Adding zigbeeModel 'Panel TW 620 UGR19'
Combination of LED Driver model 'GPDRPLOP401100CE' and 'Panel TW LED
625'

### CODE REVIEW

**Comment by sjorge** [comment]
Can you also add the color_temp range? https://github.com/Koenkk/zigbee-herdsman-converters/pull/2357#issuecomment-797574094 you might need to use endpoint1 for ledadvance instead of endpoint11 though.

**Comment by FlorentBrianFoxcorner** [comment]
@sjorge done

**Review by sjorge — APPROVED** [review]
LGTM

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
