### PR TITLE
Fixed unit errors for water level sensof ME201WZ

### PR DESCRIPTION
**Pull request by vit-um**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Jathur55800** [comment]
Hello

I have this famous ME210WZ sensor but the data reported seems to me to be incorrect.

Sonoff E Key Flashed Ember
Zigbee 2MQTT Operational

I discovered this fix but I don't know how to apply it 

Thank you By Advance

David

**Comment by vit-um** [comment]
> Hello
> 

Hello

Testing the converter on HamGeek POE Zigbee 3.0 Coordinator HamGeek CC2652P and through the native gateway Tuya. The device works identically in these two cases. 

There are problems with the level sensor ME201WZ, it does not correctly determine the water level in percent, the setting of the upper water level value does not work. But these are already questions for the manufacturer of ME201WZ.



> I have this famous ME210WZ sensor but the data reported seems to me to be incorrect.
> 
> Sonoff E Key Flashed Ember Zigbee 2MQTT Operational
> 
> I discovered this fix but I don't know how to apply it
> 
> Thank you By Advance
> 
> David

**Comment by Jathur55800** [comment]
Thanks for your answer !Return to seller ? Ou waiting....What do you think is the Best ??Cordially Envoyé de mon mobile
-------- Message d'origine --------De : VITALII UMANETS ***@***.***> Date : 23/01/2025  13:27  (GMT+01:00) À : Koenkk/zigbee-herdsman-converters ***@***.***> Cc : Jathur55800 ***@***.***>, Comment ***@***.***> Objet : Re: [Koenkk/zigbee-herdsman-converters] Fixed unit errors for water level sensof ME201WZ (PR #8265) 

Hello

Hello
Testing the converter on HamGeek POE Zigbee 3.0 Coordinator HamGeek CC2652P and through the native gateway Tuya. The device works identically in these two cases.
There are problems with the level sensor ME201WZ, it does not correctly determine the water level in percent, the setting of the upper water level value does not work. But these are already questions for the manufacturer of ME201WZ.

I have this famous ME210WZ sensor but the data reported seems to me to be incorrect.
Sonoff E Key Flashed Ember Zigbee 2MQTT Operational
I discovered this fix but I don't know how to apply it
Thank you By Advance
David

**Comment by vit-um** [comment]
> Thanks for your answer !Return to seller ? Ou waiting....What do you think is the Best ??

Liquid depth it measures correctly.
This is enough for me, see screenshot

**Pull request merged**
