### PR TITLE
Add TCP Smart variant of Siterwell GS361A-H04

### PR DESCRIPTION
**Pull request by Prouser123**

### CODE REVIEW

**Comment by Prouser123** [comment]
:wave:

It doesn't look like the fingerprint does anything, should I remove it? 

Thanks!

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of your device?

**Comment by Prouser123** [comment]
@Koenkk here's the database.db entry for one of the devices:

```json
{
    "id": 34,
    "type": "EndDevice",
    "ieeeAddr": "0x****************",
    "nwkAddr": 12482,
    "manufId": 0,
    "manufName": "_TYST11_czk78ptr",
    "powerSource": "Battery",
    "modelId": "zk78ptr\u0000",
    "epList": [
        1
    ],
    "endpoints": {
        "1": {
            "profId": 260,
            "epId": 1,
            "devId": 0,
            "inClusterList": [
                0,
                3
            ],
            "outClusterList": [
                3,
                25
            ],
            "clusters": {
                "genBasic": {
                    "attributes": {
                        "modelId": "zk78ptr\u0000",
                        "manufacturerName": "_TYST11_czk78ptr",
                        "powerSource": 3,
                        "zclVersion": 3,
                        "appVersion": 72,
                        "stackVersion": 0,
                        "hwVersion": 1,
                        "dateCode": "20180727"
                    }
                }
            },
            "binds": [],
            "configuredReportings": [],
            "meta": {}
        }
    },
    "appVersion": 72,
    "stackVersion": 0,
    "hwVersion": 1,
    "dateCode": "20180727",
    "zclVersion": 3,
    "interviewCompleted": true,
    "meta": {},
    "lastSeen": 1661846682545,
    "defaultSendRequestWhen": "immediate"
}
```

**Comment by Koenkk** [comment]
> It doesn't look like the fingerprint does anything, should I remove it?

Yes

**Comment by Prouser123** [comment]
Thank you, I've reverted that change.

**Comment by Koenkk** [comment]
Thanks!

**Comment by james-fry** [comment]
Oh nice. this looks like it adds support for the TRV I am trying to add support for in this issue: https://github.com/Koenkk/zigbee2mqtt/issues/13820

But... when I checked siterwell.js after the PR is merged I dont see the "modelId": "zk78ptr\u0000" and "manufacturerName": "_TYST11_czk78ptr" are added there...

There are two versions of the TRV based different tuya module, with Zigbee IDs: 
- "zk78ptr"; "_TYST11_czk78ptr"
- "_TZE200_czk78ptr"; "TS0601"

@Prouser123 Has only the TS0601 version been added by your PR?

**Comment by james-fry** [comment]
I tried the updated siterwell.js as an extrernal converter with my TCP TRV type zk78ptr\u0000.
Z2M hassio addon version 1.27.2-1
I have exactly the same issues as mentioned in my issue raised to support this TRV https://github.com/Koenkk/zigbee2mqtt/issues/13820

i.e.:

- Battery is showing Null
- States showing as off / auto / heat. States should be manual / away / auto - in that order

**Comment by Prouser123** [comment]
> I tried the updated siterwell.js as an extrernal converter with my TCP TRV type zk78ptr\u0000.
> 
> Z2M hassio addon version 1.27.2-1
> 
> I have exactly the same issues as mentioned in my issue raised to support this TRV https://github.com/Koenkk/zigbee2mqtt/issues/13820
> 
> 
> 
> i.e.:
> 
> 
> 
> - Battery is showing Null
> 
> - States showing as off / auto / heat. States should be manual / away / auto - in that order
> 
> 
> 
> @Prouser123  is battery and state working for you?

Hi, for me the battery, running state and position are Null, n/a and n/a respectively. States also show as off/auto/heat.

This issue might be helpful (maybe related?) Koenkk/zigbee2mqtt#12870?

**Comment by Prouser123** [comment]
> Oh nice. this looks like it adds support for the TRV I am trying to add support for in this issue: https://github.com/Koenkk/zigbee2mqtt/issues/13820
> 
> 
> 
> But... when I checked [siterwell.js after the PR is merged](https://github.com/Koenkk/zigbee-herdsman-converters/blob/3767b3c1986e4c22e7137252968ea86f1cf055c9/devices/siterwell.js) I dont see the "modelId": "zk78ptr\u0000" and "manufacturerName": "_TYST11_czk78ptr" are added there...
> 
> 
> 
> There are two versions of the TRV based different tuya module, with Zigbee IDs: 
> 
> - "zk78ptr"; "_TYST11_czk78ptr"
> 
> - "_TZE200_czk78ptr"; "TS0601"
> 
> 
> 
> @Prouser123 Has only the TS0601 version been added by your PR?

Hi, my TRVs are 
modelId: zk78ptr\u0000 manufacturerName: TYST11_czk78ptr

Adding the modelId (first line change) was enough for it to be picked up as supported in zigbee2mqtt.

Thanks!

**Comment by james-fry** [comment]
> > I tried the updated siterwell.js as an extrernal converter with my TCP TRV type zk78ptr\u0000.
> > Z2M hassio addon version 1.27.2-1
> > I have exactly the same issues as mentioned in my issue raised to support this TRV [Koenkk/zigbee2mqtt#13820](https://github.com/Koenkk/zigbee2mqtt/issues/13820)
> > i.e.:
> > 
> > * Battery is showing Null
> > * States showing as off / auto / heat. States should be manual / away / auto - in that order
> > 
> > @Prouser123  is battery and state working for you?
> 
> Hi, for me the battery, running state and position are Null, n/a and n/a respectively. States also show as off/auto/heat.
> 
> This issue might be helpful (maybe related?) [Koenkk/zigbee2mqtt#12870](https://github.com/Koenkk/zigbee2mqtt/issues/12870)?

Thanks @Prouser123 

So looks like we have the same devices and same issues :)
Just picked a bunch of these up from screwfix so hoping to get as good support as possible ready for the winter of discontent.

From research [on the ZHA support for these TCP devices](https://github.com/zigpy/zha-device-handlers/issues/1180) (_TYST11_czk78ptr), I think that they dont report valve position or running state. They do however apparently report if there is valve fault and if window is detected open (both boolean) but I wasnt able to see what should be the tuya datapoints to support these. With ZHA support for this valve, running state is calculated based on rules rather than sent from the device. (I guess based on system mode and set point vs local temperature)

I had  better success with a converter cloned from the [alecto device js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/ea55b9118c8c1a5b4aee422697821524582c1657/devices/alecto.js).

This removes the non-working valve postion and running state, but with the issues I mentioned before - battery still null and the system mode not aligned with the values in the tcp and siterwell manuals (away, manual, auto). 

Also noting that as of [HA 2022.9](https://github.com/home-assistant/core/pull/76299) mqtt climate device mode "away" is deprecated and removed in favour of "preset_mode", so something would need to be done here, too.

This is my mostly working converter:

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

module.exports = [
    {
        fingerprint: [
            {modelID: 'zk78ptr\u0000', manufacturerName: '_TYST11_czk78ptr'},
        ],
        model: 'WTRV',
        vendor: 'TCP Smart',
        description: 'Radiator valve with thermostat',
        fromZigbee: [
            fz.tuya_thermostat, 
            fz.ignore_basic_report,
            fz.tuya_data_point_dump,
        ],
        meta: {
            tuyaThermostatSystemMode: tuya.thermostatSystemModes4,
            tuyaThermostatPreset: tuya.thermostatPresets,
            tuyaThermostatPresetToSystemMode: tuya.thermostatSystemModes4
        },
        toZigbee: [
            tz.tuya_thermostat_child_lock,
            tz.siterwell_thermostat_window_detection,
            tz.tuya_thermostat_current_heating_setpoint, 
            tz.tuya_thermostat_system_mode,
            tz.tuya_data_point_test,
        ],
        exposes: [e.child_lock(), 
                  e.window_detection(), 
                  e.battery(), 
                  exposes.climate()
                  .withSetpoint('current_heating_setpoint', 5, 30, 0.5, ea.STATE_SET)
                  .withLocalTemperature(ea.STATE)
                  .withSystemMode(['off', 'auto', 'heat'], ea.STATE_SET)],
    }
];

```

I dont have a tuya bridge, so I can't experiment further to work out the DPs for the missing stuff :(

**Pull request merged**
