### PR TITLE
Remove redundant code Sinope th1124zb

### PR DESCRIPTION
**Pull request by MattL0**

### CODE REVIEW

**Comment by Koenkk** [comment]
Why is this redundant?

**Comment by MattL0** [comment]
This is the exact same code pasted twice 

            await reporting.readMeteringMultiplierDivisor(endpoint);
            await reporting.currentSummDelivered(endpoint, {min: 10, max: 303, change: [1, 1]});
            try {
                 await reporting.instantaneousDemand(endpoint, {min: 10, max: 304, change: 1});
             } catch (error) {/* Do nothing*/}

             await reporting.readMeteringMultiplierDivisor(endpoint);
             await reporting.currentSummDelivered(endpoint, {min: 10, max: 303, change: [1, 1]});
             try {
                 await reporting.instantaneousDemand(endpoint, {min: 10, max: 304, change: 1});
             } catch (error) {/* Do nothing*/}

**Comment by Koenkk** [comment]
I should look better next time, thanks! 😄

**Comment by MattL0** [comment]
😆

**Pull request merged**
