### PR TITLE
Added ROB_200-017-1 device.

### PR DESCRIPTION
**Pull request by Chamondgl**
Added ROB_200-017-1 device.

### CODE REVIEW

**Comment by Chamondgl** [comment]
I'm having trouble with the following error. 

`Error:   174:1    error  This line has a length of 146. Maximum allowed is 140  max-len

I've tested the file locally and it works. I've fixed the comma error.

**Comment by Koenkk** [comment]
Thanks!

**Comment by MPowerData** [comment]
@Koenkk , great to see support for this device!

How can I use this in the latest zigbee2mqtt docker image?

**Comment by Koenkk** [comment]
It is available in the latest-dev (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by MPowerData** [comment]
Awesome, thanks.

**Pull request merged**
