### PR TITLE
Correct lux calculation

### PR DESCRIPTION
**Pull request by Erelen-Laiquendi**
Based on https://github.com/Koenkk/zigbee2mqtt/issues/2837

### CODE REVIEW

**Comment by Koenkk** [comment]
As this will be a breaking change (which I wan't to avoid for now), I've made this a configurable option. To enable it set `lux: true` in the device options (https://www.zigbee2mqtt.io/information/configuration.html#example).

Let me know if this is OK for you and I will merge it.

**Comment by Erelen-Laiquendi** [comment]
But just for me - it's ok anyway, but...

I think, it's bad practice to show strange "zigbee raw value" by default. And, of couse, it's bad practice to show raw value with "unit = lx" - because it's not lx.

I don't know any context, when user needs "zigbee raw value". So, your solution turns into "we have a bug because it was in first version".

**Comment by Koenkk** [comment]
I completely agree, but as this already has been in from zigbee2mqtt 0.1 many people assume the much higher values in e.g. automations. Therefore we can only convert it completely in zigbee2mqtt 2.0.0.

**Comment by Erelen-Laiquendi** [comment]
Ok.
Now, waiting for 2.0 :)

**Comment by Erelen-Laiquendi** [comment]
Anyway, I will be good to remove "lx" as unit, unless `lux: true` - because in other case it is actual error.
And, may be, unless `lux: true`, set output real lx value to attribute?

**Comment by Koenkk** [comment]
@Erelen-Laiquendi yes I agree, what about in addition to `illuminance` also return `illuminance_lux` here? (and remove the option?)

**Comment by Erelen-Laiquendi** [comment]
In this case (real lux only in attribute) I can't use it natively in HA numeric state triggers and conditions. I can use only template condition (numeric state is more clear and convenient), or I can create template sensor, than represents this attribute and use it (but it's ugly, and in this way, I can do it now, without any z2m modification - with formula in template sensor).

===

Option, that change z2m sensor state to real lux, give me way to use illuminance data without any workarounds and ugly hacks.

**Comment by Koenkk** [comment]
No, in that case we will also discover a new sensor to home assistant called `illuminance_lux` which can be used the same was as you use `illuminance` now.

**Comment by Erelen-Laiquendi** [comment]
Hm, looks like best solution.

(I can't explain, why I think about attribute after you previous comment ^)

**Comment by Koenkk** [comment]
Thanks!

**Comment by sjorge** [comment]
Are we sure this is correct for the RTCGQ11LM? I have only seen the value range for 0-1000 on mine, making this effectively always have a illuminance_lux of 0 with the code as it is nwo?

**Comment by Koenkk** [comment]
@sjorge looks like that the value indeed is already in lux:

image

**Comment by sjorge** [comment]
So we shouldn’t the reverse for this sensor? Have illuminance_lux set directly and calculate the illuminance value?

**Comment by Koenkk** [comment]
Fixed, thanks!

**Comment by sjorge** [comment]
Just to double check and avoid confusion on my part:
- RTCGQ11LM will be have both normal and _lux set to the lux value (as it came in from the sensor)
- other sensor will have normal and _lux set to different values?

If so, won’t that be a bit confusion as one of them will then return different data than the rest? (Non _lux for the RT...)

(On phone does excuse the bad formatting)

**Comment by Koenkk** [comment]
@sjorge yes, but changing this will result in a breaking change.

For now always use `illuminance_lux`, after zigbee2mqtt 2.0.0 `illuminance_lux` will replace `illuminance`.

**Comment by sjorge** [comment]
Ack, since the sensor I am using already has the lux value as illuminance, I can just keep the things as is.

Do you have a list of things to deprecate In 2.x?
We might want to drop the eurotronic stuff marked as deprecated too then.

~ sjorge

**Comment by Koenkk** [comment]
@sjorge don't have a list yet, but searching for `deprecated` or `obsolete` in the zigbee2mqtt/zigbee-herdsman-converters code base will give an idea (zigbee2mqtt 2.0.0 is not really close either).

**Comment by sjorge** [comment]
Great, then it is already tagged in the comment... (but search didn't find it 🤷‍♂ )

**Pull request merged**
