### PR TITLE
fix: _TZE284_g2e6cpnw / _TZE284_sgabhwa6 datapoint mappings

### PR DESCRIPTION
**Pull request by rare-magma**
The mapping applied in https://github.com/Koenkk/zigbee-herdsman-converters/pull/7812 seems to match this device better than the previous one created in https://github.com/Koenkk/zigbee-herdsman-converters/pull/7609

### CODE REVIEW

**Comment by Koenkk** [comment]
The datapoints are very similar to those of the `NAS-STH02B2`, could try with that definition, and if it works move `NAS-STH02B2` to `tuya.ts` and add a `tuya.whitelabel` there?

**Comment by rare-magma** [comment]
@Koenkk these 2 particular devices don't emit the datapoints 1 ('Soil electrical conductivity') and 4 ('Soil fertility'), I think it makes sense to have different definitions

**Comment by Koenkk** [comment]
I see, thanks!

**Comment by setfire2** [comment]
My `_TZE284_sgabhwa6` works really well with this patch. Only the battery state does not show up but I can live with it as long as the battery level in percent works, which it does. Soil Moisture changes are also noticed in 1% steps. Almost perfect, thanks a lot! Id' love to see this in the next release.

**Comment by setfire2** [comment]
@goberhammer, @rare-magma: what is your battery level showing? Mine is showing 63,6% for a week already. This must not be wrong but I find it a little suspicious.

**Comment by goberhammer** [comment]
Hi @setfire2 , I've waited a few days before responding to you to be sure: both my battery and my battery state read as "N/S" in the Exposes tab and are not present in the state packet

**Comment by setfire2** [comment]
Thanks for the info @goberhammer. It seems that there still an issue with the battery information for that device. Here's what my panel for that sensor looks like:
moisturesensor

**Pull request merged**
