### PR TITLE
support for _TZ3000_mrpevh8p

### PR DESCRIPTION
**Pull request by Chartreusito**
Added support for _TZ3000_mrpevh8p which was recognized as a TS0041 wall switch.
Tried an external converter successfully with this config.

Picture PR is here : https://github.com/Koenkk/zigbee2mqtt.io/pull/2225

### CODE REVIEW

**Comment by Koenkk** [comment]
This can be merged with https://github.com/Koenkk/zigbee-herdsman-converters/blob/e283152b6a77096fd0217ec91b2c8045a1ff0582/src/devices/tuya.ts#L1873

**Comment by Chartreusito** [comment]
I didn't realize whitelabel supported their own device pictures 🤩

**Comment by paris21aek** [comment]
I have problem with this device. Z2m didn't recognized it. Get a ''not supported" message. What i can do to fix it?

**Comment by paris21aek** [comment]
@Koenkk can you see it pls because I have 4 of this button and when I pair them says was unsupported.

**Comment by Koenkk** [comment]
are you running the latest z2m version? if yes, provide the dara/database.db entry of your device

**Comment by OJBender** [comment]
Like this? 

``cat database.db | grep a4c1389c9d37ab2
{"id":97,"type":"Unknown","ieeeAddr":"0xa4c1389c9d37ab2b","nwkAddr":53424,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{},"lastSeen":1701506182727,"defaultSendRequestWhen":"immediate"}``

From the outside the button looks like the white mono colored and supported SH-SC07 as in the [list of supported devices](https://www.zigbee2mqtt.io/devices/SH-SC07.html#tuya-sh-sc07) run by a 2450 battery.

**Comment by Koenkk** [comment]
`"interviewCompleted":false` -> pairing failed, try to force remove it and pair again: https://www.zigbee2mqtt.io/guide/faq/#interview-fails

**Comment by OJBender** [comment]
Tried 20 times. Cold reset, button reset. Pressed function button one a second etc. 
Interview fails after 30-40 seconds. Would it make sense to wireshark the interview communication? Debug mode? SONOFF P chip coordinator has (latest) revision 20230507. Maybe I ran into a fake or covertly changed TUYA buton version.

**Pull request merged**
