### PR TITLE
LocalTemperatureCalibration on TRVs to float and change max range

### PR DESCRIPTION
**Pull request by KartoffelToby**
For the issue #3488

This PR will change the calibration resolution to match the local temp resolution, it also make the max range wider to avoid issues that appeared since the last release

### CODE REVIEW

**Comment by Padm59** [comment]
Please change change it so that we can use higher calibration precision!

**Comment by Koenkk** [comment]
Thanks!

**Comment by brunoleon** [comment]
Hello and thanks for your work.

I rebuilt zigbee2mqtt using tag 14.0.348 where this PR should be present, but the step is still 1 instead of 0.1.
Is there anything else to do to be able to use this code ?

Thanks

**Comment by KartoffelToby** [comment]
@brunoleon I have Eurotronics Spirits, the 0.1 calibration will work with this patch for them and should work for others too, other TRVs have the problem of decimal to hex convert problems based on this PR. #3527 But i need help there

**Comment by brunoleon** [comment]
OK @KartoffelToby I'll check how to test it next week probably

**Comment by Se7enair** [comment]
@KartoffelToby I changed to the newest dev. The calibrationvalues are now float, but they where even with the latest stable. But the temperature from the thermostat is still only 0.5° steps.
I use also Eurotronic Thermostats

Zigbee2MQTT Version
1.22.1-dev commit: f9aa525

**Pull request merged**
