### PR TITLE
fix issue battery (200%) for VES-ZB-REM-013

### PR DESCRIPTION
**Pull request by devildant**
i apply this fix because the battery on [VES-ZB-REM-013](https://www.zigbee2mqtt.io/devices/VES-ZB-REM-013.html#vesternet-ves-zb-rem-013) show me 200%

hi @martyn-vesternet, here is a new fix for Vesternet, for me the battery show me 200%, but I don't know how to split configurations correctly

### CODE REVIEW

**Comment by martyn-vesternet** [comment]
@devildant this is one of the changes I'm currently working on, it only effects newer versions of the device

**Comment by devildant** [comment]
> @devildant this is one of the changes I'm currently working on, it only effects newer versions of the device

@martyn-vesternet hoo ok, so can I close this pull request? 

I kept trying I can't find how to split by version without changing the device name

**Comment by martyn-vesternet** [comment]
@devildant yes, please close for now as I'm just submitting a PR to cover all my recent updates

**Comment by devildant** [comment]
> @devildant yes, please close for now as I'm just submitting a PR to cover all my recent updates


ok I'll do that :)

**Pull request closed without merging**
