### PR TITLE
Add _TZE200_5toc8efa to BHT-002-GCLZB

### PR DESCRIPTION
**Pull request by VoltickVL**
Add support _TZE200_5toc8efa to fix moesLocalTemp

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by VoltickVL** [comment]
Koennk, i think need also edit this code section:
```shell
            case tuya.dataPoints.moesHeatingSetpoint:
                return {current_heating_setpoint: value};
```
Because current_heating_setpoint don't work again :(

**Comment by Koenkk** [comment]
Could you make a PR again?

**Comment by VoltickVL** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/5328

**Comment by VoltickVL** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/5328/commits/48601e8e5c81ded6f1dc12dc06bd6f7aa4b7112f

**Comment by VoltickVL** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/5334

**Pull request merged**
