### PR TITLE
Add support for Skydance 5-in-1 LED Controller WZ5

### PR DESCRIPTION
**Pull request by blazewicz**
Adds support for generic Tuya light source device as created in https://iot.tuya.com online creator.

closes https://github.com/Koenkk/zigbee2mqtt/issues/6867

### CODE REVIEW

**Comment by blazewicz** [comment]
In current state it requires #2453

**Comment by kirovilya** [comment]
Hello. Good work. Checked the RGB mode (manufacturerName: '_TZE200_9hghastn') for this device - it works!
But for RGBW mode (manufacturerName: '_TZE200_3thxjahu'), I did not understand how to manage a separate white channel.

**Comment by andreypolyak** [comment]
Hi @blazewicz ,
Thanks for the work!
Do you have any plans to finalize converter and merge it to the code?

Regards,
Andrey

**Comment by prondzyk** [comment]
> Hi @blazewicz ,
> Thanks for the work!
> Do you have any plans to finalize converter and merge it to the code?
> 
> Regards,
> Andrey

Hello @blazewicz 

Same question as above :) 

Regards

**Comment by SandrRu** [comment]
> Hi @blazewicz ,
> Thanks for the work!
> Do you have any plans to finalize converter and merge it to the code?
> 
> Regards,
> Andrey

Any progress for this controller?
With best regards
Alexandr

**Comment by lustyffh** [comment]
Hi All,

I have exact same model - WZ5. Zigbee+RF. However, the problem with my instance is that it's always identified by the same `manufacturerName` regardless of the mode set. On mine `manufacturerName` is always `_TZE200_9mt3kgn0`. Therefore proposed Commit won't work in my case. I only needed DIM mode. For that to work adding another fingerprint to the `zigbee-herdsman-converters/blob/master/devices/tuya.js` under `TS0601_dimmer` made the trick.

**Comment by chris173972** [comment]
Hi All, 

I have the WZ5 Zigbee+RF too but in RGB+CCT Mode. It identifies it's self as this below. Any progress with this integration or how to fix it?
```Zigbee model 'TS0601' and manufacturer name '_TZE200_aa9awrng``` 
Thanks in advance
Chris

**Comment by SandrRu** [comment]
Also WZ5 RGB+CCT
Model TS0601
Manufacture name _TZE200_mde0utnv

**Comment by manwe-pl** [comment]
Also have `Zigbee model 'TS0601' and manufacturer name '_TZE200_aa9awrng'`. Any chances for this PR to be merged?

**Pull request closed without merging**
