### PR TITLE
Add QS-Zigbee-S05-LN (1 gang switch module with neutral wire)

### PR DESCRIPTION
**Pull request by mjamro**
Add QS-Zigbee-S05-LN which is a 1 channel version of QS-Zigbee-S04-2C-LN.

### CODE REVIEW

**Comment by mjamro** [comment]
Any plans on merging that?

**Comment by Koenkk** [comment]
> Any plans on merging that?

Sorry, wrote the review comment but forget to submit it.

**Comment by tranzeo** [comment]
Also it's working fine with:
   ```
{
        fingerprint: [{modelID: 'TS0003', manufacturerName: '_TYZB01_ncutbjdi'}],
        model: 'QS-Zigbee-S05-LN',
        vendor: 'Lonsonho',
        description: '1 gang switch/socket module with neutral wire',
        supports: 'on/off',
        fromZigbee: [fz.ignore_basic_report, fz.on_off],
        toZigbee: [tz.on_off],
        endpoint: (device) => {
            return {'l1': 1};
        },
        meta: {configureKey: 1, multiEndpoint: true},
        configure: async (device, coordinatorEndpoint) => {
            await bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
        },
    },
```
It was tested over 5 weeks.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
