### PR TITLE
add support for TS0505

### PR DESCRIPTION
**Pull request by Hykario**
Hello,
this will add support for TS0505 

I Got another Question. This GU10 is supposed to be Tuya but it works with modern extends.
So i was wondering if the TS0505B and other versions of this also works without the Tuya convert.
I got one at Home and will try later.

### CODE REVIEW

**Comment by Koenkk** [comment]
Does this device not work out of the box with z2m 1.42.0?

**Comment by Koenkk** [comment]
I see, could you add this to `tuya.ts` instead and use `Tuya` as the vendor.

**Comment by Hykario** [comment]
okey added it to tuya as tuya device. i hope it is correct if not let me know what to change

**Comment by Koenkk** [comment]
Thanks!

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `TS0505.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by fredericgermain** [comment]
Thanks for the PR!
I just wanted to add that the B22 here is also a TS0505
https://www.aliexpress.com/item/1005007212350943.html

**Pull request merged**
