### PR TITLE
Added converter for LeTV 8key FreePad mod

### PR DESCRIPTION
**Pull request by xyzroe**
[LeTV 8key FreePad mod](https://modkam.ru/?p=1791)

### CODE REVIEW

**Comment by Koenkk** [comment]
This looks very similar to https://github.com/Koenkk/zigbee-herdsman-converters/commit/4170fdcd93c40aed3d372935b8c07e0bc8cfd40e , @nurrik should that one be reverted?

**Comment by xyzroe** [comment]
@Nurrik used incorrect model id so it won’t work.
In addition, when using one converter, the number of buttons is incorrect, the image is incorrect., picture and keys count.
It seems logical to me to use different converters for different devices, even if the firmware is almost the same.

**Comment by nurikk** [comment]
> This looks very similar to [4170fdc](https://github.com/Koenkk/zigbee-herdsman-converters/commit/4170fdcd93c40aed3d372935b8c07e0bc8cfd40e) , @nurikk should that one be reverted?

It's the same firmware flashed into different devices

**Comment by Koenkk** [comment]
good, thanks!

**Pull request merged**
