### PR TITLE
New Device TS0726

### PR DESCRIPTION
**Pull request by evangelo18**
4 gang switch with neutral wire

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by evangelo18** [comment]
@Koenkk  I ended up using 'power_on_behavior_2' however the database entry is as below. Have I done it correctly?

{"id":79,"type":"Router","ieeeAddr":"0x187a3efffe0f6058","nwkAddr":64666,"manufId":4098,"manufName":"_TZ3000_wsspgtcd","powerSource":"Mains (single phase)","modelId":"TS0726","epList":[1,2,3,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":4,"inClusterList":[0,3,4,5,6,57344,57345],"outClusterList":[25,10],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":0,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53280":0,"powerOnBehavior":0}},"genBasic":{"attributes":{"modelId":"TS0726","manufacturerName":"_TZ3000_wsspgtcd","powerSource":1,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":4,"inClusterList":[3,4,5,6,57344,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"53280":0,"powerOnBehavior":0}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":4,"inClusterList":[3,4,5,6,57344,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"53280":0,"powerOnBehavior":0}}},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":4,"inClusterList":[3,4,5,6,57344,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"53280":0,"powerOnBehavior":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1681295180168,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
@evangelo18 if it is working correctly then it's OK

**Comment by evangelo18** [comment]
@Koenkk when using this device via a tuya gateway, it has the option to assign each switch as a 'toggle switch' or 'scene switch'.
I believe this functionality may be the '53280' attribute. How can this function be added into the code?

**Comment by Koenkk** [comment]
Can you sniff this when you set it?

https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html

**Comment by evangelo18** [comment]
> Can you sniff this when you set it?
> 
> https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html

Will need to wait for hardware to arrive so i can do this..

**Comment by evangelo18** [comment]
@Koenkk I am a bit confused as to how i sniff this. I can only set the switch between switch and scene when i have it connected to a tuya gateway. Are you able to elaborate?

**Comment by Koenkk** [comment]
You have to sniff the traffic while you connect the device to the TuYa gateway.

**Comment by Koenkk** [comment]
What is the network key?

**Comment by evangelo18** [comment]
> What is the network key?

Sorry - its
404dc6dde9a2f1b3fb085bdecdaa82dd

**Comment by Koenkk** [comment]
Thanks, I've added the switch mode, please check if it works: https://gist.github.com/Koenkk/1c7811ba5296543905aaf0482b54484e

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if switch_mode works.

**Comment by evangelo18** [comment]
Debug 2023-07-16 20:52:11Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,100,253,0],"type":"Buffer"}' from endpoint 4 with groupID 0

Debug 2023-07-16 20:52:59No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,101,253,0],"type":"Buffer"}'

**Comment by evangelo18** [comment]
> Thanks, I've added the switch mode, please check if it works: https://gist.github.com/Koenkk/1c7811ba5296543905aaf0482b54484e
> 
> * save this as file next to `configuration.yaml` as `ext_converter.js`
> * add it to `configuration.yaml`:
> 
> ```yaml
> external_converters:
>   - ext_converter.js
> ```
> 
> * start z2m, check if switch_mode works.

Thanks. The ability to select scene or switch now works, however it does not seem to send any command when a button is pressed if its set as scene.

**Comment by Koenkk** [comment]
> however it does not seem to send any command when a button is pressed if its set as scene.

Is anything logged in the debug log when pressing?

**Comment by evangelo18** [comment]
> Debug 2023-07-16 20:52:11Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,100,253,0],"type":"Buffer"}' from endpoint 4 with groupID 0
> 
> Debug 2023-07-16 20:52:59No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,101,253,0],"type":"Buffer"}'

@Koenkk see above

**Comment by Koenkk** [comment]
That looks good, we can add a converter for that. But before doing so, can you provide the log when triggering the other scene buttons?

**Comment by evangelo18** [comment]
@Koenkk  log below when triggering scene button 1 through 4 sequentially

Debug 2023-07-20 19:14:25Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,99,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Debug 2023-07-20 19:14:25No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,99,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:25Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,99,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Debug 2023-07-20 19:14:25No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,99,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:25Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,99,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Debug 2023-07-20 19:14:25No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,99,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:25Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,99,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Debug 2023-07-20 19:14:25No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,99,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:25Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,99,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Debug 2023-07-20 19:14:25No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,99,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:27Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,100,253,0],"type":"Buffer"}' from endpoint 2 with groupID 0
Debug 2023-07-20 19:14:27No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,100,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:27Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,100,253,0],"type":"Buffer"}' from endpoint 2 with groupID 0
Debug 2023-07-20 19:14:27No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,100,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:27Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,100,253,0],"type":"Buffer"}' from endpoint 2 with groupID 0
Debug 2023-07-20 19:14:27No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,100,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:27Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,100,253,0],"type":"Buffer"}' from endpoint 2 with groupID 0
Debug 2023-07-20 19:14:27No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,100,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:28Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,100,253,0],"type":"Buffer"}' from endpoint 2 with groupID 0
Debug 2023-07-20 19:14:28No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,100,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:29Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,101,253,0],"type":"Buffer"}' from endpoint 3 with groupID 0
Debug 2023-07-20 19:14:29No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,101,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:30Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,101,253,0],"type":"Buffer"}' from endpoint 3 with groupID 0
Debug 2023-07-20 19:14:30No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,101,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:30Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,101,253,0],"type":"Buffer"}' from endpoint 3 with groupID 0
Debug 2023-07-20 19:14:30No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,101,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:30Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,101,253,0],"type":"Buffer"}' from endpoint 3 with groupID 0
Debug 2023-07-20 19:14:30No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,101,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:30Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,101,253,0],"type":"Buffer"}' from endpoint 3 with groupID 0
Debug 2023-07-20 19:14:30No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,101,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:32Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,102,253,0],"type":"Buffer"}' from endpoint 4 with groupID 0
Debug 2023-07-20 19:14:32No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,102,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:32Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,102,253,0],"type":"Buffer"}' from endpoint 4 with groupID 0
Debug 2023-07-20 19:14:32No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,102,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:33Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,102,253,0],"type":"Buffer"}' from endpoint 4 with groupID 0
Debug 2023-07-20 19:14:33No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,102,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:33Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,102,253,0],"type":"Buffer"}' from endpoint 4 with groupID 0
Debug 2023-07-20 19:14:33No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,102,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:33Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,102,253,0],"type":"Buffer"}' from endpoint 4 with groupID 0
Debug 2023-07-20 19:14:33No converter available for 'TS0726' with cluster 'genOnOff' and type 'raw' and data '{"data":[1,102,253,0],"type":"Buffer"}'
Debug 2023-07-20 19:14:33Received Zigbee message from 'Bedroom 1 Switch 2', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0

**Comment by Koenkk** [comment]
I updated https://gist.github.com/Koenkk/1c7811ba5296543905aaf0482b54484e, please check if it works.

**Comment by evangelo18** [comment]
@Koenkk only 'scene 1' appears to be an option to select when creating an automation. see snippet 
image

log when pressing scene switch 1 FYI is below

Debug 2023-07-21 17:16:16Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,116,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Info 2023-07-21 17:16:16MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2', payload '{"action":"scene_1","linkquality":145,"power_on_behavior_l1":"previous","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","switch_mode_l1":"scene","switch_mode_l2":"switch","switch_mode_l3":"scene","switch_mode_l4":"scene"}'
Info 2023-07-21 17:16:16MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2', payload '{"action":"","linkquality":145,"power_on_behavior_l1":"previous","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","switch_mode_l1":"scene","switch_mode_l2":"switch","switch_mode_l3":"scene","switch_mode_l4":"scene"}'
Info 2023-07-21 17:16:16MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2/action', payload 'scene_1'
Debug 2023-07-21 17:16:17Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,116,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2', payload '{"action":"scene_1","linkquality":145,"power_on_behavior_l1":"previous","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","switch_mode_l1":"scene","switch_mode_l2":"switch","switch_mode_l3":"scene","switch_mode_l4":"scene"}'
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2', payload '{"action":"","linkquality":145,"power_on_behavior_l1":"previous","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","switch_mode_l1":"scene","switch_mode_l2":"switch","switch_mode_l3":"scene","switch_mode_l4":"scene"}'
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2/action', payload 'scene_1'
Debug 2023-07-21 17:16:17Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,116,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2', payload '{"action":"scene_1","linkquality":145,"power_on_behavior_l1":"previous","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","switch_mode_l1":"scene","switch_mode_l2":"switch","switch_mode_l3":"scene","switch_mode_l4":"scene"}'
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2', payload '{"action":"","linkquality":145,"power_on_behavior_l1":"previous","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","switch_mode_l1":"scene","switch_mode_l2":"switch","switch_mode_l3":"scene","switch_mode_l4":"scene"}'
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2/action', payload 'scene_1'
Debug 2023-07-21 17:16:17Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,116,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2', payload '{"action":"scene_1","linkquality":142,"power_on_behavior_l1":"previous","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","switch_mode_l1":"scene","switch_mode_l2":"switch","switch_mode_l3":"scene","switch_mode_l4":"scene"}'
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2', payload '{"action":"","linkquality":142,"power_on_behavior_l1":"previous","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","switch_mode_l1":"scene","switch_mode_l2":"switch","switch_mode_l3":"scene","switch_mode_l4":"scene"}'
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2/action', payload 'scene_1'
Debug 2023-07-21 17:16:17Received Zigbee message from 'Bedroom 1 Switch 2', type 'raw', cluster 'genOnOff', data '{"data":[1,116,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2', payload '{"action":"scene_1","linkquality":145,"power_on_behavior_l1":"previous","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","switch_mode_l1":"scene","switch_mode_l2":"switch","switch_mode_l3":"scene","switch_mode_l4":"scene"}'
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2', payload '{"action":"","linkquality":145,"power_on_behavior_l1":"previous","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","switch_mode_l1":"scene","switch_mode_l2":"switch","switch_mode_l3":"scene","switch_mode_l4":"scene"}'
Info 2023-07-21 17:16:17MQTT publish: topic 'zigbee2mqtt/Bedroom 1 Switch 2/action', payload 'scene_1'

**Comment by Koenkk** [comment]
I see you only pressed the first button, what if you press the other buttons? Then these actions should be added.

**Comment by evangelo18** [comment]
> I see you only pressed the first button, what if you press the other buttons? Then these actions should be added.

yes that worked! thanks

**Comment by Koenkk** [comment]
Great, integrated the changes!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by evangelo18** [comment]
@Koenkk the ability scene button actions from these switches seem to have stopped working in a recent update. The triggers are still there and able to be selected, however the action doesn't work in any automation
log when pressing buttons below

Debug 2024-04-29 20:37:36Received Zigbee message from 'Bedroom 1 Switch 2', type 'commandTuyaAction', cluster 'genOnOff', data '{"value":0}' from endpoint 3 with groupID 0
Debug 2024-04-29 20:37:37Received Zigbee message from 'Bedroom 1 Switch 2', type 'commandTuyaAction', cluster 'genOnOff', data '{"value":0}' from endpoint 1 with groupID 0
Debug 2024-04-29 20:37:38Received Zigbee message from 'Bedroom 1 Switch 2', type 'commandTuyaAction', cluster 'genOnOff', data '{"value":0}' from endpoint 4 with groupID 0

**Comment by Koenkk** [comment]
Can you check with the next release on Wednesday?

**Comment by evangelo18** [comment]
> Can you check with the next release on Wednesday? If not, please provide the debug log of that when pressing the scene buttons.

Wednesday's update fixed this issue. Thankyou!

**Pull request merged**
