### PR TITLE
New IKEA GU10 led bulb

### PR DESCRIPTION
**Pull request by Spiffo**
added support for LED2005R5

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you rebase this PR and add the `zigbeeModel` to the existing  `LED2005R5` (https://github.com/Koenkk/zigbee-herdsman-converters/blob/59f551cbfcac45f84a601b77a2c253803dc67953/devices/ikea.js#L603)

**Comment by Koenkk** [comment]
Note to self, after this merge https://github.com/Koenkk/zigbee2mqtt.io/pull/907

**Comment by Spiffo** [comment]
done

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
