### PR TITLE
HSV gamma correction, new light utilities

### PR DESCRIPTION
**Pull request by jasperro**
This patch was specifically made for my OSRAM lights that had problems with xy color, but where hsv produced the correct colors. The only thing missing from the xy color implementation was gamma correction (see https://tasmota.github.io/docs/Lights/#gamma-correction), which this patch implements. This patch also cleans up some stuff in the hue/saturation code.

Tested on OSRAM AC03647/AC03645 and the Philips HUE Bluetooth+Zigbee.

### CODE REVIEW

**Comment by jasperro** [comment]
@Koenkk do you think this is useful? Do you think it should be enabled on all lights, or as quirks for the OSRAMS/other devices that require this in devices.js, as a config option in configuration.yaml or something else?

Unrelated to this patch, should XY also be converted to HSV? Or should HSV data be removed on XY change from MQTT, is this possible? In home assistant once HSV has been set on a light, XY color changes don't update the color wheel. It seems to have a preference for HSV in the color wheel, so maybe it should be changed in home assistant?

**Comment by Koenkk** [comment]
Hi @jasperro, somehow I missed this PR, sorry.

I'm fine with merging this (for all devices) if it produces better colours.

> Unrelated to this patch, should XY also be converted to HSV?

I'm not sure I'm following this. What would be the added value?

**Comment by jasperro** [comment]
> I'm not sure I'm following this. What would be the added value?

When using home assistant, the color wheel doesn't change when using xy mode after changing the colour with hsv. A very small issue, and this doesn't effect this patch. Updating XY values when changing hsv will update the wheel again, or just setting the xy color to null. Removing the retained messages doesn't work, I guess it's stored in z2m.

I think the patch is able to be merged as I have been running this for about a month now and haven't had any more issues than the aforementioned color wheel issues.

**Comment by Koenkk** [comment]
@jasperro that sounds more like a Home Assistant issue. Possible workaround is to only use xy when using Home Assistant.

**Pull request merged**
