### PR TITLE
SMaBiT AV2010/32: allow get/set of hysteresis low and high

### PR DESCRIPTION
**Pull request by sjorge**
Completes implementation for https://github.com/Koenkk/zigbee2mqtt/issues/17194

I did not add these to the exposes values, it's something you set once and can forget about. I also don't think a lot of people will want to change the default.

### CODE REVIEW

**Comment by Koenkk** [comment]
> I did not add these to the exposes values, it's something you set once and can forget about. I also don't think a lot of people will want to change the default.

Even if set once, it should be exposed. Otherwise it doesn't end up in the docs (and cannot be set via the frontend) and this becomes an undocumented feature.

**Comment by sjorge** [comment]
> > I did not add these to the exposes values, it's something you set once and can forget about. I also don't think a lot of people will want to change the default.
> 
> Even if set once, it should be exposed. Otherwise it doesn't end up in the docs (and cannot be set via the frontend) and this becomes an undocumented feature.

I was going to add it to the docs manually like for the ctrlSeqOpr stuff.

I vaguely remember something about having a settings like expose too, perhaps this is something that could be sent that way?

Or is that one only for device options?

**Comment by Koenkk** [comment]
> I vaguely remember something about having a settings like expose too, perhaps this is something that could be sent that way?

That is only for device options (applied at the z2m side)

**Comment by sjorge** [comment]
I’ll refactor this a bit more so it can be one expose entry.

**Comment by sjorge** [comment]
Now looks like this
image

**Comment by Koenkk** [comment]
Clean, thanks!

**Pull request merged**
