### PR TITLE
Add support for Zemismart 6-Gang Smart Wall Switch

### PR DESCRIPTION
**Pull request by jairbj**
Add support for Zemismart 6-Gang Smart Wall Switch

I also needed to edit FZ and TZ converters to allow 6 states on tuya_switch and tuya_switch_state, respectively.

### CODE REVIEW

**Comment by platbr** [comment]
I have tested it and it's working.

**Comment by platbr** [comment]
> This PR solves #4315

The right issue number is #4311

**Comment by jairbj** [comment]
> > This PR solves #4315
> 
> The right issue number is #4311

Thanks for testing. Let's wait for the commit to be merged.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
