### PR TITLE
support Feibit

### PR DESCRIPTION
**Pull request by qlwz**
support Feibit

### CODE REVIEW

**Comment by Koenkk** [comment]
I did some updates, can you verify that everything is still OK?

**Comment by qlwz** [comment]
zigbeeModel: FB56+ZSW1HKJ2.2    model is SLS201ZB
zigbeeModel: FB56+ZSW1IKJ2.2      model is SLS301ZB

**Comment by qlwz** [comment]
Not in the latest version?

**Comment by Koenkk** [comment]
Merged, could you also provide pictures (URL) for these devices? (for documentation)

**Pull request merged**
