### PR TITLE
Add Philips Hue devices 3418131P6, 3417931P6 and 1741530P7

### PR DESCRIPTION
**Pull request by avacore**
This pull request adds Zigbee device models 3418131P6, 3417931P6 and 1741530P7. The first two are variants of the Philips Hue White Ambiance GU10 with Bluetooth which were distributed with Hue Adore fixtures. The final device is a variant of the Hue Lily outdoor spot light.

### CODE REVIEW

**Comment by sjorge** [comment]
Can you grab the colorTempPhyMin/Max from database.db.

**Comment by avacore** [comment]
> Can you grab the colorTempPhyMin/Max from database.db... example here [f981f21](https://github.com/Koenkk/zigbee-herdsman-converters/commit/f981f219b5274a6e7b8531366a092173d46c5943)

Shall do. I assume that these are the fields named colorTempPhysicalMin/Max, at least in the version I have?

**Comment by sjorge** [comment]
Yep, they should be called that in database.db.

~ sjorge

**Comment by avacore** [comment]
If you're interested I'd be happy to go through my lights and add it for any other lights I have that are missing this.

**Comment by sjorge** [comment]
That would be great!

~ sjorge

**Comment by avacore** [comment]
> That would be great! ~ sjorge

Happy to do so. Should anyone else want to do so, the following jq filter is incredibly useful:
[.endpoints."11".clusters|.genBasic.attributes.modelId,.lightingColorCtrl.attributes.colorTempPhysicalMin,.lightingColorCtrl.attributes.colorTempPhysicalMax]

**Comment by Koenkk** [comment]
Thanks @avacore and @sjorge !

**Pull request merged**
