### PR TITLE
Big Tuya rework

### PR DESCRIPTION
**Pull request by drzony**
This rework separates data point ids from data type, creates a common list of Tuya data points and adds some other fixes.

Also it adds some debugging tools for Tuya devices

According to https://github.com/Koenkk/zigbee-herdsman/issues/249

Should me merged together with https://github.com/Koenkk/zigbee-herdsman/pull/253

### CODE REVIEW

**Comment by Koenkk** [comment]
@Hacker-CB can you do a final check for these changes, does it still work with your ETOP thermostats after this? Also requires https://github.com/Koenkk/zigbee-herdsman/pull/253

**Comment by Hacker-CB** [comment]
@Koenkk I checked with HT-08. All basic functions, including `away` mode works as expected.
For the `weekly_schedule` - we still need to make some exposes standard.

**Comment by Koenkk** [comment]
@Hacker-CB thanks for testing, @drzony big thanks for doing this!

**Comment by drzony** [comment]
I'm out of steam today, but I'll do (maybe I'll manage tomorrow) a PR for zigbee2mqtt.io with a documentation about "Adding new Tuya devices", I'll describe how to use the "debug" converters, my python script and how to add data points

**Pull request merged**
