### PR TITLE
Fix ZNCLDJ12LM function

### PR DESCRIPTION
**Pull request by nukusinji**
fix running state and battery level

### CODE REVIEW

**Comment by surfingbytes** [comment]
I downloaded latest-dev, and battery_state (which works fine in latest) now reports null. running reports null in both latest and latest-dev, and newly added motor_state also reports null in latest-dev.

**Comment by nukusinji** [comment]
> 

What is firmware date and version?
I checked date: 20200803, version 2019www.

state always come when send command open, close, reconnect battery, push button on motor.

**Comment by nukusinji** [comment]
> I downloaded latest-dev, and battery_state (which works fine in latest) now reports null. running reports null in both latest and latest-dev, and newly added motor_state also reports null in latest-dev.

7BC4FE37-7255-4150-819D-03DD954836E1

What is firmware date and version?
I checked date: 20200803, version 2019www.

state always come when send command open, close, reconnect battery, push button on motor.

**Comment by nukusinji** [comment]
> I downloaded latest-dev, and battery_state (which works fine in latest) now reports null. running reports null in both latest and latest-dev, and newly added motor_state also reports null in latest-dev.
168518429-5e101e1d-ea60-475e-8fd3-cd1fa4125786

What is firmware date and version?
I checked date: 20200803, version 2019www.

state always come when send command open, close, reconnect battery, push button on motor.

**Comment by surfingbytes** [comment]
Same firmware - Firmware build date 20200803, Firmware version 2019www. battery, running, motor_state are all null. I don't see power_outage_count on mine, I run it on battery. Do you have it plugged in? That could make the difference, can you try running it on battery?

**Comment by nukusinji** [comment]
> Same firmware - Firmware build date 20200803, Firmware version 2019www. battery, running, motor_state are all null. I don't see power_outage_count on mine, I run it on battery. Do you have it plugged in? That could make the difference, can you try running it on battery?

power_outage_count is new PR (https://github.com/Koenkk/zigbee-herdsman-converters/pull/4246#issue-1236267195)

I run by battery. It's same.

**Comment by nukusinji** [comment]
> 

what is your coordinator firmware version?

**Comment by surfingbytes** [comment]
I have Sonoff Zigbee 3.0 USB Dongle Plus, which should come with latest Z-Stack 3.x.0, but I can't find info on how to know what version is it actually running.

**Comment by nukusinji** [comment]
> 

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/CHANGELOG.md
My coordination is version 20220219 and CC1352 .

**Comment by Otnow** [comment]
> I have Sonoff Zigbee 3.0 USB Dongle Plus, which should come with latest Z-Stack 3.x.0, but I can't find info on how to know what version is it actually running.

The firmware version of the coordinator can be seen in the [z2m web interface](https://www.zigbee2mqtt.io/guide/configuration/frontend.html#frontend) (`Settings -> About -> Coordinator revision`):

Zigbee2MQTT_Coordinator_revision

**Comment by surfingbytes** [comment]
Thank you. It looks like I have older version - 20210708. I'll flash new one and let you know. Thanks again.

**Comment by Otnow** [comment]
> Thank you. It looks like I have older version - 20210708. I'll flash new one and let you know. Thanks again.

Please note that after updating the firmware of the coordinator, you will be required to re-pair the device.

**Comment by Otnow** [comment]
@surfingbytes, fine, you are welcome 👍🙂

[Added](https://github.com/Koenkk/zigbee2mqtt.io/pull/1387) information to the documentation about the need to update the firmware of the coordinator and re-pair the device.

**Pull request merged**
