### PR TITLE
ZBT-DIMController-D0800 tint remote added

### PR DESCRIPTION
**Pull request by woolfg**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by woolfg** [comment]
Hey @JLFN, did you try to reset the remote by pressing the reset button for a few seconds?

**Comment by JLFN** [comment]
@woolfg i did remove the battery and reset and also reset only i just get 
igbee2MQTT:info  2020-12-10 17:51:26: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x00158d0001fe5a20"},"type":"device_announced"}'


Zigbee2MQTT:info  2020-12-10 17:51:29: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x00158d0001fe5a20"},"type":"device_announced"}'
Nothing more

**Comment by woolfg** [comment]
I had a similar behaviour at the beginning. But after some time it worked, maybe it was due to some test configurations I tried.

I just wanted to reset and test it in my setup but had to find out that the device is broken or the battery is already empty...weird after 2 days....I have to see what is wrong and then, can do some tests again on my side.

**Pull request merged**
