### PR TITLE
added battery reporting for PARASOLL

### PR DESCRIPTION
**Pull request by thatslolo**
changed battery reporting from voltage to percent for SOMRIG

### CODE REVIEW

**Comment by thatslolo** [comment]
should be ready now

**Comment by thatslolo** [comment]
> should be ready now

now ;)

**Comment by Koenkk** [comment]
Thanks!

**Comment by mrskycriper** [comment]
@thatslolo Hello, is there any reason for `genBasic` and `ssIasZone` binds? It should work without them. I can't seem to find any issues that necessitated them

**Comment by thatslolo** [comment]
Afaik I needed the Gennadi for battery reporting. For the other I don’t remember. Would there be a benefit in removing them?

**Comment by mrskycriper** [comment]
> Afaik I needed the genBasic for battery reporting. For the other I don’t remember. Would there be a benefit in removing them?

Battery reporting is done using `genPowerCfg` cluster. So it should be bound instead. But since it works now, this bind would be unnecessary too.

I just would like to remove unnecessary binds since I'm doing a big IKEA converters cleanup. Can you please test it without those 2 binds?

**Comment by thatslolo** [comment]
I can test it tomorrow.

**Comment by mrskycriper** [comment]
> I can test it tomorrow.

Thanks!

**Comment by thatslolo** [comment]
@mrskycriper tested it with joining a new PARASOLL sensor. Everything works as expected. Actually, I don't have a clue why I added these bindings.

**Comment by mrskycriper** [comment]
> @mrskycriper tested it with joining a new PARASOLL sensor. Everything works as expected. Actually, I don't have a clue why I added these bindings.

Thanks, I'll just remove those since they aren't really needed, which is to be expected. Since Ikea more or less follows the Zigbee specifications

**Comment by thatslolo** [comment]
@mrskycriper since I used the modernExtend I think all the config for the battery reporting is also redundant…

**Comment by mrskycriper** [comment]
> @mrskycriper since I used the modernExtend I think all the config for the battery reporting is also redundant…

I've moved everything to modern extends. You can check it out in this PR https://github.com/Koenkk/zigbee-herdsman-converters/pull/7220

**Pull request merged**
