### PR TITLE
Add Wenzhi WZ-M100-Z as whitelabel for TuYa ZY-M100-S_1

### PR DESCRIPTION
**Pull request by Ansuel**
Add Wenzhi WZ-M100-Z as whitelabel of the TuYa ZY-M100 as this is a clone and implement the same features.

By opening the device and looking at the PCB and the chip used, the device use the same sensor and the same ARM controller of the Tuya ZY-M100.

Only the fingerprint reported is different.

### CODE REVIEW

**Comment by Koenkk** [comment]
Please merge with https://github.com/Koenkk/zigbee-herdsman-converters/blob/b35b8e57c560c6951acdc40d0c7bfc8e37dad78e/src/devices/tuya.ts#L4444, you can use the whitelabel feature to detect it correctly:

https://github.com/Koenkk/zigbee-herdsman-converters/blob/b35b8e57c560c6951acdc40d0c7bfc8e37dad78e/src/devices/tuya.ts#L567

**Comment by Ansuel** [comment]
@Koenkk is it ok to merge? On aliexpress I can se various product from this company so it might be a good idea to create a new .ts?

**Comment by Ansuel** [comment]
@Koenkk anyway implemented with whitelabel. Thanks for the ultra mega fast review!

**Comment by Koenkk** [comment]
Thanks, with the whitelabel we greatly reduce the amount of code 😄

**Comment by Ansuel** [comment]
@Koenkk hi, I just updated to the new release version and I notice the whitelabel thing is not working? Any hint on how to bisect?

(I removed the external converter)

**Comment by Koenkk** [comment]
can you provide the data/database.db of your device?

**Comment by Ansuel** [comment]
Here https://go.wetransfer.com/t-L0l8pbKHQR

**Comment by Ansuel** [comment]
Sorry this... https://go.wetransfer.com/t-j0hMHAFfnO

**Comment by Koenkk** [comment]
Should be good, are you sure you don't have an external converter in your configuration.yaml, can you provide 2 screenshots
1. Z2M frontend -> settings -> about page
2. Z2M frontend -> device -> about page

**Comment by Ansuel** [comment]
image
image

**Comment by Koenkk** [comment]
It was missing from the `fingerprint`, added it now!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Ansuel** [comment]
@Koenkk ohhhh my bad sorry!!! at times i tought it was just an additional example and didn't understood i had to add the id in both place! Again sorry and thanks for the help!

**Comment by sigalou** [comment]
Good evening, I am using version 1.33.2 but the WZ-M100 equipment is still failing:

presence3

image

**Comment by Ansuel** [comment]
@sigalou you need to wait for the new version or use the nightly version. There was an error on submission and was later fixed.

**Pull request merged**
