### PR TITLE
Fixes Miboxer FUT039Z

### PR DESCRIPTION
**Pull request by plasticrake**
The existing configuration for this device was not working for me. Color temperatures were reversed, and setting color was not working. See Koenkk/zigbee2mqtt#10923

### CODE REVIEW

**Comment by kirovilya** [comment]
wait. where is 'color_power_on_behavior' and 'do_not_disturb' ?

**Comment by plasticrake** [comment]
@kirovilya I set `disableColorTempStartup: false` as in my testing it didn't seem the device supported it when it was on. This model `TS0505B` appears throughout this repo and I set this version of it similarly to how all the others were setup.

I do see that in moes.js it is setup a little differently than the rest, I can test this with my device and see if it works.
```js
        toZigbee: extend.light_onoff_brightness_colortemp_color().toZigbee.concat([
            tz.tuya_do_not_disturb, tz.tuya_color_power_on_behavior,
        ]),
        meta: {applyRedFix: true, enhancedHue: false},
        fromZigbee: extend.light_onoff_brightness_colortemp_color().fromZigbee,
        exposes: extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 500]}).exposes.concat([
            exposes.binary('do_not_disturb', ea.STATE_SET, true, false)
                .withDescription('Do not disturb mode'),
            exposes.enum('color_power_on_behavior', ea.STATE_SET, ['initial', 'previous', 'cutomized'])
                .withDescription('Power on behavior state'),
        ]),
```

Also, is `'cutomized'` how it should appear? Is the misspelling of `customized` deliberate?

**Comment by plasticrake** [comment]
When configured as in the `moes.js` file `color_power_on_behavior` is now working in my testing. However I don't know if `do_not_disturb` is working for my device. I do not see any difference regardless if it is set to On or Off. Perhaps I don't understand how it is supposed to work.

**Comment by kirovilya** [comment]
Checked. Very bad red.
applyRedFix doesn't help
The rest - it works.

**Comment by plasticrake** [comment]
@kirovilya I agree the red has too much blue, regardless if `applyRedFix` is true or false. How do you fix that?

**Comment by kirovilya** [comment]
can't think of a quick fix

**Comment by kirovilya** [comment]
if change the 'color' exposes from 'XY' to 'HS', then the red color will be correct.

**Comment by plasticrake** [comment]
I think I have it correct now. The red looks better for me

**Comment by Koenkk** [comment]
thanks!

**Pull request merged**
