### PR TITLE
Update legrand.js

### PR DESCRIPTION
**Pull request by brantmacga**
Add support for Remote Dimmer Switch (WNAL63, WNRL63), Add support for Hospitality On Off Switch (WNAL10, WNRL10), Add support for Hospitality Dimmer Switch (WNAL50, WNRL50), also know as Legrand with Netatmo.

### CODE REVIEW

**Comment by Koenkk** [comment]
There seems to be some merge conflicts, can you fix these?

**Comment by brantmacga** [comment]
I created a new pull request. I believe the conflict was that one of my devices already existed; I didn't realize I'd already submitted it, and I tried to add an additional model name for a different variant with the same internals.

**Comment by Koenkk** [comment]
Thanks!

**Comment by Bdouille** [comment]
Can you integrate the device 069875?

**Comment by brantmacga** [comment]
> Can you integrate the device 069875?

you should start a new topic for this. I'm not sure exactly what this device is, but it appears to be an outdoor rated light that is controlled via wireless zigbee switch. 

I don't readily have access to this product to be able to help you with it.

**Comment by Bdouille** [comment]
Ok, I used what I read in the file "legrand.js" to create a file "069875.js" in which I wrote:
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: [' Dimmer switch w/o neutral evo\u0000'], 
    model: '069875',
    vendor: 'Legrand',
    description: 'Dimmer switch w/o neutral evo',
    fromZigbee: [fz.brightness, fz.identify, fz.on_off,fz.power_on_behavior],
    toZigbee: [tz.light_onoff_brightness, tz.legrand_deviceMode, tz.legrand_identify, tz.ballast_config, tz.power_on_behavior], 
    exposes: [e.action(['identify', 'on', 'off'])], 
};

module.exports = definition;

and it works

**Pull request merged**
