### PR TITLE
Add basic support for BMCT-RZ

### PR DESCRIPTION
**Pull request by danielpetrovic**
On/off function works. As this is my first converter, can anyone help?

There are quite some options, many are probably overlapping with the Shutter/Light control II but the internal relays are different and this one has a single relay that is Potential Free.

It supports on/off and pulse mode, default mode seems to be on/off.

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you update this with the [generated external definition](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition)?

**Comment by danielpetrovic** [comment]
> Can you update this with the [generated external definition](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition)?

```
const {onOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['RBSH-MMR-ZB-EU'],
    model: 'RBSH-MMR-ZB-EU',
    vendor: 'BOSCH',
    description: 'Automatically generated definition',
    extend: [onOff({powerOnBehavior: false})],
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Can you try with the generated one and update this PR with it?

**Comment by danielpetrovic** [comment]
Yes, it works the same. But when I change the PR to this code it gives an error that the OnOff is not recognised.

I’ve only changed vendor and description from the generated one, to be in line with the other Bosch devices.

**Comment by Koenkk** [comment]
Add the following to the top of the file: `import {onOff} from '../lib/modernExtend';`

**Comment by danielpetrovic** [comment]
> Add the following to the top of the file: `import {onOff} from '../lib/modernExtend';`

Done, it finished without errors now.

**Pull request merged**
