### PR TITLE
Change Zemismart ZM_AM02

### PR DESCRIPTION
**Pull request by Burki24**
Zemismart ZM_AM02 was listet inside tuya.js as tubular-motor. that wasn't correct. Switched from tuya.js to zemismart.js as Roller Shade Converter.
https://www.zemismart.com/products/zmam02

### CODE REVIEW

**Comment by Burki24** [comment]
@Koenkk sorry for the left issues. :-(

**Comment by Koenkk** [comment]
No problem, thanks!

**Comment by little-dgek** [comment]
After this update, this roller didn't appear in Homebridge. But in zigbee2mqtt web ui I can control it.

**Comment by Burki24** [comment]
> After this update, this roller didn't appear in Homebridge. But in zigbee2mqtt web ui I can control it. Even after delete/force delete/restart etc

With the last update, this issue seems to be fixed:
https://github.com/Koenkk/zigbee2mqtt/issues/11190

**Pull request merged**
