### PR TITLE
Added EARU smart circuit breaker white label

### PR DESCRIPTION
**Pull request by M66B**
Product page: https://nl.aliexpress.com/item/1005005461998289.html

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by kva4991** [comment]
Hello, could you look at this task? can you help me sort it out? you are welcome!!!
https://github.com/Koenkk/zigbee2mqtt/issues/16118#issuecomment-1670414934

**Comment by M66B** [comment]
@Koenkk it looks like mentioning the device as whitelabel device only is not enough to let it be recognized:

```
        whiteLabel: [
            tuya.whitelabel('TONGOU', 'TO-Q-SY2-163JZT', 'Smart circuit breaker', ['_TZ3000_cayepv1a']),
            tuya.whitelabel('EARU', 'EAKCB-T-M-Z', 'Smart circuit breaker', ['_TZ3000_lepzuhto']),
        ],
```

Does it need to be included as a fingerprint too?

```
        fingerprint: tuya.fingerprint('TS011F', ['_TZ3000_cayepv1a', '_TZ3000_lepzuhto']),
```

**Comment by Koenkk** [comment]
You are right, integrated the fix.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by M66B** [comment]
@Koenkk thanks for this!

**Comment by oscrey** [comment]
Please, add also support for similar device EAYCBM-Z-2P
Zigbee Model: **TS0601**
Zigbee Manufacturer:  **_TZE204_davzgqq0**
https://www.aliexpress.com/i/1005004894443815.html

**Comment by danielszilagyi** [comment]
+1 the _TZE204_davzgqq0 would be nice to be added, it's TS0601 not TS011F

any input needed for this?

**Comment by paris21aek** [comment]
> Please, add also support for similar device EAYCBM-Z-2P Zigbee Model: **TS0601** Zigbee Manufacturer: **_TZE204_davzgqq0** https://www.aliexpress.com/i/1005004894443815.html

Yes. It's a very popular device but I can't understand why is unsupported from z2m. With the external converter has misleading functions as last state when power off, problem to set maximum and minimum thresholds and so on. So bad for the device.

**Comment by beliy1985** [comment]
I’m also really looking forward to adding this device

**Comment by Koenkk** [comment]
For the _TZE204_davzgqq0 let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/16118

**Comment by joviado** [comment]
Please, add also support for device EAYCBM-Z-2P
Zigbee Manufacturer: _TZ3000_zrm3oxsh

**Comment by andreas-glaser** [comment]
Please, add also support for device EAYCBM-Z-2P
Zigbee Manufacturer: _TZ3000_zrm3oxsh

**Comment by piavia** [comment]
Please, add also support for device EAYCBM-Z-2P
Zigbee Manufacturer: _TZ3000_zrm3oxsh

**Pull request merged**
