### PR TITLE
Added White Label For Danor SK-Z802C-US

### PR DESCRIPTION
**Pull request by danieledwardgeorgehitchcock**
Resolves Koenkk/zigbee2mqtt#20754

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks for this (and also all your previous contributions), very appreciated 😄

**Comment by moshiko2312** [comment]
Thanks for your for all your job🙏.
Waiting for update when I can check the device if it's working

**Comment by moshiko2312** [comment]
I have  only one entity, this switch Have a 2 curtain 
image

**Comment by danieledwardgeorgehitchcock** [comment]
I will have a look into this over the next few days

**Comment by moshiko2312** [comment]
Thanks🙏

בתאריך יום א׳, 14 בינו׳ 2024 ב-11:18 מאת danieledwardgeorgehitchcock <
***@***.***>:

**Comment by moshiko2312** [comment]
Hi Daniel can you please fix that issues?
Thanks

בתאריך יום א׳, 14 בינו׳ 2024 ב-11:35 מאת moshiko peer ***@***.***

**Pull request merged**
