### PR TITLE
add my firmware

### PR DESCRIPTION
**Pull request by qlwz**
add my firmware

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide links (urls) of these devices?

**Comment by qlwz** [comment]
> Can you provide links (urls) of these devices?

no links，retrofit for existing hardware

**Comment by Koenkk** [comment]
For DIY devices to be supported, the firmwares including a guide how to make these has to be published. Otherwise other people cannot use it.

**Comment by qlwz** [comment]
QQ图片20200419214519

如何配网：
1、按一次OK
2、长按一次左键
3、长按一次右键
4、长按一次左键
5、长按一次右键
6、长按一次OK

**Comment by fyanjin** [comment]
I'm using this firmware now, so I hope it can be added to ZigBee-herdsman-converters as soon as possible

**Pull request closed without merging**
