### PR TITLE
Expose cover running state

### PR DESCRIPTION
**Pull request by Drafteed**
Related PR: Koenkk/zigbee2mqtt/pull/11789

The expose added for all devices where the `running` can be present.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Koenkk** [comment]
Right after merging I found out this is a breaking change (since all running sensors will be removed from HA). To avoid that I propose to add the binary running sensor where applicable (like https://github.com/Koenkk/zigbee-herdsman-converters/blob/87f53ea94a97e89bf78961ed764ea4e1bdc4ae52/devices/xiaomi.js#L1288)

**Comment by Drafteed** [comment]
Oops... sorry.

**Comment by leroyloren** [comment]
I use an intermediate position to open the blind (open, intermediate position, closed) and this PR has made it impossible to work with the blind when the intermediate position is open. Resp. only full opening is active, closing from intermediate position is inactive.

**Comment by Drafteed** [comment]
> I use an intermediate position to open the blind (open, intermediate position, closed) and this PR has made it impossible to work with the blind when the intermediate position is open. Resp. only full opening is active, closing from intermediate position is inactive.

Which device model?

**Comment by leroyloren** [comment]
_TZE200_xuzcvlku

**Comment by Drafteed** [comment]
Is `Running` value always true? [Here already wrote about it.](https://github.com/Koenkk/zigbee2mqtt/commit/8f1787ed4a32912ca5f5a0e2b9cc5ff8b6064fb8#commitcomment-68595849) I will remove the expose for this device.

**Comment by Drafteed** [comment]
> and could motor_speed delete this device as well please? The device does not support this, but this option is in the settings.

I can't do it, because it may work [on other devices](https://github.com/Koenkk/zigbee-herdsman-converters/blob/4bed9034520c78827a8d0a5563aaae36b64d47a2/devices/tuya.js#L946-L977).

**Pull request merged**
