### PR TITLE
Add support for lumi.light.acn031 & lumi.light.acn032

### PR DESCRIPTION
**Pull request by banister4728**
White and RGB light works. Only thing found not working is that the RGB color can't be changed within Zigbee2MQTT but works fine in HA.

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you try with the following code:

```js
    {
        zigbeeModel: ['lumi.light.acn031', 'lumi.light.acn032'],
        model: 'T1/T1m',
        vendor: 'Aqara',
        description: 'Ceiling light T1/T1m',
        meta: {multiEndpoint: true},
        endpoint: () => ({white: 1, rgb: 2}),
        fromZigbee: light({colorTemp: {range: [153, 370]}, color: true}).fromZigbee,
        toZigbee: light({colorTemp: {range: [153, 370]}, color: true}).toZigbee,
        exposes: [
            // White light: On/Off, brightness, color temperature, no color_temp_startup
            e.light_brightness_colortemp([153, 370]).removeFeature('color_temp_startup').withEndpoint('white'),
            // [Notification Light]
            e.light_brightness_colorxy().withEndpoint('rgb'),
        ],
    },
```

**Comment by banister4728** [comment]
> Can you try with the following code:
> 
> ```js
>     {
>         zigbeeModel: ['lumi.light.acn031', 'lumi.light.acn032'],
>         model: 'T1/T1m',
>         vendor: 'Aqara',
>         description: 'Ceiling light T1/T1m',
>         meta: {multiEndpoint: true},
>         endpoint: () => ({white: 1, rgb: 2}),
>         fromZigbee: light({colorTemp: {range: [153, 370]}, color: true}).fromZigbee,
>         toZigbee: light({colorTemp: {range: [153, 370]}, color: true}).toZigbee,
>         exposes: [
>             // White light: On/Off, brightness, color temperature, no color_temp_startup
>             e.light_brightness_colortemp([153, 370]).removeFeature('color_temp_startup').withEndpoint('white'),
>             // [Notification Light]
>             e.light_brightness_colorxy().withEndpoint('rgb'),
>         ],
>     },
> ```

Works! Only thing left now is changing of color via ZB2MQTT dashboard doesn't work, although changing via HA works. Thank you so much.

**Comment by mrskycriper** [comment]
Modern extend from the start would be welcome

Can you test this instead of `meta`, `endpoint`, `fromZigbee`, `toZigbee` and `exposes`?

```js
extend: [
  deviceEndpoints({endpoints: {'white': 1, 'rgb': 2}}),
  lumiLight({colorTemp: true, powerOutageMemory: 'light', endpointNames: ['white']}),
  lumiLight({colorTemp: true, color: {modes: ['xy']}, endpointNames: ['rgb']}),
  lumiZigbeeOTA()
],
```

**Comment by banister4728** [comment]
@mrskycriper Not sure why the check failed but your code works when I used it as a external converter.

**Comment by Koenkk** [comment]
thanks!

**Comment by corvis** [comment]
@banister4728 can you confirm if powerOutageMemory function actually works?

**Comment by banister4728** [comment]
@corvis Don't think it works. When i click on it in zb2mqtt exposes tab, I get the following:

`Publish 'set' 'power_outage_memory' to 'ceilinglight' failed: 'Error: Write 0x54ef4410008f1023/1 genBasic({"65305":{"value":1,"type":16}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'`

**Comment by corvis** [comment]
Thanks for checking. I replicated this ZHA quirk and got the same result so wanted to check if the original was actually working.

Are there any ideas how to make it work?

**Comment by mrskycriper** [comment]
It probably uses different attribute here. Maybe it's just binary?

**Comment by corvis** [comment]
After some more debugging I think I nailed it. I'm not zigbee2mqtt user so I can't propose a PR but maybe this will be helpful.

Power behavior of this device is controlled by the following attribute:

```
Cluster: 0xFCC0 # Manufacturer Specific
Endpoint: 0x01
Attribute: 0x0517
Type: 0x20 # 8-bit int
Manufacturer Code: 4447
Value: 
    0x00 - Always On (default) - Will be turned on after power outage.
    0x01 - Preserve State - Will keep the state it was before power outage.
    0x02 - Always Off - Will be turned off after power outage.
```

**Comment by mrskycriper** [comment]
`lumiLight` definitely needs an update

**Comment by corvis** [comment]
I created PR to ZHA, maybe it will be helpful for the developer who will be working on PR to zigbee2mqtt: https://github.com/zigpy/zha-device-handlers/pull/3070

**Comment by banister4728** [comment]
> I created PR to ZHA, maybe it will be helpful for the developer who will be working on PR to zigbee2mqtt: [zigpy/zha-device-handlers#3070](https://github.com/zigpy/zha-device-handlers/pull/3070)

Unfortunately this is beyond my capability. 
Are you able to control the RGB animation on zha?

**Comment by corvis** [comment]
> Are you able to control the RGB animation on zha?

No

**Comment by geduxas** [comment]
For RGB led stripe, i have some idea, has anyone tried to mix support from T1 LED strip to this lamp? Don't aquare use same control logic for led strip effect's ? 
It seams [lumi.light.acn132](https://github.com/Koenkk/zigbee2mqtt/issues/18471#issuecomment-1873575860) allready have effect's enabled, maybe same control logic should be and for this lamp?

**Pull request merged**
