### PR TITLE
Adding support for Heiman Smart Doorbell

### PR DESCRIPTION
**Pull request by popescunsergiu**
Adding support for Heiman HS2DB Smart Doorbell

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you share the data/database.db entry of this device?

Note to self: after this merge https://github.com/Koenkk/zigbee2mqtt.io/pull/802

**Comment by danieledwardgeorgehitchcock** [comment]
Could this not be accomplished by adding a White label attribute to the Lidl HG06668 doorbell or vice versa?

I believe the Lidl HG06668 Doorbell is manufactured by Heiman and is the same hardware so one should represent the other and there should be no need to create separate converters..

**Comment by danieledwardgeorgehitchcock** [comment]
@popescunsergiu can you share the data/database.db entry for this device or let me know what the manufacturer name is reported as so that I can merge the Lidl and Heiman device handlers in PR #2873?

**Comment by Koenkk** [comment]
Closing this in favour of https://github.com/Koenkk/zigbee-herdsman-converters/pull/2873

**Pull request closed without merging**
