### PR TITLE
Add support for L&S Emotion Home Base

### PR DESCRIPTION
**Pull request by nordish1**

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide a link to this device?

**Comment by nordish1** [comment]
https://zigbee.blakadder.com/L_S_7061288.html

https://7459402.fs1.hubspotusercontent-na1.net/hubfs/7459402/L%26S_Handbuch%20Steuerungssysteme_2021_small.pdf

**Comment by nordish1** [comment]
Can you help me? This ist my first pull request and I don't know what's the problem.

**Comment by Koenkk** [comment]
The device looks like a gateway, not a light?

**Comment by nordish1** [comment]
Yes, the Home Base converts Zigbee to Emotion. But only lights are controlled.

**Comment by Koenkk** [comment]
You should pair the lights directly to z2m, not the the emotion base (which is alternative to zigbee2mqtt)

**Comment by nordish1** [comment]
No, that is not possible. The gateway also converts Zigbee to a properetary Emotion radio signal.

**Comment by Koenkk** [comment]
Were you able to pair the base to zigbee2mqtt?

**Comment by nordish1** [comment]
Yes, and with the "ls.js" config I created, it also works. But the check fails.

**Comment by nordish1** [comment]
Done

**Comment by Koenkk** [comment]
Can you update the contents of this file to:

```js
import {Definition} from '../lib/types';
import extend from '../lib/extend';

const definitions: Definition[] = [
    {
        zigbeeModel: ['Emotion'],
        model: 'A319463',
        vendor: 'LS Deutschland GmbH',
        description: 'Home base',
        extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 454]}),
    },
];

module.exports = definitions;

```

**Comment by nordish1** [comment]
I've update the file. But the follwing message is shown "Type annotations can only be used in TypeScript files. "

**Comment by Koenkk** [comment]
This device is supported now.

**Comment by isabelkort** [comment]
I've added my L&S Emotion HomeBase to Zigbee2MQTT. It doesn't work. When i click on or off he light on the Home Base ist red.
And the log in Z2M show:
 2023-11-21 17:44:36MQTT publish: topic 'zigbee2mqtt/Kochinsel Beleuchtung', payload '{"color_mode":"xy","linkquality":228,"state_l1":"OFF"}'
Info 2023-11-21 17:44:36MQTT publish: topic 'zigbee2mqtt/Kochinsel Beleuchtung/l1', payload '{"state":"OFF"}'
Info 2023-11-21 17:44:36MQTT publish: topic 'zigbee2mqtt/Kochinsel Beleuchtung', payload '{"color_mode":"xy","linkquality":224,"state_l1":"OFF"}'
Info 2023-11-21 17:44:36MQTT publish: topic 'zigbee2mqtt/Kochinsel Beleuchtung/l1', payload '{"state":"OFF"}'
Info 2023-11-21 17:44:37MQTT publish: topic 'zigbee2mqtt/Kochinsel Beleuchtung', payload '{"color_mode":"xy","linkquality":168,"state_l1":"ON"}'
Info 2023-11-21 17:44:37MQTT publish: topic 'zigbee2mqtt/Kochinsel Beleuchtung/l1', payload '{"state":"ON"}'
Info 2023-11-21 17:44:37MQTT publish: topic 'zigbee2mqtt/Kochinsel Beleuchtung', payload '{"color_mode":"xy","linkquality":224,"state_l1":"ON"}'
Info 2023-11-21 17:44:37MQTT publish: topic 'zigbee2mqtt/Kochinsel Beleuchtung/l1', payload '{"state":"ON"}'

Can you help me?

**Pull request closed without merging**
