### PR TITLE
Add support for Lonsonho switches

### PR DESCRIPTION
**Pull request by artem-dudarev**
https://www.aliexpress.com/item/4000298926256.html

X711A (1 gang):
```json
{"id":2,"type":"Router","ieeeAddr":"0xec1bbdfffe69c0b5","nwkAddr":45496,"manufId":4098,"manufName":"_TZE200_8vxj8khv","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_8vxj8khv","powerSource":1,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[]}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1594578663028}
```

X712A (2 gang):
```json
{"id":3,"type":"Router","ieeeAddr":"0xec1bbdfffe69c040","nwkAddr":33193,"manufId":4098,"manufName":"_TZE200_dhdstcqc","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_dhdstcqc","powerSource":1,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[]}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1594578656105}
```

Although these switches have 1 and 2 buttons, they still report 3 states, that's why I'm returning `l1, l2, l3` from the `endpoint`.

### CODE REVIEW

**Comment by Koenkk** [comment]
> Although these switches have 1 and 2 buttons, they still report 3 states, that's why I'm returning l1, l2, l3 from the endpoint.

I don't understand this, for e.g. the single button, why does it return 3 states? What do these state values mean?

**Comment by artem-dudarev** [comment]
It looks like they just use the same firmware for 1, 2 and 3 gang switches, which always sends 3 messages (one for each output line) even if the switch has 1 or 2 buttons.
Each message contains a line number (1, 2, or 3) and the state (1 or 0) which tells if this line is on or off.

**Comment by Koenkk** [comment]
To make things cleaner and allow to control the 1 gang with just `state` instead of `state_l1` I propose to make the following changes, does this work?

**toZigbee.js**
```js
tuya_switch_state: {
    key: ['state'],
    convertSet: async (entity, key, value, meta) => {
        const lookup = {l1: 1, l2: 2, l3: 3, l4: 4};
        const multiEndpoint = meta.mapped.meta && meta.mapped.meta.multiEndpoint;
        const keyid = multiEndpoint ? lookup[meta.endpoint_name] : 1;
        await entity.command(
            'manuSpecificTuyaDimmer', 'setData', {
                status: 0, transid: 16, dp: 256+keyid, fn: 0, data: [1, (value === 'ON') ? 1 : 0],
            },
            {disableDefaultResponse: true},
        );

        return {state: {state: value.toUpperCase()}};
    },
},
```

**fromZigbee.js**
```js
tuya_switch2: {
    cluster: 'manuSpecificTuyaDimmer',
    type: 'commandGetData',
    convert: (model, msg, publish, options, meta) => {
        const multiEndpoint = model.meta && model.meta.multiEndpoint;
        const dp = msg.data.dp;
        const state = msg.data.data[0] ? 'ON' : 'OFF';
        if (multiEndpoint) {
            const lookup = {257: 'state_l1', 258: 'state_l2', 259: 'state_l3'};
            return {[lookup[dp]]: state}
        } else {
            return {state: state};
        }
    },
},
```

**devices.js**

```js
// Lonsonho
{
    fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_8vxj8khv'}],
    model: 'X711A',
    vendor: 'Lonsonho',
    description: '1 gang switch',
    supports: 'on/off',
    fromZigbee: [fz.tuya_switch2, fz.ignore_time_read],
    toZigbee: [tz.tuya_switch_state],
},
{
    fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_dhdstcqc'}],
    model: 'X712A',
    vendor: 'Lonsonho',
    description: '2 gang switch',
    supports: 'on/off',
    fromZigbee: [fz.tuya_switch2, fz.ignore_time_read],
    toZigbee: [tz.tuya_switch_state],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        // Endpoint selection is made in tuya_switch_state
        return {'l1': 1, 'l2': 1};
    },
},
```

Note to self after this merge: https://github.com/Koenkk/zigbee2mqtt/pull/3901

**Comment by artem-dudarev** [comment]
Unfortunately, it doesn't work for 1-gang switch.
When I click its button to turn on the light, it sends three messages: the first message is for the line 1, which I just turned on, and two more messages are for non-existent lines 2 and 3:
```
Received Zigbee message from 'switch4', type 'commandGetData', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":63,"dp":257,"fn":0,"data":{"type":"Buffer","data":[1]}}' from endpoint 1 with groupID 0
MQTT publish: topic 'zigbee2mqtt/switch4', payload '{"state":"ON","linkquality":57}'
Received Zigbee message from 'switch4', type 'commandGetData', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":64,"dp":258,"fn":0,"data":{"type":"Buffer","data":[0]}}' from endpoint 1 with groupID 0
MQTT publish: topic 'zigbee2mqtt/switch4', payload '{"state":"OFF","linkquality":63}'
Received Zigbee message from 'switch4', type 'commandGetData', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":65,"dp":259,"fn":0,"data":{"type":"Buffer","data":[0]}}' from endpoint 1 with groupID 0
MQTT publish: topic 'zigbee2mqtt/switch4', payload '{"state":"OFF","linkquality":60}'
```
As you can see, the first message is converted to `state: ON`, which is correct, but the other two messages immediately overwrite it with `state : OFF`.
So for 1-gang switch we should convert only `dp: 257` and ignore `dp: 258` and `dp: 259`.

**Comment by artem-dudarev** [comment]
I changed the code to `return dp == 257 ? {state: state} : null;` - now it works.
Probably we should also remove `state_l3` for the 2-gang switch, shouldn't we?

**Comment by artem-dudarev** [comment]
What about something like this?
```js
meta: {multiEndpoint: true, endpointsCount: 2},
```
```js
const multiEndpoint = model.meta && model.meta.multiEndpoint;
const endpoint = msg.data.dp - 256;
const state = msg.data.data[0] ? 'ON' : 'OFF';
if (multiEndpoint) {
    if (endpoint > 0 && endpoint <= model.meta.endpointsCount) {
        return {[`state_l${endpoint}`]: state};
    } else {
        return null;
    }
} else {
    return endpoint === 1 ? {state: state} : null;
}
```

**Comment by Koenkk** [comment]
Does this work?

```js
tuya_switch2: {
    cluster: 'manuSpecificTuyaDimmer',
    type: 'commandGetData',
    convert: (model, msg, publish, options, meta) => {
        const multiEndpoint = model.meta && model.meta.multiEndpoint;
        const dp = msg.data.dp;
        const state = msg.data.data[0] ? 'ON' : 'OFF';
        if (multiEndpoint) {
            const lookup = {257: 'l1', 258: 'l2', 259: 'l3'};
            const ep = lookup[dp];
            if (ep in model.endpoint(msg.endpoint.getDevice())) {
                return {[`state_${lookup[dp]}`]: state};
            }
        } else {
            return dp === 257 ? {state: state} : null;
        }
    },
},
```

**Comment by artem-dudarev** [comment]
Yes, it works. But is it correct to not return anything when `if (ep in model...)` is false?

Also, I think we should add `multiEndpoint: true` to Norklmes switch because it uses `tz.tuya_switch_state`, which behavior has been changed.

**Comment by Koenkk** [comment]
Looks good now, can I merge this?

**Comment by artem-dudarev** [comment]
Yes, please.

**Comment by Koenkk** [comment]
Thanks!

**Comment by tabletka-ao** [comment]
@Koenkk, @artem-dudarev 
I see added support for Lonsonho switches.
What should I do for the switches to work correct with Zigbee2mqtt Hass.io?

**Comment by artem-dudarev** [comment]
@tabletka-ao You should install zigbee2mqtt-edge version of the add-on:
https://github.com/danielwelch/hassio-zigbee2mqtt#installation
But I would wait for the new release.

**Comment by artem-dudarev** [comment]
By the way, the seller on AliExpress was very interested in adding support for his switches to Zigbe2mqtt, and he sent me the 3 gang switch X713A for free :) So I will add it as soon as the package arrives.

**Comment by PWSteal** [comment]
I got 3-gang version yesterday. Not sure if it's X713A, but it is "No RF433 Function | With Neutral | 3-Gang" from [the same link in first comment](https://www.aliexpress.com/item/4000298926256.html).

`{"id":3,"type":"Router","ieeeAddr":"0xec1bbdfffe76c088","nwkAddr":7204,"manufId":4098,"manufName":"_TZE200_fqytfymk","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_fqytfymk","powerSource":1,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[]}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1595682243936}`

Next week I'll get another one 3-gang with neutral.

**Comment by artem-dudarev** [comment]
@PWSteal You can find the model on the switch:
image

**Comment by lostpoint-ru** [comment]
I got my 3-gang neutral version today, patched zigbee-herdsman-converters based on 2-gang one (just added l3 endpoint and changed fingerprints/model), and it works weird.

Home Assistant reads state changes perfectly when I toggle the physical buttons, but most of the time it either ignores state changes (the toggle UI element changes, but nothing happens with switch in the real world), or delays changes or sometimes even invert toggler state (shows off when the light is on and vice versa).

I'm trying to figure out, do I need to patch something in z2m/converters, or I just got myself a faulty unit. :/

It's "russian" IML version, with a firmware that looks like a curtain motor to z2m by default.

**Comment by lostpoint-ru** [comment]
Mine is labeled X703A btw, not X713A, for some reason.

**Comment by lostpoint-ru** [comment]
Lol, I googled this SKU and found this item sold as vovoway brand (though I bought it from Lonsonho official ali store).
https://www.aliexpress.com/i/4000709813999.html

Mine also has blue "ON" leds, unlike my other Lonsonho switches.

**Comment by artem-dudarev** [comment]
@lostpoint-ru As far as I understand, X703A is `With Neutral` and X713A is `No Neutral`.
My 1 and 2 gang switches have similar weird behavior, so it's rather faulty design than a faulty unit.
Also, I noticed that these switches always execute the `toggle` command instead of specific `on` or `off` commands.
Anyways, I've ordered the Tuya gateway from the same seller, so I'll see how the native application works with these switches.

**Comment by lostpoint-ru** [comment]
Oh, I see. 

I thought you've managed to get them work perfectly, so I ordered mine hoping to not have any major troubles with it. )

I can't even imagine, why do they even bother to have different firmwares for basically the same units (the ones they sell from China and the ones they ship from Russia via IML).

Toggle seems to be the explanation why sometimes it works properly and sometimes it works inverted. 

Also I cannot get it, why do they use vendor field to distinct different units instead of model -- they have plenty of kinds with same model and different "vendors" like _TZE200_8vxj8khv, _TZE200_dhdstcqc, _TZE200_fqytfymk 😟 

--

Артём, а можно с вами как-то пообщаться в тележке или воцапе каком-нибудь?

**Comment by PWSteal** [comment]
So I got another one 3-gang with neutral and now I have:

1. X703A 3-gang with neutral, shipping form Ru. Leds are red (off) \ blue (on).
In HA MQTT integrations hown as TuYa Curtain motor (TS0601)
Database entry:

`{"id":10,"type":"EndDevice","ieeeAddr":"0xec1bbdfffe803958","nwkAddr":2159,"manufId":4098,"manufName":"_TYZB01_xfpdrwvc","powerSource":"Battery","modelId":"TS0011","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,4,5,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"65506":19,"modelId":"TS0011","manufacturerName":"_TYZB01_xfpdrwvc","powerSource":3,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[]}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1594815972577}`

2. X703A 3-gang with neutral, shipping from China. Leds are bright green (off) \ dim green (on).
In HA MQTT integrations shown as [Zemismart Smart light switch - 3 gang with neutral wire (ZM-L03E-Z)](https://www.zigbee2mqtt.io/devices/ZM-L03E-Z.html). Works straight out of the box.
Database entry:

`{"id":11,"type":"Router","ieeeAddr":"0xec1bbdfffe7bd48b","nwkAddr":1489,"manufId":0,"manufName":"_TYZB01_b8cr31hp","powerSource":"Mains (single phase)","modelId":"TS0003","epList":[1,2,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"TS0003","manufacturerName":"_TYZB01_b8cr31hp","powerSource":1,"zclVersion":3,"appVersion":66}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018eba449","endpointID":1}]},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018eba449","endpointID":1}]},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018eba449","endpointID":1}]}},"appVersion":66,"zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1595853120175}`

**Comment by lostpoint-ru** [comment]
looks like it's easier to just order another one from China and leave blue version for the future..

**Comment by lostpoint-ru** [comment]
I wonder, is there some way do dump firmware from Chinese versions and upload it into Russian ones?..

**Comment by lostpoint-ru** [comment]
> 1. X703A 3-gang with neutral, shipping from China. Leds are bright green (off) \ dim green (on).
>    In HA MQTT integrations shown as [Zemismart Smart light switch - 3 gang with neutral wire (ZM-L03E-Z)](https://www.zigbee2mqtt.io/devices/ZM-L03E-Z.html). Works straight out of the box.

BTW, if you're in Russia and, by chance, is willing to sell Chinese version, I would gladly buy to save me some time, I wasted much of it first buying several 1/2 gang switches (they ended up not fitting wall boxes together), then ordering 3-gang from Russia and now I have to order another one from China.. :/

**Comment by PWSteal** [comment]
> willing to sell Chinese version

Nah, thanks)

BTW Chinese X703A has much louder clicks in comparison with Ru when you make switch from HA (not physical buttons). I also have 1-gang without neutral (bought it 1-2 months ago) and it is silent when you control it from HA.

Also, added pics to previous post.

**Comment by lostpoint-ru** [comment]
> Nah, thanks)

Well, it was a long shot anyway :)

Thanks for the pictures, looks like they have completely different PCBs despite sharing the very same plastic housing.
Whatever, I think it's time to go order a Chinese one.

**Comment by lostpoint-ru** [comment]
I found some interesting clue, btw.

Just hooked up this switch to test Raspberry test stand with separate mosquitto, and trying it with MQTT Explorer.

When I send random payload to `zigbee2mqtt/bedroom_light/l2/set` queue, it toggles L2 output, just like Artem said. 
If command is executed properly (i.e. switch changed state), then a message disappears from queue.
And when switch does nothing -- a message is still left in queue.

Maybe it has something to do with z2m fails to properly deliver toggle command?

**Comment by rkiller2006** [comment]
> @lostpoint-ru As far as I understand, X703A is `With Neutral` and X713A is `No Neutral`.
> My 1 and 2 gang switches have similar weird behavior, so it's rather faulty design than a faulty unit.
> Also, I noticed that these switches always execute the `toggle` command instead of specific `on` or `off` commands.
> Anyways, I've ordered the Tuya gateway from the same seller, so I'll see how the native application works with these switches.

Hello Artem,

I think you in the right way to know how it works.
We are waiting for good news.

**Comment by rkiller2006** [comment]
Hello,

Do we have the solution to solve toggle behavior of switch?

**Comment by artem-dudarev** [comment]
@rkiller2006 Unfortunately this is a hardware (firmware) issue. The current firmware doesn't distinguish `on` and `off` commands.
The native Tuya application with Tuya hub has the same problem.

**Comment by rkiller2006** [comment]
Do alternative firmware exist, like tasmota?

**Comment by rkiller2006** [comment]
Help me, how can I change identification of X711A to X713A, I noticed that my X711A has 3 button physically, It is the reason for 3 payload message in Z2M I supposed. The middle button is the same for manual pushing. I would like to try identify it as 3 button switch and deactivate 1 and 3rd button.

**Pull request merged**
