### PR TITLE
Added support for ZNCZ04LM

### PR DESCRIPTION
**Pull request by tomaae**
zigbee2mqtt:info  2019-11-23T00:00:18: Device 'Computer' joined
zigbee2mqtt:info  2019-11-23T00:00:18: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"Computer"}}'
zigbee2mqtt:info  2019-11-23T00:00:18: Starting interview of 'Computer'
zigbee2mqtt:info  2019-11-23T00:00:18: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"Computer"}}'
zigbee2mqtt:info  2019-11-23T00:00:19: Successfully interviewed 'Computer', device has successfully been paired
zigbee2mqtt:info  2019-11-23T00:00:19: Device 'Computer' is supported, identified as: Xiaomi Mi power plug ZigBee EU (ZNCZ04LM)
zigbee2mqtt:info  2019-11-23T00:00:19: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"Computer","model":"ZNCZ04LM","vendor":"Xiaomi","description":"Mi power plug ZigBee EU","supported":true}}'
zigbee2mqtt:info  2019-11-23T00:00:22: MQTT publish: topic 'zigbee2mqtt/Computer', payload '{"state":"OFF","linkquality":36,"power":4.67}'
zigbee2mqtt:info  2019-11-23T00:00:38: MQTT publish: topic 'zigbee2mqtt/Computer', payload '{"state":"ON","linkquality":2,"power":4.67}'
zigbee2mqtt:info  2019-11-23T00:00:47: MQTT publish: topic 'zigbee2mqtt/Computer', payload '{"state":"ON","linkquality":34,"power":4.75}'
zigbee2mqtt:info  2019-11-23T00:01:18: MQTT publish: topic 'zigbee2mqtt/Computer', payload '{"state":"ON","linkquality":23,"power":0}'
zigbee2mqtt:info  2019-11-23T00:01:32: MQTT publish: topic 'zigbee2mqtt/Computer', payload '{"state":"ON","linkquality":28,"power":4.67}'

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks! Could you provide an AliExpress link to the devive? Im interested in it.

**Comment by tomaae** [comment]
> 
> 
> Thanks! Could you provide an AliExpress link to the devive? Im interested in it.

I got it in a local xiaomi shop. I have already tried to look up this device, but it does not seem to be anywhere online yet.
Btw, it does not retain power state after power loss/unplug. In case that is something you need.

**Comment by Koenkk** [comment]
Ok thanks, I guess its really new! Does it have the eu ground connectors?

**Comment by tomaae** [comment]
> 
> 
> Ok thanks, I guess its really new! Does it have the eu ground connectors?
> 
> EDIT: and whats the price?
> 
> EDIT 2: Could you make a photo of it?

It uses german shuko connectors (type F) and can be of course plugged into type E

Price was 29.99e, but thats a local shop, I bet it will be cheaper elsewhere

I have my PC plugged into it right now, but here is a photo of the packaging:
IMG_1335

**Comment by Koenkk** [comment]
Looks great, thanks!

**Comment by rezmus** [comment]
@tomaae can you share which country you bought it in? i wait for this plug to show up on the market.

**Comment by tomaae** [comment]
> 
> 
> @tomaae can you share which country you bought it in? i wait for this plug to show up on the market.

Sure, Slovakia.
Its small and fairly quick to update watts. But wont retain power state after power loss, so my search continues.

**Comment by Koenkk** [comment]
@tomaae I think the power state is configurable from the Xiaomi gateway, once it is available on AliExpress I will buy it and figure it out.

**Comment by tomaae** [comment]
too bad they dont sell xiaomi gateway standalone here, otherwise I would give that a try.
but if it is configurable from xiaomi gateway, should not it be possible to do the same using z2m by sending it some payload? I think some other devices can be configured that way, like motion sensors are configured that way.

**Comment by rezmus** [comment]
this plug in not in mi home yet. atm it is only supported by chinese aqara hub firmware, but we should get update for mi eu / aqara eu hubs as well.

**Comment by rezmus** [comment]
this is how mi home read/write plug props via hub (based on lumi.plug.v1)

> {"method":"get_device_prop","params":["lumi.158d000xxxxxxx","poweroff_memory","charge_protect","en_night_tip_light"]}
< {"code":0,"result":[1,0,1]}

> {"method":"set_device_prop","params":{"sid":"lumi.158d000xxxxxxx","poweroff_memory":1}}
< {"code":0,"result":["ok"]}

**Comment by rezmus** [comment]
and this is device config for lumi.plug.* from new combo hub firmware (lumi.gateway.mgl03).

{
  "type": "plug",
  "mode": "alway_wake",
  "props": 
  {
    "channel_0"         :{"type":"status", "sync":true,  "default":"off"},
    "load_voltage"      :{"type":"status", "sync":true,  "default":0},
    "load_power"        :{"type":"status", "sync":true,  "default":0},
    "power"             :{"type":"status", "sync":true,  "default":"off"},
    "protect"           :{"type":"status", "sync":false, "default":"temp"},
    "fw_ver"            :{"type":"status", "sync":false, "default":0},
    "hw_ver"            :{"type":"status", "sync":false, "default":0},
    "poweroff_memory"   :{"type":"status", "sync":true,  "default":0},
    "charge_protect"    :{"type":"status", "sync":true,  "default":0},
    "en_night_tip_light":{"type":"config", "sync":false, "default":0},
    "power_on_join"     :{"type":"config", "sync":false, "default":0},
    "plug_detection"    :{"type":"config", "sync":false, "default":"plug_out"},
    "max_power"         :{"type":"config", "sync":true,  "default":1800}
  },
  "prop_trans": 
  {
    "lumi2xiaomi_prop":
    {
      "0.11.85"    :[["*", "p;load_voltage;*"]],
      "0.12.85"    :[["*", "p;load_power;*"]],
      "0.13.85"    :[["*", "n;;_"]],
      "13.1.85"    :[["*", "n;;_"]],
      "14.1.111"   :[["*", "n;;_"]],
      "14.30.85"   :[["*", "n;;_"]],
      "14.31.85"   :[["*", "n;;_"]],
      "14.9.111"   :[["*", "n;;_"]],
      "14.9.85"    :[["*", "n;;_"]],
      "4.1.104"    :[["*", "n;;_"]],
      "4.1.85"     :[["0", "p;channel_0;\"off\""], ["1", "p;channel_0;\"on\""], ["2", "n;;_"]],
      "4.1.87"     :[["*", "n;;_"]],
      "4.10.85"    :[["*", "n;;_"]],
      "4.4.85"     :[["*", "n;;_"]],
      "410.0.85"   :[["*", "n;;_"]],
      "8.0.2002"   :[["*", "n;;_"]],
      "8.0.2003"   :[["*", "n;;_"]],
      "8.0.2004"   :[["*", "n;;_"]],
      "8.0.2005"   :[["*", "n;;_"]],
      "8.0.2006"   :[["*", "n;;_"]],
      "8.0.2007"   :[["*", "n;;_"]],
      "8.0.2008"   :[["*", "n;;_"]],
      "8.0.2009"   :[["*", "n;;_"]],
      "8.0.2010"   :[["*", "n;;_"]],
      "8.0.2011"   :[["*", "n;;_"]],
      "8.0.2012"   :[["*", "n;;_"]],
      "8.0.2013"   :[["*", "n;;_"]],
      "8.0.2014"   :[["1", "p;protect;\"temp\""], ["2", "p;protect;\"voload\""]],
      "8.0.2015"   :[["1", "p;power;\"on\""], ["0", "p;power;\"off\""], ["2", "p;power;\"unknown\""]],
      "8.0.2021"   :[["*", "n;;_"]],
      "8.0.2022"   :[["*", "p;fw_ver;*"]],
      "8.0.2023"   :[["*", "p;hw_ver;*" ]],
      "8.0.2024"   :[["*", "n;;_"]],
      "8.0.2025"   :[["*", "n;;_"]],
      "8.0.2026"   :[["*", "n;;_"]],
      "8.0.2027"   :[["*", "n;;_"]],
      "8.0.2028"   :[["*", "n;;_"]],
      "8.0.2029"   :[["*", "n;;_"]],
      "8.0.2030"   :[["*", "p;poweroff_memory;*"]],
      "8.0.2031"   :[["*", "p;charge_protect;*"]],
      "8.0.2032"   :[["*", "p;en_night_tip_light;*"]],
      "8.0.2033"   :[["*", "n;;_"]],
      "8.0.2041"   :[["*", "n;;_"]],
      "8.0.2042"   :[["*", "p;max_power;*"]],
      "8.0.2044"   :[["0", "p;plug_detection;\"plug_out\""], ["1", "p;plug_detection;\"plug_in\""]],
      "8.0.2045"   :[["*", "n;;_"]],
      "8.0.2086"   :[["*", "n;;_"]],
      "8.0.9001"   :[["*", "n;;_"]]
    },
    "lumi2xiaomi_upload": 
    {
      "0.11.85"    :[["*", "p;load_voltage;*"]],
      "0.12.85"    :[["*", "p;load_power;*"]],
      "0.13.85"    :[["*", "n;;_"]],
      "13.1.85"    :[["*", "n;;_"]],
      "14.1.111"   :[["*", "n;;_"]],
      "14.30.85"   :[["*", "n;;_"]],
      "14.31.85"   :[["*", "n;;_"]],
      "14.9.111"   :[["*", "n;;_"]],
      "14.9.85"    :[["*", "n;;_"]],
      "4.1.104"    :[["*", "n;;_"]],
      "4.1.85"     :[["0", "p;channel_0;\"off\""], ["1", "p;channel_0;\"on\""], ["2", "n;;_"]],
      "4.1.87"     :[["*", "n;;_"]],
      "4.10.85"    :[["*", "n;;_"]],
      "4.4.85"     :[["*", "n;;_"]],
      "410.0.85"   :[["*", "n;;_"]],
      "8.0.2002"   :[["*", "n;;_"]],
      "8.0.2003"   :[["*", "n;;_"]],
      "8.0.2004"   :[["*", "n;;_"]],
      "8.0.2005"   :[["*", "n;;_"]],
      "8.0.2006"   :[["*", "n;;_"]],
      "8.0.2007"   :[["*", "n;;_"]],
      "8.0.2008"   :[["*", "n;;_"]],
      "8.0.2009"   :[["*", "n;;_"]],
      "8.0.2010"   :[["*", "n;;_"]],
      "8.0.2011"   :[["*", "n;;_"]],
      "8.0.2012"   :[["*", "n;;_"]],
      "8.0.2013"   :[["*", "n;;_"]],
      "8.0.2014"   :[["1", "p;protect;\"temp\""], ["2", "p;protect;\"voload\""]],
      "8.0.2015"   :[["1", "p;power;\"on\""], ["0", "p;power;\"off\""], ["2", "p;power;\"unknown\""]],
      "8.0.2021"   :[["*", "n;;_"]],
      "8.0.2022"   :[["*", "p;fw_ver;*"]],
      "8.0.2023"   :[["*", "p;hw_ver;*" ]],
      "8.0.2024"   :[["*", "n;;_"]],
      "8.0.2025"   :[["*", "n;;_"]],
      "8.0.2026"   :[["*", "n;;_"]],
      "8.0.2027"   :[["*", "n;;_"]],
      "8.0.2028"   :[["*", "n;;_"]],
      "8.0.2029"   :[["*", "n;;_"]],
      "8.0.2030"   :[["*", "n;;_"]],
      "8.0.2031"   :[["*", "n;;_"]],
      "8.0.2032"   :[["*", "n;;_"]],
      "8.0.2033"   :[["*", "n;;_"]],
      "8.0.2041"   :[["*", "n;;_"]],
      "8.0.2042"   :[["*", "p;max_power;*"]],
      "8.0.2044"   :[["1", "e;plug_detection;\"plug_in\""], ["0", "e;plug_detection;\"plug_out\""]],
      "8.0.2045"   :[["*", "n;;_"]],
      "8.0.2086"   :[["*", "n;;_"]],
      "8.0.9001"   :[["*", "n;;_"]]
    },
    "xiaomi2lumi": 
    {
      "channel_0"         :["4.1.85", [["\"on\"", "1"], ["\"off\"", "0"], ["\"toggle\"", "2"]]],
      "load_voltage"      :["0.11.85", [["*" , "*" ]]],
      "load_power"        :["0.12.85", [["*" , "*" ]]],
      "power"             :["8.0.2015", [["\"on\"", "1"], ["\"off\"", "0" ], ["\"unknow\"", "2"]]],
      "protect"           :["8.0.2014", [["\"temp\"", "8"], ["\"voload\"","4"]]],
      "fw_ver"            :["8.0.2022", [["*" , "*" ]]],
      "hw_ver"            :["8.0.2023", [["*" , "*" ]]],
      "poweroff_memory"   :["8.0.2030", [["*" , "*" ]]],
      "charge_protect"    :["8.0.2031", [["*" , "*" ]]],
      "en_night_tip_light":["8.0.2032", [["*" , "*" ]]],
      "plug_detection"    :["8.0.2044", [["\"plug_in\"", "0"], ["\"plug_out\"", "1"]]],
      "max_power"         :["8.0.2042", [["*" , "*" ]]]
    }
  }
}

**Comment by tomaae** [comment]
sending it poweroff_memory option does nothing.
I tried to look over the code, but cant figure out this one.

**Comment by rezmus** [comment]
"data":"{\"poweroff_memory\":\"on\"}

**Comment by tomaae** [comment]
I have already tried that, but I dont think it is supposed to work like that.

**Comment by rezmus** [comment]
this is log from serial console of lumi dev working on eu plug which shows when poweroff_memory is being switched on.

[12:08:06:694]send to sdk {"cmd":"read","model":"plug.mmeu01","sid":"4cf8cdf3c74639c","short_id":"53546","token":"10014523","data":"{\"poweroff_memory\":\"status\"}"}
[12:08:06:739]serial port recv:{"cmd":"report","model":"plug.mmeu01","sid":"4cf8cdf3c74639c","short_id":53546,"token":"179","data":"{\"poweroff_memory\":\"off\"}"}
[12:08:11:582]send to sdk {"cmd":"write","model":"plug.mmeu01","sid":"4cf8cdf3c74639c","short_id":"53546","token":"10014530","data":"{\"poweroff_memory\":\"on\"}"}
[12:08:11:628]serial port recv:{"cmd":"report","model":"plug.mmeu01","sid":"4cf8cdf3c74639c","short_id":53546,"token":"950","data":"{\"poweroff_memory\":\"on\"}"}
[12:08:11:655]Debug  : ===========AAA============= 153  send to ot_fd:{"id":46655,"method":"props","model":"lumi.plug.mmeu01","params":{"from.poweroff_memory":"0,,,0.trg=0","poweroff_memory":1},"sid":"lumi.4cf8cdf3c74639c"}

**Comment by Koenkk** [comment]
It doenst work like that, somebody needs to sniff the traffic while connected to the xiaomi gateway, then it can be added.

**Comment by tomaae** [comment]
I have 2 spare cc2531 on the way, I can turn one into a sniffer. Question is, which gateway version do I need that supports most mi/aqara devices so I can get configuration parameters for other devices too.

**Comment by rezmus** [comment]
most devices should be supported by new mi combo hub. sale starts on 12th december and it's priced ~18 USD in china.

**Comment by tomaae** [comment]
I see, there will be both new Mi and Aqara hub and bunch of new sensors available soon. I will wait then, thanks.

**Comment by rezmus** [comment]
https://www.mobilonline.sk/produkt/mi-smart-zastrcka

**Comment by tomaae** [comment]
> 
> 
> https://www.mobilonline.sk/produkt/mi-smart-zastrcka

Nice find. I will grab few from there once we get poweroff memory working

**Comment by rezmus** [comment]
do you have official xiaomi distributor on slovakia? i saw it already in 2 online .sk shops. strange i can't get it in any other eu country. in poland we have official distributor / mi stores, but still unknown when eu zigbee socket will be sold.

**Comment by tomaae** [comment]
I got it at mi-store.sk. Not sure if they are official, but it seems so. They don’t have it on their web yet tho. 
If you need help ordering it from sk site, I can help with translation and instructions.

**Comment by rezmus** [comment]
tx i'm not in such hurry and i don't think these shops ship abroad. it's kinda strange they sell it already, because this plug is still missing in mi home and current mi eu hub firmware won't pair with it afaik. it may only work with aqara hub via aqara app atm.

**Comment by rezmus** [comment]
there is also aqara brand new eu plug

https://aqara.ru/product/aqara-smart-plug/

**Comment by rezmus** [comment]
@tomaae i confirmed with polish reseller that they don't know anything about this product so it won't be fast till it's available here. i don't think that any .sk shop ships abroad, so any chance you can order one for me? i should be able to make it work with my rooted eu hub.

**Comment by rezmus** [comment]
found another .sk shop, but they only ship to slovakia, czech, hungary.

https://www.rychlypresun.sk/produkty/540-mi-smart-zastrcka-wi-fi.html

there is also some info

XIAOMi products on our website are imported by the official XIAOMI distributor for the Slovak market and all are properly certified for the EU market.

so i guess there is official xiaomi distributor for slovakia and already have this plug in stock.

**Comment by tomaae** [comment]
Careful, thats a wifi version. zigbee one is square, see photo above.
Of course I can get it for you, but if they dont send to Poland, I will have to ship it.
I'm on vacation right now, so I wont be able to get to mi store until next week. But if you want me to ship it to you, please contact me on twitter or discord. We dont want to put any personal information here :)

**Comment by rezmus** [comment]
ohh i think they mixed up zigbee model ZNCZ04LM and description with wifi plug photo (i have it, made by chuangmi, model ZNCZ05CM). anyway i will contact you next week, have a nice vacation!

**Comment by rezmus** [comment]
managed to buy it from mobilonline.sk, i should have it next week :)

**Comment by rezmus** [comment]
got mi eu plug. works fine with mi eu hub. does not pair with mi cn hub. power memory option works fine.

**Comment by tomaae** [comment]
I have ordered that new mi hub yesterday, we see. I hope it work, since I cannot but eu hub standalone for sniffing.
also their new light sensor, I just hope that one is faster to react then philips.

**Comment by rezmus** [comment]
i've also ordered cc2531 with sniffer fw and will try to log zigbee payload for poweroff_memory ;)

**Comment by tomaae** [comment]
perfect, once we get poweroff_memory working in z2m parameter working, it will be a perfect plug :)

**Comment by ryanbeaton** [comment]
Would be great to see powering_memory working. Closest I’ve ever seen was:
https://github.com/Koenkk/zigbee2mqtt/issues/297#issuecomment-415929791

**Comment by tomaae** [comment]
I found a pcap here: 
https://github.com/Koenkk/zigbee2mqtt/issues/201#issuecomment-415231510
It does not say much to me tho. data possibly needs decoding, but I never did that so not sure. I will try to find out how to do that when I have more free time.

**Comment by rezmus** [comment]
@tomaae @Koenkk

poweroff_memory

Attribute Field, Boolean: 0x01
Attribute: 0x0201
Data Type: Boolean (0x10)
0000 0001 = Boolean: True

en_night_tip_light

Attribute Field, Boolean: 0x01
Attribute: 0x0203
Data Type: Boolean (0x10)
0000 0001 = Boolean: True

max_power

Attribute Field, Float: 2300
Attribute: 0x020b
Data Type: Single Precision Floating Point (0x39)
Float: 2300

**Comment by tomaae** [comment]
Perfect, I will check if I’m able to get it working when I get home

**Comment by tomaae** [comment]
I have tried, but it does not do anything. No mention in debugs too, so not sure.

`    ZNCZ04LM_poweroff_memory: {
        key: ['poweroff_memory'],
        convertSet: async (entity, key, value, meta) => {
            await entity.write('genBasic', {0x0201: {value: value ? 0x01 : 0x00, type: 0x10}}, options.xiaomi);
        },
    },
    ZNCZ04LM_led: {
        key: ['led'],
        convertSet: async (entity, key, value, meta) => {
            await entity.write('genBasic', {0x0203: {value: value ? 0x01 : 0x00, type: 0x10}}, options.xiaomi);
        },
    },`

**Comment by rezmus** [comment]
can you log raw hex payload being sent? in hex it looks like 01 02 10 01 for poweroff_memory true (reversed byte order of attribute 0x0201). i can provide full pcap if needed.

**Comment by tomaae** [comment]
I dont have a sniffer yet, so I cant. but if you can give me pcap, I will have a look :)

**Comment by rezmus** [comment]
https://ufile.io/559nxojm

**Comment by tomaae** [comment]
image
I see there is a custom cluster. I tried to add it, but nothing. Guess we need someone more experienced with this.

**Comment by tomaae** [comment]
I have created #827 , hopefully someone can help

**Comment by tomaae** [comment]
I see my custom cluster implementation was recognized tho

`2019-12-19 06:40:31: No converter available for 'ZNCZ04LM' with cluster 'manuSpecificXiaomi' and type 'attributeReport' and data '{"247":{"type":"Buffer","data":[100,16,1,3,40,30,152,57,0,0,0,0,149,57,41,163,106,62,150,57,0,32,20,69,151,57,0,0,0,0,5,33,38,0,154,32,16,8,33,22,1,7,39,0,0,0,0,0,0,0,0,9,33,2,8,11,32,0,155,16,0]}}'

I wonder what are those. Some settings I guess.

**Comment by tomaae** [comment]
and this seems to be detection that something was plugged physically into the socket. Nice
>zigbee2mqtt:warn  2019-12-19 06:45:24: No converter available for 'ZNCZ04LM' with cluster 'manuSpecificXiaomi' and type 'attributeReport' and data '{"519":0}'
zigbee2mqtt:warn  2019-12-19 06:45:26: No converter available for 'ZNCZ04LM' with cluster 'manuSpecificXiaomi' and type 'attributeReport' and data '{"519":1}'

**Comment by rezmus** [comment]
poweroff_memory / en_night_tip_light state change does not lead to any changes in 0x00f7. btw 0x0202 is charge_protect.

**Comment by tomaae** [comment]
hmm, too bad, that means we cannot show them in UI. but thats not really important to see in UI.
seems like my implementation for poweroff_memory and led is correct according to example Koenkk gave me. 
I'm so confused about whats wrong there. Your pcap cannot be wrong, we have correct values.

Also, while looking for some things, I found this on google, saying it is in this thread for some reason. Seems to be a complete device config:
> { "type": "plug", "mode": "alway_wake", "props": { "channel_0" :{"type":"status", "sync":true, "default":"off"}, "load_voltage" :{"type":"status", "sync":true, "default":0}, "load_power" :{"type":"status", "sync":true, "default":0}, "power" :{"type":"status", "sync":true, "default":"off"}, "protect" :{"type":"status", "sync":false, "default":"temp"}, "fw_ver" :{"type":"status", "sync":false, "default":0}, "hw_ver" :{"type":"status", "sync":false, "default":0}, "poweroff_memory" :{"type":"status", "sync":true, "default":0}, "charge_protect" :{"type":"status", "sync":true, "default":0}, "en_night_tip_light":{"type":"config", "sync":false, "default":0}, "power_on_join" :{"type":"config", "sync":false, "default":0}, "plug_detection" :{"type":"config", "sync":false, "default":"plug_out"}, "max_power" :{"type":"config", "sync":true, "default":1800} }, "prop_trans": { "lumi2xiaomi_prop": { "0.11.85" :[["", "p;load_voltage;"]], "0.12.85" :[["", "p;load_power;"]], "0.13.85" :[["", "n;;_"]], "13.1.85" :[["", "n;;"]], "14.1.111" :[["*", "n;;"]], "14.30.85" :[["", "n;;_"]], "14.31.85" :[["", "n;;"]], "14.9.111" :[["*", "n;;"]], "14.9.85" :[["", "n;;_"]], "4.1.104" :[["", "n;;"]], "4.1.85" :[["0", "p;channel_0;"off""], ["1", "p;channel_0;"on""], ["2", "n;;"]], "4.1.87" :[["", "n;;_"]], "4.10.85" :[["", "n;;"]], "4.4.85" :[["*", "n;;"]], "410.0.85" :[["", "n;;_"]], "8.0.2002" :[["", "n;;"]], "8.0.2003" :[["*", "n;;"]], "8.0.2004" :[["", "n;;_"]], "8.0.2005" :[["", "n;;"]], "8.0.2006" :[["*", "n;;"]], "8.0.2007" :[["", "n;;_"]], "8.0.2008" :[["", "n;;"]], "8.0.2009" :[["*", "n;;"]], "8.0.2010" :[["", "n;;_"]], "8.0.2011" :[["", "n;;"]], "8.0.2012" :[["*", "n;;"]], "8.0.2013" :[["", "n;;_"]], "8.0.2014" :[["1", "p;protect;"temp""], ["2", "p;protect;"voload""]], "8.0.2015" :[["1", "p;power;"on""], ["0", "p;power;"off""], ["2", "p;power;"unknown""]], "8.0.2021" :[["", "n;;"]], "8.0.2022" :[["", "p;fw_ver;"]], "8.0.2023" :[["", "p;hw_ver;" ]], "8.0.2024" :[["*", "n;;"]], "8.0.2025" :[["", "n;;_"]], "8.0.2026" :[["", "n;;"]], "8.0.2027" :[["*", "n;;"]], "8.0.2028" :[["", "n;;_"]], "8.0.2029" :[["", "n;;"]], "8.0.2030" :[["", "p;poweroff_memory;"]], "8.0.2031" :[["", "p;charge_protect;"]], "8.0.2032" :[["", "p;en_night_tip_light;"]], "8.0.2033" :[["*", "n;;"]], "8.0.2041" :[["", "n;;_"]], "8.0.2042" :[["", "p;max_power;"]], "8.0.2044" :[["0", "p;plug_detection;"plug_out""], ["1", "p;plug_detection;"plug_in""]], "8.0.2045" :[["", "n;;"]], "8.0.2086" :[["*", "n;;"]], "8.0.9001" :[["", "n;;_"]] }, "lumi2xiaomi_upload": { "0.11.85" :[["", "p;load_voltage;"]], "0.12.85" :[["", "p;load_power;"]], "0.13.85" :[["", "n;;"]], "13.1.85" :[["*", "n;;"]], "14.1.111" :[["", "n;;_"]], "14.30.85" :[["", "n;;"]], "14.31.85" :[["*", "n;;"]], "14.9.111" :[["", "n;;_"]], "14.9.85" :[["", "n;;"]], "4.1.104" :[["*", "n;;"]], "4.1.85" :[["0", "p;channel_0;"off""], ["1", "p;channel_0;"on""], ["2", "n;;"]], "4.1.87" :[["*", "n;;"]], "4.10.85" :[["", "n;;_"]], "4.4.85" :[["", "n;;"]], "410.0.85" :[["*", "n;;"]], "8.0.2002" :[["", "n;;_"]], "8.0.2003" :[["", "n;;"]], "8.0.2004" :[["*", "n;;"]], "8.0.2005" :[["", "n;;_"]], "8.0.2006" :[["", "n;;"]], "8.0.2007" :[["*", "n;;"]], "8.0.2008" :[["", "n;;_"]], "8.0.2009" :[["", "n;;"]], "8.0.2010" :[["*", "n;;"]], "8.0.2011" :[["", "n;;_"]], "8.0.2012" :[["", "n;;"]], "8.0.2013" :[["*", "n;;"]], "8.0.2014" :[["1", "p;protect;"temp""], ["2", "p;protect;"voload""]], "8.0.2015" :[["1", "p;power;"on""], ["0", "p;power;"off""], ["2", "p;power;"unknown""]], "8.0.2021" :[["", "n;;_"]], "8.0.2022" :[["", "p;fw_ver;"]], "8.0.2023" :[["", "p;hw_ver;" ]], "8.0.2024" :[["", "n;;"]], "8.0.2025" :[["*", "n;;"]], "8.0.2026" :[["", "n;;_"]], "8.0.2027" :[["", "n;;"]], "8.0.2028" :[["*", "n;;"]], "8.0.2029" :[["", "n;;_"]], "8.0.2030" :[["", "n;;"]], "8.0.2031" :[["*", "n;;"]], "8.0.2032" :[["", "n;;_"]], "8.0.2033" :[["", "n;;"]], "8.0.2041" :[["*", "n;;"]], "8.0.2042" :[["", "p;max_power;"]], "8.0.2044" :[["1", "e;plug_detection;"plug_in""], ["0", "e;plug_detection;"plug_out""]], "8.0.2045" :[["", "n;;_"]], "8.0.2086" :[["", "n;;"]], "8.0.9001" :[["*", "n;;"]] }, "xiaomi2lumi": { "channel_0" :["4.1.85", [[""on"", "1"], [""off"", "0"], [""toggle"", "2"]]], "load_voltage" :["0.11.85", [["" , "" ]]], "load_power" :["0.12.85", [["" , "" ]]], "power" :["8.0.2015", [[""on"", "1"], [""off"", "0" ], [""unknow"", "2"]]], "protect" :["8.0.2014", [[""temp"", "8"], [""voload"","4"]]], "fw_ver" :["8.0.2022", [["" , "" ]]], "hw_ver" :["8.0.2023", [["" , "" ]]], "poweroff_memory" :["8.0.2030", [["" , "" ]]], "charge_protect" :["8.0.2031", [["" , "" ]]], "en_night_tip_light":["8.0.2032", [["" , "" ]]], "plug_detection" :["8.0.2044", [[""plug_in"", "0"], [""plug_out"", "1"]]], "max_power" :["8.0.2042", [["" , "" ]]] } } }

**Comment by rezmus** [comment]
"lumi_plug_setting_maxPower": "Maximum power limit",
"lumi_plug_setting_cutOff": "Power outage memory",
"lumi_plug_setting_cutOff_tps": "When the plug is on again, it restores the settings before the power outage.",
"lumi_plug_charging_protect": "Charging protection",
"lumi_plug_close_overload": "If the power is less than 2 W for half an hour, the plug will be turned off automatically",
"lumi_plug_setting_indecateLight": "Turn off indicator",
"lumi_plug_setting_indecateLight_tips": "Turn off the indicator from 21:00 to 09:00",

it's config for lumi.plug.* from hub firmware, but looks like mmeu01 only supports these

"method":"get_device_prop","params":["lumi.XXXX","channel_0","load_voltage","load_power","poweroff_memory","charge_protect","en_night_tip_light","max_power"]

load_voltage / load_power are not sent to zigbee socket however.

**Pull request merged**
