### PR TITLE
hotfix(Sengled): return RGB colors to bulbs and convert to modern extend

### PR DESCRIPTION
**Pull request by mrskycriper**
- Fix https://github.com/Koenkk/zigbee2mqtt/issues/22035
- Fix https://github.com/Koenkk/zigbee2mqtt/issues/22052
- Fix https://github.com/Koenkk/zigbee2mqtt/issues/22051

This bug was introduced in https://github.com/Koenkk/zigbee-herdsman-converters/pull/7168

Also converted all Sengled devices to modern extend along the way :)

### PS

~~I'm not sure about `color: true` since previous legacy extend technically only exposed XY color by default.~~

### CODE REVIEW

**Comment by mrskycriper** [comment]
## Marking as draft before testing confirmation

Can somebody please test any affected Sengled bulb with this temporary external converter? I need to now if they support hs, xy or both color modes. Replace `zigbeeModel` for your bulb if necessary.

```js
const {light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['E21-N1EA'],
    model: 'E21-N1EA',
    description: 'Smart LED multicolor A19 bulb',
    vendor: 'Sengled',
    extend: [light({effect: false, powerOnBehavior: false, colorTemp: {range: [154, 500]}, color: {modes: ['xy', 'hs']}})],
}

module.exports = definition;
```

**Comment by mrskycriper** [comment]
## UPD

HS color mode is confirmed to be supported. Re-opeing PR as ready for merge.

**Comment by BronsonZ** [comment]
I tested my Sengled E12-N1E BR30 bulbs with the following external converter:
```js
const {light, electricityMeter, forcePowerSource} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['E12-N1E'],
    model: 'E12-N1E',
    vendor: 'Sengled',
    description: 'Smart LED multicolor (BR30)',
    extend: [
        light({effect: false, powerOnBehavior: false, colorTemp: {range: [154, 500]}, color: {modes: ['hs']}}),
        electricityMeter({cluster: 'metering'}),
        forcePowerSource({powerSource: 'Mains (single phase)'})
    ]
};

module.exports = definition;
```

Using only `color: {modes: ['hs']}` I was not able to change the color of the bulbs, only the color temperature

When I set `color: {modes: ['xy']}` I was able to change the color again

At least for my bulbs, it doesn't look like they respond to "color_mode": "hs"

Setting `color: true` and `color: {modes: ['xy', 'hs']}` also works, it just uses the xy color mode.

**Comment by Koenkk** [comment]
Many thanks! Seems I was sleeping during https://github.com/Koenkk/zigbee-herdsman-converters/pull/7168 😴

**Pull request merged**
