### PR TITLE
Set colorTempRange for MLI 404000/404005/404012

### PR DESCRIPTION
**Pull request by sjorge**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by MattWestb** [comment]
Hey @sjorge its looks like your famous IKEA panels have getting one Zigbee 3 update now !!
https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html

**Comment by sjorge** [comment]
Not showing up yet in z2m it seems.

~ sjorge

**Comment by MattWestb** [comment]
I looking for the model IDs in the OTA files so can see for witch devices the new files is for :-))

**Comment by MattWestb** [comment]
Now all IKEA lights is Zigbee 3 only the old CWS is not updated and the old round gyro dimmer  and old motion sensor but its not  so bad :-))
```
OTA file name			Model ID 	OTA device namme
tradfri_light_lp		0x4201 16897	FLOALT panel WS 30x30 (FLOALT EU)
tradfri_light_hp		0x4202 16898	FLOALT panel WS 60x60 (FLOALT EU)
tradfri_light_basic		0x2101 8449	TRÅDFRI bulb E27 opal 1000lm (LED1622G12E27EU)
tradfri_light_ansluta_basic	0x4101 16641	TRADFRI transformer 10W (ICPSHC2410EUIL1)
```
I hope you is getting it very sooooon !!!

**Comment by sjorge** [comment]
Found the problem, they are only on the non testing ota source, updating all 4 now. Hopefully all up to date tomorrow.

Let’s hope the push a fix for the remotes soon too. There is apparently a new SDK for the firmware they are using.

~ sjorge

**Comment by MattWestb** [comment]
Great !!

I asking ZHA for the SDK version from Silabs they have using :-)))


And tomorrow you have new Zigbee 3 panels !!

**Comment by MattWestb** [comment]
SKD is updated but not to the "golden version" 6.7.8.0 that have the critical stack killing fix:

| OTA file name 		| Model ID Hex/Dec | OTA device namme				 | Version   | SDK     |
|-------------------------------|------------------|---------------------------------------------|-----------|---------|
| tradfri_light_lp		| 0x4201 16897 	   | FLOALT panel WS 30x30 (FLOALT EU)		 | 2.3.068   | 6.3.1.1 |
| tradfri_light_hp		| 0x4202 16898	   | FLOALT panel WS 60x60 (FLOALT EU)		 | 2.3.068   | 6.3.1.1 |
| tradfri_light_basic		| 0x2101 8449	   | TRÅDFRI bulb E27 opal 1000lm (LED1622G12E27EU)| 2.3.068 | 6.3.1.1 |
| tradfri_light_ansluta_basic	| 0x4101 16641	   | TRADFRI transformer 10W (ICPSHC2410EUIL1)	 | 2.3.068   | 6.3.1.1 |

I think you need repairing your devices then endpoints and cluster is changed.

**Pull request merged**
