### PR TITLE
Support 2 new Namron devices

### PR DESCRIPTION
**Pull request by runenerg**
* Support Namron ZigBee 4 channel switch K8, model 4512703
Supports on/off and dimming on 4 endpoints

* Allow dimmer buttons to dim all the way down to 0 and up to 255

* Support Namron ZigBee 1 channel switch K4, model 4512702.
Have separate buttons for on/off and dim up/down.

* Support Namron ZigBee 1 channel switch K4, model 4512702.
It has separate buttons for on/off and dim up/down.

Try again with squashed commit to avoid eslint triggering on separate commit

### CODE REVIEW

**Comment by runenerg** [comment]
I can't find the spaces eslint is complaining about. The line/column numbers don't make sense to me. Any possibility for some help where to look?

**Comment by Koenkk** [comment]
Note to self: after this merge https://github.com/Koenkk/zigbee2mqtt.io/pull/234

**Comment by Koenkk** [comment]
Thanks, I've updated the PR to make it more in line with the current insights:
- Only use `action` and make actions more naming more consistent
- Brightness is not in for the moment, if you think this is useful I can re-add this.

Can you test if it works correctly?

**Comment by runenerg** [comment]
It works as expected. All buttons on both devices give different actions which can be parsed into the nessesary information. So complete the pull request if you thinks its ok now.
I can live without brightness being stored in and reported from zigbee2mqtt. I'm using Domoticz as a frontend, and the autodim feature (implemented in ictcg1) was neat, but i probably can find a way to do the same in Domoticz and the brightness value is already stored there.
I removed some converters I previously added, which is not is use anymore.

**Comment by Koenkk** [comment]
- I've refactored to code a bit more
- Can you check if the `battery` works as expected now?

I will already merge this one but feel free to open an issue when it's not correct.

**Pull request merged**
