### PR TITLE
Rewrite the level_onoff_brightness converter

### PR DESCRIPTION
**Pull request by pyos**
Hopefully the comments should make the reasoning behind the code clearer.

This commit fixes two issues:

  1. `toggle` without transition after `off` with transition sets brightness to 1 (so #1097, but with `"state": "toggle"` instead of `"state": "on"`);

  2. `OnLevel` attribute is not respected by `on` with transition (which instead always restores the light to the previous level).

It also adds a new feature: publishing `{"brightness": ..., "state": null}` allows setting brightness without affecting state.

  * If the light is on and new brightness is 0, it will stay on, but switch to minimum brightness.

  * If the light is off and new brightness is not 0, the light might ignore the command or remember the brightness for the next time it is turned on (if `Options` has bit 0 set - see Koenkk/zigbee-herdsman#534).

Known remaining issues:

  * Sending "state": "on"/"off" with brightness or transition to a group may or may not affect the state of devices that don't support brightness. E.g. [Envilar ZG302-BOX-RELAY](https://www.zigbee2mqtt.io/devices/ZG302-BOX-RELAY.html) reacts to MoveToLevelWithOnOff commands despite not implementing the Level Control cluster, while the [LEDVANCE SMART+ plug](https://www.zigbee2mqtt.io/devices/AC10691.html) does not.

  * `OnLevel` is still ignored if the entity is a group.

  * When `on` has to use `MoveToLevelWithOnOff` due to previous `off` having used it too, the transition is 0 rather than `OnTransitionTime`.

### CODE REVIEW

**Comment by pyos** [comment]
Also, found another bug in the current implementation thanks to these tests - when `{state: "on"}` is sent after `{state: "off", transition: any}`, the lamp turns on immediately rather than with a transition of OnTransitionTime.

**Comment by Koenkk** [comment]
Reviewed the code now and this looks good. Would it be possible to fix the remaining 2 test cases? The use case for `Should turn device off when brightness 0 is send` is e.g. when you have a dimmer which only sends brightness; without this feature the dimmer is not able to turn the bulb off.

**Comment by pyos** [comment]
The difference in these tests is how the device turns on afterwards - currently sending `{state: "on"}` (without transition) after `{brightness: 0}` turns the device on at minimum brightness, while `{state: "on", transition: 0}` restores the old brightness. With this PR the brightness is restored regardless.

**Comment by Koenkk** [comment]
I see now, thanks!

**Pull request merged**
