### PR TITLE
Updates acova.js

### PR DESCRIPTION
**Pull request by molusk**
Older TAFFETAS2 devices have different model name.

### CODE REVIEW

**Comment by molusk** [comment]
Don't merge yet, please.
Previous model stop working, it is not recognized as supported anymore... it seems there are hidden caracters messing things up.

**Comment by Koenkk** [comment]
Could you share the data/database.db entry of this device?

**Comment by molusk** [comment]
It should be okay now.
Thank's for your work, this project and zigbee2mqtt are amazing !

**Comment by molusk** [comment]
Oops... talked too fast.
It seems I now need a line break between the two zigbeeModels. I will look for other files were this issue is managed to make sure I don't break things this time.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
