### PR TITLE
Сhanged priority to use external converters

### PR DESCRIPTION
**Pull request by xyzroe**
findByZigbeeModel and findByDevice return last candidate of all possible

Please check is it possible to do like this?
I got everything working.

### CODE REVIEW

**Comment by Koenkk** [comment]
Instead of doing this I prefer to add an additional parameter to https://github.com/Koenkk/zigbee-herdsman-converters/blob/3ec30751ac017104d7371195e45923be69930bc0/index.js#L39 called `addInFront` (default false) and set that to true here: https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/externalConverters.js#L13

**Comment by xyzroe** [comment]
And then, at https://github.com/Koenkk/zigbee-herdsman-converters/blob/3ec30751ac017104d7371195e45923be69930bc0/index.js#L59 and https://github.com/Koenkk/zigbee-herdsman-converters/blob/3ec30751ac017104d7371195e45923be69930bc0/index.js#L68 check if exists any item with addInFront = true, return than one? Right?
Ok I'l work on it later.

**Comment by xyzroe** [comment]
I tried, but I'm not so good at tests writing. 
But I checked everything manually. 
I am my opinion everything works as expected.

**Comment by nurikk** [comment]
> Instead of doing this I prefer to add an additional parameter to
> 
> https://github.com/Koenkk/zigbee-herdsman-converters/blob/3ec30751ac017104d7371195e45923be69930bc0/index.js#L39
> 
> called `addInFront` (default false) and set that to true here: https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/externalConverters.js#L13

Why do we need to do this? Why not let to override internal converter by default? This behaviour is quite safe, since user need to do two steps:
1) put external converter in data folder
2) add external converter into configuration.json
This can't cause any unexpected behaviour.

**Comment by xyzroe** [comment]
I started from made returning last candidate of all possible, it is the easiest way to implement this function.

**Comment by Koenkk** [comment]
@xyzroe sorry to switch opinions, but I think the solution provided by @nurikk is better indeed.

So the only changed required here is:

```js
- return candidates ? candidates[0] : null; 
+ return candidates ? candidates[candidates.length - 1] : null;
```

**Comment by xyzroe** [comment]
How about findByDevice() ?  
I think it is also necessary to change the order

**Comment by nurikk** [comment]
> How about findByDevice() ?
> I think it is also necessary to change the order

Yes, apply this logic everywhere where it necessary. I just gave small example

**Comment by xyzroe** [comment]
returned everything as it was originally in the commit e064dd9

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
