### PR TITLE
Support GP-WOU019BBDWG SmartThings UK Plug (2019)

### PR DESCRIPTION
**Pull request by eyeson**
My first ever go at a git PULL, and editing any code... so please be critical.
I've based this one off of this https://github.com/Koenkk/zigbee-herdsman-converters/pull/930

Not entirely sure I've done everything correctly!

### CODE REVIEW

**Comment by Koenkk** [comment]
Looks good, thanks! :100:

**Comment by magnayn** [comment]
I'm not sure this is 100% right yet ..

The plugs report both current and power (current = draw right now: Amps or Watts; power = "how much power has been used", kWh - which always should go up, for obvious reasons).

I get my plugs to pair, I'm successfully getting some data. But:
The current value isn't being put into /current, it's being put into /power ?
/current is always zero (as is Voltage)

I don't really understand the architecture of herdsman/converters to be able to grok why this is the case..

**Comment by Koenkk** [comment]
Can you provide the debug logging?

**Comment by eyeson** [comment]
> I'm not sure this is 100% right yet ..
> 
> The plugs report both current and power (current = draw right now: Amps or Watts; power = "how much power has been used", kWh - which always should go up, for obvious reasons).
> 
> I get my plugs to pair, I'm successfully getting some data. But:
> The current value isn't being put into /current, it's being put into /power ?
> /current is always zero (as is Voltage)
> 
> I don't really understand the architecture of herdsman/converters to be able to grok why this is the case..

Agreed - it does look like I need to do some more work on this. I can't provide logs at the moment - but I will try and get to it this week.

**Pull request merged**
