### PR TITLE
Improvements for Bosch BTH-RA

### PR DESCRIPTION
**Pull request by compujuckel**
- Add input for remote temperature sensor. Setting `remote_temperature` will override the value of `local_temperature`.
- Add `displayed_temperature` to choose which temperature is shown on the thermostat display
- Fix range of `local_temperature_calibration`
- Add running state

Unfortunately I haven't figured out yet how to "exit" this remote temperature mode. Writing 0 just sets the internal temperature to 0°C.

### CODE REVIEW

**Comment by BBJake** [comment]
Great work!
How did you find out that the ID 0x4040 is responsible for this?

**Comment by BBJake** [comment]
I also tried to figured that out, but I thought that form the Zigbee-specification ID 0x0001 (outdoor temperatur) has something to do whit that... but that is just for reading...
image
The remote sensing should toggle that
image

image
But I was not able to set this. Additionally the spec doesn't seems to describe how to set a remote value...

Have you tried to set a very high value to disable it?
May the invalid value mentioned for the "LocalTemperature" ) 0x8000 works for this...

**Comment by compujuckel** [comment]
I just sent a "Discover Attributes" command and checked the attributes with the same data type as LocalTemperature

**Comment by BBJake** [comment]
> I just sent a "Discover Attributes" command and checked the attributes with the same data type as LocalTemperature

Please excuse my ignorance, but how to do that with Zigbee2MQTT?
I haven't found this option anywhere yet.

**Comment by compujuckel** [comment]
I've patched that into my local z2m, will create a PR for that at some point probably

**Comment by r-eckert** [comment]
First of all great work figuring this out!
I have modified better_thermostat so I can test the new remote_temperature feature in my Home Assistant setup and it seems like the device reverts to using the internal temperature sensor after about 30 minutes if no new remote_temperature is sent. I have added an automatic refresh feature that regulary sends the temperature even if it didn't change and now the local_temperature no longer shows any strange jumps so I assume that must be what's happening.

**Comment by Dommoe** [comment]
Where do I have to enter this so that I already have these functions on my Bosch thermostat?

**Comment by compujuckel** [comment]
bump to keep this open, need to finish it properly

**Comment by sestriel** [comment]
When do you think you could have it ready? I would be happy if it quickly ended up in the ioBroker Zigbee adapter afterwards

**Comment by DerDreschner** [comment]
@compujuckel : What is still open here? Maybe I can continue the open points for you.

**Comment by sestriel** [comment]
Any news at this @compujuckel ? Are you still on it?
Otherwise i would open a new PullRequest to finish this up cause others are waiting and this can easily be completed

**Comment by compujuckel** [comment]
@sestriel @DerDreschner sorry, I kinda got sidetracked with other things. Feel free to create a new PR for the stuff that's still open (local_temperature_calibration was fixed in another PR already)

**Pull request closed without merging**
