### PR TITLE
Add new device: IKEA RODRET E2201

### PR DESCRIPTION
**Pull request by thatslolo**
Koenkk/zigbee2mqtt.io#2129

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by MattWestb** [comment]
The current firmware is is supporting group binding but i have not testing if device binding is working or not in ZHA.

**Comment by thatslolo** [comment]
In my testing group binding worked as well as device binding.

**Comment by MattWestb** [comment]
Sound great then they is using EZSP stack 7.1.X and it shall being possible doing both and also ZHA is still getting all events to the coordinator after paring and adding one group so its looks IKEA have doing somthing good this time in there "kitchen".

**Comment by coolspot18** [comment]
I just tried the latest 1.32.2-1 but the E2201 is not responding to any button presses? The action field is not returning anything?

**Comment by MattWestb** [comment]
@martin-vl Witch model is you having then the PR is only doe the dimmer switch and not foe short cut and OpenCloce versions ?

**Comment by martin-vl** [comment]
@MattWestb I see that I have the E2213 type. The picture looked the same ;). Maybe I'm going to try to add this one. Fingers crossed.

**Comment by MattWestb** [comment]
I dont knowing how you was getting it then its not Zigbee certified but its in the pipe like the shortcut bottom, RGB LED Stripes and new motion and windows/door sensors but all is expected after new year

**Pull request merged**
