### PR TITLE
Change mode for Aqara Opple switch

### PR DESCRIPTION
**Pull request by kirovilya**
Ability to switch modes: with and without binding.
"Event" mode by default.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by sjorge** [comment]
So with this we can change the mode and bind it to a group of bulbs so it works even if the coordinator is down ? ( like the ikea remots)

**Comment by kirovilya** [comment]
yes. in command mode you can bind some buttons to other lamps/relays/groups

**Comment by kirovilya** [comment]
but you need wakeup switch for apply mode and bind

**Pull request merged**
