### PR TITLE
Add support for zigfred plus in-wall switch by Siglis AG

### PR DESCRIPTION
**Pull request by Atokulus**
This pull request will add support for zigfred plus in-wall switch by Siglis AG.
There are some issues yet, which need to be addressed first:

* ~~The bindings are not functional yet. We are currently investigating this issue.~~ (fixed)
* Some `to_zigbee` converters are in conflict, as they are applied to all endpoints (e.g. on/off/toggle commands for light endpoints are in conflict with up/down/stop commands for cover endpoints). Is there any mechanism, to apply certain converters only to specific endpoints?

### CODE REVIEW

**Comment by Koenkk** [comment]
> Is there any mechanism, to apply certain converters only to specific endpoints?

This is not possible, but making sure the `exposes` are correct this shouldn't be a problem.

**Comment by Atokulus** [comment]
> > Is there any mechanism, to apply certain converters only to specific endpoints?
> 
> This is not possible, but making sure the `exposes` are correct this shouldn't be a problem.

Thanks for the hint!

Best regards
Markus

**Comment by Atokulus** [comment]
Dear @Koenkk

The main issue can be found in https://github.com/Koenkk/zigbee-herdsman-converters/blob/d5791e769f48abf7863c0b1f2f70ad080b6479a9/converters/toZigbee.js#L841
As the key `state` is the same for window covers and lights, these converters are in conflict, resulting in an exception:

```
Zigbee2MQTT:error 2022-05-25 13:18:21: Publish 'set' 'state' to '0xf4ce3647c9121172' failed: 'Error: State value of message: '{"state":"OPEN"}' invalid, must be 'ON', 'OFF' or 'TOGGLE''
```

I will therefore add our own converter, if this is okay?

Have a nice day and best regards 😊👍
Markus

**Comment by Koenkk** [comment]
> For the future, it might be useful to directly expose the classes within exposes.js to override behaviour more easily.

This is already possible. e.g. `exposes.switch()`: https://github.com/Koenkk/zigbee-herdsman-converters/blob/546c0f6c2983b3ace62dc22b7d91e4c5ec8622dc/devices/legrand.js#L41

Can the custom classes be removed due to this?

**Comment by Atokulus** [comment]
> > For the future, it might be useful to directly expose the classes within exposes.js to override behaviour more easily.
> 
> This is already possible. e.g. `exposes.switch()`:
> 
> https://github.com/Koenkk/zigbee-herdsman-converters/blob/546c0f6c2983b3ace62dc22b7d91e4c5ec8622dc/devices/legrand.js#L41
> 
> Can the custom classes be removed due to this?

Yes. Adding the `withState()` method to the Cover class should do the trick.

**Comment by Koenkk** [comment]
> Yes. Adding the withState() method to the Cover class should do the trick.

Done!

Can you cleanup the `Zigfred*` exposes classes?

**Comment by Atokulus** [comment]
Dear @Koenkk

I just integrated `with_state()`. This pull request should now be ready for a merge.

Best regards and have a nice weekend :)
Markus

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
