### PR TITLE
Support for TuYa Temperature and humidity sensor TS0601 _TZE200_qyflbnbj

### PR DESCRIPTION
**Pull request by alxbator**
Support for  TuYa Temperature and humidity sensor TS0601 / _TZE200_qyflbnbj
Links:
[https://aliexpress.ru/item/1005004212078770.html](https://aliexpress.ru/item/1005004212078770.html)

### CODE REVIEW

**Comment by Koenkk** [comment]
Can this be merged with the already existing `TS0601_temperature_humidity_sensor`? 

Note to self; check https://github.com/Koenkk/zigbee2mqtt.io/pull/1467 after this.

**Comment by alxbator** [comment]
I think `TS0601_temperature_humidity_sensor` does not send datapoint 3 (enum battery level) and it would be wrong to expose battery_low, battery_level for that sensor

**Comment by alxbator** [comment]
Thank you for the advice!

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
