### PR TITLE
Changed Bitron AV2010/32 - Report Interval

### PR DESCRIPTION
**Pull request by Chrischi-**
Changed Bitron AV2010/32 - Report Interval to min. 900 and max. one hour

### CODE REVIEW

**Comment by Koenkk** [comment]
Why not use the default one? https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L151 (we can update to min report interval if you want).

**Comment by Chrischi-** [comment]
With default settings, new values appear every 30 seconds. This thermostat is a battery operated thermostat. Each saved interval also saves also battery.

**Comment by Koenkk** [comment]
But I mean, why not change the defaults? This will also be an improvement for other thermostats.

**Comment by Chrischi-** [comment]
That would be an option. But with constantly powered devices the frequency wouldn't matter and these people might want more updates. I think here we have to find a suitable middle way.

**Comment by Koenkk** [comment]
Ok, thanks!

**Pull request merged**
