### PR TITLE
Update zemismart.js

### PR DESCRIPTION
**Pull request by rossco555**
Appears recommended code in https://github.com/Koenkk/zigbee2mqtt/issues/11594 has not been merged.

### CODE REVIEW

**Comment by rossco555** [comment]
@Koenkk https://github.com/Koenkk/zigbee2mqtt/issues/11594

**Comment by rossco555** [comment]
@Koenkk https://github.com/Koenkk/zigbee2mqtt/issues/11594

**Comment by Koenkk** [comment]
Does it also work with:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: [
        'owvfni3\u0000', 'owvfni3', 'u1rkty3', 'aabybja', // Curtain motors
        'mcdj3aq', 'mcdj3aq\u0000', // Tubular motors
    ],
    fingerprint: [
        // Curtain motors:
        {modelID: 'TS0601', manufacturerName: '_TZE200_5zbp6j0u'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_nkoabg8w'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_xuzcvlku'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_4vobcgd3'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_nogaemzt'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_r0jdjrvi'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_pk0sfzvr'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_fdtjuw7u'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_zpzndjez'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_wmcdj3aq'},
        { modelID: 'TS0601', manufacturerName: '_TZE200_gubdgai2' },
        {modelID: 'TS0601', manufacturerName: '_TZE200_cowvfni3'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_rddyvrci'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_nueqqe6k'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_xaabybja'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_rmymn92d'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_3i3exuay'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_tvrvdj6o'},
        {modelID: 'zo2pocs\u0000', manufacturerName: '_TYST11_fzo2pocs'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_cf1sl3tj'},
        // Roller blinds:
        {modelID: 'TS0601', manufacturerName: '_TZE200_fctwhugx'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_zah67ekd'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_hsgrhjpf'},
        // Window pushers:
        {modelID: 'TS0601', manufacturerName: '_TZE200_g5wdnuow'},
        // Tubular motors:
        {modelID: 'TS0601', manufacturerName: '_TZE200_5sbebbzs'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_zuz7f94z'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_68nvbio9'},
    ],
    model: 'TS0601_cover',
    vendor: 'TuYa',
    description: 'Curtain motor/roller blind motor/window pusher/tubular motor',
    whiteLabel: [
        {vendor: 'Yushun', model: 'YS-MT750'},
        {vendor: 'Zemismart', model: 'ZM79E-DT'},
        {vendor: 'Binthen', model: 'BCM100D'},
        {vendor: 'Binthen', model: 'CV01A'},
        {vendor: 'Zemismart', model: 'M515EGB'},
        {vendor: 'TuYa', model: 'M515EGZT'},
        {vendor: 'TuYa', model: 'DT82LEMA-1.2N'},
        {vendor: 'TuYa', model: 'ZD82TN', description: 'Curtain motor'},
        {vendor: 'Moes', model: 'AM43-0.45/40-ES-EB'},
        {vendor: 'Larkkey', model: 'ZSTY-SM-1SRZG-EU'},
        {vendor: 'Zemismart', model: 'ZM85EL-2Z', description: 'Roman Rod I type curtains track'},
        {vendor: 'Zemismart', model: 'AM43', description: 'Roller blind motor'},
        {vendor: 'Zemismart', model: 'M2805EGBZTN', description: 'Tubular motor'},
        {vendor: 'Zemismart', model: 'BCM500DS-TYZ', description: 'Curtain motor'},
        {vendor: 'A-OK', model: 'AM25', description: 'Tubular motor'},
        {vendor: 'Alutech', model: 'AM/R-Sm', description: 'Tubular motor'},
    ],
    fromZigbee: [fz.tuya_cover, fz.ignore_basic_report],
    toZigbee: [tz.tuya_cover_control, tz.tuya_cover_options],
    exposes: [
        e.cover_position().setAccess('position', ea.STATE_SET),
        exposes.composite('options', 'options')
            .withFeature(exposes.numeric('motor_speed', ea.STATE_SET)
                .withValueMin(0)
                .withValueMax(255)
                .withDescription('Motor speed'))],
};

module.exports = definition;

```

**Comment by rossco555** [comment]
Sorry, I have not used or tested. I don't understand it but was just going
off the linked PR which looks to have gone stale and closed before it got
implemented.

**Comment by Koenkk** [comment]
To test:

- save this as file (from previous post) next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by rossco555** [comment]
> ```yaml
> external_converters:
>   - ext_converter.js
> ```

I've done this. I can see a difference in the UI but position doesn't actually do anything that I can see:

Screen Shot 2022-08-04 at 10 11 59 pm

In the screenshot, I have moved it to 37. The motor does not start. But to be fair, the unit doesn't have a reference for "37", or anything else for that matter, because I have not been able to set any open and close limits (being able to set these is my motivator for getting pulled into this PR... I don't have the required Zigbee bridge and the manufacturer can't advise how to use the RF remote to set limits, if that is at all possible even).

Settings is unchanged. It's here I was hoping to see 'set limit' type options perhaps.

Screen Shot 2022-08-04 at 10 17 49 pm

**Comment by Koenkk** [comment]
Thanks for checking, it appears that this device was already added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/3970/files, so it should work out-of-the-box in z2m 1.27.0

**Comment by rossco555** [comment]
When you say work, can you please confirm what functionality you mean? Is
there a way to support setting the upper and lower limits?

**Comment by Koenkk** [comment]
You can find the exposed functionalities here; https://www.zigbee2mqtt.io/devices/ZM-AM02_cover.html#exposes

**Comment by rossco555** [comment]
> You can find the exposed functionalities here; https://www.zigbee2mqtt.io/devices/ZM-AM02_cover.html#exposes

Well this doesn't work then. As you can see from my screenshot it only "exposes": `state`, `position`, 'motor_speed` and `link_quality`. All of which I think were existing.

To confirm, `Motor_working_mode`, `Percent_state`, `Mode`, `Motor_direction`, `Border`, etc do not appear on the Exposes panel/tab.

**Comment by Koenkk** [comment]
I see, thanks!

**Comment by odelma** [comment]
> being able to set these is my motivator for getting pulled into this

Did you ever get this working @rossco555? I am facing the same issue, however, even with latest zigbee2mqtt it does not appear to work to set border up / down. Is there perhaps some additional trick to get it to accept these? Also, when I sent this, I can see an error:
`No converter available for 'border' ("DOWN")`

**Comment by rossco555** [comment]
Unfortunately not. I ended up going for the Aqara equivalents which work
fine.

**Comment by odelma** [comment]
Not sure if I understand this correct, but for me the is recognized as TS0601_cover_1
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js#L2184
which do not expose the border property. 
image

However, _cover_3 exposes border properties:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js#L2291
image

Should these be added to cover_1 as well?

**Comment by odelma** [comment]
I should add that zigbee2mqtt recognizes this as manufacturer _TZE200_hsgrhjpf
https://github.com/Koenkk/zigbee-herdsman-converters/blob/4a4b156103a8790e199560bf72254315821ec6fd/devices/tuya.js#L2171

while in the docs it looks like it should be recognized as _TZE200_gubdgai2
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/zemismart.js#L172

So it is maybe the recognition that for some reason goes wrong and that is why it does not work as expected. I should also mention that I have previous V1 version of M515ZEGBZ which is recognized as _TZE200_nueqqe6k
https://github.com/Koenkk/zigbee-herdsman-converters/blob/4a4b156103a8790e199560bf72254315821ec6fd/devices/tuya.js#L2158

However, this model supports setting the limits via physical buttons so I am able to operate it without problems.

**Comment by odelma** [comment]
I did open an issue about this as I think something is a bit off with this device: https://github.com/Koenkk/zigbee-herdsman-converters/issues/5677

**Pull request merged**
