### PR TITLE
Add support for 5063430P7

### PR DESCRIPTION
**Pull request by SHxKM**
This adds support for the Fugato 4 spots

### CODE REVIEW

**Comment by Koenkk** [comment]
This one is already supported: https://github.com/Koenkk/zigbee-herdsman-converters/blob/0577e2c2e55d364a2c33bb7e1cfc61992e6a8ea6/devices/philips.js#L1386

**Comment by SHxKM** [comment]
@Koenkk it’s interesting however the way I’ve mapped it (with one string per bulb in the array) vs the way it was implemented. Any conventional wisdom on this difference?

**Comment by Koenkk** [comment]
@SHxKM adding the same zigbeeModel multiple times doesn't make any difference.

**Comment by SHxKM** [comment]
@Koenkk Interesting, so I’ve seen with some models we have to append `_n` to each one of the lights in a fixture, in fact this is what I tried to do first with one but it didn’t work. I wonder if I could have figured if I need or needn’t do that in any way? database.db and MQTT logs didn’t give much details. I just figured I will try to remove and just name each one of the devices the same (as the model name).

**Comment by Koenkk** [comment]
You have to add all `modelId` from the `database.db` to the `zigbeeModel` array.

**Pull request closed without merging**
