### PR TITLE
Update tuya.js

### PR DESCRIPTION
**Pull request by jrosier**
Version 2 of dinrail kWh meter (Tuya/Thomz/Hiking). Photo is the same.

### CODE REVIEW

**Review by jrosier — COMMENTED** [review]
New vesion of dinrail kWh meter Tuya/Thomz/Hiking

**Review by jrosier — COMMENTED** [review]
Changed genOnOff to genBasic

**Comment by Koenkk** [comment]
Can you provide a link to this device?

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
