### PR TITLE
Improve Lidl Parkside Watering Timer Support

### PR DESCRIPTION
**Pull request by Big4SMK**
This is adding the code developed in https://github.com/Koenkk/zigbee2mqtt/issues/7695 thereby adding a lot of functionality for the watering meter.

Code is created by @zinserjan, changed by @moritzbeck01 to change the frost guard switch to a sensor and a button. I confirmed the frost guard sensor and reset to work by freezing the device for a little bit so I think this code is ready to move from an external converter into mainline.

Let me know if I'm missing anything that still needs to be done.

### CODE REVIEW

**Comment by Big4SMK** [comment]
Sure thing, I hope to find some time within the next week or so.

**Comment by Big4SMK** [comment]
Still planning on building this out

**Comment by Big4SMK** [comment]
I've spent a couple of hours refactoring but couldn't get things to work. Maybe at some point someone with more knowledge of the tuya code cares enough to convert the current code to the new standard.

**Comment by d0np3p3** [comment]
Okay thanks for the try, shouldn't the ticket kept open, until it works?

**Comment by DenDeXTeR51** [comment]
Hi! When this code (additional fetaures) will be added to master branch? or maybe there is external converter so I can use it separatelly?

**Comment by Big4SMK** [comment]
The converter can be found in the zigbee2mqtt topic, more specifically here: https://github.com/Koenkk/zigbee2mqtt/issues/7695#issuecomment-1086721715

**Pull request closed without merging**
