### PR TITLE
add support for ROB_200-007-0

### PR DESCRIPTION
**Pull request by defcon84**
Added support for Robb Smarrt ROB_200-007-0

https://www.robbshop.nl/wandzender-8v-zigbee-robb-smarrt

### CODE REVIEW

**Comment by Koenkk** [comment]
I've updated the PR to use the default converters, can you check if everything is still ok?

Note to self after this merge https://github.com/Koenkk/zigbee2mqtt/pull/3125

**Comment by defcon84** [comment]
Yeah, it seems i was working on an older version (12.0.32) shipped with version 1.11.0. 

Anyway, I also added fz.command_stop_with_on_off to it.

Bedankt kerel. :)

**Comment by Koenkk** [comment]
Thanks, veel plezier er mee!

**Comment by Simanias** [comment]
Hmmm I'm getting the following message when I try to add this device:

`Zigbee2MQTT:warn  2021-01-06 09:00:50: Received message from unsupported device with Zigbee model 'ROB_200-007-0' and manufacturer name 'ROBB smarrt'`

I'm on the latest Zigbee2MQTT 1.17.0.1

**Comment by defcon84** [comment]
@Simanias https://github.com/Koenkk/zigbee-herdsman-converters/issues/2035 is it this?

**Pull request merged**
