### PR TITLE
add supported MOES TS0012 (ZS-EUB_2gang)

### PR DESCRIPTION
**Pull request by antonburesh**
add supported MOES TS0012 (ZS-EUB_2gang)

### CODE REVIEW

**Comment by antonburesh** [comment]
please add my code

**Comment by antonburesh** [comment]
Please help me, where my error ? TEST Failed(

**Comment by Koenkk** [comment]
I expect that this device already works out-of-the box (detected as a TuYa TS0012)

**Comment by antonburesh** [comment]
it works out of the box, but there is no support
```
 e.switch().withEndpoint('left').setAccess('state', ea.STATE_SET),
        e.switch().withEndpoint('right').setAccess('state', ea.STATE_SET),
        exposes.presets.power_on_behavior(),
        exposes.presets.switch_type_2(),
        exposes.enum('backlight_mode', ea.ALL, ['LOW', 'MEDIUM', 'HIGH'])
            .withDescription('Indicator light status: LOW: Off | MEDIUM: On| HIGH: Inverted'),
```

**Comment by Koenkk** [comment]
Can you add this to the existing `TS0012` definition?

**Comment by antonburesh** [comment]
There is a brand tuya and this is already moes

**Comment by Koenkk** [comment]
I know, but this creates a lot of code duplication.

**Comment by antonburesh** [comment]
Are you sure TuYa switch will support the same functions as Moes?

**Comment by Koenkk** [comment]
Probably yes, Moes = TuYa

**Pull request closed without merging**
