### PR TITLE
Legrand - more support

### PR DESCRIPTION
**Pull request by cemonneau**
WIP / Do not merge
- moved security for pairing on global "onEvent"
- add micromodule support : see https://github.com/Koenkk/zigbee2mqtt/issues/2399#issuecomment-572719099
- fix Bticino parameter : see https://github.com/Koenkk/zigbee2mqtt/issues/2626#issuecomment-570691689
- add connected power outleg support : on/off, power measurement

### CODE REVIEW

**Comment by cemonneau** [comment]
Require https://github.com/Koenkk/zigbee-herdsman/pull/124

**Comment by Koenkk** [comment]
Is this still WIP or can it be merged?

**Comment by cemonneau** [comment]
Still WIP. Working on other devices (plug, ...). Will tag you once done (1 week max)

**Comment by cemonneau** [comment]
@Koenkk I think it's good. 
I tested the join procedure with a non supported device and it didn't left. Added new support & corrected some device compatiblity.
Ready to be merged

**Comment by Koenkk** [comment]
Awesome, thanks again!

**Comment by ellavas** [comment]
@cemonneau : I'm trying to connect a shutter (Legrand Dooxie) but the device leave the network just after the configuration. Do you have any idea ?

**Pull request merged**
