### PR TITLE
Add support for Immax NEO SMART plug.

### PR DESCRIPTION
**Pull request by hanzz**

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by JiriFurda** [comment]
@hanzz Have you tested the power measurement? I have found several reviews stating that it does not have this functionality (e. g. on [Alza.cz](https://www.alza.cz/immax-neo-smart-zasuvka-d5569071.htm#recenze)). It is even not listed on the [manufacturer's page](https://www.immax.cz/immax-neo-smart-zasuvka-16-a-3680w-zigbee-3-0.html)

**Comment by hanzz** [comment]
Yes, it works for me. I have toaster connected to this plug and every morning when we start preparing toasts for breakfast, it sends the power consumption to openhab2 which detects we are preparing breakfast and says google calendar appointments for next 3 days.

I've also used this to measure power consumption of some machines we have at home (like oven, washing machine) to find out how much money we cost on them. So definitely it works for me as expected with this "driver".

I also bought it on alza.cz on the very same page as you sent.

**Comment by hanzz** [comment]
Hm, but to be honest, I bought one for 799 Kč which is much higher than current price. Maybe they have removed that functionality from this product recently....

**Comment by daha76** [comment]
I have 2 plugs bought in Slovakia and both report actual power in Watts, but not Energy consumptions in Watts/h. Energy consumption measurement has to be setup manually in HA. But the plug does not support entities like AC Voltage and AC Current or at least it looks like that, but for some reason those entities are sent from zigbee2mqtt to HA.

**Pull request merged**
