### PR TITLE
All buttons events for Aqara Opple Switch

### PR DESCRIPTION
**Pull request by kirovilya**
https://github.com/Koenkk/zigbee-herdsman/issues/132

### CODE REVIEW

**Comment by kirovilya** [comment]
because there is no standard for naming event attributes, it is done by analogy with WXKG02LM_click_multistate

**Comment by Koenkk** [comment]
The preferred naming is `action` (because it's more generic), but devices which previously used this won't be changed as this will be a big breaking change.

**Comment by kirovilya** [comment]
ok. i will change it back

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
