### PR TITLE
Correct SPZB0001 system_mode mapping

### PR DESCRIPTION
**Pull request by sjorge**
New mapping as per #788
boost -> heat
off -> off
comfort (manual calls it this) -> auto

### CODE REVIEW

**Comment by sjorge** [comment]
@sti0 @allofmex here is the PR to map the system_mode... I only give a quick test but I am remote from the valve... I will do some more testing this week once I am next to it.

@Koenkk please hold of a bit on merging until I have done more testing

**Comment by sti0** [comment]
Thanks. Will test it in the next days,too.

**Comment by sjorge** [comment]
The easy way to do this is to install from this branch
```
npm install https://github.com/sjorge/zigbee-herdsman-converters#spzb0001_sysmode
```

Or you can just apply the same diff locally.

**Comment by sjorge** [comment]
Looks like the fromZigbee is not working :( I don't imediatly see why.

**Comment by sjorge** [comment]
Ok the problem seems to be that, `system_mode` is both two ways :s
- thermostat_att_report
- eurotronic_thermostat

So doing a get for system_mode will read it via thermostat_att_report, if I do a get for eurotronic_system_mode it will update both eurotronic_system_mode and system_mode via using eurotronic_thermostat...

Not really sure how to proceed here.

**Comment by sti0** [comment]
I look into this when I'm at home later today.

**Comment by sjorge** [comment]
OK I think I figured it out...

The device reports a propert system_mode that seems to be heat even when boost is enabled!
The eurotronic_system_mode is a device specific attribute...

bit 1: normal -> now mapped to `auto` (while hvacThermostat reports `heat`)
bit 2: boot -> now mapped to `heat` (not sure what hvacThermostat repots here)
bit 4: window is open -> now mapped to `off` (not sure what hvacThermostat repots here)

I think overriding system_mode for there is wrong. I think it would be better to report them seperate as seperate values and leave system_mode as is reported by hvacThermostat.

If we decode all of the bit fields, we can remove eurotronic_system_node and publish
eurotronic_host_mirror_display: 0|1
eurotronic_host_boot: 0|1
eurotronic_host_window_open: 0|1
eurotronic_host_child_protect: 0|1

**Comment by sti0** [comment]
Overriding system_mode for Eurotronic devices is nesessary for Home Assistant because HA uses the system mode property for handling state. As you said if we use the normal system mode it would be always heat. In my opinion a false implementation in the device firmware.
This topic is discussed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/682

**Comment by sjorge** [comment]
*sigh* I'll close this for now and take another jab at it this weekend, I have some ideas but they are way more annoying to implement.

**Pull request closed without merging**
