### PR TITLE
Fix FromZigbee accordingly to: #8005

### PR DESCRIPTION
**Pull request by Dukobpa3**
Fix FromZigbee accordingly to: https://github.com/Koenkk/zigbee-herdsman-converters/pull/8005

### CODE REVIEW

**Comment by Drafteed** [comment]
This and #8005 broke the `Max Temperature Limit` setting (it always 39 and can't be changed) and removed the `Min Temperature Limit` (defrost) setting for my Moes thermostat ([it look like this](https://moeshouse.com/cdn/shop/products/wifi-central-air-conditioner-thermostat-temperature-controller-2-pipe-4-pipe-3-speed-fan-coil-unit-work-with-alexa-google-home-482301.jpg?v=1615966377)).

This change should be reverted.

**Comment by Drafteed** [comment]
Moreover I can't change `Deadzone temperature` now.

**Comment by Dukobpa3** [comment]
@Drafteed 
Which `manufacturerName` is your device? I'll check

**Comment by Dukobpa3** [comment]
@Drafteed 
`Min Temperature Limit` – returned by this one.

`Max Temperature limit` and `Deadzone` I'll check

**Comment by Drafteed** [comment]
Zigbee Model: TS0601
Zigbee Manufacturer: _TZE204_aoclfnxz
Model: BHT-002/BHT-006

**Comment by Dukobpa3** [comment]
@Drafteed 
Looks like piece of tuya shit... Two different devices with different zigbee endpoints but with the same signature...

This is my own with the same signature and I've made this PRs to fix it. I've checked real communication through tuya developer apps and made changes accordingly to it...

image
image

@Koenkk 
Any ideas how to deal with it?

**Comment by Drafteed** [comment]
First of all, I propose to revert #8005 and #8063, cause old revision is more popular than new one.

**Pull request merged**
