### PR TITLE
fix: Fix pairing of Legrand devices failing

### PR DESCRIPTION
**Pull request by Koenkk**
Requires https://github.com/Koenkk/zigbee-herdsman/pull/982

Fixes https://github.com/Koenkk/zigbee-herdsman/issues/979

### CODE REVIEW

**Comment by sjorge** [comment]
tsc is not willing to build this

**Comment by sjorge** [comment]
With the way it is done now, I guess we could also move this to a modernExtend we attach to all legrand/biticino/netamo devices ?

**Comment by Koenkk** [comment]
>  I guess we could also move this to a modernExtend we attach to all legrand/biticino/netamo devices ?


We cannot, since this happen before interview finishes (until interview finishes, it is not linked against a definition).

Does the fix work?

**Comment by sjorge** [comment]
Ah good point! We need it during interviewing too!

Yes, this code as is works.

**Comment by Koenkk** [comment]
Great, will fix the tests and merge this.

**Pull request merged**
