### PR TITLE
Update min/max ct range for ZL1000100-CCT-US-V1A02

### PR DESCRIPTION
**Pull request by sjorge**
This should address  Koenkk/zigbee2mqtt#6123

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by sjorge** [comment]
Maybe we should put out a call for database entries somehow to fill in the missing data?

**Comment by Koenkk** [comment]
We can use the `configure()` to set this. Example: https://github.com/Koenkk/zigbee-herdsman-converters/blob/b3db136d9ad4213e8f2a2217480e85d290ec219d/devices.js#L1677

**Comment by sjorge** [comment]
We already read and save those attributes. We just don't use the stored entries in the exposes info.

**Comment by Koenkk** [comment]
Ah I see, the expose part is indeed a static thing and cannot be updated from the actual runtime device. Currently this does not fit well with how the whole expose thing has been setup.

**Comment by sjorge** [comment]
Maybe we can start by making sure newly added devices at least have it filled in.

**Comment by Koenkk** [comment]
Yes agree, I will check this.

**Pull request merged**
