### PR TITLE
Add GL-SD-301P

### PR DESCRIPTION
**Pull request by Aogu181**
| ------------- | ------------------------------------------   |
| Model         | GL-SD-301P                                           |
| Vendor        | Gledopto			                              |
| Description | Zigbee triac AC dimmer                         |
| ------------- | ------------------------------------------  |

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by Aogu181** [comment]
> thanks!
**When will it be updated?**
image

**Comment by Koenkk** [comment]
With the next release (1 November)

**Comment by smitjohan** [comment]
@Koenkk the GL-SD-301P is now recognized in my zigbee2mqtt, but I had hoped that the physical status would also be recognized (pressing the physical button). Are there any specific settings required or will this be included in a future update?

**Comment by Koenkk** [comment]
Fixed, after updating make sure to re-configure the device via the frontend.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by smitjohan** [comment]
> Fixed, after updating make sure to re-configure the device via the frontend.
> 
> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

I just loaded the dev branch and gave gledopto a reconfiguration. Works absolutely perfectly now, super thanks for that!

**Pull request merged**
