### PR TITLE
Adding SP-EUC01 temperature

### PR DESCRIPTION
**Pull request by Vodochnik**
it works from GenDeviceTempCfg cluster.
See https://github.com/Koenkk/zigbee2mqtt/issues/6861

### CODE REVIEW

**Comment by Koenkk** [comment]
@islepnev can you check if it works now?

**Comment by Vodochnik** [comment]
wait pls)

**Comment by Vodochnik** [comment]
Okay, after some investigations... this plug does not support reporting for device temperature.
Temperature is reported only once on plugging in the wall outlet, but not afterward.
So we need polling for it.
Big thanks to @kirovilya for pointing me in right direction how to accomplish it.
withValueMin(-60) is for Russia :P

**Comment by Vodochnik** [comment]
@islepnev please check if it works for you now) Polling time is set to 60 sec.

**Comment by islepnev** [comment]
@Vodochnik, it works perfectly!

History plot for my sockets:
Screenshot from 2021-09-09 21-14-42

**Comment by Vodochnik** [comment]
@Koenkk done)

**Comment by Koenkk** [comment]
Could you increase the poll duration? I'm not a fan of polling since it increases the stress on the network and I feel polling every 30 mins-1 hours is enough

**Comment by Vodochnik** [comment]
> 
> 
> Could you increase the poll duration? I'm not a fan of polling since it increases the stress on the network and I feel polling every 30 mins-1 hours is enough

Updated polling interval to 30 min, added explaining description.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
