### PR TITLE
Added support for Tradfri PAR38 bulb

### PR DESCRIPTION
**Pull request by danieledwardgeorgehitchcock**
Resolves Koenkk/zigbee2mqtt#14969

OP could not fetch color temperature range from device

### CODE REVIEW

**Comment by Koenkk** [comment]
Waiting for the correct model number: https://github.com/Koenkk/zigbee2mqtt/issues/14969#issuecomment-1314102692

**Comment by Koenkk** [comment]
Thanks!

**Comment by danieledwardgeorgehitchcock** [comment]
Where did you find the model number out of curiosity? I googled it but couldn't find anything..

**Comment by apadua** [comment]
I took a photo of the bulb. Found it there.

IMG_2827

**Pull request merged**
