### PR TITLE
Add "CCT Light" model to paulmann devices

### PR DESCRIPTION
**Pull request by MarBra**
I've got a new paulmann lamp and it is reported as "CCT Light" model.

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by MarBra** [comment]
> Can you provide the data/database.db entry of this device?

Sure.
```
{
   "id":40,
   "type":"Router",
   "ieeeAddr":"0x00158d0005092b86",
   "nwkAddr":12792,
   "manufId":4137,
   "manufName":"Paulmann lamp",
   "powerSource":"Mains (single phase)",
   "modelId":"CCT Light",
   "epList":[
      1,
      242
   ],
   "endpoints":{
      "1":{
         "profId":260,
         "epId":1,
         "devId":268,
         "inClusterList":[
            0,
            4,
            3,
            6,
            8,
            5,
            768,
            65535,
            65535,
            4096,
            4111
         ],
         "outClusterList":[
            25,
            4111
         ],
         "clusters":{
            "genBasic":{
               "attributes":{
                  "modelId":"CCT Light",
                  "manufacturerName":"Paulmann lamp",
                  "powerSource":1,
                  "zclVersion":2,
                  "appVersion":1,
                  "stackVersion":1,
                  "hwVersion":21,
                  "dateCode":"20200710",
                  "swBuildId":"00.00.01"
               }
            },
            "lightingColorCtrl":{
               "attributes":{
                  "colorCapabilities":16,
                  "colorTempPhysicalMin":153,
                  "colorTempPhysicalMax":454
               }
            },
            "genOnOff":{
               "attributes":{
                  "onOff":1
               }
            }
         },
         "binds":[
            
         ],
         "configuredReportings":[
            
         ],
         "meta":{
            
         }
      },
      "242":{
         "profId":41440,
         "epId":242,
         "devId":102,
         "inClusterList":[
            33
         ],
         "outClusterList":[
            33
         ],
         "clusters":{
            
         },
         "binds":[
            
         ],
         "configuredReportings":[
            
         ],
         "meta":{
            
         }
      }
   },
   "appVersion":1,
   "stackVersion":1,
   "hwVersion":21,
   "dateCode":"20200710",
   "swBuildId":"00.00.01",
   "zclVersion":2,
   "interviewCompleted":true,
   "meta":{
      "configured":2
   },
   "lastSeen":1656235056077,
   "defaultSendRequestWhen":"immediate"
}
```

**Comment by Koenkk** [comment]
Thanks!

**Comment by raveit65** [comment]
@MarBra 
please take a look at https://github.com/Koenkk/zigbee-herdsman-converters/pull/11186#issuecomment-3724749004
Can you please recheck the data/database.db entry your device?
Your device has the same modelId and manufName (and database entry) than another paulmann bulb.

**Comment by raveit65** [comment]
@MarBra 
And is the product really 50064 (led spot light?) or 50394 (led filament bulb?)

**Comment by MarBra** [comment]
> @MarBra And is the product really 50064 (led spot light?) or 50394 (led filament bulb?)

Sorry I don't have the product anymore. It has been a bulb.

**Pull request merged**
