### PR TITLE
Fixes the 4257050-RZHAC handler when falling back.

### PR DESCRIPTION
**Pull request by zikeji**
Resolves https://github.com/Koenkk/zigbee2mqtt/issues/4378

### CODE REVIEW

**Comment by Koenkk** [comment]
@nanobra1n would you be able to test out these changes? (see https://github.com/Koenkk/zigbee2mqtt/issues/4378#issuecomment-693371874)

**Comment by nanobra1n** [comment]
No bueno :)

Tried it out and with the same LED bulb as in https://github.com/Koenkk/zigbee2mqtt/issues/3575#issuecomment-636472808 . I configured the outlet and I now get:
`Zigbee2MQTT:info  2020-09-18 13:17:43: MQTT publish: topic 'zigbee2mqtt/Outlet', payload '{"current":9.8,"last_seen":"2020-09-18T13:17:43-04:00","linkquality":63,"power":113,"state":"ON","voltage":119}'`

I would expect ~93mA and a power of ~11 W.

The `database.db` entry for this device is:

`{"id":5,"type":"Router","ieeeAddr":"0x000d6f0004482310","nwkAddr":59726,"manufId":49887,"manufName":"CentraLite","powerSource":"Mains (single phase)","modelId":"4257050-RZHAC","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,2820,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"4257050-RZHAC","manufacturerName":"CentraLite","powerSource":1,"zclVersion":1,"stackVersion":0,"hwVersion":3,"dateCode":"����������������"}},"haElectricalMeasurement":{"attributes":{"activePower":2,"rmsCurrent":4,"rmsVoltage":118,"acCurrentMultiplier":1,"acCurrentDivisor":10,"powerMultiplier":1,"powerDivisor":10}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca5cb1c","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca5cb1c","endpointID":1}],"meta":{}}},"stackVersion":0,"hwVersion":3,"dateCode":"����������������","zclVersion":1,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1600450074874}`

**Comment by zikeji** [comment]
Here's my device.db entry:
```
{"id":2,"type":"Router","ieeeAddr":"0x000d6f000b057a5e","nwkAddr":11508,"manufId":49887,"manufName":"CentraLite","powerSource":"Mains (single phase)","modelId":"4257050-RZHAC","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,2820,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"4257050-RZHAC","manufacturerName":"CentraLite","powerSource":1,"zclVersion":1,"appVersion":21,"stackVersion":0,"hwVersion":3,"dateCode":"����������������"}},"haElectricalMeasurement":{"attributes":{"acCurrentMultiplier":1,"acCurrentDivisor":1000,"powerMultiplier":1,"powerDivisor":10,"rmsVoltage":119,"activePower":2140,"rmsCurrent":1849,"acPowerMultiplier":1,"acPowerDivisor":10}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff05eded","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00212effff05eded","endpointID":1}],"meta":{}}},"appVersion":21,"stackVersion":0,"hwVersion":3,"dateCode":"����������������","zclVersion":1,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1600448384845}
```

The only difference I see on mine is my appVersion is 21 and your entry doesn't list an appversion.

Looking at the Zigbee docs shows the ApplicationVersion attribute description:
> The ApplicationVersion attribute is 8 bits in length and specifies the version number of the application software contained in the device. The usage of this attribute is manufacturer dependent.

I notice in Samsung's (public version of the device handler)[https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/smartpower-outlet.src/smartpower-outlet.groovy] they aren't doing any special handling and use a divisor of 10 as well, so I'm not sure what's going on here. I'd prefer not to have to override devices.js to get the correct reading off my specific outlet, can the appVersion be leveraged in the configuration step or is that an unreliable attribute to use?

**Comment by Koenkk** [comment]
@zikeji using the appVersion is fine, you can access it with `endpoint.getDevice().applicationVersion`

**Comment by zikeji** [comment]
@Koenkk Does this look like an appropriate solution? You mentioned the endpoint.getDevice().applicationVersion but I saw the device.applicationVersion used in another device handler. I tested this change and (as expected) my 4257050-RZHAC configures correctly.

**Comment by Koenkk** [comment]
That's even better! @nanobra1n can you test again?

**Comment by zikeji** [comment]
Actually based on @nanobra1n 's earlier test I expect it'll still output wrong. The only divisor that got changed in my original commit was the acCurrentDivisor changed to 1000. But I also fixed the typo on acPowerMultiplier and acPowerDivisor that was making them not have any affect - considering nanobra1n's power was coming in with the wrong reading it seems like the current will read correctly but the power will read wrong. Not really sure what to do about that though.

**Pull request closed without merging**
