### PR TITLE
Added support for ID Lock 150

### PR DESCRIPTION
**Pull request by TheStigh**

### CODE REVIEW

**Comment by TheStigh** [comment]
@Koenkk hehe, you had changed the structure of devices since last time :)

**Comment by Koenkk** [comment]
:smile: I did some small changes, can you check if everything is still OK?

**Comment by TheStigh** [comment]
> 
> 
> 😄 I did some small changes...

SMALL ?  😄😄😄

I'll reset and test your "small" changes...

**Comment by Koenkk** [comment]
Only some refactoring (cosmetics) and some code reduction. No functional changes :smile:

**Comment by TheStigh** [comment]
Ok, tested - all is OK except `doorState `

`doorState` show up in log with `0` (or `1`)  depending if door are open or closed:
```
Zigbee2MQTT:debug 28-04-2021 20:42:29: Received Zigbee message from '0x680ae2fffe6bb522', type 'readResponse', cluster 'closuresDoorLock', data '{"doorState":0,"lockState":2,"soundVolume":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  28-04-2021 20:42:29: MQTT publish: topic 'zigbee2mqtt/0x680ae2fffe6bb522', payload '{"battery":null,"linkquality":60,"lock_mode":null,"lock_state":"unlocked","master_pin_mode":null,"relock_enabled":null,"rfid_enable":null,"sound_volume":"low_volume","state":"UNLOCK"}'
```
... but it does not show up as an attribute. This means I can't monitor if the door are open or shut.
Old code worked, your change broke `doorState`.

You replaced 
```
    if (msg.data.hasOwnProperty('doorState')) {
        const lookup = ['open', 'closed', 'error jammed', 'error forced open', 'error unspecified', 'undefined'];
        result.door_state = lookup[msg.data['doorState']];
    }
```
...with

```
    if (msg.data.hasOwnProperty('doorState')) {
        const lookup = {
            0: 'open', 1: 'closed', 2: 'error_jammed', 3: 'error_forced_open', 4: 'error_unspecified', 0xff: 'undefined'};
        result.door_state = lookup[msg.data['doorState']];
    }
```

**Review by TheStigh — COMMENTED** [review]
Tested OK.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
