### PR TITLE
Add support for SIN-4-FP-21 from NodOn

### PR DESCRIPTION
**Pull request by AlexisPolegato**
Update nodon.ts file to add support for SIN-4-FP-21

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by yoan-m** [comment]
Hi @AlexisPolegato do you know how to change the heating mode (ECO, CONFORT, etc) ?

**Comment by AlexisPolegato** [comment]
Hi @yoan-m , working on it. In the meantime, you can do ON for COMFORT and OFF for HG. But the product is not on the market yet.

**Comment by yoan-m** [comment]
Perfect, thanks you, I'm using the SIN-4-FP-21_EQU from Adeo witch is already on the market

**Comment by skwat75** [comment]
On my side, SIN-4-FP-21_EQU is not reconized with 15.106.0

**Comment by yoan-m** [comment]
Yes, you have to edit the file zigbee-herdsman-converters/devices/adeo.js
and add this
`      {
        zigbeeModel: ['SIN-4-FP-21_EQU'],
        model: 'SIN-4-FP-21_EQU',
        vendor: 'ADEO',
        description: 'Equation pilot wire heating module',
        ota: ota.zigbeeOTA,
        fromZigbee: [fromZigbee_1.default.on_off, fromZigbee_1.default.metering],
        toZigbee: [toZigbee_1.default.on_off],
        exposes: [e.switch(), e.power(), e.energy()],
        configure: async (device, coordinatorEndpoint, logger) => {
            const ep = device.getEndpoint(1);
            await reporting.bind(ep, coordinatorEndpoint, ['genBasic', 'genIdentify', 'genOnOff', 'seMetering']);
            await reporting.onOff(ep, { min: 1, max: 3600, change: 0 });
            await reporting.readMeteringMultiplierDivisor(ep);
            await reporting.instantaneousDemand(ep);
            await reporting.currentSummDelivered(ep);
        },
    },`

**Comment by skwat75** [comment]
Thanks yoan-m, thats already done, but the device is still not reconized. 
Did I forget something?

**Comment by Koenkk** [comment]
@yoan-m could you make a PR to add support for this device out-of-the-box?

**Comment by pipiche38** [comment]
+1

**Comment by multinet33** [comment]
Hello, I get an CRC32 error when i try to update my nodon firmware SIN 4 FP 21 from 773 to 778

IMG_9769

**Pull request merged**
