### PR TITLE
add 2ch box relay from envilar

### PR DESCRIPTION
**Pull request by tbowmo**
Support for new 2 channel relay from Envilar

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks! Could you also provide a link to this device?

**Comment by tbowmo** [comment]
@Koenkk do you mean a product link? I have only seen it on danish websites so far..

**Comment by Koenkk** [comment]
yes (I need a picture for the docs)

**Comment by tbowmo** [comment]
I already added a "pseudo" image to the documentation (they all look the same).
Anyways, found a link with images here https://www.plusled.dk/zigbee-relae-3-0-2-udgange-philips-hue-kompatibel.html

**Pull request merged**
