### PR TITLE
add U86Z223A10-ZJU01(GD)

### PR DESCRIPTION
**Pull request by 65698888**
add U86Z223A10-ZJU01(GD)

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you provide a picture of this device?

**Comment by 65698888** [comment]
> 你能提供这个设备的图片吗？



> U86Z223A10-ZJU01（GD）

2021083002275245691_BIG

**Comment by 65698888** [comment]
> 你能提供这个设备的图片吗？
屏幕截图 2023-07-16 144900

**Comment by 65698888** [comment]
> 你能提供这个设备的图片吗？
I am a novice, temporarily testing can be used.
Adding USB separate control is being tested, but is not familiar with this.
endpoint 2  genOnOff 
Can you help me.
very thankful.

LOG:
2023-07-16 14:20:50Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
2023-07-16 14:20:50Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 2 with groupID 0
2023-07-16 14:20:50Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsVoltage":2270}' from endpoint 1 with groupID 0
2023-07-16 14:20:50Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":0}' from endpoint 1 with groupID 0
2023-07-16 14:20:51Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
2023-07-16 14:20:51Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 2 with groupID 0
2023-07-16 14:20:51Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":0}' from endpoint 1 with groupID 0
2023-07-16 14:20:51Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,6]}' from endpoint 1 with groupID 0
2023-07-16 14:20:55Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsVoltage":2270}' from endpoint 1 with groupID 0
2023-07-16 14:20:55Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":50}' from endpoint 1 with groupID 0
2023-07-16 14:20:55Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":70}' from endpoint 1 with groupID 0
2023-07-16 14:20:55Received Zigbee message from '0x000d6f0016bd62df', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,6]}' from endpoint 1 with groupID 0

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
