### PR TITLE
ICTC-G-1. Reducing the number of messages from the dimmer and some im…

### PR DESCRIPTION
**Pull request by kirovilya**
…provements

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by frontend89** [comment]
@kirovilya could you copy that solution for E1744?
https://www.zigbee2mqtt.io/devices/E1744.html

**Comment by ginkage** [comment]
Looks like this is still an issue in 1.8.0: for every event from ICTC-G-1 I get 8 different MQTT messages... This basically makes this dimmer unusable with Home Assistant.

**Comment by ginkage** [comment]
It seems to me that there's some sort of a race condition: values read from "s." are stale when being processed by the next event handler. This causes the timers to not get discarded, and when I try to compare the last action and brightness with current ones, I see a bunch of events using the same old value few times in a row, as if all of those handlers were being launched on different threads, and read the value from store at the same time, then going on to process them concurrently.
Is there a good way to guard against that?

**Pull request merged**
