### PR TITLE
Cleanup Gen 2 E-Wand. Report position and state information correctly.

### PR DESCRIPTION
**Pull request by Leah-Anderson**
As this cover doesn't report a position attribute another fromZigbee converter was added to set the position of the cover to the same value of the tilt position. This ensures things such as auto discovery for Home Assistant can accurately reflect the cover status in the UI. Additionally added support for reporting state from the on_off status so that it properly reflects as opened or closed. 

This is related to: Koenkk/zigbee2mqtt#7648

### CODE REVIEW

**Comment by Leah-Anderson** [comment]
This isn't quite ready to be merged in. I thought I had it working but after checking further it doesn't seem to be. Will try to update again shortly.

**Comment by Koenkk** [comment]
Let me know once it is ready

**Comment by Leah-Anderson** [comment]
Will do :) It might take a few days as I'm seeing some weird behavior. I think it's an issue with the Zigbee stick I have but I'm still investigating further be sure. At worst I have another Zigbee stick arriving next week which might help in debugging.

**Comment by Leah-Anderson** [comment]
@Koenkk One of the things I keep seeing in the logs is:

```
No converter available for 'CP180335E-01' with cluster '64528' and type 'raw' and data '{"data":[13,99,18,98,128,182,213,224,128,254,2,0,0,0,59,32,65,0,0,202,65,0,255,0,0,161,0],"type":"Buffer"}'
```
Do you have any recommendations on how to track that down? Or at least what cluster that is?

**database.db entry**

```
{
  "id": 12,
  "type": "EndDevice",
  "ieeeAddr": "0x84fd27fffe80e0d5",
  "nwkAddr": 56718,
  "manufId": 4707,
  "manufName": "Current Products Corp",
  "powerSource": "Battery",
  "modelId": "E-Wand",
  "epList": [
    1
  ],
  "endpoints": {
    "1": {
      "profId": 260,
      "epId": 1,
      "devId": 514,
      "inClusterList": [
        0,
        1,
        3,
        4,
        5,
        6,
        8,
        32,
        258,
        2821,
        64528
      ],
      "outClusterList": [
        3,
        25
      ],
      "clusters": {
        "genBasic": {
          "attributes": {
            "modelId": "E-Wand",
            "manufacturerName": "Current Products Corp",
            "powerSource": 3,
            "zclVersion": 3,
            "dateCode": ""
          }
        },
        "genPowerCfg": {
          "attributes": {
            "batteryPercentageRemaining": 182
          }
        },
        "closuresWindowCovering": {
          "attributes": {
            "currentPositionTiltPercentage": 81
          }
        }
      },
      "binds": [
        {
          "cluster": 258,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0014d94976",
          "endpointID": 1
        },
        {
          "cluster": 6,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0014d94976",
          "endpointID": 1
        },
        {
          "cluster": 1,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0014d94976",
          "endpointID": 1
        }
      ],
      "configuredReportings": [
        {
          "cluster": 258,
          "attrId": 9,
          "minRepIntval": 1,
          "maxRepIntval": 62000,
          "repChange": 1
        },
        {
          "cluster": 6,
          "attrId": 0,
          "minRepIntval": 0,
          "maxRepIntval": 3600,
          "repChange": 0
        },
        {
          "cluster": 1,
          "attrId": 33,
          "minRepIntval": 3600,
          "maxRepIntval": 62000,
          "repChange": 0
        }
      ],
      "meta": {}
    }
  },
  "dateCode": "",
  "zclVersion": 3,
  "interviewCompleted": true,
  "meta": {
    "configured": -754511626
  },
  "lastSeen": 1623118965616
}
```

**Comment by Leah-Anderson** [comment]
@Koenkk  Thanks! When I get a bit more time I might reach out to them. For now though this is ready to be merged as this fixes the issue I was seeing with Home Assistant not showing the state of the cover correctly. Let me know if I missed anything.

**Comment by Koenkk** [comment]
> This ensures things such as auto discovery for Home Assistant can accurately reflect the cover status in the UI. 

What exactly is not reflected correctly when there is no position? (I'm wondering if this HA issue should be fixed here)

**Comment by Leah-Anderson** [comment]
So if you only expose the tilt position the state color of cover in HA won't change color if it's open or closed (all the other controls work as expected as far as I can tell). It seems as though HA will only change the cover state color/icon based on the position attribute. 

image

**Comment by Koenkk** [comment]
Then this looks like a HA issue (solving it here in z2m feels like a hack). Please open an issue here: https://github.com/home-assistant/core/issues

**Comment by Leah-Anderson** [comment]
It does look like the state is determine solely by position. I'll go ahead and submit an issue with HA to see if that behavior can be modified.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/cover.py#L313

**Comment by Leah-Anderson** [comment]
@Koenkk There's been an at least partial improvement on the HA side which will allow the open/close tilt buttons disable correctly based on the state. There's still an issue where the overall device state isn't reflecting in the UI correctly. 

Assuming the overall state issue gets resolved based on the HA issue it seems that configuring a command_topic and state_topic isn't correct behavior for a tilt only device. I'm not really sure what the best approach would be so wanted to get your thoughts. 

1. Is there a way from within the device configuration to specify what topics to configure? My main idea was just some way to prevent the state_topic and command_topic from being added to the HA MQTT discovery. I looked through some of the existing converters and didn't see anything so just wanted to be sure. 
2. I could submit a documentation change for the device to disable HA discovery and indicate that users will have to manually configure each device in HA. This seems like the cumbersome approach. 
3.  Move forward with the approach in this PR to have this device report it's position from the tilt_position. I do agree that's still a bit of a hack but it would allow the normal discovery to work as expected for new users and minimize the amount of changes for what seems like a fringe issue. 

I'm open to alternatives I'm just trying to find a path forward :)

**Comment by Koenkk** [comment]
> Assuming the overall state issue gets resolved based on the HA issue it seems that configuring a command_topic and state_topic isn't correct behavior for a tilt only device. 

@emontnemery what would be the correct way to discover a cover that only supports `tilt`? From the z2m perspective:
- State is discovered on e.g. `zigbee2mqtt/my_cover`, payload `{"tilt": 60}`
- Controlling can be done through e.g. `zigbee2mqtt/my_cover/set` , payload `{"tilt": 60}` OR `zigbee2mqtt/my_cover/set/tilt` , payload `60`

**Comment by Leah-Anderson** [comment]
@Koenkk Do you have any recommendations on where to go with this next? I'm happy to keep working on this but I'm not sure where to try to look next and as it stands it's in a relatively broken state. 

Additionally I've noticed in it's current form when exposing the devices to Google Home you can't open or close the devices to a percentage. You can only fully open or fully close them.

Again I completely understand the initial take that it seems like a bit of a hack but this seems like the most straightforward and functional approach.

**Comment by Koenkk** [comment]
Ping @emontnemery

**Comment by emontnemery** [comment]
There was a discussion about it here: https://github.com/home-assistant/core/issues/51793

**Comment by Koenkk** [comment]
@emontnemery thanks, looking at https://github.com/home-assistant/core/issues/51793 this can be solved from z2m.

@Leah-Anderson what happens when sending to `zigbee2mqtt/MY_COVER_NAME/set` payload `{"state": "open"}` and `{"state": "close"}`? (does the cover respond?)

**Comment by Leah-Anderson** [comment]
@Koenkk Yeah if send those payloads then they open/close as expected. Let me know if you want me to try anything else.

**Comment by Koenkk** [comment]
@emontnemery from https://github.com/home-assistant/core/issues/51793 I understand the the `command_topic` and `state_topic` (`OPEN`/`CLOSE`) should be removed for tilt only covers, however to me this does not make sense. A tilt only can also be `OPEN` or `CLOSE`.

**Comment by emontnemery** [comment]
@Koenkk A Home Assistant cover can be in states `open` or `closed`, the tilt is auxiliary functionality and not represented in its state.

I think the suggestion here https://github.com/home-assistant/core/issues/51793#issuecomment-872884608 is good, but the frontend could be tweaked a bit to improve the frontend: https://github.com/home-assistant/core/issues/51793#issuecomment-873272098

**Comment by Koenkk** [comment]
@emontnemery thanks for your input again! I've changed the logic now to only discovery the `command_topic` and `state_topic` when: `!hasTilt || (hasTilt && hasPosition)`.

@Leah-Anderson can you confirm the issue is fixed in the latest dev branch?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Leah-Anderson** [comment]
@Koenkk I haven't had a chance to really look into why exactly but I can't get the controls to work in HA any longer. The controls do still work in z2m. Also I can't remember if I ever noticed it before but the state in z2m doesn't update correctly either. The open/close/stop buttons work they just don't reflect it's actual value.

**Pull request closed without merging**
