### PR TITLE
Change window_open to window_detection for Bosch Thermostats.

### PR DESCRIPTION
**Pull request by danielpetrovic**
Discussed here: https://github.com/Koenkk/zigbee2mqtt/pull/21285

### CODE REVIEW

**Comment by danielpetrovic** [comment]
I am testing this, but now I get:

No converter available for 'window_open' ("ON")
No converter available for 'window_open' ("OFF")

And it still doesn't show up in HA. Can anyone help to change the window_open to windows_detection properly?

**Comment by GatoPharaoh** [comment]
sorry, didn't see you already opened a pull request - looks good to me works on my end

> No converter available for 'window_open' ("ON")
> No converter available for 'window_open' ("OFF")

had this on the first start - my BTH-RAs needed to reconfigure once. just press reconfigure in the frontend or /get the `window_detection` topic. triggering the window_detection switch via z2m frontend made it also appear in home assistant. maybe it's just cached on your end.
grafik

**Comment by danielpetrovic** [comment]
How can you keep the changes persistent? First time I reboot Zigbee2MQTT after I change the Bosch.js file it stays and I can test the changes. But then when I reboot again it reverts to the one in the repository…

I still had the No Converter Available error after reconfiguring so wanted to reboot to test and then it reverted to previous version…

I am using the HA Add-On.

**Comment by GatoPharaoh** [comment]
as I use HA-core, I don't really know how addons work. I just set up a test environment following Koenkks [advice](https://github.com/Koenkk/zigbee2mqtt/discussions/11930)

**Comment by danielpetrovic** [comment]
I cannot do a setup like the example mentions but did find a better way to edit the file inside the add-on through Advanced SSH & Web Terminal Add-on.

I was able to test it now and it seems to work ok here as well with the BTH-RM. So this was all the change that was needed to fix the switch. So it can be merged.

**Comment by Koenkk** [comment]
@danielpetrovic you forgot to update https://github.com/Koenkk/zigbee-herdsman-converters/blob/aeea2fc1b056c61c22e0bcd876e383825c883ccb/src/devices/bosch.ts#L1059

**Comment by danielpetrovic** [comment]
> @danielpetrovic you forgot to update
> 
> https://github.com/Koenkk/zigbee-herdsman-converters/blob/aeea2fc1b056c61c22e0bcd876e383825c883ccb/src/devices/bosch.ts#L1059

It is there when I check in 9dfb5a4fe42e8de51e0c1d30ee4d48347f29acc0 is this not the latest commit?

**Comment by Koenkk** [comment]
You are right, somehow missed it, thanks!

**Comment by salopette** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/21208#issuecomment-1973879602

**Pull request merged**
