### PR TITLE
Zemismart ZM-CSW032-D Curtain/roller blind switch get calculate position

### PR DESCRIPTION
**Pull request by ullrik**
If you add 2 properties in your configuration.yaml, you can get the real position (because on the old solution, we could only recover 3 values by zemismarth : [100, 50, 0]).

### CODE REVIEW

**Comment by ullrik** [comment]
If you want, I can update for add the modification that I had made on the existing code to take into account the action "50", but ignore the action 50 which intervenes automatic 60 sec after the action up or down?
I had done this before leaving on the solution that I propose to you. And it works even without the new elements that I added in the configuration.yaml

**Comment by Koenkk** [comment]
> And it works even without the new elements that I added in the configuration.yaml

Can you explain this? It is still needed to set `time_close` and `time_open` right?

**Comment by ullrik** [comment]
Knowing that for my evolution, it is necessary to add two elements in the "Configuration.yaml", I also planned that it could work without (as currently on the branch master).
And for time_close and time_open, here is my configuration in configuration,yaml ; 
`  '0xec1bbdfffe946690':
    friendly_name: MyCover
    time_close: 27
    time_open: 28`
For set time_close and time_open, you must close completely by recording the time (start, end) and the same thing to open.

I hope my English is not too bad :). 
Tell me if you still have questions?

**Comment by Koenkk** [comment]
Thanks, before merging this, can you check on last thing for me?

First disable your solution (don't put `time_open`/`time_close` in `configuration.yaml`).

Now change the definition of the device in `devices.js` to

```js
{
    zigbeeModel: ['TS0302'],
    model: 'ZM-CSW032-D',
    vendor: 'Zemismart',
    description: 'Curtain/roller blind switch',
    supports: 'open, close, stop',
    fromZigbee: [fz.ignore_basic_report, fz.ZMCSW032D_cover_position_tilt],
    toZigbee: [tz.cover_state, tz.cover_position_tilt],
    meta: {configureKey: 1, multiEndpoint: true},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['closuresWindowCovering']);
        // Configure reporing of currentPositionLiftPercentage always fails.
        // https://github.com/Koenkk/zigbee2mqtt/issues/3216
    },
    onEvent: async (type, data, device) => {
        console.log('received something');
        if (data.type === 'attributeReport' && data.cluster === 'closuresWindowCovering') {
            const result = await device.getEndpoint(1).read('closuresWindowCovering', ['currentPositionLiftPercentage']);
            console.log('TEST ' + result);
        }
    },
},
```

Can you provide the debug logging when controlling the blinds now?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by ullrik** [comment]
You will find below the logs after taking into account your elements :

I did the following cutscene:
1) up to the top
2) down and stop after 5 to 10 seconds

`...
juil. 07 22:32:34 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:32:34: Received MQTT message on 'zigbee2mqtt/InterVolet_PorteFenetre_Cuisine/set' with data 'OPEN'
juil. 07 22:32:34 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:32:34: Publishing 'set' 'state' to 'InterVolet_PorteFenetre_Cuisine'
juil. 07 22:32:34 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:32:34: Received Zigbee message from 'InterVolet_PorteFenetre_Cuisine', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":100}' from endpoint 1 with groupID 0
juil. 07 22:32:34 raspberrypi npm[18142]: zigbee2mqtt:info  2020-07-07 22:32:34: MQTT publish: topic 'zigbee2mqtt/InterVolet_PorteFenetre_Cuisine', payload '{"position":100,"linkquality":76}'
juil. 07 22:32:34 raspberrypi npm[18142]: received something
juil. 07 22:32:34 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:32:34: Received Zigbee message from 'InterVolet_PorteFenetre_Cuisine', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":255}' from endpoint 1 with groupID 0
juil. 07 22:32:34 raspberrypi npm[18142]: zigbee2mqtt:info  2020-07-07 22:32:34: MQTT publish: topic 'zigbee2mqtt/InterVolet_PorteFenetre_Cuisine', payload '{"position":255,"linkquality":76}'
juil. 07 22:32:34 raspberrypi npm[18142]: received something
juil. 07 22:32:34 raspberrypi npm[18142]: TEST [object Object]
juil. 07 22:32:49 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:32:49: Received Zigbee message from 'InterVolet_Chambre_Principale', type 'raw', cluster 'genBasic', data '{"type":"Buffer","data":[9,103,10,1,0,32,66,226,255,32,19]}' from endpoint 1 with groupID 0
juil. 07 22:32:49 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:32:49: No converter available for 'ZM-CSW032-D' with cluster 'genBasic' and type 'raw' and data '{"type":"Buffer","data":[9,103,10,1,0,32,66,226,255,32,19]}'
juil. 07 22:32:49 raspberrypi npm[18142]: received something
juil. 07 22:32:59 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:32:59: Received Zigbee message from 'InterVolet_BaieVitree_Salon', type 'raw', cluster 'genBasic', data '{"type":"Buffer","data":[9,17,10,1,0,32,66,226,255,32,19]}' from endpoint 1 with groupID 0
juil. 07 22:32:59 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:32:59: No converter available for 'ZM-CSW032-D' with cluster 'genBasic' and type 'raw' and data '{"type":"Buffer","data":[9,17,10,1,0,32,66,226,255,32,19]}'
juil. 07 22:32:59 raspberrypi npm[18142]: received something
juil. 07 22:33:13 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:33:13: Received Zigbee message from 'InterVolet_Fenetre_Bureau', type 'raw', cluster 'genBasic', data '{"type":"Buffer","data":[9,14,10,1,0,32,66,226,255,32,19]}' from endpoint 1 with groupID 0
juil. 07 22:33:13 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:33:13: No converter available for 'ZM-CSW032-D' with cluster 'genBasic' and type 'raw' and data '{"type":"Buffer","data":[9,14,10,1,0,32,66,226,255,32,19]}'
juil. 07 22:33:13 raspberrypi npm[18142]: received something
juil. 07 22:33:16 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:33:16: Received MQTT message on 'zigbee2mqtt/InterVolet_PorteFenetre_Cuisine/set' with data 'CLOSE'
juil. 07 22:33:16 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:33:16: Publishing 'set' 'state' to 'InterVolet_PorteFenetre_Cuisine'
juil. 07 22:33:16 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:33:16: Received Zigbee message from 'InterVolet_PorteFenetre_Cuisine', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID 0
juil. 07 22:33:16 raspberrypi npm[18142]: zigbee2mqtt:info  2020-07-07 22:33:16: MQTT publish: topic 'zigbee2mqtt/InterVolet_PorteFenetre_Cuisine', payload '{"position":0,"linkquality":78}'
juil. 07 22:33:16 raspberrypi npm[18142]: received something
juil. 07 22:33:16 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:33:16: Received Zigbee message from 'InterVolet_PorteFenetre_Cuisine', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":255}' from endpoint 1 with groupID 0
juil. 07 22:33:16 raspberrypi npm[18142]: zigbee2mqtt:info  2020-07-07 22:33:16: MQTT publish: topic 'zigbee2mqtt/InterVolet_PorteFenetre_Cuisine', payload '{"position":255,"linkquality":84}'
juil. 07 22:33:16 raspberrypi npm[18142]: received something
juil. 07 22:33:16 raspberrypi npm[18142]: TEST [object Object]
juil. 07 22:33:22 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:33:22: Received MQTT message on 'zigbee2mqtt/InterVolet_PorteFenetre_Cuisine/set' with data 'STOP'
juil. 07 22:33:22 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:33:22: Publishing 'set' 'state' to 'InterVolet_PorteFenetre_Cuisine'
juil. 07 22:33:23 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:33:23: Received Zigbee message from 'InterVolet_PorteFenetre_Cuisine', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":50}' from endpoint 1 with groupID 0
juil. 07 22:33:23 raspberrypi npm[18142]: received something
juil. 07 22:33:23 raspberrypi npm[18142]: zigbee2mqtt:debug 2020-07-07 22:33:23: Received Zigbee message from 'InterVolet_PorteFenetre_Cuisine', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":255}' from endpoint 1 with groupID 0
juil. 07 22:33:23 raspberrypi npm[18142]: zigbee2mqtt:info  2020-07-07 22:33:23: MQTT publish: topic 'zigbee2mqtt/InterVolet_PorteFenetre_Cuisine', payload '{"position":255,"linkquality":76}'
juil. 07 22:33:23 raspberrypi npm[18142]: received something
juil. 07 22:33:23 raspberrypi npm[18142]: TEST [object Object]
`

Is-it ok for you ? 
Unless I'm mistaken, I shouldn't keep the modification "onEvent" ?

**Comment by Koenkk** [comment]
Looks that it doesn't solve it, I will merge this, thanks!

**Pull request merged**
