### PR TITLE
Added support for BlitzWolf sensors BW-IS2 and BW-IS3

### PR DESCRIPTION
**Pull request by AlwinZwets**
I've added contact support for [BlitzWolf BW-IS2](https://m.blitzwolf.com/ZigBee-Contact-Sensor-p-439.html) and occupancy support for [BlitzWolf BW-IS3](https://m.blitzwolf.com/Rechargeable-ZigBee-PIR-Motion-Sensor-p-442.html).

I reused the occupancy_with_timeout converter in the converter for the BW-IS3.

### CODE REVIEW

**Comment by Koenkk** [comment]
Bedankt!

**Comment by Koenkk** [comment]
Could you please share the `database.db` entry for this device? I need it because a conflict with the same `zigbeeModel` regarding https://github.com/Koenkk/zigbee-herdsman-converters/pull/1026

**Comment by AlwinZwets** [comment]
For the RH3001 (BW-IS2) that is
```{"id":13,"type":"EndDevice","ieeeAddr":"0xec1bbdfffe6f2c46","nwkAddr":7796,"manufId":4098,"manufName":"TUYATEC-trhrga6p","powerSource":"Battery","modelId":"RH3001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,10,1,1280],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0011","65506":21,"modelId":"RH3001","manufacturerName":"TUYATEC-trhrga6p","powerSource":3,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":22}}},"binds":[]}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1579717392629}```

**Comment by blakadder** [comment]
BW-IS3 motion sensor is constantly showing occupied in 60 second intervals

**Comment by GijsvanDulmen** [comment]
So setting the occupancy_timeout lower as 60s should not work?

**Pull request merged**
