### PR TITLE
Track direction for Xiaomi Aqara curtain motor ZNCLDJ11LM

### PR DESCRIPTION
**Pull request by yozik04**
Depends on https://github.com/Koenkk/zigbee2mqtt/pull/1671

Solves: https://github.com/Koenkk/zigbee2mqtt/issues/1639

### CODE REVIEW

**Comment by Koenkk** [comment]
While I have nothing against this, I would first like to see if somebody could help us with: https://github.com/Koenkk/zigbee2mqtt/issues/1639#issuecomment-502443362. If nobody helps I will merge this.

**Comment by yozik04** [comment]
I agree.

**Comment by yozik04** [comment]
Can we send a byte string to the device now with zigbee-herdsman?

**Comment by Koenkk** [comment]
I think we still need https://github.com/Koenkk/zigbee2mqtt/issues/1639#issuecomment-516761761

**Pull request closed without merging**
