### PR TITLE
Add device innr SP 220

### PR DESCRIPTION
**Pull request by gnu-belette**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by FutureCow** [comment]
Hello gnu-belette,

do you know if the new SP 220 also support power measurement, like the "old" Innr SP 120?

**Comment by gnu-belette** [comment]
Hello @FutureCow,

I don't think it is a "new" model superior to the Innr SP 120, but rather a less expensive model and above all less polluting at Zigbee level.

To answer your question, the Innr SP 220 model does not supports power measurement.

**Comment by Kosta-Github** [comment]
@gnu-belette 

- is the plug working for you in a stable manner?
- the plug is also a zigbee-router and can extend the zigbee-network, correct?

right now, I am using the [OSRAM Smart+ plug](https://www.zigbee2mqtt.io/devices/AB3257001NJ.html) which doesn't seem to be very stable and I am thinking about switching to the `Innr` ones... my main use-case for them is extending the zigbee network for my motion/occupancy sensors...

**Comment by FutureCow** [comment]
I'm using de SP220 (along the SP120) for 3 months now. They are working nice and stable, not a single problem. They also function as router(I see around 15 arrows from and to the plugs in the zigbee map).

**Pull request merged**
