### PR TITLE
[LIXEE] Add EDF zen WE plus Lundi/Vendredi & fix missing indexes expose

### PR DESCRIPTION
**Pull request by Mikado8231**
Fix: expose 
EASF04 : HP Week-end
EASF05 : HC Mercredi
EASF06 : HP Mercredi

Add: Edf zen plus WE Lundi & Vendredi by copy of Mercredi

@vk496 ok for you ?

Thanks.

### CODE REVIEW

**Comment by Mikado8231** [comment]
#5194

**Comment by Koenkk** [comment]
@vk496 could you review this?

**Comment by Mikado8231** [comment]
@Koenkk any chance to be reviewed and available in the next release?

**Comment by Mikado8231** [comment]
@Koenkk @vk496 thanks you for your jobs 👍

**Comment by Koenkk** [comment]
Thanks!

**Comment by SilentT-FR** [comment]
I think we can regroup all Standard - Sem WE Lundi/Mercredi/Vendredi all in one because its same index/filter  ?

EASF04 : HP Week-end
EASF05 : HC Lundi/Mercredi/Vendredi
EASF06 : HP Lundi/Mercredi/Vendredi

**Pull request merged**
