### PR TITLE
Zigbee Environment Sensor

### PR DESCRIPTION
**Pull request by iharyadi**
Hello,  

My name is Iman.  I am a hobbyist/maker.  I made an Environment Sensor for my my own use. 

I like to make the sensor compatible with Zigbee2mqtt.   I have followed the document to add a new device for Zigbee2mqtt.  This is one of the modification to get my module working with Zigbee2mqtt.  I also have another change in zigbee-herdman.

As bit of background,  I am not too well verse in Node JS.  But,  I am a long time developer mostly working in C/C++ code.  I am familiar with Zigbee.  To the best of my knowledge,  I have tested my changes.  It work per my expectation.

Here is the module that I make.

IMG_20200526_120059

The sensor is Zigbee sensor that measure Pressure, Humidity and Temperature of a room using Bosch BME280. It also have ambient light sensor based on TEMT6000.

I think what is unique about the sensor is that the sensor is configured as Zigbee Router. The Zigbee radio comes with dedicated power amplifier. As a router, the sensor require 5V DC power from a phone charger.

It also come with a LIPO/LI-on battery backup. This will help with your Zigbee mesh as you build your Zigbee infrastructure.

I also design the sensor for DIYer so that it can be expanded. There is one digital input, digital output and analog input. It also has Serial expansion so that It can interact with Arduino to handle complex sensors.

I use HA to show the sensor values

Untitled

If you need my module to test the code,  I will be more than happy to send you one for testing free of charge.

I recently start manufacturing the sensor and sell it on Ebay.   I think it will me valuable to  Zigbee2mqtt user to be able to use the sensor by getting the modification directly from your repository.

Thanks
Iman

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you provide a link to a document explaining how to create such device? This is a requirement when integrating DiY devices.

**Comment by Koenkk** [comment]
Note to self, after this check: https://github.com/Koenkk/zigbee-herdsman/pull/191

**Comment by iharyadi** [comment]
I follow this link to get my device running.

https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

I have to read the code from other device to use as example.

**Comment by iharyadi** [comment]
Hello,  I have not heard from you.  I am just wondering whether you are looking for different type of document.  Please let me know.

The basic Environment Sensor (Temperature, Humidity, Pressure and Light)  follow Zigbee standard clusters.  The sensor also expose one Binary Input, Binary Output and Analog Input for expansion.

I am selling the sensor in ebay.  I do not expect the user to build the sensor themselves.  Here is the sensor in the ebay.  I apologize about the DIY term.  It is not meant that use will have to build the sensor by hand.  You can get the sensor pre-built.  The DIY aspect is just for expanding the sensor.   However,  I expect that the basic  Temperature, Humidity, Pressure and Light reading is the primary use of the sensor.

https://www.ebay.com/itm/Zigbee-Temperature-Humidity-Environment-Sensor-for-SmartThings-and-Hubitat/164220197906

Thank you.  Let me know if you need more information.

**Comment by Koenkk** [comment]
Thanks for explaining further, as you are selling the device I think its fine to add. If in the future you make more devices feel free to add them.

**Comment by iharyadi** [comment]
Thank you so much.  

Is there a way that we can communicate in private?  Please reach out to me at iharyadi at gmail dot com.   I would like to send you free sample of the sensor so that you can keep it as document as well.   Please do not feel pressure to do so.  I am good good either way.  I think it is prudent on my side that you are properly introduced to this sensor.   

Thank you 
Iman

**Comment by Koenkk** [comment]
@iharyadi we can talk on telegram (@koenkk)

**Pull request merged**
