### PR TITLE
Support Hue Go with Bluetooth LCT026 (7602031P7)

### PR DESCRIPTION
**Pull request by mkaay**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Conphilpott** [comment]
Just wondering how you managed to get this device to pair/reset, I managed once before I added the device converter as soon as the light came out of the box, but now it seems impossible to reset it!
I also have the original hue go and that was a pain to pair too, maybe its something i'm doing or not doing?

**Comment by mkaay** [comment]
It looks like the pairing/reset instructions got a little bit messed up in the documentation.
You can find it under power on behavior https://www.zigbee2mqtt.io/devices/7146060PH.html#power-on-behavior

> For the 7146060PH (Philips Hue Go), the power cord has to be connected, after the blinking light (INSTEAD of step four in the video), press and keep holding the button on the bottom until the device is paired (+- 60 seconds).

I just held the botton until i saw the interveiw successful message in the zigbee2mqtt logs.

**Comment by Conphilpott** [comment]
Thanks, that seemed to put it into bluetooth pairing mode for me, I ended up just using touchlink in the end with no issues.

**Pull request merged**
