### PR TITLE
_TZ3000_ji4araar added on TS0011_switch_module

### PR DESCRIPTION
**Pull request by eraycetinay**
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3561/files/f4739d4f1db42f8de58611b89c0c0c3339984735
Explained here.

### CODE REVIEW

**Comment by Koenkk** [comment]
`_TZ3000_ji4araar` has already been added here, it cannot appear in two definitions: https://github.com/Koenkk/zigbee-herdsman-converters/blob/f599b6074709d92eee9cd396fbe112614b98fd1f/devices/tuya.js#L1276

**Comment by eraycetinay** [comment]
@Koenkk 

> `_TZ3000_ji4araar` has already been added here, it cannot appear in two definitions:
> 
> https://github.com/Koenkk/zigbee-herdsman-converters/blob/f599b6074709d92eee9cd396fbe112614b98fd1f/devices/tuya.js#L1276

I was added a review on this [commit](https://github.com/Koenkk/zigbee-herdsman-converters/pull/3561/files/f4739d4f1db42f8de58611b89c0c0c3339984735)

In the past this manufacturername was added as 'TS0011_switch_module'  
But on that commit it changed and not i cant use my switch module.

review -----------------------------------------
Probably because of this change i cant use my switch module :(
i have a TS0011_switch_module which have the _TZ3000_ji4araar name as manufacturerName
bought it from here

now its seen as light switch and i cant use 'power_on_behavior, switch_type' attributes which is quite important.

@Koenkk
I don't know if there can be two different modules with the same manufacturerName.
master...eraycetinay:patch-5

**Comment by Koenkk** [comment]
@DavidFFerreira  since you committed https://github.com/Koenkk/zigbee-herdsman-converters/pull/3561 , could you check this?

**Comment by eraycetinay** [comment]
> @DavidFFerreira since you committed #3561 , could you check this?

i sent a commit which restores the code before @DavidFFerreira  edit.

**Comment by Arno500** [comment]
Hello, any update on this?
Mine is simply called "TS0011" with manufacturer "_TZ3000_ji4araar" and it does work but I have the same issue as @eraycetinay and I can't use the switch settings. I think it was an error on David's side.
@DavidFFerreira any idea?
Thanks to all!

**Comment by eraycetinay** [comment]
> Hello, any update on this? Mine is simply called "TS0011" with manufacturer "_TZ3000_ji4araar" and it does work but I have the same issue as @eraycetinay and I can't use the switch settings. I think it was an error on David's side. @DavidFFerreira any idea? Thanks to all!

I have a commit which fixes the problem but not accepted yet.
So, until they have a decision to accept the pull request, i fixed it by using the external converters feature. 
You can use it if you like. 

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'TS0011', manufacturerName: '_TZ3000_ji4araar'}],
    model: 'TS0011_switch_module',
    vendor: 'TuYa',
    description: '1 gang switch module - (without neutral)',
    toZigbee: extend.switch().toZigbee.concat([tz.moes_power_on_behavior, tz.tuya_switch_type]),
    fromZigbee: extend.switch().fromZigbee.concat([fz.moes_power_on_behavior, fz.tuya_switch_type]),
    exposes: [
        e.switch(),
        exposes.presets.power_on_behavior(),
        exposes.presets.switch_type_2(),
    ],
    whiteLabel: [{vendor: 'AVATTO', model: '1gang N-ZLWSM01'}, {vendor: 'SMATRUL', model: 'TMZ02L-16A-W'}],
    // The configure method below is needed to make the device reports on/off state changes
    // when the device is controlled manually through the button on it.
    configure: async (device, coordinatorEndpoint, logger) => {
        await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
        device.powerSource = 'Mains (single phase)';
        device.save();
    },
};

module.exports = definition;`

**Comment by Koenkk** [comment]
Since @DavidFFerreira did not respond and another issue was opened about this (https://github.com/Koenkk/zigbee2mqtt/issues/10952) I will merge this.

Thanks @eraycetinay

**Pull request merged**
