### PR TITLE
Fixing Maximum temperature bug. Adding running state based on output_status

### PR DESCRIPTION
**Pull request by nagydavid**
the earlier converter restricted the maximum allowed temperature to 30 Celsius, it threw an error time-to-time, when the regulator send out an update where the maximum allowed temperature is 35. 
Also added a running_state attribute, based on the output status, so it can be visible on the thermostat card, if the actuator is active or not.

### CODE REVIEW

**Comment by nagydavid** [comment]
@robertalexa @Koenkk 
Hi I am trying to create a PR, but I have some error which does not give mi any insight.

**Comment by nagydavid** [comment]
@robertalexa it is possible, since the solution was suggested by you :)

**Comment by nagydavid** [comment]
@robertalexa  do you know how to force the external converter to be used until it will appear in edge

**Comment by robertalexa** [comment]
> @robertalexa do you know how to force the external converter to be used until it will appear in edge?

Give your device a unique id in your external converter. Then edit your database file and change the id of your device to the new id. Restart z2m. This way your paired device will not match the supported device, but it will match the external converter.

Hope this helps

**Comment by nagydavid** [comment]
Thanx, but what do you mean by "database file" . devices.yaml? or ....

**Comment by nagydavid** [comment]
@robertalexa  @Koenkk 
I tested in Home Assistant as well, and it works

Screenshot 2022-07-15 at 15 57 06

**Pull request merged**
