### PR TITLE
fix: Neo Solar Alarm NAS-AB06B2

### PR DESCRIPTION
**Pull request by Burki24**
Thanks to @fortiko, @tm1981 and all others, who build and worked on implementation. I transfered the external converter to the internal neo.ts file.

This belongs to: https://github.com/Koenkk/zigbee2mqtt/discussions/17325

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you use `tuyaDatapoints` instead of creating custom `fz`/`tz` converters? Example: https://github.com/Koenkk/zigbee-herdsman-converters/blob/4784bf1d86f8c33d17ccaf4fc6b6b5603f04d465/src/devices/tuya.ts#L628

**Comment by Burki24** [comment]
> Can you use `tuyaDatapoints` instead of creating custom `fz`/`tz` converters? Example:
> 
> https://github.com/Koenkk/zigbee-herdsman-converters/blob/4784bf1d86f8c33d17ccaf4fc6b6b5603f04d465/src/devices/tuya.ts#L628

Hopefully, it's done.

**Comment by Koenkk** [comment]
Great, thanks!

**Comment by Burki24** [comment]
> Great, thanks!

@Koenkk 

Sorry, but your changes to “charge_state” and “battpercentage” unfortunately don’t work. I had already tested this beforehand and therefore didn't use the standards.
image

**Comment by averter** [comment]
It's not working for me (displaying as unsupported) as per the image below. I'm using
Zigbee2MQTT version
    [1.40.1](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.40.1) commit: [403d3c09](https://github.com/Koenkk/zigbee2mqtt/commit/403d3c09)

Coordinator type
    zStack3x0

Coordinator revision
    20230507

Coordinator IEEE Address
    0x00124b002c3a6118

Frontend version
    0.7.4

zigbee-herdsman-converters version
    20.12.1

zigbee-herdsman version
    0.57.3

image

Also, can you please rename this device so that it contains the word "siren"? Otherwise I feel that many will not find it when searching in the list of supported devices (I certainly didn't). Thanks.

**Comment by averter** [comment]
Possibly a duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/19077? However, that one was solved with Z2M v1.33.0, which is below my current version...

**Pull request merged**
