### PR TITLE
Adds support for Ledvance OTA updates

### LINKED ISSUE #1000: Osram/Ledvance OTA updates support
I've been taking a look at the Osram/Ledvance OTA updates and how we can implement this and it does seem quite trivial as they provide a fully open and very well documented API!

I've started a branch in my fork here: https://github.com/PedroLamas/zigbee-herdsman-converters/tree/pedrolamas/osram-ota

Problem is that I currently don't have any Osram device, so I'm asking anyone interested in helping to try my branch (quite trivial if you are using [Docker](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#docker)) and report back the debug values from a [zigbee2mqtt/bridge/ota_update/check](https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/ota_updates.md#check-if-an-update-is-available) call.

Thanks in advance!

### PR DESCRIPTION
**Pull request by PedroLamas**
This PR adds Osram/Ledvance OTA update support!

The list of all currently devices with firmware images available is [here](https://github.com/Koenkk/zigbee-herdsman-converters/issues/1000#issuecomment-589396003), and we can easily see that only two manufacturer codes are supported, 4489 and 4364.

However, I have no way of knowing which entries on the devices.js are supported by the API, so I've marked all devices with "OSRAM" as vendor as supported.

It was either that or just identifying the devices by their zigbeeModel names but if we go that way, we will have to manually check the API to see when devices have been added (new or old).

### CODE REVIEW

**Comment by Koenkk** [comment]
Awesome!!

One question: I will update the docs of all devices which have the ota property (automatically). But as you indicated not all devices will support it and this should be written there. How can a user find out wether his device supports it?

**Comment by PedroLamas** [comment]
Not ideal, but if a user knows his manufacturer and product codes (and converts those to hex), he can manually check here: https://update.ledvance.com/firmware-overview

I haven't tried this but we might be able to generate a direct link with that and put in the docs?

**Comment by Koenkk** [comment]
Would it be possible to throw an exception when no firmwaee is available? (`No firmware available for this device`)?

**Comment by PedroLamas** [comment]
That's how it works right now and the reason why I'm sending version 0.0 0 on check instead of the current one on the device: that way I always get firmware metadata IF it actually exists, but the assert will throw an exception if it does not!

**Comment by Koenkk** [comment]
Sorry missed that.

Big thumbs up again! 🎖

**Pull request merged**
