### PR TITLE
Added support for Connecte smart socket 4500990

### PR DESCRIPTION
**Pull request by stokket**
Tested on unit

### CODE REVIEW

**Comment by Koenkk** [comment]
This device should already be supported out of the box and be recognized as a `TS0121_plug`: https://github.com/Koenkk/zigbee-herdsman-converters/blob/bcdb6b3c593cac61741cbe9f5254606de73f67f7/devices/tuya.js#L2542

**Comment by stokket** [comment]
> This device should already be supported out of the box and be recognized as a `TS0121_plug`:
> 
> https://github.com/Koenkk/zigbee-herdsman-converters/blob/bcdb6b3c593cac61741cbe9f5254606de73f67f7/devices/tuya.js#L2542

Does not work as intended.
Added these settings to not flood zigbee network with information.

            await reporting.rmsVoltage(endpoint, {min: 10, max: 3600, change: 2});
            await reporting.rmsCurrent(endpoint, {min: 10, max: 3600, change: 0});
            await reporting.activePower(endpoint, {min: 10, max: 3600, change: 0});
            await reporting.currentSummDelivered(endpoint, {min: 10, max: 3600, change: 0});

**Comment by Koenkk** [comment]
You can update the existing definition with these changes (then all other `TS0121_plug` will also benefit from this)

**Comment by stokket** [comment]
Sure, will do that!

**Pull request closed without merging**
