### PR TITLE
Add Support TS0601 _TZE284_aao3yzhs soil sensor

### PR DESCRIPTION
**Pull request by Barneybaer84**

### CODE REVIEW

**Comment by Koenkk** [comment]
Seems to be exactly the same as `TS0601_soil`, could you add it to that definition?

**Comment by Barneybaer84** [comment]
TS0601_soil temperature have no divideBy10 but this sensor.

**Comment by Koenkk** [comment]
I see, thanks!

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `TS0601_soil_3.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by jjvelar** [comment]
Hi,
First of all, thanks for your work.
Any idea when this will be released into production?
Thanks and best regards

**Comment by Koenkk** [comment]
Today!

**Comment by jjvelar** [comment]
> Today!

Excellent timing! :-)

Quick question: I have been able to create a TS0601_soil_3.js file with the sensor configuration and include it in Z2M configuration.yaml as an external converter. Should I remove the js file and the external converter entry before updating Home Assistant's Z2M add-on, or it is not necessary to remove it at all?  

Thanks again.

**Comment by jjvelar** [comment]
> Quick question: I have been able to create a TS0601_soil_3.js file with the sensor configuration and include it in Z2M configuration.yaml as an external converter. Should I remove the js file and the external converter entry before updating Home Assistant's Z2M add-on, or it is not necessary to remove it at all?

@Koenkk, I saw the update is available in Home Assistant. Thanks again.

I created a TS0601_soil_3.js file with the sensor configuration and included it in Z2M configuration.yaml as an external converter.

Should I remove the js file and the external converter entry before updating Home Assistant's Z2M add-on, or it is not necessary to remove it at all?

**Comment by Koenkk** [comment]
You can remove the external converter after updating to z2m 1.40.0

**Comment by jjvelar** [comment]
> You can remove the external converter after updating to z2m 1.40.0

Works like a charm. Thanks again.

**Pull request merged**
