### PR TITLE
Update tuya.js

### PR DESCRIPTION
**Pull request by slashbv**
Add new device TS0001 switch module with power monitoring #14707.

### CODE REVIEW

**Comment by Koenkk** [comment]
Looks that this can be merged with https://github.com/Koenkk/zigbee-herdsman-converters/blob/b9b707a52bd650e2d36166abd7a844809669b574/devices/tuya.js#L1772

**Comment by slashbv** [comment]
that seems to be a switch not a module, not sure switch type is relevant for it.

**Comment by Koenkk** [comment]
Only description (cosmetic) is different, so please merge.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
