### PR TITLE
Add Sherzen Golden Security Technology curtains GM46

### PR DESCRIPTION
**Pull request by LoSk-p**
I have several devices from the vendor Sherzen Golden Security Technology that have connected without any issues, except for my curtains. As I was unable to find the vendor in the device files, I created a new file specifically for these curtains.
Link to the picture PR: https://github.com/Koenkk/zigbee2mqtt.io/pull/2034

### CODE REVIEW

**Comment by Koenkk** [comment]
This is the same as https://github.com/Koenkk/zigbee-herdsman-converters/blob/63973fbc15153b46c05a552bcc20113b8088bf8a/devices/tuya.js#L2529, please update the `fingerprint` and `whitelabel` there.

**Comment by LoSk-p** [comment]
Ok, thanks, I'll do that, but where can I get the `manufacturerName` in `fingerprint`? It's not the same as vendor as I can see.

**Comment by Koenkk** [comment]
You can get it from the `data/database.db` (in the z2m folder) entry of the device.

**Comment by LoSk-p** [comment]
Thank you, I've found it

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
