### PR TITLE
Add support for Philips Hue 9290031452 (LTE005)

### PR DESCRIPTION
**Pull request by nakedible**
This will add support for Philips Hue White Ambiance Filament E14 (9290031452): https://www.philips-hue.com/en-gb/p/hue-white-ambiance-filament-single-bulb-e14/8719514411807

This is a filament version of 9290022944, or the white balance version of 9290024795.

### CODE REVIEW

**Comment by Koenkk** [comment]
The PR is marked as draft, is this ready for merge?

**Comment by nakedible** [comment]
No, cleaning it up to be perfect and testing the exact version first, should be ready soon.

**Comment by nakedible** [comment]
Okay, now this is ready, and this exact version of the file has been tested.

**Comment by nakedible** [comment]
zigbee2mqtt.io pull sits in https://github.com/Koenkk/zigbee2mqtt.io/pull/1673 waiting for this so docgen can be used.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
