### PR TITLE
Update ledvance.js

### PR DESCRIPTION
**Pull request by dhanukapulkit**
Added new Flex products

### CODE REVIEW

**Comment by Koenkk** [comment]
Seeing a lot of unexpected changes under https://github.com/Koenkk/zigbee-herdsman-converters/pull/5185/files (same as with the zigbee2mqtt.io docs pr)

**Review by dhanukapulkit — COMMENTED** [review]
Deleted all the double files.
Please check now

**Comment by dhanukapulkit** [comment]
@Koenkk  Now it should be fine. Please check.

**Comment by Koenkk** [comment]
Perfect, merry Christmas!

**Pull request merged**
