### PR TITLE
System modes based on "force" attribute

### PR DESCRIPTION
**Pull request by mgrom**
I've made System Modes based on Force attribute. So we have Auto, Heat and Off modes. Presets are working only with Auto mode. Only for old Moes devices this won't work because they don't have force attrribute.

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide some more context what problem is addressed here?

**Comment by mgrom** [comment]
It's not a problem, but improvement. Moes TRV uaes

**Comment by mgrom** [comment]
It's not a problem but improvement.
Moes TRV is using presets currently, and this is ok. New version of this valve provides attribute "force". This attribute says: normal => use presets (and use PID algorithm), open => just do full open of valve (not PID), close => full close (not PID). So basically it's auto, heat and off modes.
So I've made this mapping in thus PR

**Comment by Koenkk** [comment]
I see, thanks!

**Comment by Xites** [comment]
The documentation is still with 'force'.
https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html#tuya-ts0601_thermostat

**Comment by mgrom** [comment]
@Xites let's keep it this way. Force will stay with us (sounds like line from Star Wars :D ). There are going to be some changes in Modes and Presets, because current behaviour is not inline with HA.

**Comment by Xites** [comment]
@mgrom Hmm, finding a solution for this issue costed me an hour. I checked the documentation and I thought I was wrong.
A note in the docs would have been nice.

**Pull request merged**
