### PR TITLE
Update devices.js

### PR DESCRIPTION
**Pull request by maxpd1**
added my China bulbs. Did the same before in the ioBroker/ioBroker.zigbee

### CODE REVIEW

**Comment by Koenkk** [comment]
- Please share your `data/database.db`
- Please share a link to the product (aliexpress?)

**Comment by maxpd1** [comment]
Hi,

I am very sorry for the delay.

Where do I find the database. I find only one in /opt/iobroker/node_modules/zigbee-herdsman/temp/database.db

URL: https://www.alibaba.com/product-detail/Dimmable-E27-LED-Lamp-RGB-WIFI_1600064220375.html?spm=a2700.shop_index.82.21.1db138291IrzH9

**Comment by Koenkk** [comment]
that is the databas indeed, can you post the contents here?

**Comment by maxpd1** [comment]
In fact it seems as I have 2 installations. unfortunately timestamp is an unrealisitic one in 1985 of both. I think the one with bigger size is correct and newer one.

[database2.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5751723/database2.zip)

**Comment by Koenkk** [comment]
Device is not in the database, I need the manufacturer name, probably it's also shown in the iobroker UI.

**Comment by maxpd1** [comment]
Hi Koenkk, we discussed it some time ago here: https://github.com/Koenkk/zigbee2mqtt/issues/3895 

Are these information enough?

**Comment by Koenkk** [comment]
Yes, found it in that link, thanks!

**Pull request merged**
