### PR TITLE
Fix Sinope SP2600ZB & SP2610ZB energy const

### PR DESCRIPTION
**Pull request by MattL0**
Transfert to fzLocal

### CODE REVIEW

**Comment by Koenkk** [comment]
Why is this needed?

**Comment by MattL0** [comment]
This is to fix this issue.

https://github.com/Koenkk/zigbee2mqtt/issues/15950

There is something with the generic semetering converter that makes this report null. Divider and power is both 1 for this plug. 
Maybe this has something to do with Sinope only reporting ont he second integer ex : [0, 33625253] or [0, 23]
Also, the plug is reporting in w/h . So i devided to total by 1000

**Comment by Koenkk** [comment]
The only reason this converter works and the official one doesn't is the factor. I see the metering divisors are not read which might cause this. Can you add `await reporting.readMeteringMultiplierDivisor(endpoint);` to the configure of both devices?

**Comment by MattL0** [comment]
I'm closing this

**Comment by MattL0** [comment]
> The only reason this converter works and the official one doesn't is the factor. I see the metering divisors are not read which might cause this. Can you add `await reporting.readMeteringMultiplierDivisor(endpoint);` to the configure of both devices?

aaa... i should buy glasses.... lol thanks aha

**Pull request closed without merging**
