### PR TITLE
Added support for Sunricher ZG192910-4 LED-controller

### PR DESCRIPTION
**Pull request by tomekpur**

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you provide an URL of this device?

**Comment by tomekpur** [comment]
@Koenkk It's this identical device (it was delivered as part of my new kitchen) [https://www.ledlampendirect.nl/media/wysiwyg/pdf/50208512_manual_NL.pdf](url)

However, it has the code 'ZG192910-4' printed on the front and no-brand. After initially connecting with zigbee2mqtt it passed 'Sunricher' as the vendor in the zigbee2mqtt logs.

**Comment by Koenkk** [comment]
Thanks, congratz with your new kitchen.

Last question, why did you add?:

```
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            await configureReporting.onOff(endpoint);
        },
```

**Comment by tomekpur** [comment]
Had to be the late-night-must-get-it-to-work-vibes. Just did a redo on my local config and it turned out that the message was from one of my currently unconnected bulbs. Added a new commit to the PR.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
