### PR TITLE
6 key scene switch new device support

### PR DESCRIPTION
**Pull request by evangelo18**

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by evangelo18** [comment]
{"id":10,"type":"Router","ieeeAddr":"0x8cf681fffeaf27d2","nwkAddr":58627,"manufId":4098,"manufName":"_TZ3000_zua10nyz","powerSource":"Mains
(single
phase)","modelId":"TS0026","epList":[1,2,3,4,5,6],"endpoints":{"1":{"profId":260,"epId":1,"devId":4,"inClusterList":[0,4,5,6],"outClusterList":[25,10],"clusters":{"genOnOff":{"attributes":{"tuyaBacklightMode":1,"moesStartUpOnOff":0}},"genBasic":{"attributes":{"modelId":"TS0026","manufacturerName":"_TZ3000_zua10nyz","powerSource":1,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":4,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":4,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":4,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"5":{"profId":260,"epId":5,"devId":4,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"6":{"profId":260,"epId":6,"devId":4,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1664274882022,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
Then `zigbeeModel: ['_TZ3000_zua10nyz'],` won't work, it should be `zigbeeModel: ['TS0026'],`

**Comment by Koenkk** [comment]
Thanks!

**Comment by evangelo18** [comment]
what would be the difference between 
zigbeeModel: ['TS0026'],
and
fingerprint: [{modelID: 'TS0026', manufacturerName: '_TZ3000_zua10nyz'},

**Comment by Koenkk** [comment]
That with the fingerprint approach, only the device with `_TZ3000_zua10nyz` manufacturername will be supported.

**Comment by evangelo18** [comment]
thankyou!

Regards,

Evan Pavlakos
m: 0404 276 320

**Comment by MattL0** [comment]
@evangelo18  where did you buy this switch. I fo not find it.

**Comment by evangelo18** [comment]
> @evangelo18 where did you buy this switch. I fo not find it.
> 
> 

https://sqivo.en.alibaba.com/
these guys

**Comment by evangelo18** [comment]
@Koenkk the code doesnt appear to work. I am getting this msg
Debug 2023-01-22 19:43:38No converter available for 'TS0026' with cluster 'genScenes' and type 'commandRecall' and data '{"groupid":0,"sceneid":0}'
Debug 2023-01-22 19:43:38Received Zigbee message from '6 scene switch', type 'commandRecall', cluster 'genScenes', data '{"groupid":0,"sceneid":0}' from endpoint 3 with groupID 0

**Pull request merged**
