### PR TITLE
fix(detect): Detect _TZ3210_mja6r5ix and _TZ3210_it1u8ahz as TS0505B

### PR DESCRIPTION
**Pull request by felipejfc**
- (fix): Properly set model
- (fix): Control both lights with led_control so that brightness can be set when in color mode.

### CODE REVIEW

**Comment by Koenkk** [comment]
I think this can be merged with https://github.com/Koenkk/zigbee-herdsman-converters/blob/80036cd6f7e9804f2e419a3798123f72661c0b4d/src/devices/tuya.ts#L920

**Comment by felipejfc** [comment]
> I think this can be merged with
> 
> https://github.com/Koenkk/zigbee-herdsman-converters/blob/80036cd6f7e9804f2e419a3798123f72661c0b4d/src/devices/tuya.ts#L920

Thanks for reviewing. I thought it could be merged too, however, the min temp reported by the device is 143, while the one you sent specify 153. Is it still possible to merge despite this?

**Comment by Koenkk** [comment]
Then set it to `143`

**Comment by felipejfc** [comment]
done! ptal

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
