### PR TITLE
Added OTA for Legrand 064882

### PR DESCRIPTION
**Pull request by EXP-Carthage**
In accordance with the availability of the firmware (https://github.com/Koenkk/zigbee-OTA/pull/204), i have just added the possibility to update the device via OTA.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by tuxtof** [comment]
seems not working

```
zigbee2mqtt  | Zigbee2MQTT:info  2023-01-11 10:52:51: Updating 'radiateur sdb' to latest firmware
zigbee2mqtt  | Zigbee2MQTT:info  2023-01-11 10:53:52: MQTT publish: topic 'zigbee2mqtt/radiateur sdb', payload '{"cable_outlet_mode":"off","device_mode":"pilot_on","led_when_off":"OFF","led_when_on":"OFF","linkquality":21,"power":0,"power_on_behavior":"previous","state":"ON","update":{"installed_version":541187,"latest_version":1655299,"state":"available"},"update_available":null}'
zigbee2mqtt  | Zigbee2MQTT:info  2023-01-11 10:53:52: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"radiateur sdb"},"error":"Update of 'radiateur sdb' failed (Device didn't respond to OTA request)","status":"error","transaction":"2t4oq-1"}'
zigbee2mqtt  | Zigbee2MQTT:error 2023-01-11 10:53:52: Update of 'radiateur sdb' failed (Device didn't respond to OTA request)
```

any prerequisites ?

**Comment by dupont-y** [comment]
Hello, I had the same problem as @tuxtof  until I realized yesterday that the equipment furthest from the coordinator accepted the update.

I managed to update the second one by making it no longer seen directly by the coordinator, but through a router.

My coordinator is a hacked lidl box. To be tested, as usual, your mileage may vary.

**Comment by tuxtof** [comment]
with recent z2mqtt was able to update on my side

**Comment by 01awolf** [comment]
Hi
I have 5 cable outlet.
On 4 devices, after multiple tries and having seen that I need a link with the coordinator to initate the OTA, I was able to update them.
The last one resists and I don't know how to debug it.
The download is OK until 99% but after Z2M says Timeout.
Any ideas ?
Thank you

**Pull request merged**
