### PR TITLE
 add OTA on Multiple Legrand Devices

### PR DESCRIPTION
**Pull request by SilentT-FR**
due to a lot of new firmware available on : https://github.com/Koenkk/zigbee-OTA/pull/322

### CODE REVIEW

**Comment by SilentT-FR** [comment]
thanks to @EXP-Carthage

**Comment by Koenkk** [comment]
Thanks!

**Comment by SilentT-FR** [comment]
Hi @brantmacga 

i see you have added https://github.com/Koenkk/zigbee-herdsman-converters/commit/0214a337a25ea8634ec30f5f19d9a08ccdf04ce1 
WNAL63 

sorry but between Legrand/bticino and Legrand US i dident find the link between product

can you give this type of debug messages ?
`
debug 2023-07-02 20:53:44Received Zigbee message from 'XXXXX', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":5129215,"imageType":17,"manufacturerCode":4129}' from endpoint 1 with groupID 0
`

its to verify the availability of new firmware for this product

**Comment by SilentT-FR** [comment]
Hi @cbarry 

i see you have added 

https://github.com/Koenkk/zigbee-herdsman-converters/commit/cceace5cc15279255295c32b3071f9874ebf9003
WNRR15/WNRR20

sorry but between Legrand/bticino and Legrand US i dident find the link between product

can you give this type of debug messages ?
debug 2023-07-02 20:53:44Received Zigbee message from 'XXXXX', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":5129215,"imageType":17,"manufacturerCode":4129}' from endpoint 1 with groupID 0

its to verify the availability of new firmware for this product

**Pull request merged**
