### PR TITLE
Adding Nexelec file to support Open'R product

### PR DESCRIPTION
**Pull request by ElouanHocineNexelec**
I also created a request for a picture and documentation in zigbee2mqtt.io

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you try to [generate the definition](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition) with the latest [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) and see if that works?


Note to self; after this merge https://github.com/Koenkk/zigbee2mqtt.io/pull/2487

**Comment by Koenkk** [comment]
Yes, does the definition work?

**Comment by ElouanHocineNexelec** [comment]
The definition works partially, i edited it a little (Modified product description, model and removed some identify with no adverse effects)
Values are exposed correctly, but Co2 values seems abnormal : 
image
Fresh air is around 400ppm, I'm in an office where the value should be between 900 and 1200ppm.

**Comment by Koenkk** [comment]
I think it needs to be multiplied by 10, fixed that now, can you check again with latest-dev?

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by ElouanHocineNexelec** [comment]
I've tried it just then on Zigbee2MQTT Edge, so i recon the changes were applied to it. 
Values on my products are now between 9 and 11ppm.
image
I think your first hunch was right, but on this updtae it has been divided by 10 somehow.

**Comment by Koenkk** [comment]
Whoops, pushed a fix.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by ElouanHocineNexelec** [comment]
Seems like all the extends works now! I've updated nexelec.ts for it to comply with the modernExtend import, everything should be working fine.
I have two questions : 
-It seems now that the products aren't displayed on the dashboard (example of what it looked like before in the picture below), if i use the modernExtend version it displays nothing, is this to be expected?
image

-When will the vendor file will be compatible with the Main Zigbee2MQTT branch?

Thank you very much for all your help!

**Comment by Koenkk** [comment]
> t seems now that the products aren't displayed on the dashboard. Here's an example of what it looked like using the first version of nexelec.js in the picture below, but if i use the modernExtend version it displays nothing, is this to be expected?

Can you open an issue in the [frontend repo](https://github.com/nurikk/zigbee2mqtt-frontend) for this? 

> -When will the vendor file will be compatible with the Main Zigbee2MQTT branch?

Next release is 1 Feb

**Comment by ElouanHocineNexelec** [comment]
It's open!

Thank you again for all your help, it was nice collaborating with you!
Until i need your help again, 
Be well.

**Comment by WhistleMaster** [comment]
Hi !

Trying to get a new value from the UI through the "Exposes" tab of a Nexelec / Netsecur device will through the following error:

Screenshot 2024-02-17 at 08 53 21

The device is reporting correctly the values, but forcing to get one, temperature, humidity, CO2 or battery will pop this same error.

**Comment by Dylan-DutchAndBold** [comment]
@ElouanHocineNexelec Just wanted to say I really appreciate the effort to add it to zigbee2mqtt. This is the reason I have purchased the device and it works like a charm.

@WhistleMaster I have set it up today with the latest version of koenkk/zigbee2mqtt and did not get those errors, neither when I press the refresh button next to the values.

**Pull request merged**
