### PR TITLE
Support of Lupus 2 channel relay PRS3CH2_00.00.05.10TC

### PR DESCRIPTION
**Pull request by PeterFlorian**
Support of Lupus 2 channel relay PRS3CH2_00.00.05.10TC (only channel 1)

### CODE REVIEW

**Comment by Koenkk** [comment]
Are you able to control both relays? If not, please post your database.db entry of this device an we can probably easily add it.

**Comment by PeterFlorian** [comment]
Could you please guide me how to read the database.db entry?
(I don't have a development environment here and implemented the device just by trial and error)

**Comment by Koenkk** [comment]
Please test with 

```js
{
    zigbeeModel: ['PRS3CH2_00.00.05.10TC'],
    model: '12127',
    vendor: 'Lupus',
    description: '2 chanel relay',
    supports: 'on/off',
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    meta: {multiEndpoint: true, configureKey: 2},
    endpoint: (device) => {
        return {'l1': 1, 'l2': 2};
    },
    configure: async (device, coordinatorEndpoint) => {
        const endpoint1 = device.getEndpoint(1);
        await bind(endpoint1, coordinatorEndpoint, ['genOnOff']);
        const endpoint2 = device.getEndpoint(2);
        await bind(endpoint2, coordinatorEndpoint, ['genOnOff']);
    },
},
```

You should be able to control both endpoints through topics `zigbee2mqtt/[DEVICE_ID]/l1/set` / `zigbee2mqtt/[DEVICE_ID]/l2/set` payload `{"state": "ON"}`

**Comment by PeterFlorian** [comment]
It seems reading the button state seems to be fine:
```
sudo journalctl -uzigbee2mqtt.service -f

Jun 03 16:51:42 openhab npm[8370]: zigbee2mqtt:info  2020-06-03 16:51:42: MQTT publish: topic 'zigbee2mqtt/light_store2', payload '{"state_l2":"OFF","linkquality":155,"state_l1":"ON","last_seen":"2020-06-03T16:51:42+02:00"}'
Jun 03 16:51:43 openhab npm[8370]: zigbee2mqtt:info  2020-06-03 16:51:43: MQTT publish: topic 'zigbee2mqtt/light_store2', payload '{"state_l2":"OFF","linkquality":152,"state_l1":"OFF","last_seen":"2020-06-03T16:51:43+02:00"}'
Jun 03 16:51:50 openhab npm[8370]: zigbee2mqtt:info  2020-06-03 16:51:50: MQTT publish: topic 'zigbee2mqtt/light_store2', payload '{"state_l2":"ON","linkquality":147,"state_l1":"OFF","last_seen":"2020-06-03T16:51:50+02:00"}'
Jun 03 16:51:51 openhab npm[8370]: zigbee2mqtt:info  2020-06-03 16:51:51: MQTT publish: topic 'zigbee2mqtt/light_store2', payload '{"state_l2":"OFF","linkquality":147,"state_l1":"OFF","last_seen":"2020-06-03T16:51:51+02:00"}'
```
but to control the relay does not work:
```
mosquitto_pub -t zigbee2mqtt/light_store2/11/set -m '{"state":"ON"}'
mosquitto_pub -t zigbee2mqtt/light_store2/11/set -m '{"state":"OFF"}'
mosquitto_pub -t zigbee2mqtt/light_store2/12/set -m '{"state":"ON"}'
mosquitto_pub -t zigbee2mqtt/light_store2/12/set -m '{"state":"OFF"}'

Jun 03 16:54:41 openhab npm[8370]: zigbee2mqtt:error 2020-06-03 16:54:41: Publish 'set' 'state' to 'light_store2' failed: 'TypeError: Cannot read property 'command' of undefined'
Jun 03 16:54:41 openhab npm[8370]: zigbee2mqtt:info  2020-06-03 16:54:41: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to 'light_store2' failed: 'TypeError: Cannot read property 'command' of undefined'","meta":{"friendly_name":"light_store2"}}'
Jun 03 16:54:45 openhab npm[8370]: zigbee2mqtt:error 2020-06-03 16:54:45: Publish 'set' 'state' to 'light_store2' failed: 'TypeError: Cannot read property 'command' of undefined'
Jun 03 16:54:45 openhab npm[8370]: zigbee2mqtt:info  2020-06-03 16:54:45: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to 'light_store2' failed: 'TypeError: Cannot read property 'command' of undefined'","meta":{"friendly_name":"light_store2"}}'
Jun 03 16:54:50 openhab npm[8370]: zigbee2mqtt:error 2020-06-03 16:54:50: Publish 'set' 'state' to 'light_store2' failed: 'TypeError: Cannot read property 'command' of undefined'
Jun 03 16:54:50 openhab npm[8370]: zigbee2mqtt:info  2020-06-03 16:54:50: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to 'light_store2' failed: 'TypeError: Cannot read property 'command' of undefined'","meta":{"friendly_name":"light_store2"}}'
Jun 03 16:54:54 openhab npm[8370]: zigbee2mqtt:error 2020-06-03 16:54:54: Publish 'set' 'state' to 'light_store2' failed: 'TypeError: Cannot read property 'command' of undefined'
Jun 03 16:54:54 openhab npm[8370]: zigbee2mqtt:info  2020-06-03 16:54:54: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to 'light_store2' failed: 'TypeError: Cannot read property 'command' of undefined'","meta":{"friendly_name":"light_store2"}}'
```

**Comment by PeterFlorian** [comment]
Strange: Even if I revert your changes and reboot the system I still get a payload for `state_11` and `state_12`
```
Jun 03 17:09:39 openhab npm[486]: zigbee2mqtt:info  2020-06-03 17:09:39: MQTT publish: topic 'zigbee2mqtt/light_store2', payload '{"state_l2":"OFF","linkquality":157,"state_l1":"OFF","state":"ON","last_seen":"2020-06-03T17:09:39+02:00"}'
Jun 03 17:09:40 openhab npm[486]: zigbee2mqtt:info  2020-06-03 17:09:40: MQTT publish: topic 'zigbee2mqtt/light_store2', payload '{"state_l2":"OFF","linkquality":157,"state_l1":"ON","state":"ON","last_seen":"2020-06-03T17:09:40+02:00"}'
```
I don't think I have seen this before I applied you change.
Is there a cache of all attributes that have ever occurd?

**Comment by PeterFlorian** [comment]
Thank you for the tip how to remove the cache.
I guess I can remove the entire ´data´ folder for a full reset, right?

I have two of those devices. 
The first one I only used without your modification:
```
{"id":3,"type":"Router","ieeeAddr":"0x00124b00180fa404","nwkAddr":36582,"manufId":0,"manufName":"ClimaxTechnology","powerSource":"Mains (single phase)","modelId":"PRS3CH2_00.00.05.10TC","epList":[1,2,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":9,"inClusterList":[0,3,4,5,6,2821],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{"modelId":"PRS3CH2_00.00.05.10TC","manufacturerName":"ClimaxTechnology","powerSource":1,"zclVersion":1,"appVersion":4,"hwVersion":0,"dateCode":"20180726"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0001577f15","endpointID":1}]},"2":{"profId":260,"epId":2,"devId":9,"inClusterList":[4,6],"outClusterList":[0],"clusters":{},"binds":[]},"4":{"profId":260,"epId":4,"devId":9,"inClusterList":[],"outClusterList":[25],"clusters":{},"binds":[]}},"appVersion":4,"hwVersion":0,"dateCode":"20180726","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1591156554506}
```
The second one was only used yesterday, after I added your fix, but also after I revoked it:
```
{"id":4,"type":"Router","ieeeAddr":"0x00124b00180fa073","nwkAddr":53696,"manufId":0,"manufName":"ClimaxTechnology","powerSource":"Mains (single phase)","modelId":"PRS3CH2_00.00.05.10TC","epList":[1,2,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":9,"inClusterList":[0,3,4,5,6,2821],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{"modelId":"PRS3CH2_00.00.05.10TC","manufacturerName":"ClimaxTechnology","powerSource":1,"zclVersion":1,"appVersion":4,"hwVersion":0,"dateCode":"20180726"}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0001577f15","endpointID":1}]},"2":{"profId":260,"epId":2,"devId":9,"inClusterList":[4,6],"outClusterList":[0],"clusters":{"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0001577f15","endpointID":1}]},"4":{"profId":260,"epId":4,"devId":9,"inClusterList":[],"outClusterList":[25],"clusters":{},"binds":[]}},"appVersion":4,"hwVersion":0,"dateCode":"20180726","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1591203881110}
```

**Comment by Koenkk** [comment]
According to the db, https://github.com/Koenkk/zigbee-herdsman-converters/pull/1269#issuecomment-637655642 should be good. Can you provide the debug logging if this doesn't work?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by PeterFlorian** [comment]
This is  what I did:
1. Stop zigbee2mqtt
    sudo systemctl stop zigbee2mqtt.service
1. Modify `devices.js`, not including my last commit 75aa049
1. Configure log level
1. Reset zigbee2mqtt
    sudo rm -rf /opt/zigbee2mqtt/data/log/*
    sudo rm /opt/zigbee2mqtt/data/database.db
    sudo rm /opt/zigbee2mqtt/data/state.json
1. Start zigbee2mqtt
    sudo systemctl start zigbee2mqtt.service
1. Pair the device
1. Trigger contact 1
1. Trigger contact 2
1. Send commands
    mosquitto_pub -t zigbee2mqtt/light_store2/11/set -m '{"state":"ON"}'
    mosquitto_pub -t zigbee2mqtt/light_store2/11/set -m '{"state":"OFF"}'
    mosquitto_pub -t zigbee2mqtt/light_store2/12/set -m '{"state":"ON"}'
    mosquitto_pub -t zigbee2mqtt/light_store2/12/set -m '{"state":"OFF"}'

The [logfile](https://github.com/Koenkk/zigbee-herdsman-converters/files/4741435/log.txt) and [devices.js](https://github.com/Koenkk/zigbee-herdsman-converters/files/4741439/devices.js.txt) are attached to this post.

**Comment by PeterFlorian** [comment]
In addition I send you the other files of the `/opt/zigbee2mqtt/data` directory
[data.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/4741451/data.zip)

**Comment by Koenkk** [comment]
You should use `l1`/`l2` instead of `11`/`12`, e.g. `mosquitto_pub -t zigbee2mqtt/light_store2/l1/set -m '{"state":"ON"}'`

**Comment by PeterFlorian** [comment]
Using the right character did the trick.
Now the device is working perfect.
Thank you for your support!
When merging this branch don't forget commit 75aa049, since it adds support for linkquality.

**Pull request merged**
