### PR TITLE
Added ts004f_TZ3000_0ht8dnxj To TS004F

### PR DESCRIPTION
**Pull request by danieledwardgeorgehitchcock**
Resolves Koenkk/zigbee2mqtt#20745

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by tryanderror01** [comment]
Thanks Guys!
If I run an update I guess this change is automatically implemented and I only have to reconnect the device?

**Comment by Koenkk** [comment]
Just updating is enough.

**Comment by tryanderror01** [comment]
Hi Koenkk,
thanks a lot for the support. I guess I then have to wait for the next release as the latest for me is 1.35.1 from last week :)

**Comment by hnykda** [comment]
Hey. Just got this as well. I am having z2m Edge and have this supported, noting down few observations

1. it looks like this: 
image
which is different than what's in the docs (I guess it's just a case that is different, internals are the same) - is there a way how to add that to the docs somehow?

2. when in `command` mode. Specifically, on is at top left, off is on top right (which is physically-visually a different button), and brightness_up is at bottom left, brightness_down on bottom right. I don't find it intuitive

3. you can change modes from the UI, but press some button a second after you change it to wake the device up

**Comment by kalagan55** [comment]
> Hey. Just got this as well. I am having z2m Edge and have this supported, noting down few observations
> 
> 1. it looks like this:
>    image
>    which is different than what's in the docs (I guess it's just a case that is different, internals are the same) - is there a way how to add that to the docs somehow?
> 2. when in `command` mode. Specifically, on is at top left, off is on top right (which is physically-visually a different button), and brightness_up is at bottom left, brightness_down on bottom right. I don't find it intuitive
> 3. you can change modes from the UI, but press some button a second after you change it to wake the device up
> 4. the hold button event is triggered after a very long time (like 3 seconds maybe?), and release it only after you release it, making it rather unusable for "continuous" dimming and also is pretty unintuitive (i.e. you don't see the bulb/think it controls dimming before you release the button)

Hello, I have the same device as this one, I did the last update 1.35.2-1 but I do not have the 4 buttons that go up in Zigbee2MQTT.

image

**Comment by hnykda** [comment]
Hm, what? This is how switches look like normally in z2m. The clicks are exposed as specific action. E.g. when you press the first button, it would briefly change `action=1_single` or something. You need to react to these events.

**Comment by kalagan55** [comment]
> Hum, quoi ? Voici à quoi ressemblent normalement les commutateurs dans z2m. Les clics sont exposés comme une action spécifique. Par exemple, lorsque vous appuyez sur le premier bouton, cela change brièvement `action=1_single`ou quelque chose du genre. Quand rien n’est pressé, cela s’affiche `N/A`.
> 
> Vous devez réagir à ces événements d’action.


Ok, when I press a button I get this but I can't do anything...
image

In the MQTT integration, I only have one sensor...
On the other hand, in the logbook, this indicates 1 single, 2 single, 3 single and 4 single.
How to use this information to create automation or a script?
image

**Comment by hnykda** [comment]
The empty string gets there after it fires the event IMHO (that's the None). It just happens to quickly that is shows e.g. `2_single` -> `""` and you just see the second thing. But HA will receive the first event just fine.

This is not related to zigbee-herdsman-converters, but to your home automation system (which I infer is homeassistant). I propose you open a new topic on e.g. HA community forum.

Here is how I use this switch for automating lights in home assistant:

```
alias: Control of downstair hallway ceiling and stairs bulb with 2 gang switch
description: Control lights with switch actions
trigger:
  - platform: state
    entity_id:
      - sensor.switchtheta_action
    attribute: action
action:
  - variables:
      command: "{{ trigger.to_state.state }}"
      stairsBulb: light.bulbepsilon
      downstairCeiling: light.ceilingdownstairhallway
      transition: 0.5
      defaultBrightness: 100
      dimmedBrightness: 20
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ command == '1_single' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ stairsBulb }}"
            data:
              transition: "{{ transition }}"
              brightness_pct: "{{ defaultBrightness }}"
      - conditions:
          - condition: template
            value_template: "{{ command == '1_double' }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: "{{ defaultBrightness }}"
              transition: "{{ transition }}"
            target:
              entity_id: "{{ stairsBulb }}"
      - conditions:
          - condition: template
            value_template: "{{ command == '3_single' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ stairsBulb }}"
            data:
              transition: "{{ transition }}"
      - conditions:
          - condition: template
            value_template: "{{ command == '3_double' }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: "{{ dimmedBrightness }}"
              transition: "{{ transition }}"
            target:
              entity_id: "{{ stairsBulb }}"
      - conditions:
          - condition: template
            value_template: "{{ command == '2_single' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ downstairCeiling }}"
            data:
              transition: "{{ transition }}"
              brightness_pct: "{{ defaultBrightness }}"
      - conditions:
          - condition: template
            value_template: "{{ command == '2_double' }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: "{{ defaultBrightness }}"
              transition: "{{ transition }}"
            target:
              entity_id: "{{ downstairCeiling }}"
      - conditions:
          - condition: template
            value_template: "{{ command == '4_single' }}"
        sequence:
          - service: light.turn_off
            data:
              transition: "{{ transition }}"
            target:
              entity_id: "{{ downstairCeiling }}"
      - conditions:
          - condition: template
            value_template: "{{ command == '4_double' }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: "{{ dimmedBrightness }}"
              transition: "{{ transition }}"
            target:
              entity_id: "{{ downstairCeiling }}"
mode: single
```

**Comment by kalagan55** [comment]
thank you for your help, I succeeded with a blueprint found here:
[https://community.home-assistant.io/t/ts004f-blueprint-for-z2m-version-1-22-1-all-buttons-single-double-hold-12-actions/362531](url)

**Pull request merged**
