### PR TITLE
Change behavior of MCT-340 SMA and XHS2-SE for temp, battery, etc.

### PR DESCRIPTION
**Pull request by skandragon**
This should make a generic ias-style contact sensor that can be used more generically, and apply this to the MCT-340 SMA and XHS2-SE sensors to allow gathering of battery info, tamper, temperature, etc.

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you make this PR against the zigbee-herdsman-converters branch? This branch already contains some of the changes of this PR. Note that the master branch is deprecated (on next zigbee2mqtt zigbee-herdsman-converters will replace the master branch).

**Comment by skandragon** [comment]
I believe the only difference between the MCT-340 SMA and E versions are which company asked them to be made, and which firmware they have, and that both Comcast and Cox (for instance) want to sell you new devices...

**Comment by skandragon** [comment]
I'll give that branch a try.  I will likely start building my own docker image, as right now I'm doing a serious hack to make sure I can get branches pulled in properly.  I'll get back to you, probably this weekend, but it feels like we are on the same page on how the contacts should in general be supported.  What would you like to do?  I'm happy with either solution so long as I end up with contacts of (contact, tamper, battery_low) and the IAS support, and temperature and battery level readings.

**Comment by Koenkk** [comment]
FYI: I've renamed to zigbee-herdsman-converters to master and master to zigbee-shepherd-converters. This PR should now be merged into master, can you resolve the conflicts?

**Comment by airdrummingfool** [comment]
@Koenkk my `MCT-340 E` code is ready for the new `master` branch - I'll add support for the two devices in this PR and send a new PR in an hour or two. Perhaps @skandragon could give it a once-over, and then you can merge it in?

**Comment by Koenkk** [comment]
@airdrummingfool fine with that.

**Pull request closed without merging**
