### PR TITLE
Lidl: use Tuya TS011F basis for HG08673-FR

### PR DESCRIPTION
**Pull request by nathan-gs**
This commit fixes the power usage not reported errors, eg in: https://github.com/Koenkk/zigbee2mqtt/issues/14452 

npm test & npm run lint both pass

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of your device?

**Comment by nathan-gs** [comment]
@Koenkk the  `data/database.db` entry:

```json
{
  "id": 2,
  "type": "Router",
  "ieeeAddr": "0xa4c138163459950e",
  "nwkAddr": 18934,
  "manufId": 4417,
  "manufName": "_TZ3000_typdpbpg",
  "powerSource": "Mains (single phase)",
  "modelId": "TS011F",
  "epList": [
    1,
    242
  ],
  "endpoints": {
    "1": {
      "profId": 260,
      "epId": 1,
      "devId": 266,
      "inClusterList": [
        3,
        4,
        5,
        6,
        1794,
        2820,
        57345,
        57344,
        0
      ],
      "outClusterList": [
        25,
        10
      ],
      "clusters": {
        "genBasic": {
          "attributes": {
            "65503": "���*\u0003",
            "65506": 54,
            "65508": 0,
            "65534": 0,
            "modelId": "TS011F",
            "manufacturerName": "_TZ3000_typdpbpg",
            "powerSource": 1,
            "zclVersion": 3,
            "appVersion": 77,
            "stackVersion": 0,
            "hwVersion": 1,
            "dateCode": ""
          }
        },
        "haElectricalMeasurement": {
          "attributes": {
            "acCurrentDivisor": 1000,
            "acCurrentMultiplier": 1,
            "rmsVoltage": 233,
            "rmsCurrent": 0,
            "activePower": 0
          }
        },
        "seMetering": {
          "attributes": {
            "divisor": 100,
            "multiplier": 1,
            "currentSummDelivered": [
              0,
              571
            ]
          }
        },
        "genOnOff": {
          "attributes": {
            "32768": 0,
            "onOff": 1,
            "onTime": 0,
            "offWaitTime": 0,
            "tuyaBacklightMode": 1,
            "moesStartUpOnOff": 2,
            "tuyaBacklightSwitch": 1
          }
        },
        "manuSpecificTuya_3": {
          "attributes": {
            "53248": 1,
            "53249": 0,
            "53250": 2752503,
            "53251": 123,
            "53252": 10912,
            "53253": 1307,
            "powerOnBehavior": 2,
            "switchType": 0
          }
        }
      },
      "binds": [
        {
          "cluster": 6,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c0c109",
          "endpointID": 242
        },
        {
          "cluster": 2820,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c0c109",
          "endpointID": 242
        },
        {
          "cluster": 1794,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c0c109",
          "endpointID": 242
        },
        {
          "cluster": 6,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c0c109",
          "endpointID": 1
        },
        {
          "cluster": 2820,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c0c109",
          "endpointID": 1
        },
        {
          "cluster": 1794,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c0c109",
          "endpointID": 1
        }
      ],
      "configuredReportings": [
        {
          "cluster": 2820,
          "attrId": 1285,
          "minRepIntval": 5,
          "maxRepIntval": 3600,
          "repChange": 5
        },
        {
          "cluster": 2820,
          "attrId": 1288,
          "minRepIntval": 5,
          "maxRepIntval": 3600,
          "repChange": 50
        },
        {
          "cluster": 2820,
          "attrId": 1291,
          "minRepIntval": 5,
          "maxRepIntval": 3600,
          "repChange": 10
        },
        {
          "cluster": 1794,
          "attrId": 0,
          "minRepIntval": 5,
          "maxRepIntval": 3600,
          "repChange": [
            1,
            1
          ]
        }
      ],
      "meta": {}
    },
    "242": {
      "profId": 41440,
      "epId": 242,
      "devId": 97,
      "inClusterList": [],
      "outClusterList": [
        33
      ],
      "clusters": {},
      "binds": [],
      "configuredReportings": [],
      "meta": {}
    }
  },
  "appVersion": 77,
  "stackVersion": 0,
  "hwVersion": 1,
  "dateCode": "",
  "zclVersion": 3,
  "interviewCompleted": true,
  "meta": {
    "configured": -1798312590
  },
  "lastSeen": 1665831386034,
  "defaultSendRequestWhen": "immediate"
}
```

**Comment by Koenkk** [comment]
This device is not detected as a `HG08673-FR` but a `TS011F_plug_1`?

**Comment by nathan-gs** [comment]
I see I posted the wrong device, sorry! 

The correct one:
```json
{
  "id": 20,
  "type": "Router",
  "ieeeAddr": "0xa4c1381f8ccf7230",
  "nwkAddr": 35817,
  "manufId": 4417,
  "manufName": "_TZ3000_ynmowqk2",
  "powerSource": "Mains (single phase)",
  "modelId": "TS011F",
  "epList": [
    1,
    242
  ],
  "endpoints": {
    "1": {
      "profId": 260,
      "epId": 1,
      "devId": 266,
      "inClusterList": [
        3,
        4,
        5,
        6,
        1794,
        2820,
        57345,
        57344,
        0
      ],
      "outClusterList": [
        25,
        10
      ],
      "clusters": {
        "genBasic": {
          "attributes": {
            "65503": "\u0000\u0000\u0000\u0000\u0012\u0000\u0000\u0000\u0000\u0012\u0000\u0000\u0000\u0000\u0012\u0000\u0000\u0000\u0000\u0012",
            "65506": 53,
            "65508": 0,
            "65534": 0,
            "modelId": "TS011F",
            "manufacturerName": "_TZ3000_ynmowqk2",
            "powerSource": 1,
            "zclVersion": 3,
            "appVersion": 68,
            "stackVersion": 0,
            "hwVersion": 1,
            "dateCode": ""
          }
        },
        "seMetering": {
          "attributes": {
            "divisor": 100,
            "multiplier": 1,
            "currentSummDelivered": [
              0,
              907
            ]
          }
        },
        "haElectricalMeasurement": {
          "attributes": {
            "acVoltageMultiplier": 1,
            "acVoltageDivisor": 1,
            "acCurrentMultiplier": 1,
            "acCurrentDivisor": 1000,
            "acPowerMultiplier": 1,
            "acPowerDivisor": 1,
            "rmsVoltage": 230,
            "rmsCurrent": 0,
            "activePower": 0
          }
        },
        "genOnOff": {
          "attributes": {
            "32768": 0,
            "onOff": 1,
            "onTime": 0,
            "offWaitTime": 0,
            "tuyaBacklightMode": 0,
            "moesStartUpOnOff": 1,
            "tuyaBacklightSwitch": 1
          }
        },
        "manuSpecificTuya_3": {
          "attributes": {
            "53248": 0,
            "53249": 0,
            "53250": 0,
            "53251": 0,
            "53252": 0,
            "53253": 0,
            "powerOnBehavior": 1,
            "switchType": 0
          }
        }
      },
      "binds": [
        {
          "cluster": 6,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c0c109",
          "endpointID": 1
        },
        {
          "cluster": 2820,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c0c109",
          "endpointID": 1
        },
        {
          "cluster": 1794,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c0c109",
          "endpointID": 1
        }
      ],
      "configuredReportings": [
        {
          "cluster": 2820,
          "attrId": 1285,
          "minRepIntval": 5,
          "maxRepIntval": 3600,
          "repChange": 5
        },
        {
          "cluster": 2820,
          "attrId": 1288,
          "minRepIntval": 5,
          "maxRepIntval": 3600,
          "repChange": 50
        },
        {
          "cluster": 2820,
          "attrId": 1291,
          "minRepIntval": 5,
          "maxRepIntval": 3600,
          "repChange": 10
        },
        {
          "cluster": 1794,
          "attrId": 0,
          "minRepIntval": 5,
          "maxRepIntval": 3600,
          "repChange": [
            1,
            1
          ]
        }
      ],
      "meta": {}
    },
    "242": {
      "profId": 41440,
      "epId": 242,
      "devId": 97,
      "inClusterList": [],
      "outClusterList": [
        33
      ],
      "clusters": {},
      "binds": [],
      "configuredReportings": [],
      "meta": {}
    }
  },
  "appVersion": 68,
  "stackVersion": 0,
  "hwVersion": 1,
  "dateCode": "",
  "zclVersion": 3,
  "interviewCompleted": true,
  "meta": {
    "configured": -1798312590
  },
  "lastSeen": 1667058221850,
  "defaultSendRequestWhen": "immediate"
}
```

**Comment by nathan-gs** [comment]
On the outside of the device is following label: `HG08673-FR`

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
