### PR TITLE
Develco SPLZB-131: power_reactive (VAR) reading

### PR DESCRIPTION
**Pull request by emandtf**
Useful to distinguish between Capacitive and Inductive load (negative values are common for negative-energy).

Maybe other Develco SPLZB-13x could have same capability, but I don't have any of them.

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by sk-pub** [comment]
@emandtf, it seems that this change caused incorrect power measurements. All my 5 SPLZB-131 devices now report 100 times less power.

**Comment by emandtf** [comment]
> @emandtf, @Koenkk, All my 5 SPLZB-131 devices now report 100 times less power.

There isn't any relation about previous or other types of measurements. This commit regards a NEW value and nothing is changed to normal ones of the way them are retrieved/read/parsed.
I'm using this code/commit for all my 11 SPLZB-131 devices from middle of April and all is working well for all kind of measurements.

**Comment by sk-pub** [comment]
> > @emandtf, @Koenkk, All my 5 SPLZB-131 devices now report 100 times less power.
> 
> There isn't any relation about previous or other types of measurements. This commit regards a NEW value and nothing is changed to normal ones of the way them are retrieved/read/parsed. I'm using this code/commit for all my 11 SPLZB-131 devices from middle of April and all is working well for all kind of measurements.

I have no better guess – it's the only change for this device in 1.31.0. Downgrading to 1.30.4 solved this problem for me.

**Comment by emandtf** [comment]
> @emandtf,  now report 100 times less power.
Please open your "z2m/data/configuration.db" using a normal Text editor anche check for multiplier/divider values for those 131 devices, and check if they are correct or fix it if needed, the restart Z2M.
I had a similar issue 1 year ago when something (I never discovered who and why) changed those values and power was 10 and 100 times less than the real ones.

**Comment by sk-pub** [comment]
> > @emandtf,  now report 100 times less power.
> 
> Please open your "z2m/data/configuration.db" using a normal Text editor anche check for multiplier/divider values for those 131 devices, and check if they are correct or fix it if needed, then restart Z2M. I had a similar issue 1 year ago when something (I never discovered who and why) changed those values and power was 10 and 100 times less than the real ones.

I'd rather stick to ver. 1.30.4 :)

**Pull request merged**
