### PR TITLE
Whitelabel Samotech - SM309

### PR DESCRIPTION
**Pull request by umairyounus**
Samotech - SM309 is a Whitelabel product of ZG9101SAC-HP.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by umairyounus** [comment]
Hi @Koenkk , I've added `Samotech - SM309` to the Whitelabel of `ZG9101SAC-HP` but it
still complaining about the unknown device. If I clone `ZG9101SAC-HP` and rename it to `SM309` then it's working. Is there any other step involve to make Whitelabel work?

**Comment by Koenkk** [comment]
whitelabel is pure cosmetic, only used in the documention.

Does the following addition to `devices.js` work?

```js
{
    zigbeeModel: ['SM309'],
    model: 'SM309',
    vendor: 'Samotech',
    description: 'ZigBee AC phase-cut dimmer',
    extend: generic.light_onoff_brightness,
    meta: {configureKey: 2},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
        await configureReporting.onOff(endpoint);
    },
},
```

**Comment by umairyounus** [comment]
Following Code has worked for me:

`    {
      zigbeeModel: ['SM309'],
      model: 'SM309',
      vendor: 'SM0TECH',
      description: 'ZigBee dimmer 400W',
      extend: generic.light_onoff_brightness,
      meta: {configureKey: 1},
      configure: async (device, coordinatorEndpoint) => {
          const endpoint = device.getEndpoint(1);
          await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
          await configureReporting.onOff(endpoint);
      },
  }`

**Comment by Koenkk** [comment]
Added.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by umairyounus** [comment]
thanks man

**Pull request merged**
