### PR TITLE
Update ecodim to support all white label versions of the dimmer switch

### PR DESCRIPTION
**Pull request by KDanielK**
Added support for all white label versions of the Dimmer-Switch-ZB3.0 since they all have manufacturerID 4714 For example MoooN AB that is missing now

NOTE: most likely the other versions such as Namron can be removed now since they all have 4714 as manufacturerID

### CODE REVIEW

**Comment by Koenkk** [comment]
looks good, can you remove the others?

**Comment by KDanielK** [comment]
> looks good, can you remove the others?

Done! :)

**Comment by Koenkk** [comment]
Thanks!

**Comment by zeminator** [comment]
Still a noobie.. All my ecodim devices are failing to fetching firmware.. Getting error "no image available for imagetype '60'". I have both 07 and 10 devices.

**Pull request merged**
