### PR TITLE
Update giex.ts add white label _TZE204_4fblxpma

### PR DESCRIPTION
**Pull request by Oggymator**
Add one more tuya white label
zigbeeModel: ['TS0601'],
model: 'TS0601',
vendor: '_TZE204_4fblxpma',

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Oggymator** [comment]
not sure if it is a problem, but you missed a ' in the code 

`tuya.whitelabel('GiEX', 'GX02', 'Water valve', ['_TZE204_7ytb3h8u', '_TZE204_4fblxpma]),`

**Comment by Federfox** [comment]
could you please add: vendor: _TZE284_7ytb3h8u
Thanks in advance !

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Pull request merged**
