### PR TITLE
Update tuya.ts added BAB-1413 Pro - Corrected

### PR DESCRIPTION
**Pull request by Steefph**
Hi Koen, it is my first attempt to something to your great project so, please if anything, let me know

### CODE REVIEW

**Comment by Koenkk** [comment]
Many thanks!

**Comment by ChrisPallasch** [comment]
onEvent: tuya.onEventSetTime,
needs to be changed to LOCAL
onEvent: tuya.onEventSetLocalTime

Otherwise the TRV will display/use a wrong DoW

BTW, current_heating_setpoint does not work

**Comment by Steefph** [comment]
The issue with "current_heating_setpoint" is that it needs to be written when the device is awake. If you write the setpoint several times, it does stay. Don't know how to fix that.

I will update the time. (where can I read up on this :) )

**Comment by Koenkk** [comment]
- Is that the case for all the attributes?
- Can you try changing: 
https://github.com/Steefph/zigbee-herdsman-converters/blob/e235a2371a71ba86c91a83c97fe224d48133989e/src/lib/tuya.ts#L216

to 

```
await entity.command('manuSpecificTuya', cmd, {seq, dpValues}, {disableDefaultResponse: true, sendWhen: 'active'});
```

**Comment by ChrisPallasch** [comment]
The change on L216 didn't have any effect on the behavior of the BAB-1413

Maybe it helps if I report, that if the changes are made via the frontend's "slider" (NOT! if changed via numeric field), than the change is accepted.

**Comment by ChrisPallasch** [comment]
> The issue with "current_heating_setpoint" is that it needs to be written when the device is awake. If you write the 

If you publish to `<device>/set` with payload `{"current_heating_setpoint": 19}`  the TRV will accept it. Same for other temp settings.

**Comment by xs400dohc** [comment]
Hi there,
I'm working also on support for BAB-1413 Pro aka _TZE204_g2ki0ejr (see PR #6534 #6526 ).
By now the TRV is nearby usable. But I have problems with following:
- changing SystemMode shows 'Publish 'set' 'system_mode' to '0xa4c1386dbd845299' failed: 'Error: No datapoint defined for 'system_mode'''
- changing RunningState shows 'No converter available for 'running_state' ("heat")'
- -changing schedule via frontend shows 'Publish 'set' 'schedule' to '0xa4c1386dbd845299' failed: 'Error: No datapoint defined for 'schedule'''
- valve returns 'NULL'
- factory_reset does nothing (i can see)
- expose open_window_time / boost_time to frontend
In my home the TRVs _TZE200_dv8abrrz, _TZE200_hue3yfsn are running quite well.
I tried following by now:
- _TZE200_dv8abrrz expose 'position' of the valve, but using the code of _dv8abrrz in _g2ki0ejr gives no progress
- _hue3yfsn exposes 'boost timeset countdown'. Using this code also gives no progress
Hopefully someone can give, a beginner like me, a hint, how to fix the problems.

**Comment by ChrisPallasch** [comment]
For schedule try adding (~ L2669) at tuya.js:
```
[26, 'working_day', tuya.valueConverterBasic.lookup({ 'mon_sun': tuya.enum(0), 'mon_fri+sat+sun': tuya.enum(1),'separate': tuya.enum(2) })],
[27, 'schedule', tuya.valueConverter.thermostatScheduleDaySingleDP]
```

Sadly I get an Error ref to string conversion when trying to set a schedule, but there are also probs setting it directly at the TRV itself.

To set an option choose DataPoint 2 "preset". Has to be "man(ual)" aka enum[2].
Publish to mqtt broker '0xa4c1386dbd845299/set {"preset" : "man"}' 

Valve (dp:49) only seams to report true/false, no detailed percentage.

**Comment by xs400dohc** [comment]
yes, you're right, for homeautomation schedule is unimportant. So I won't waste my/your time with this.
Your suggestion with datapoints 26 and 27 doesn't work, z2m is stuck in reboot. Probably because these datapoints doesn't exist.
All datapoints I extracted from tuya-development-platform are already listed in the code.
The only datapoint that would be nice to have, but not neede to run an automation, is datapoint 49 'valve'. So it's possible to prove, if something is wrong (i.e. the valve is fully closed, but temperature rises -> TRV not mounted probably / fell of) (Don't know, if 'error_status' shows such error and found no documentation, which state of 'error_status' means which error).
Also, I don't know, if it's important, to set 'system_mode' (I get the error 'Publish 'set' 'system_mode' to '0xa4c1386dbd845299' failed: 'Error: No datapoint defined for 'system_mode''' if I change it) and 'running_state' (error 'No converter available for 'running_state' ("heat")')

**Comment by ChrisPallasch** [comment]
May I ask if you did set the "komma" at the end of the line?
It's a common error which lets z2m hangup.

**Comment by xs400dohc** [comment]
My mistake, the komma was missing.

But schedule is still not changeable, but no further error-messages.

**Comment by xs400dohc** [comment]
Any progress in schedule will be only nice to have and only let me learn, how it works. But it's really not important, for homeautomation.

**Comment by ChrisPallasch** [comment]
Due to SmartLife doesnt work on schedule, I'll will the weekend try Tuya App (there are 2 apps if I recall correctly). Maybe ioBroker (my homeautomatition) reports some newly set values. SmartLife wasnt able to change strange default falues.

**Comment by xs400dohc** [comment]
Let me know, if you find some more information. If you take a look, you can also look for 'valve' and what kind of data it reports (on/off or percentage). I haven't found anything about in tuya-development.

**Comment by ChrisPallasch** [comment]
valve (equaling to mode) only reports true/false (heat/idle) via dp:49
No percentage (non-zero) point (up to dp:100) found.

**Comment by ChrisPallasch** [comment]
I dont wanted to wait till the weekend (even though it's 9pm and am watching TV).
Tuya App looks like SmartLife App, even though 2 Apps installed.
Did use this 15 bucks China Tuya Gateway (Zigbee/BLE/IR) for testing.

This time, all mobile/cloud set schedule values were accepted (prooveable on TRV display)

Sadly, the mqtt broker values via z2m are as strange as before
set was:
06:00/18°C, 11:30/19°C, 13:30/20°C,m 17:00/19°C

mqtt report says:
trv-1413

**Pull request merged**
