### PR TITLE
Add two Legrand devices: 067774 and 067694

### PR DESCRIPTION
**Pull request by jd1900**
Add support for 067774 and 067694 from Legrand.
067774 --> Wireless double remote switch: https://www.legrand.es/documentos/Ficha-Comando-doble-iluminacion-741812-42-72.pdf
067694 --> Remote toggle switch: https://zigbee.blakadder.com/Legrand_067694.html or https://www.grupolegrand.es/e-catalogo/pdf-prod.php?product=067694

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks, I've made some small changes, can you test if everything still works ok? (https://github.com/Koenkk/zigbee-herdsman-converters/pull/1355/commits/c83f629fcc0d13f5377dabe1d732ce6efc1f5b91)

**Comment by Koenkk** [comment]
Note to self: after this merge https://github.com/Koenkk/zigbee2mqtt/pull/3815/files

**Comment by jd1900** [comment]
Works fine, thank you!!

**Comment by Koenkk** [comment]
Why did you close this, I assume you want this to be merged? If so pleas re-open

**Comment by jd1900** [comment]
OK. My fault.

**Comment by Koenkk** [comment]
thanks!

**Pull request merged**
