### PR TITLE
Merging aesedepece's work into the mainline

### PR DESCRIPTION
**Pull request by grinco**
Looks like the branch is 7 commits ahead for the master.

### CODE REVIEW

**Comment by Koenkk** [comment]
@aesedepece is this something that should be merged?

**Comment by aesedepece** [comment]
In theory they were already merged in https://github.com/Koenkk/zigbee-herdsman-converters/pull/2407, but maybe I changed something afterwords or I rebased and force-pushed out something. Let me check.

**Comment by aesedepece** [comment]
Well, apparently these are the exactly same commits that were merged back in #2407,  but for some reason they are apparently no longer on master :shrug: 

Thus let's have these merged again :wink:

**Comment by Koenkk** [comment]
@grinco can you rebase this pr, it has some merge conflicts

**Pull request closed without merging**
