### PR TITLE
Add support for reading the temperature of MCCGQ11LM (Aqara door & window contact sensor)

### PR DESCRIPTION
**Pull request by BerndAmend**
The same should work with the RTCGQ11LM, but I don't have one to test it.
I tested the code with a couple of sensors and all provided the correct temperature (precision 1° C)

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks! Merged it with `fz. xiaomi_contact_interval`

**Comment by pedrolamas** [comment]
Wow... I've had these for ages and never knew they supported temperature report!! Great find and nice work there @BerndAmend 🙂

**Comment by diplix** [comment]
i tested this with my RTCGQ11LM sensors and it works for them, too. changed code in
devices.js
```
    {
        zigbeeModel: ['lumi.sensor_magnet'],
        model: 'MCCGQ01LM',
        vendor: 'Xiaomi',
        description: 'MiJia door & window contact sensor',
        meta: {battery: {voltageToPercentage: '3V_2100'}},
        fromZigbee: [fz.xiaomi_battery, fz.xiaomi_contact],
        toZigbee: [],
        exposes: [e.battery(), e.contact()],
    },
```

fromZigbee.js

```
    RTCGQ11LM_interval: {
        cluster: 'genBasic',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            if (msg.data.hasOwnProperty('65281')) {
                const result = {};
                if (msg.data['65281'].hasOwnProperty('11')) {
                    result.illuminance = calibrateAndPrecisionRoundOptions(msg.data['65281']['11'], options, 'illuminance');
                    result.illuminance = calibrateAndPrecisionRoundOptions(msg.data['65281']['11'], options, 'illuminance_lux');
                }


                if (msg.data['65281'].hasOwnProperty('3')) {
                    let temperature = msg.data['65281']['3'];
                    temperature = calibrateAndPrecisionRoundOptions(temperature, options, 'temperature');
                    result.temperature = temperature;
                }


                return result;
            }
        },
    },
```

result in home-assistant:

Bildschirmfoto 2021-01-12 um 21 33 14

**Comment by Koenkk** [comment]
@diplix added, done!

**Comment by qosmio** [comment]
Curious if there's any documentation regarding the update intervals for temperature measurement? All of my RTCGQ11LM have the 5 sec hardware mod, but the temperature does not seem to update in a set interval (or at all), even on extreme temperature changes like the dedicated Aqara temperature sensors. They all seem to be consistently report 26C even though my house is well below that.

**Comment by andyinno** [comment]
I have a lot of RTCGQ11LM that I bought during the years, 
All of them are reporting temperature 0°C after the last update to 1.17.1 

There are any tricks with them? It is correct that it reports something when it shouldn't?

**Comment by qosmio** [comment]
I see that on the [deconz](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/488#issuecomment-373966661) discussion from 2018 reports the same thing 0C and 26C consistently. That the readings update every hour, however the reading aren't really trustful.

**Comment by CypherMK** [comment]
I got this working on 7 RTCGQ11LM sensors and 2 MCCGQ11LM sensors. but the temperatures are way off, if I compare them with 2 WSDCGQ11LM sensors. 3 to 7 degrees off. Would it be possible to adjust this like with this sensor: https://www.zigbee2mqtt.io/devices/WSDCGQ11LM.html

**Comment by andyinno** [comment]
Back home from work, they are giving a value different from 0.

In the same room I can see on 3 sensors:

- 23°C
- 29°C
- 24°C

They are in no way reliable seen that two xiaomi temperature/humidity sensors in the same room for comparison are at:

- 19.85°C
- 19.80°C

I don't see an usage from them. 

Should I exclude them from auto gruping? 
@Koenkk: or could this unreliable sensor filtered out directly from z2m?

**Comment by BerndAmend** [comment]
I have 15 sensors, and 3 provide wrong values. The others provide values with +-1° C of other temperature sensors.

**Comment by AntoineTESTE** [comment]
Hello.

Same here. with an RTCGQ11LM and an MCCGQ11LM. Both output the same value: temperature 30°C, while the room is measured at 21°C.

**Comment by martin-g-it** [comment]
Hi there; just added a new RTCGQ11LM on 1.17.1, but there is no temperature mentioned in the payload...
On the other hard; my existing MCCGQ11LM door sensors so start to report temperature now. Am I missing something?

RTCGQ11LM payload '{"illuminance":16,"illuminance_lux":16,"linkquality":69,"occupancy":true}'
MCCGQ11LM payload '{"battery":91,"contact":true,"linkquality":63,"temperature":18,"voltage":2985}'

After checking further, it seems that only 1 out of 3 RTCGQ11LM PIR sensors is reporting the temperature...

**Pull request merged**
