### PR TITLE
IKEA: try and be smart about dontDividePercentage

### PR DESCRIPTION
**Pull request by sjorge**
https://github.com/Koenkk/zigbee2mqtt/issues/16412

@Koenkk can you confirm 2.4.x is where IKEA change it?

My on/off ones are on 2.2.010 which is the last one with group binding support, dontDividePercentage=true is needed
My open/close that I got with my fyrtur are on 2.3.079, no group bind but they also seem to require dontDividePercentage=true

It seems the one form the issue was on 2.4.x so I picked that as the cutoff. For now anything < 2.4 has dontDividePercentage=true and everything else has it dontDividePercentage=false.

For my tests I had it at 2.3 so I could see if the code path was doing the right thing, and it was:

```
# 2.2.x
Zigbee2MQTT:debug 2023-02-12 14:17:19: Received MQTT message on 'zigbee2mqtt/remote/office/light_desk/get' with data '{"battery":""}'
Zigbee2MQTT:debug 2023-02-12 14:17:19: Publishing get 'get' 'battery' to 'remote/office/light_desk'
Zigbee2MQTT:debug 2023-02-12 14:17:22: Received Zigbee message from 'remote/office/light_desk', type 'readResponse', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":74}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2023-02-12 14:17:22: XXX: dontDividePercentage = true
Zigbee2MQTT:info  2023-02-12 14:17:22: MQTT publish: topic 'zigbee2mqtt/remote/office/light_desk', payload '{"battery":74,"linkquality":116,"update":{"installed_version":570492465,"latest_version":587699761,"state":"available"}}'

# 2.3.x
Zigbee2MQTT:debug 2023-02-12 14:17:33: Received MQTT message on 'zigbee2mqtt/remote/livingroom/side_back_window/get' with data '{"battery":""}'
Zigbee2MQTT:debug 2023-02-12 14:17:33: Publishing get 'get' 'battery' to 'remote/livingroom/side_back_window'
Zigbee2MQTT:debug 2023-02-12 14:17:37: Received Zigbee message from 'remote/livingroom/side_back_window', type 'readResponse', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":87}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2023-02-12 14:17:37: XXX: dontDividePercentage = false
Zigbee2MQTT:info  2023-02-12 14:17:38: MQTT publish: topic 'zigbee2mqtt/remote/livingroom/side_back_window', payload '{"battery":43.5,"linkquality":69,"update":{"installed_version":587699761,"latest_version":587699761,"state":"idle"}}'
```

I also added `tz.battery_percentage_remaining` as that made testing easier and no harm in having this, as it's quite useful to be able to trigger a refresh of the battery info (as always, you do have to wake up the device after)

### CODE REVIEW

**Comment by Koenkk** [comment]
I expect that it indeed broke at 2.4.x (e.g. https://github.com/Koenkk/zigbee2mqtt/issues/16637). 

Bedankt! 😄

**Comment by sjorge** [comment]
> I think this fix should be incorporated into the roller blinds as well. My PRAKTLYSING and KADRILJ on 24.4.10 show the same behaviour. E1926 E2102

I only have fyrtur but they don't seem to have a firmware newer that 2.3.088 available. Do your PRAKTLYSING and KADRILJ show a 24.4.* or is it 2.4.* like with the remotes?

**Comment by thatslolo** [comment]
They both show 24.4.10. The fw was installed when I was using the Dirigera hub. It seems not to be released through the "official" channel z2m uses

**Comment by thatslolo** [comment]
My remotes are also on 24.4.* fw. But the check for fw >2.3.x fixed the issue for my remotes as well.

**Comment by m-stefanski** [comment]
I have the same problem (battery reported as 200%) in my E1810. 

OTA reports there is no newer firmware for it, it is on 1.2.223. 
Is it something I can override for my specific device?

**Pull request merged**
