### PR TITLE
fix TS011F_plug

### PR DESCRIPTION
**Pull request by yratanov**
following https://github.com/Koenkk/zigbee-herdsman-converters/pull/2571

Reporting is not supported.

### CODE REVIEW

**Comment by Koenkk** [comment]
Would be a pitty if this is the case. Can you/someone sniff how this device works with the original TuYa gateway? https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by yratanov** [comment]
Sadly I don’t have tuya gateway

**Comment by Koenkk** [comment]
Asked for help in https://github.com/Koenkk/zigbee2mqtt/issues/7405

**Comment by Koenkk** [comment]
I've received this plug today, luckily it does support reporting, pushed some small improvement.s

**Comment by yratanov** [comment]
@Koenkk it was my mistake. I haven't press Reconfigure after changing the code. Now I did it and it works well 👍

**Pull request closed without merging**
