### PR TITLE
danfoss: set min/max heatSetPointLimit to match the devices max range

### PR DESCRIPTION
**Pull request by sjorge**
Waiting for someone to test this, see https://github.com/Koenkk/zigbee2mqtt/discussions/11125

### CODE REVIEW

**Comment by sjorge** [comment]
@robertalexa FYI, not sure you still have the device to possible test with though.

**Comment by robertalexa** [comment]
@sjorge See my reply in the conversation thread.

TLDR - i don't think this PR is needed, but i am open to debate

**Comment by sjorge** [comment]
Same, I'm not 100% convinced this is needed either. Also why it's a draft so it doesn't get merged too soon by accident.

**Comment by robertalexa** [comment]
On my Hive TRV max 3200 works, 3500 -> INVALID VALUE error.

So 500 to 3200 can be configured correctly via Dev Console.

I would personally say not to push the PR, despite the command working correctly. OP was the only time we heard of sth like this, and we both know the Ally is super popular and a lot of people are engaged with the Ally thread. I am sure we would know from others if this was a true problem.

Ultimately the decision is yours, in my use case my minimum is 9C to match Google Home minimum. Pushing your commit will re-write my setup upon reconfigure, which happens with every z2m update (i think?)

**Comment by robertalexa** [comment]
If anything, i wonder if maybe we should expose the min and max as attributes and then people can set them "easier", and also providing description in z2m rather than having to find documentation?

**Comment by sjorge** [comment]
I'll close the PR, I guess we can indeed expose the min/max but I don't think we can update the expose data automatically to match. So that's probably going to cause more problems and confusion.

**Comment by robertalexa** [comment]
We can read the values of those attributes though, so adding there here

image

Should automatically populate the Frontend and things would be nice and simple?

**Pull request closed without merging**
