### PR TITLE
Moes Star ring smart dimmer switch 2 gangs

### PR DESCRIPTION
**Pull request by kirovilya**
https://moeshouse.com/products/moes-star-ring-zigbee-smart-dimmer-switch-for-light-dimming-work-with-alexa-google-home-dimmable-1-3gang

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by martindell** [comment]
On / off basically working but dimmer function seems a bit unpredictable.  How can I help you troubleshoot?

**Comment by demcas** [comment]
Just tested the it on EDGE and the 2gang dimmer switch is working but the 1gang and 3 gang is still unsupported

**Comment by demcas** [comment]
On the non dimmable version you have other options such as power-on behavior and balight mode.  But on the dimmer version access on edge it does have these same options. 
image
image

**Comment by demcas** [comment]
@Koenkk 
Hi, I am new to Github so apologise in advance if this is a rookie question.  I tested the Moes ZS-SR-EUD-2 which now connected under EDGE, but the other variants Moes ZS-SR-EUD-1 and Moes ZS-SR-EUD-3 still don't work.  

I also found that the above models are missing the backlight_mode.  This is available on the equivalent non dimmable models ZS-EUB_1gang, ZS-EUB_2gang, ZS-EUB_3gang.

**Comment by Koenkk** [comment]
Please provide the data/database.db entries of ZS-SR-EUD-1 and ZS-SR-EUD-3

**Comment by demcas** [comment]
> Please provide the data/database.db entries of ZS-SR-EUD-1 and ZS-SR-EUD-3

https://github.com/Koenkk/zigbee2mqtt/issues/18650

Thank for looking into this.  I raised this in the issue 18650. See below

3 Gang Dimmer Switch
{"id":22,"type":"Router","ieeeAddr":"0xa4c13850205a2891","nwkAddr":29034,"manufId":4417,"manufName":"_TZE204_1v1dxkck","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE204_1v1dxkck","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1692679020965,"defaultSendRequestWhen":"immediate"}

2 Gang Dimmer Switch
{"id":23,"type":"Router","ieeeAddr":"0xa4c1387689c3638a","nwkAddr":56774,"manufId":4417,"manufName":"_TZE204_zenj4lxv","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE204_zenj4lxv","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1692679781242,"defaultSendRequestWhen":"immediate"}

1 Gang Dimmer Switch
{"id":24,"type":"Router","ieeeAddr":"0xa4c1383c626d9231","nwkAddr":38689,"manufId":4417,"manufName":"_TZE204_hlx9tnzb","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE204_hlx9tnzb","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1692680034957,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
@demcas thanks, added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by demcas** [comment]
> @demcas thanks, added!
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

@Koenkk 
I have been testing and the above update across the ZS-SR-EUD 1,2,3 gang switches and it operates on/off and is dimmable. 
 One function which doesn't seem to appear on MQTT is the Backlight Mode available on the non Dimmable version of the same switch ZS-EUB.

Non Dimmable ZS-EUB:
https://www.zigbee2mqtt.io/devices/ZS-EUB_1gang.html & https://www.zigbee2mqtt.io/devices/TS0012.html
Backlight mode (enum)
Mode of the backlight. Value can be found in the published state on the backlight_mode property. To read (/get) the value publish a message to topic zigbee2mqtt/FRIENDLY_NAME/get with payload {"backlight_mode": ""}. To write (/set) a value publish a message to topic zigbee2mqtt/FRIENDLY_NAME/set with payload {"backlight_mode": NEW_VALUE}. The possible values are: off, normal, inverted

Is this something that can be built in?

Lastly, I would like to contribute by donating funds to the MQTT team to help support this community.  Do you have a link?

**Comment by demcas** [comment]
image

**Comment by Koenkk** [comment]
> Non Dimmable ZS-EUB

This device is quite different, it uses a standard Zigbee api while these devices use the TuYa api.

@kirovilya do you know if these devices support backlight mode with the original TuYa gateway? if yes, what is the datapoint?

Regarding donations, click the "sponsor" button here: https://github.com/koenkk/zigbee2mqtt, thanks in advance!

**Comment by demcas** [comment]
> > Non Dimmable ZS-EUB
> 
> This device is quite different, it uses a standard Zigbee api while these devices use the TuYa api.
> 
> @kirovilya do you know if these devices support backlight mode with the original TuYa gateway? if yes, what is the datapoint?
> 
> Regarding donations, click the "sponsor" button here: https://github.com/koenkk/zigbee2mqtt, thanks in advance!

@Koenkk 
Yea they do support backlight mode.  They are are the exact same switch.  This is all new to me as I learn home assistant and Mqtt.

Do you need the data point from the tuya gateway or MQTT?

I found this in the DB file in MQTT, it from the two non dimmable light switches from the Moes light switches I’ve been testing. 

{"id":8,"type":"EndDevice","ieeeAddr":"0xa4c1381a6b560e05","nwkAddr":6775,"manufId":4417,"manufName":"_TZ3000_18ejxno0","powerSource":"Mains (single phase)","modelId":"TS0012","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0011","65506":55,"65508":0,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_18ejxno0","zclVersion":3,"appVersion":80,"modelId":"TS0012","powerSource":3}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":2,"moesStartUpOnOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe1677c2","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe1677c2","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1794938824},"lastSeen":1694410567918,"defaultSendRequestWhen":"immediate"}

{"id":9,"type":"EndDevice","ieeeAddr":"0xa4c138b2e8107806","nwkAddr":37083,"manufId":4417,"manufName":"_TZ3000_hhiodade","powerSource":"Mains (single phase)","modelId":"TS0011","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"genOnOff":{"attributes":{"onOff":1,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":2,"moesStartUpOnOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe1677c2","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-999208499},"lastSeen":1694694120624,"defaultSendRequestWhen":"immediate"}

**Comment by kirovilya** [comment]
@Koenkk I can confirm that there is backlight control and a status saving setting.
DP 21 - Indicator Status
DP 14 - Power-on Status
image
I forgot about them when I added support :(

**Comment by Koenkk** [comment]
would you mind to add them?

**Comment by kirovilya** [comment]
difficult decision: allocate a separate description for this device or add to the existing one? I’m not sure that the existing ones have these capabilities.

**Comment by Koenkk** [comment]
Let's add it to existing one.

**Comment by kirovilya** [comment]
done https://github.com/Koenkk/zigbee-herdsman-converters/pull/6172

I can't check how this will work for Moes Star Ring 1 and 3 gang dimmers

**Comment by demcas** [comment]
> done #6172
> 
> I can't check how this will work for Moes Star Ring 1 and 3 gang dimmers

Thank you.  I just updated edge and paired the 1, 2 & 3 Gang Moes Star Ring dimmers switches.  Unfortunately the backlight option isn't appearing. Has the change been pushed through to the latest version of Edge?

I also found that on the non dimmable version of the Ring Star switch has backlight Off | Normal | Inverted 
https://www.zigbee2mqtt.io/devices/ZS-EUB_1gang.html#moes-zs-eub_1gang

image

Backlight mode (enum)
Mode of the backlight. Value can be found in the published state on the backlight_mode property. To read (/get) the value publish a message to topic zigbee2mqtt/FRIENDLY_NAME/get with payload {"backlight_mode": ""}. To write (/set) a value publish a message to topic zigbee2mqtt/FRIENDLY_NAME/set with payload {"backlight_mode": NEW_VALUE}. The possible values are: off, normal, inverted

**Comment by kirovilya** [comment]
@demcas sorry, indeed, there is one more state for backlight_mode ... I’ll add it a little later

**Comment by Koenkk** [comment]
@demcas check the  latest edge addon in 3 hours from now. I just bumped the version.

**Comment by kvn1351** [comment]
> @demcas check the latest edge addon in 3 hours from now. I just bumped the version.

I'm on the latest Edge release and the 2 gang switch only supports on/off. Anything specific I could provide to help?

**Pull request merged**
