### PR TITLE
Merged into a single entity

### PR DESCRIPTION
**Pull request by vitalybibikov**
Deleted the previous PR, merged into a single item

### CODE REVIEW

**Comment by vitalybibikov** [comment]
I don't know how to fix this linter issue or how to understand what the issue is

When i run all the commands,

```
npm install
npm run eslint -- --fix
npm run pretty:write
npm run build
npm test

```
 I am getting 381 files being changes after

`npm run eslint -- --fix`

is being executed. 

image

Is it normal?

**Comment by vitalybibikov** [comment]
Though all commands are executed successfully

image

**Comment by vitalybibikov** [comment]
Ah, nvm, that's the magic of the typescript I guess and my absence of knowledge of how it works now.

Thanks

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
