### PR TITLE
set state open close are not invert for cover

### PR DESCRIPTION
**Pull request by tomamplius**

### CODE REVIEW

**Comment by tomamplius** [comment]
link to #4529

**Comment by Koenkk** [comment]
I misread https://github.com/Koenkk/zigbee2mqtt/issues/13528 a bit. The goal of invert cover is to invert the position, e.g. to make position 100 or 0 be the closed position. What I understand now is that an open command could possibly close the cover, what is the use case for this?

**Comment by tomamplius** [comment]
Yes, SR-ZG9080A close the cover when open is send like bticino_4027C_cover_state

**Comment by tomamplius** [comment]
I think it why i have make this : https://github.com/Koenkk/zigbee-herdsman-converters/pull/2505/commits/273925162c4a9d275400d6790f4756f30e67dbc1, remove because maybe not needed

**Comment by tomamplius** [comment]
error on wiring :-p sorry

**Pull request closed without merging**
