### PR TITLE
add new device ZS-SR-EUC

### PR DESCRIPTION
**Pull request by tdelsupexhe**

### CODE REVIEW

**Comment by Koenkk** [comment]
Does it also work with the `TS0601_cover_5` definition from `tuya.ts`/

**Comment by tdelsupexhe** [comment]
I just tried and couldn't get it to work

**Comment by Koenkk** [comment]
What doesn't work?

**Comment by tdelsupexhe** [comment]
I'll try to replace the definition from the one in TS0601_cover_5 and nothing work

**Comment by Koenkk** [comment]
The should be the same:

https://github.com/Koenkk/zigbee-herdsman-converters/blob/aebfa997703e22019e460e22bc0a6693186a63a9/src/devices/tuya.ts#L5927

**Comment by tdelsupexhe** [comment]
Sorry I misunderstood what you have said. If I replace this line only, it works perfectly.

**Comment by tdelsupexhe** [comment]
Done

**Comment by Koenkk** [comment]
I mean removing it from `moes.ts` and merging it with `TS0601_cover_5`

**Comment by tdelsupexhe** [comment]
Ok, I can do this but with the TS0601_cover_5 definition the backlight mode and the child lock does not work. I do not have a TuyaDatapoint 7 and 103 but I have a 14.

**Comment by Koenkk** [comment]
I see, then this is fine!

**Pull request merged**
