### PR TITLE
Add device: IKEA PARASOLL door/windows sensor E2013

### PR DESCRIPTION
**Pull request by Noettore**
I was able to get an IKEA PARASOLL door/window sensor before being released.

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by rjblake** [comment]
See you've added e.tamper to the sensor, but I'm not sure there is any tamper sensor for this. The IKEA documentation and press release does not mention this ability.

**Comment by Noettore** [comment]
Hi @rjblake,
you're right, my bad.
I'll create a new PR removing the e.tamper and also the e.battery_low, as I don't believe that exists either.

Thanks,
Ettore

**Comment by ArdaXi** [comment]
@Noettore If you're going to be creating a new PR, you might consider adding the standard battery converter too, since it does seem to expose a standard `genPowerCfg` cluster. That way you can still see the battery percentage.

**Comment by rufferson** [comment]
And ota
```
{
    zigbeeModel: ['PARASOLL Door/Window Sensor'],
    model: 'E2013',
    vendor: 'IKEA',
    description: 'PARASOLL Door/Window Sensor',
    fromZigbee: [fz.ias_contact_alarm_1, fz.battery],
    toZigbee: [],
    ota: ota.tradfri,
    exposes: [e.battery(), e.contact()],
}
```

**Comment by rjblake** [comment]
> @Noettore If you're going to be creating a new PR, you might consider adding the standard battery converter too, since it does seem to expose a standard `genPowerCfg` cluster. That way you can still see the battery percentage.

Seems like there is some battery info - found this post [https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7417#issuecomment-1845192248](url)

**Pull request merged**
