### PR TITLE
Refactor Sinope.js (Cosmetics)

### PR DESCRIPTION
**Pull request by MattL0**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by onixx** [comment]
I believe since this change, I am getting these errors upon startup of zigbee2mqtt:
 2023-01-01 12:57:08Failed to configure 'Thermostat Living Room', attempt 2 (Error: ConfigureReporting 0x500b914000020255/1 hvacThermostat([{"attribute":"systemMode","minimumReportInterval":10,"maximumReportInterval":3600,"reportableChange":null}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:694:22) at Object.thermostatSystemMode (/app/data/jp/zigbee-herdsman-converters/lib/reporting.js:135:9) at Object.configure (/app/data/jp/zigbee-herdsman-converters/devices/sinope.js:804:13) at Configure.configure (/app/lib/extension/configure.ts:117:13))

**Comment by Koenkk** [comment]
@onixx what is the model of your device?

**Comment by onixx** [comment]
@Koenkk The error above comes from all 4 of my TH1400ZB.

I also noticed this another error coming from my TH1300ZB;
Failed to configure 'Thermostat Upstairs Bathroom', attempt 1 (Error: ConfigureReporting 0x500b914000020790/1 manuSpecificSinope([{"attribute":"floorLimitStatus","minimumReportInterval":1,"maximumReportInterval":3600,"reportableChange":1}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4508,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'INVALID_DATA_TYPE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:694:22) at Object.configure (/app/data/jp/zigbee-herdsman-converters/devices/sinope.js:715:13) at Configure.configure (/app/lib/extension/configure.ts:117:13))

**Comment by MattL0** [comment]
> @Koenkk The error above comes from all 4 of my TH1400ZB.
> 
> I also noticed this another error coming from my TH1300ZB; Failed to configure 'Thermostat Upstairs Bathroom', attempt 1 (Error: ConfigureReporting 0x500b914000020790/1 manuSpecificSinope([{"attribute":"floorLimitStatus","minimumReportInterval":1,"maximumReportInterval":3600,"reportableChange":1}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4508,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'INVALID_DATA_TYPE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:694:22) at Object.configure (/app/data/jp/zigbee-herdsman-converters/devices/sinope.js:715:13) at Configure.configure (/app/lib/extension/configure.ts:117:13))

Was systemMode reportable by your thermostat before?

**Comment by onixx** [comment]
I don’t think so

**Comment by MattL0** [comment]
I guess this is the issue https://github.com/Koenkk/zigbee-herdsman/commit/e7087028642a2f76b05495648f7d4d131f5ab27d

**Comment by onixx** [comment]
Thanks for the PR. I believe for the 1400ZB we just need a try/catch like implemented for the 1123ZB. I iust dont know if any of these really support reporting of systemMode so don’t know if we really need it at all?

**Comment by MattL0** [comment]
Yes done the pr for the th1400zb .I didn’t really work on this one in particular but will check for any inconsistencies, this week. 

I think it depend on firmware. I updated all my th1124zb to the very latest and the mode + power(watt) became reportable. And after I shipped back the Sinope cloud module to amazon. 

It would be great to be able to have a different config for each firmware version.But that would make a big file lol.

**Comment by MattL0** [comment]
@Koenkk I think it would be great if you can merge theses two pr to the stable release. Or this type of issue might comme back this month, and configure will fail for a lot a people .

**Comment by Koenkk** [comment]
@MattL0 I will make a hotfix release in the coming days.

**Comment by MattL0** [comment]
Thank you

**Pull request merged**
