### PR TITLE
add some private function in sonoff devices

### PR DESCRIPTION
**Pull request by liangjia2019**
1.SNZB-03P add battery,occupancy_ult_timeout
2.SNZB-04P add tamper
3.SNZB-06P add occupancy_ult_timeout,occupancy_ult_sensitivity, illumination.

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you use the `modernExtend` instead? This replaces `fromZigbee`/`toZigbee` and `exposes, example: https://github.com/Koenkk/zigbee-herdsman-converters/blob/77da13d3db98de610ccc16d627cbbcf11b88ab7e/src/devices/xiaomi.ts#L1028

**Comment by liangjia2019** [comment]
> Could you use the `modernExtend` instead? This replaces `fromZigbee`/`toZigbee` and `exposes, example:
> 
> https://github.com/Koenkk/zigbee-herdsman-converters/blob/77da13d3db98de610ccc16d627cbbcf11b88ab7e/src/devices/xiaomi.ts#L1028
Of course, if you wish me to do so, I will follow it myself

**Comment by liangjia2019** [comment]
> I will follow it myself

Also, I would like to know when the next version of Zigbee2mqtt will be planned

**Comment by Koenkk** [comment]
Great, the next release is on 1 January.

**Comment by Koenkk** [comment]
> If you use get method, there will be a read button on the front-end, but most of the time it will not succeed because the device is in sleep mode

This is the case for all end devices, document this in the `description` instead.

**Pull request closed without merging**
