### PR TITLE
Updated Sengled defininition to include E13 a21

### PR DESCRIPTION
**Pull request by clockbrain**
Works as an external converter but I haven't been able to test it within the sengled.ts file because of compile issues with zigbee-herdsman-converters in my local environment. Obviously there is something amiss with my setup. Here is the issue I've been having:
[https://github.com/Koenkk/zigbee2mqtt/discussions/21544#discussioncomment-10735454
](https://github.com/Koenkk/zigbee2mqtt/discussions/21544#discussioncomment-10735454
)

Also note that configuration for electrical metering reporting needs to be adjusted manually via the UI due I suspect to this issue:
[https://github.com/Koenkk/zigbee-herdsman-converters/issues/7917](https://github.com/Koenkk/zigbee-herdsman-converters/issues/7917)

### CODE REVIEW

**Comment by Koenkk** [comment]
> Also note that configuration for electrical metering reporting needs to be adjusted manually via the UI due I suspect to this issue:

With the current definition, it does not update any power measurements? If yes:
- Could you provide the data/database.db entry of this device
- What reporting values do you use when manually set it up after which it works?

**Comment by clockbrain** [comment]
Using latest dev, here is the database.db entry for the e13-a21 after joining using the external converter.
```
{"id":2,"type":"EndDevice","ieeeAddr":"0xb0ce18140319e015","nwkAddr":16959,"manufId":4448,"manufName":"sengled","powerSource":"Mains (single phase)","modelId":"E13-A21","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,1794,2821,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"E13-A21","manufacturerName":"sengled","powerSource":1,"zclVersion":1,"appVersion":1,"stackVersion":0,"hwVersion":2}},"seMetering":{"attributes":{"divisor":10000,"multiplier":1,"instantaneousDemand":123,"currentSummDelivered":10}},"manuSpecificSengledMotionSensor":{"attributes":{"motionStatus":0}}},"binds":[{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00212effff04db7b","endpointID":1},{"cluster":64513,"type":"endpoint","deviceIeeeAddress":"0x00212effff04db7b","endpointID":1}],"configuredReportings":[{"cluster":1794,"attrId":1024,"minRepIntval":10,"maxRepIntval":65000,"repChange":50000},{"cluster":1794,"attrId":0,"minRepIntval":10,"maxRepIntval":65000,"repChange":1000},{"cluster":64513,"attrId":3,"minRepIntval":1,"maxRepIntval":65000,"repChange":1,"manufacturerCode":4448}],"meta":{}}},"appVersion":1,"stackVersion":0,"hwVersion":2,"zclVersion":1,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1727822901158}

```

I've mostly tested with instantaneous demand as that is easiest to see the changes.
So, the values from the zigbee2mqtt configuration on join with the e13-a21 external converter are:
Min: 10, Max: 65000, Change: 50000. Doesn't report but will update the values on manual refresh

For reference the values configured by the Sengled hub for instantaneous demand are:
Min: 3, Max: 300, Change: 10

I tested a few permutations and the one that really made it work was setting the Min to 3. Adjusting the Max or Change values didn't have any effect that I could see but the bulb would not report to zigbee2mqtt unless I lowered the Min to 3. I don't understand as I thought that Min just limited frequency of reporting but it seems to be a magic number with this device. I even tested it with a value of 4 for Min and it refused to report but changing it back to 3 got it reporting again.

For completeness the Sengled hub reporting configuration for current summation delivered is:
Min: 3, Max: 1200, Change: 100

**Comment by Koenkk** [comment]
Then I guess we should extend https://github.com/Koenkk/zigbee-herdsman-converters/blob/ff9ad52aa88c7b275599ad568e66af9720aa5c0a/src/lib/modernExtend.ts#L1617 to also allow passing the `min` value.

**Comment by Koenkk** [comment]
Thanks!

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `E13-A21.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by clockbrain** [comment]
> Thanks!
> 
> Could you also submit a picture for the docs? This can be done by:
> 
> 1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
> 2. Go to the `public/images/devices` directory, _Add file_ -> _Upload files_
> 3. Upload the files and press _Commit changes_
> 4. Press _Contribute_ -> _Open pull request_ -> update title/description -> _Create pull request_
> 
> Make sure that:
> 
> * The filename is `E13-A21.png`
> * The size is 512x512
> * The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

Already merged https://github.com/Koenkk/zigbee2mqtt.io/pull/3048

**Pull request merged**
