### PR TITLE
Small improvements for Legrand Devices

### PR DESCRIPTION
**Pull request by FabianMangold**
This PR brings:
- [feat(update)!: Improved Legrand HA integration]
- [feat(add): Enabled OTA for all remaining Legrand devices]
- [fix(ignore): Code-Dedup: Legrand LED handling]

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by jafar-atili** [comment]
@FabianMangold, Thank you for your work!
Do you know if possible to expose power consumption from K4411C and K4003C to Z2M?

**Comment by FabianMangold** [comment]
Hi @jafar-atili ,

Could you please open another issue for that please ?
Since i don't have any BTicino devices, i cannot test this on my own really, sorry for that.
You may want to use the new "Automatic generator of definitions" as a starting point, as described [here](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition)

**Comment by jafar-atili** [comment]
Thanks @FabianMangold!
I submitted [this issue](https://github.com/Koenkk/zigbee2mqtt/issues/22213), I hope someone can guide me roughly through the process to make it happen and I'll do it.

**Pull request merged**
