### PR TITLE
Update xiaomi.js

### PR DESCRIPTION
**Pull request by JanLue4**
Add temperature expose for Xiaomi MCCGQ14LM

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by nukusinji** [comment]
temperature is not working. the value is only '25'.

**Comment by FIetch** [comment]
same here. All 4 sensors show 25 degrees

**Comment by JustAnyGitHubUser** [comment]
Same here. All temperatures show a value of 25degC. To get this to work, is the new firmware a must have? It does mention a firmware for Xiaomi E1 devices? [link](https://github.com/Koenkk/Z-Stack-firmware/releases/tag/Z-Stack_Home_3.x.0_20211217)

**Comment by JanLue4** [comment]
I have created a pull request to undo my changes. the temperature always shows 25 degree C too.

**Pull request merged**
