### PR TITLE
feat: add support for IKEA Home Smart OTA firmware updates

### PR DESCRIPTION
**Pull request by IceHamster**
- Introduced `homesmartOta()` for managing IKEA Home Smart firmware updates from a new endpoint.
- Updated INSPELNING smart plug configuration to use `homesmartOta()` for OTA.
- Added checksum support for SHA-3 256 in OTA logic.
- Created a new module for handling IKEA Home Smart OTA logic (`homesmart.ts`), including certificate handling and secure download.
- Updated documentation with IKEA Home Smart OTA URL and release notes location.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks for the PR! I was thinking to combine all IKEA firmwares into the [zigbee-OTA](https://github.com/Koenkk/zigbee-OTA/pull/562) repo as suggested here, this has some benefits over a custom OTA provider:
- We can use `ota.zigbeeOTA` for all IKEA devices (no need to figure out for every device where the OTA is)
- No separate OTA provider needed (less code, no certificate handling which might break in the future)
- In case IKEA pushes a bad OTA (which happened in the past), we can quickly remove it

The way I see this is that zigbee-OTA has a GitHub action which runs e.g. daily, combines OTAs from both the old an new feed and automatically creates a PR with new OTAs. What do you think?

**Comment by IceHamster** [comment]
> Thanks for the PR! I was thinking to combine all IKEA firmwares into the [zigbee-OTA](https://github.com/Koenkk/zigbee-OTA/pull/562) repo as suggested here, this has some benefits over a custom OTA provider:
> 
>     * We can use `ota.zigbeeOTA` for all IKEA devices (no need to figure out for every device where the OTA is)
> 
>     * No separate OTA provider needed (less code, no certificate handling which might break in the future)
> 
>     * In case IKEA pushes a bad OTA (which happened in the past), we can quickly remove it
> 
> 
> The way I see this is that zigbee-OTA has a GitHub action which runs e.g. daily, combines OTAs from both the old an new feed and automatically creates a PR with new OTAs. What do you think?

That sounds like a great idea! We could either 
- Create a list of IKEA devices for which we want to fetch the firmware, and then run a scheduled action.
- Fetch all OTA firmware on the IKEA feeds, and the replace newer ones

It seems that some OTA firmwares are published on both the old and new feeds, sometimes with different names, so we might need to check the headers of the OTA images before replacing any existing firmware.

 The only potential issue I see is the legal aspect: are we allowed to host third-party firmware on GitHub?

**Comment by Koenkk** [comment]
> The only potential issue I see is the legal aspect: are we allowed to host third-party firmware on GitHub?

Zigbee-OTA already hosts firmwares for various vendors for quite some years, I don't expect any problems.

**Comment by Nerivec** [comment]
Implemented in https://github.com/Koenkk/zigbee-OTA/pull/581 + https://github.com/Koenkk/zigbee-herdsman-converters/pull/8273 for Z2M 2.0.0 😉

@IceHamster @jamesonuk I don't have any Ikea device... Can you confirm https://static.homesmart.ikea.com/releaseNotes/ has the release notes for the new URL as opposed to https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html for the old one? That new one seemed to be mostly focused on the Hub updates (can't see any device notes since mid-2023)?
I'll change the URL for release notes in the zigbee-OTA repo accordingly.

**Comment by IceHamster** [comment]
> Implemented in [Koenkk/zigbee-OTA#581](https://github.com/Koenkk/zigbee-OTA/pull/581) + #8273 for Z2M 2.0.0 😉
> 
> @IceHamster @jamesonuk I don't have any Ikea device... Can you confirm https://static.homesmart.ikea.com/releaseNotes/ has the release notes for the new URL as opposed to https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html for the old one? That new one seemed to be mostly focused on the Hub updates (can't see any device notes since mid-2023)? I'll change the URL for release notes in the zigbee-OTA repo accordingly.

@Nerivec I am not completly sure. I have seen the same thing, that IKEA has not updated the new URL. I do not find the new IKEA sockets devices in the new or the old release notes pages.

**Comment by Koenkk** [comment]
With the OTA refactor that landed in the dev branch, I think this can be closed now.

**Pull request closed without merging**
