### PR TITLE
Add support for 929003055901_01

### PR DESCRIPTION
**Pull request by brhahlen**
929003055901_01 is a Hue white ambiance bathroom ceiling light Adore with Bluetooth

### CODE REVIEW

**Comment by Koenkk** [comment]
Please remove draft state once this is ready for merge.

**Comment by brhahlen** [comment]
Definitely, seems to be working fine

**Comment by Koenkk** [comment]
Thanks!

**Comment by brhahlen** [comment]
My pleasure :-)
Glad I'm able to contribute a little bit here!

**Pull request merged**
