### PR TITLE
feat(added new device): added Philips Hue Adore Bathroom Mirror

### PR DESCRIPTION
**Pull request by pree**
Added support for the Hue Adore Bathroom Mirror.
https://www.philips-hue.com/en-gb/p/hue-white-ambiance-adore-bathroom-mirror/3418631P6

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you share your data/database.db entry of this device?

**Comment by pree** [comment]
> Could you share your data/database.db entry of this device?

Sure!
```json
{
	"id": 33,
	"type": "Router",
	"ieeeAddr": "0x001788010920c94a",
	"nwkAddr": 9571,
	"manufId": 4107,
	"manufName": "Philips",
	"powerSource": "Mains (single phase)",
	"modelId": "3418631P6",
	"epList": [11, 242],
	"endpoints": {
		"11": {
			"profId": 260,
			"epId": 11,
			"devId": 268,
			"inClusterList": [0, 3, 4, 5, 6, 8, 4096, 768],
			"outClusterList": [25],
			"clusters": {
				"genBasic": {
					"attributes": {
						"modelId": "3418631P6",
						"manufacturerName": "Philips",
						"powerSource": 1,
						"zclVersion": 2,
						"appVersion": 2,
						"stackVersion": 1,
						"hwVersion": 0,
						"dateCode": "20190529",
						"swBuildId": "1.56.7_r29434"
					}
				},
				"genOnOff": {
					"attributes": {
						"onOff": 0
					}
				},
				"genLevelCtrl": {
					"attributes": {
						"currentLevel": 254
					}
				}
			},
			"binds": [{
				"cluster": 6,
				"type": "endpoint",
				"deviceIeeeAddress": "0x00124b0021a8e720",
				"endpointID": 1
			}, {
				"cluster": 8,
				"type": "endpoint",
				"deviceIeeeAddress": "0x00124b0021a8e720",
				"endpointID": 1
			}, {
				"cluster": 768,
				"type": "endpoint",
				"deviceIeeeAddress": "0x00124b0021a8e720",
				"endpointID": 1
			}],
			"configuredReportings": [{
				"cluster": 6,
				"attrId": 0,
				"minRepIntval": 0,
				"maxRepIntval": 300,
				"repChange": 0
			}, {
				"cluster": 8,
				"attrId": 0,
				"minRepIntval": 3,
				"maxRepIntval": 300,
				"repChange": 1
			}],
			"meta": {}
		},
		"242": {
			"profId": 41440,
			"epId": 242,
			"devId": 97,
			"inClusterList": [],
			"outClusterList": [33],
			"clusters": {},
			"binds": [],
			"configuredReportings": [],
			"meta": {}
		}
	},
	"appVersion": 2,
	"stackVersion": 1,
	"hwVersion": 0,
	"dateCode": "20190529",
	"swBuildId": "1.56.7_r29434",
	"zclVersion": 2,
	"interviewCompleted": true,
	"meta": {
		"reporting": 1
	},
	"lastSeen": 1617212302998
}
```

**Comment by Koenkk** [comment]
Thanks, I cannot find it in your database.db entry but what I need is the minimum and maximum color temp (https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#31-retrieving-color-temperature-range-only-required-for-lights-which-support-color-temperature). This has been added in 1.18.2 so what you have to do is:
- upgrade to 1.18.2
- reapply your changes to devices.js
- follow instructions in the link

**Comment by pree** [comment]
`Zigbee2MQTT:info  2021-04-05 17:53:56: Read result of 'lightingColorCtrl': {"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}`

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
