### PR TITLE
added LED controller YSRSAI ZB-CL01

### PR DESCRIPTION
**Pull request by krencl**

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide a link (url) of this device?

**Comment by krencl** [comment]
> Can you provide a link (url) of this device?
> 
> Note to self: after this merge [Koenkk/zigbee2mqtt.io#337](https://github.com/Koenkk/zigbee2mqtt.io/pull/337)

https://www.aliexpress.com/item/10000038540202.html
https://ysrsai.aliexpress.com/store/5431355

**Comment by krencl** [comment]
I added support for hass.io too:
https://github.com/Koenkk/zigbee2mqtt/pull/3876

**Comment by Koenkk** [comment]
The one you linked is Wifi, I guess it's this one: https://www.aliexpress.com/item/10000201621618.html?gps-id=pcStoreJustForYou&scm=1007.23125.137358.0&scm_id=1007.23125.137358.0&scm-url=1007.23125.137358.0&pvid=e4474202-c066-479f-944b-d7ea5f90647a&spm=a2g0o.store_home.smartJustForYou_599234666.2 ?

Also which version is this: RGBW, RGB or RGB + CCT?

**Comment by krencl** [comment]
Sure, it is zigbee version, sorry. This one is RGB + CCT.

**Comment by Koenkk** [comment]
Thanks!

**Comment by Koenkk** [comment]
@krencl can you provide the data/database.db entry of this device? (for https://github.com/Koenkk/zigbee2mqtt/issues/4944)

**Comment by krencl** [comment]
@Koenkk Sure:
`{"id":6,"type":"Router","ieeeAddr":"0x00124b001cd6a473","nwkAddr":39018,"manufId":0,"manufName":"YSRSAI","powerSource":"Mains (single phase)","modelId":"ZB-CL01","epList":[1,13],"endpoints":{"1":{"profId":49246,"epId":1,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"ZB-CL01","manufacturerName":"YSRSAI","powerSource":1,"zclVersion":1,"appVersion":6,"stackVersion":2,"hwVersion":1,"dateCode":"20200507","swBuildId":"1.0.6"}}},"binds":[],"meta":{}},"13":{"profId":49246,"epId":13,"devId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[],"meta":{}}},"appVersion":6,"stackVersion":2,"hwVersion":1,"dateCode":"20200507","swBuildId":"1.0.6","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1608617396877}`

**Pull request merged**
