### PR TITLE
Update fromZigbee.js

### PR DESCRIPTION
**Pull request by han-alink**
I would like to have a more general purpose way to describe the presentValue attribute from the genBinaryInput cluster. The current descriptions are all bound to a manufacturer. So instead of a terncy_contact, I would like to have a true_false_input.

### CODE REVIEW

**Comment by Koenkk** [comment]
This converter is not used, why add it?

**Comment by han-alink** [comment]
Hi,Not yet, but I will add my diy devices soon. It's my frist pull request and wanted to see how the mechanism works.
-------- Oorspronkelijk bericht --------Van: Koen Kanters ***@***.***> Datum: 20-09-2021  13:00  (GMT+00:00) Aan: Koenkk/zigbee-herdsman-converters ***@***.***> Cc: han-alink ***@***.***>, Author ***@***.***> Onderwerp: Re: [Koenkk/zigbee-herdsman-converters] Update fromZigbee.js (#3048) 
This converter is not used, why add it?

**Comment by han-alink** [comment]
> This converter is not used, why add it?

It's now used after the device update !

**Comment by han-alink** [comment]
Added the device updzte

**Comment by Koenkk** [comment]
Can you provide a link where these devices can be bought?

**Comment by han-alink** [comment]
Not for sale; my own devices

**Comment by Koenkk** [comment]
Are there any manuals on how to create these devices? This is a requirement for devices to be supported, if not use the external converters instead.

**Comment by han-alink** [comment]
Hi No manuals. The hardware schematics are available. The devices conform to the home automation profile specification as defined by the zigbee alliance. I'm wondering why this zigbee alliance document and the devices definitions are not used instead of all the manufacturer dependent  definitions. The device Id's would , in my opinion, be a much better entry in the device list.It's a pity, and I'm disappointed, that my devices can not be part of the standard device list.Han
-------- Oorspronkelijk bericht --------Van: Koen Kanters ***@***.***> Datum: 27-09-2021  19:39  (GMT+01:00) Aan: Koenkk/zigbee-herdsman-converters ***@***.***> Cc: han-alink ***@***.***>, State change ***@***.***> Onderwerp: Re: [Koenkk/zigbee-herdsman-converters] Update fromZigbee.js (#3048) 
Are there any manuals on how to create these devices? This is a requirement for devices to be supported, if not use the external converters instead.

**Comment by Koenkk** [comment]
I see, but I hope you understand that it does not make sense to make a device unsupported while only 1 user can use it. External converters provide a great alternative for this, will close this.

**Comment by han-alink** [comment]
Okay,I can have an external device file in my own file system. Is it also possible to have a local to zigbee and from zigbee file?Han
-------- Oorspronkelijk bericht --------Van: Koen Kanters ***@***.***> Datum: 29-09-2021  21:29  (GMT+01:00) Aan: Koenkk/zigbee-herdsman-converters ***@***.***> Cc: han-alink ***@***.***>, State change ***@***.***> Onderwerp: Re: [Koenkk/zigbee-herdsman-converters] Update fromZigbee.js (#3048) 
I see, but I hope you understand that it does not make sense to make a device unsupported while only 1 user can use it. External converters provide a great alternative for this, will close this.

**Comment by Koenkk** [comment]
> local to zigbee and from zigbee file

Other files are not possible, you can embed those converters in the external converter file.

**Pull request closed without merging**
