### PR TITLE
fix(detect): Detect  as MiBoxer E2-ZR

### PR DESCRIPTION
**Pull request by ppanagiotis**
Fixes https://github.com/Koenkk/zigbee2mqtt/issues/21185

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by andrew01144** [comment]
Hi - I have this problem, and have not succeeded in fixing it.
I my E2-ZR successfully joined Z2M, but it appeared as Tuya TS0502B. (Z2M rev was ~01-Jun, that's before the fix).
I upgraded Z2M; herdsman now shows as 19.62.0.
I removed the device. Re-joined the device, but it still appears as Tuya TS0502B.
Am I missing a step?
Many thanks!

Also - setting 'transition' seems to have no affect on the actual transition.

**Comment by pvyleta** [comment]
@ppanagiotis Are you sure this is correct? I can see you added the `E2-ZR` into the section of RGB+CCT lights, while in fact the `E2-ZR` is just Dual-White controller, similar to the Miboxer FUT035.

In fact, `E2-ZR` reports itself as `TS0502B` and not as `TS0505B` as your PR assumes. 

Is there any chance that you wanted to add the `E3-ZR` instead of the `E2-ZR` ?

**Comment by ppanagiotis** [comment]
> @ppanagiotis Are you sure this is correct? I can see you added the `E2-ZR` into the section of RGB+CCT lights, while in fact the `E2-ZR` is just Dual-White controller, similar to the Miboxer FUT035.
> 
> In fact, `E2-ZR` reports itself as `TS0502B` and not as `TS0505B` as your PR assumes.
> 
> Is there any chance that you wanted to add the `E3-ZR` instead of the `E2-ZR` ?

I'm not sure. In the past few months, I didn't have the opportunity to test if it works properly. Feel free to modify or adjust it as needed.

**Comment by pvyleta** [comment]
@ppanagiotis Thanks for the clarification! I therefore can let you know that my hunch was correct, and once I moved the definition of the device, it now works like a charm for me and for others. Thanks a lot for the initial contribution, I would not be able to locate the right place without your previous PR.

**Pull request merged**
