### PR TITLE
Fix #2552 Ubisys configuration throws UNSUPPORTED_ATTRIBUTE

### LINKED ISSUE #2552: Ubisys C4 UNSUPPORTED_ATTRIBUTE on writing configure_device_setup
```
Zigbee2MQTT:debug 2021-05-05 22:01:00: Received MQTT message on 'zigbee2mqtt/livingroom/light/switch2/set' with data '{"configure_device_setup":{"input_action_templates":[{"type":"dimmer_single"},{"type":"dimmer_single"}]}}'
Zigbee2MQTT:debug 2021-05-05 22:01:00: Publishing 'set' 'configure_device_setup' to 'livingroom/light/switch2'
Zigbee2MQTT:warn  2021-05-05 22:01:00: ubisys: Using input(s) 0 and endpoint 1 for 'dimmer_single'.
Zigbee2MQTT:warn  2021-05-05 22:01:00: ubisys: Using input(s) 1 and endpoint 2 for 'dimmer_single'.
Zigbee2MQTT:debug 2021-05-05 22:01:00: ubisys: input_actions to be sent to 'livingroom/light/switch2': [[0,7,1,6,0,2],[0,134,1,8,0,5,0,50],[0,198,1,8,0,5,1,50],[0,11,1,8,0,3],[1,7,2,6,0,2],[1,134,2,8,0,5,0,50],[1,198,2,8,0,5,1,50],[1,11,2,8,0,3]]
Zigbee2MQTT:error 2021-05-05 22:01:00: Publish 'set' 'configure_device_setup' to 'livingroom/light/switch2' failed: 'Error: Write 0x001fee0000005baa/232 manuSpecificUbisysDeviceSetup({"inputActions":{"elementType":"octetStr","elements":[[0,7,1,6,0,2],[0,134,1,8,0,5,0,50],[0,198,1,8,0,5,1,50],[0,11,1,8,0,3],[1,7,2,6,0,2],[1,134,2,8,0,5,0,50],[1,198,2,8,0,5,1,50],[1,11,2,8,0,3]]}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4338,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Zigbee2MQTT:debug 2021-05-05 22:01:00: Error: Write 0x001fee0000005baa/232 manuSpecificUbisysDeviceSetup({"inputActions":{"elementType":"octetStr","elements":[[0,7,1,6,0,2],[0,134,1,8,0,5,0,50],[0,198,1,8,0,5,1,50],[0,11,1,8,0,3],[1,7,2,6,0,2],[1,134,2,8,0,5,0,50],[1,198,2,8,0,5,1,50],[1,11,2,8,0,3]]}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4338,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:196:23)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:225:26)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

@felixstorm I got a C4 to play with, but it's not taking the configuration of the inputs, it gives UNSUPPORTED_ATTRIBUTE. After that, the device is 'bricked' until it is power cycled.

I have not yet upgraded the device, I will do so and try again.

Edit: there was no update available, so maybe they changed how this works on the newer firmwares?

### PR DESCRIPTION
**Pull request by sjorge**
This fixes  #2552

### CODE REVIEW

**Comment by sjorge** [comment]
Ping @felixstorm

**Comment by felixstorm** [comment]
@sjorge Thanks, looks good to me!

I am pretty sure that the same problem also applies to the `manuSpecificUbisysDimmerSetup` cluster used with the D1 and the D1-R as my test also returned `UNSUPPORTED_ATTRIBUTE` and also it's exactly the same situation as with `manuSpecificUbisysDeviceSetup` - both are full custom clusters that have nothing to do with the ZCL standard clusters.  
So even if you are not able to test it personally, I think it would be safe to also apply `ubisysNull` to `manuSpecificUbisysDimmerSetup`. At least the functions using this cluster are currently broken and the fix would not make it any worse :wink:

**Comment by sjorge** [comment]
Let me push another commit to do manuSpecificUbisysDimmerSetup also.

**Comment by Koenkk** [comment]
thanks!

**Pull request merged**
