### PR TITLE
Sinope refactor. This would be a first step. 

### PR DESCRIPTION
**Pull request by MattL0**
Next would be to create consts in the sinope.js to reduce the file lenght.

### CODE REVIEW

**Comment by MattL0** [comment]
I tired to incorporate all what has been committed here https://github.com/Koenkk/zigbee-herdsman-converters/pull/5031

If there still something to incorporate from this pr.  it shall be little

**Comment by MattL0** [comment]
Feel free to no accept it. I saw somewhere that tozigbee and fromzigbee was getting too big.

**Comment by Koenkk** [comment]
- Can you rebase this?
- Are these only refactoring changes? (no functionality changes)

**Comment by MattL0** [comment]
yes when i have the time

**Pull request closed without merging**
