### PR TITLE
Added support for Philips Daylo outdoor wall lamp

### PR DESCRIPTION
**Pull request by danieledwardgeorgehitchcock**
Resolves Koenkk/zigbee2mqtt#9550

### CODE REVIEW

**Comment by danieledwardgeorgehitchcock** [comment]
Awaiting details from database.db and correct colour temps

**Comment by hoeselr** [comment]
[db.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/7495970/db.txt)

Hi @danieledwardgeorgehitchcock 
here is the db Entry of the Device, how / in which way can i send a payload in Homeassistant to get the color temp ?

thank you!

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks,

In HA, if you go to `dev tools` -> `services` -> `MQTT: Publish`

Topic: `zigbee2mqtt/0x0017880109819431/set`
Payload: `{"read": {"cluster": "lightingColorCtrl", "attributes": ["colorTempPhysicalMin", "colorTempPhysicalMax"]}}`

**Comment by hoeselr** [comment]
@danieledwardgeorgehitchcock sorry but this is my first time :-)

i am getting this message now:
Error Cannot publish to unsupported device 'Deckenleuchte TR'

Steps done :
i created a file called unsupported.js in zigbee2mqtt Folder (att)
also edited  zigbee2mqtt configuration.yaml as described (att)

no luck - thank you in advance

Screenshot 2021-11-08 133855
Screenshot 2021-11-08 133649

**Comment by danieledwardgeorgehitchcock** [comment]
You shouldn’t need to do any of that.

You should just need to send the message I posted previous and watch your Z2M debug logs for the response

**Comment by hoeselr** [comment]
this is the output :

Received MQTT message on 'zigbee2mqtt/0x0017880109819431/set' with data '{"read": {"cluster": "lightingColorCtrl", "attributes": ["colorTempPhysicalMin", "colorTempPhysicalMax"]}}
Screenshot 2021-11-08 135420
'

**Comment by danieledwardgeorgehitchcock** [comment]
Try changing the topic to your light friendly name

i.e. 0x0017880109819431 to Deckenleuchte Whirlpool TR

**Comment by hoeselr** [comment]
i think it`s the same message :
Screenshot 2021-11-08 140955
:

**Comment by danieledwardgeorgehitchcock** [comment]
I’ll code you up a quick external converter so that you can get the device to a supported level to run the attribute fetch

**Comment by danieledwardgeorgehitchcock** [comment]
create an external converter, add it to your config file with this content:

```javascript
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const ota = require('zigbee-herdsman-converters/lib/ota');

const extend = require('zigbee-herdsman-converters/lib/extend');

const hueExtend = {
    light_onoff_brightness: (options={}) => ({
        ...extend.light_onoff_brightness(options),
        toZigbee: extend.light_onoff_brightness(options).toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
    }),
    light_onoff_brightness_colortemp: (options={}) => ({
        ...extend.light_onoff_brightness_colortemp(options),
        toZigbee: extend.light_onoff_brightness_colortemp(options).toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
    }),
    light_onoff_brightness_color: (options={}) => ({
        ...extend.light_onoff_brightness_color({supportsHS: true, ...options}),
        toZigbee: extend.light_onoff_brightness_color({supportsHS: true, ...options}).toZigbee
            .concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
    }),
    light_onoff_brightness_colortemp_color: (options={}) => ({
        ...extend.light_onoff_brightness_colortemp_color({supportsHS: true, ...options}),
        toZigbee: extend.light_onoff_brightness_colortemp_color({supportsHS: true, ...options})
            .toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
    }),
};

const definition = {
        zigbeeModel: ['1746530P7'],
        model: '1746530P7',
        vendor: 'Philips',
        description: 'Hue White and color ambiance Daylo outdoor wall lamp',
        meta: {turnsOffAtBrightness1: true},
        extend: hueExtend.light_onoff_brightness_colortemp_color(),
        ota: ota.zigbeeOTA,
    };

module.exports = definition;
```

Remove the unsupported device from Z2M, restart Z2M, then re-add the device. Hopefully, it should show up as supported. If so, run the query then.

**Comment by hoeselr** [comment]
i created the external converter,excluded/included again
now following message appears in Log

Screenshot 2021-11-08 143058

**Comment by hoeselr** [comment]
@danieledwardgeorgehitchcock should i try additional steps ?

thank you

**Comment by danieledwardgeorgehitchcock** [comment]
Hi @hoeselr,

Everything that I have given you above should allow you to join the device and fetch the values. There must be an error somewhere in your process..?

**Comment by hoeselr** [comment]
@danieledwardgeorgehitchcock 

i found it - in the const definition there was a wrong model 1746530P7 i changed it to 1746547P7 now the payload was successful :-) thank you!

Debug Publishing 'set' 'read' to '0x0017880109819431'
Debug Received Zigbee message from '0x0017880109819431', type 'readResponse', cluster 'lightingColorCtrl', data '{"colorTempPhysicalMax":500,"colorTempPhysicalMin":153}' from endpoint 11 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0x0017880109819431', payload '{"color_mode":"xy","linkquality":27,"state":"OFF","update_available":null}'
Info Read result of 'lightingColorCtrl': {"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by danieledwardgeorgehitchcock** [comment]
Ah great! I grabbed the model number originally from the link that you provided in your post. I have updated it now, and will get it ready for review!

**Comment by Koenkk** [comment]
Thanks @danieledwardgeorgehitchcock  🎖️

**Comment by Xerx3s** [comment]
> @danieledwardgeorgehitchcock
> 
> i found it - in the const definition there was a wrong model 1746530P7 i changed it to 1746547P7 now the payload was successful :-) thank you!

Hey,
I got the same lamp but its Zigbee Model is "1746530P7" not "1746547P7" so it doesn't get recognized. It's working fine with an external converter, but is there a way to add another Zigbee Model to an existing db entry?

Thanks for all the great work!

**Comment by danieledwardgeorgehitchcock** [comment]
Yes, multiple models can be added into the array. Will do this later if nobody jumps on it before me

**Comment by macfr76** [comment]
Hi,

Is this Hue device 1746530P7 supported now in the last zigbee2mqtt release ?

I did try to add one this afternoon, but it's shown as "not suppported" as said in those logs :
`Info Device '0x001788010858652e' joined
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010858652e","ieee_address":"0x001788010858652e"},"type":"device_joined"}'
Info Starting interview of '0x001788010858652e'
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010858652e","ieee_address":"0x001788010858652e","status":"started"},"type":"device_interview"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010858652e","ieee_address":"0x001788010858652e"},"type":"device_announce"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010858652e","ieee_address":"0x001788010858652e"},"type":"device_announce"}'
Info Successfully interviewed '0x001788010858652e', device has successfully been paired
Warning Device '0x001788010858652e' with Zigbee model '1746530P7' and manufacturer name 'Philips' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x001788010858652e","ieee_address":"0x001788010858652e","status":"successful","supported":false},"type":"device_interview"}'`

**Pull request merged**
