### PR TITLE
Added converter for Zemismart 6 scene switch

### PR DESCRIPTION
**Pull request by DHM47**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by DavidFFerreira** [comment]
Nice 🗡️ I was hopping for that one xD

**Comment by DavidFFerreira** [comment]
@Koenkk its not working. It dont show the battery and the action dont show nothing :(

**Comment by DavidFFerreira** [comment]
image
image
image

**Comment by DavidFFerreira** [comment]
@Koenkk can u have a lock at this?
https://drive.google.com/file/d/1WaoM80xPi2TMsf-Z-itKLr2p7VKFZ5xh/view

**Comment by Koenkk** [comment]
- Battery isn't supported: https://github.com/Koenkk/zigbee2mqtt/discussions/10323#discussioncomment-1867885 (same as in the smartthings code you linked), just removed it.
- Also try repairing the device close to the coordinator
- @DavidFFerreira @DHM47 what coordinator/firmware version are you using?

**Comment by DavidFFerreira** [comment]
@Koenkk I have the zzh CC2652R
I did try near the zzh with same result, and I did try pairing and pressing on keys to wakup the device during the pairing

**Comment by DHM47** [comment]
@Koenkk I'm using the CC2652P from SMARTLIGHT, and the coordinator revision is
20210319

@DavidFFerreira after it is paired, click all the buttons, including a single, a double click, and a long click. Note that you'll need to leave a couple of seconds between each action. And the double click needs getting used to (two quick clicks don't register, so you'll need to 'click > pause > click' the hard part is getting the pause right).

Once that is done you'll see the actions in the automations of Home Assistant but not in zigbee2mqtt.
Screenshot_20220101-125032
Screenshot_20220101-125114

**Comment by DavidFFerreira** [comment]
I will try it

**Pull request merged**
