### PR TITLE
add support for Micro Matic ZB250 / SZ1000

### PR DESCRIPTION
**Pull request by geirra**
First try to add support for a device in zigbee2mqtt, so there might be errors.
The code is based on other devices.

### CODE REVIEW

**Comment by geirra** [comment]
Attached screenshot of the exposed dimmer.

Screenshot 2022-01-20 at 16 04 59

**Comment by Koenkk** [comment]
> Is this based on SummDelivered? If so there is something strange going on, since this is reporting
While the reported value in the ui is listed as 1,2kwh

This looks good to me, the representation might looks strong but that is because this is an unsigned 48 bit integer.

Note to self; after this merge https://github.com/Koenkk/zigbee2mqtt.io/pull/1151

**Comment by geirra** [comment]
@Koenkk thanks for the confirmation, i have tested it and with load it reports the correct numbers.

I fear that the value is going to spam the zigbee network tough, tried setting a min change to 0,001 or 0,01, but it doesn´t seem to have any affect.
Do you have any suggestions?

```
debug 2022-01-20 18:49:26: Received Zigbee message from 'Kjellerstue', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,4554409]}' from endpoint 1 with groupID 0
debug 2022-01-20 18:49:31: Received Zigbee message from 'Kjellerstue', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,4555014]}' from endpoint 1 with groupID 0
debug 2022-01-20 18:49:36: Received Zigbee message from 'Kjellerstue', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,4555740]}' from endpoint 1 with groupID 0
debug 2022-01-20 18:49:42: Received Zigbee message from 'Kjellerstue', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,4556345]}' from endpoint 1 with groupID 0
debug 2022-01-20 18:49:47: Received Zigbee message from 'Kjellerstue', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,4556950]}' from endpoint 1 with groupID 0
debug 2022-01-20 18:49:52: Received Zigbee message from 'Kjellerstue', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,4557676]}' from endpoint 1 with groupID 0
debug 2022-01-20 18:49:58: Received Zigbee message from 'Kjellerstue', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,4558281]}' from endpoint 1 with groupID 0
```

**Comment by Koenkk** [comment]
try with higher values, e.g. 10 or 100

**Comment by geirra** [comment]
> try with higher values, e.g. 10 or 100

@Koenkk This what I don't find any information on, is the min change based on  the 48bit integer or the converted sum?

I have tried 10, 100, 1000 but it still hits the min interval. 

Noticed that there is one a few develco devices that does some tuning on this also. 
```
 await reporting.currentSummDelivered(endpoint, {change: [0, 20]}); // Limit reports to once every 5m, or 0.02kWh
```

But that doesn't seem to slow down the messages either in this case.

**Comment by Koenkk** [comment]
Then instead of `change: [0, 20]` you can use `min` which is the minimum reporting interval in seconds

**Comment by geirra** [comment]
@Koenkk This should be tuned pretty good now.
Added comments as to why the values are chosen.

So think it can be merged.

**Comment by Koenkk** [comment]
thanks!

**Pull request merged**
