### PR TITLE
lywsd03mc: add toggle for temperature degrees selection

### PR DESCRIPTION
**Pull request by devbis**
Add a toggle for Fahrenheit degrees on the screen

Related PR to move temperature_display_mode to config category: https://github.com/Koenkk/zigbee2mqtt/pull/19631

### CODE REVIEW

**Comment by devbis** [comment]
@Koenkk Hi! Can I modify this converter to make thermostat_temperature_display_mode's  entity_category to be config or diagnostic? Or it is what z2m does?

**Comment by Koenkk** [comment]
@devbis z2m does it in homeassistant.ts, can I merge this pr?

**Comment by devbis** [comment]
Yes, please

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
