### PR TITLE
Add energy monitoring on sinope th1300zb

### PR DESCRIPTION
**Pull request by cloutierjo**
IMPORTANT, this change apparently break the device, not to be merged before we can confirm it to work.

Added energy information for the Sinope th1300zb based on information from someone that was able to retrieve this data. I don't own the device directly and couldn't test. But the person who has it try the modification and had a strange behaviour that made his device unrecognized:

with this modification

    Zigbee2MQTT:info  2023-02-13 23:11:04: SINOPETH1300ZB5 (0x500b9140000xxxxx): Not supported (Router)

With the original device converter

    Zigbee2MQTT:info  2023-02-13 23:17:13: SINOPETH1300ZB5 (0x500b9140000xxxxx): TH1300ZB - Sinopé Zigbee smart floor heating thermostat (Router)

I'm not sure what could have caused it

cc'ing related contributors in case you could test the change if you own the device: @MattL0 @embak

### CODE REVIEW

**Comment by cloutierjo** [comment]
Might have found the issue after the test ran ([0093c6f](https://github.com/Koenkk/zigbee-herdsman-converters/pull/5474/commits/0093c6f6ddbd5d6dc3cd4405f9b990cbe5366e37)), the person that own the device will try it again and I'll update this thread

**Comment by MattL0** [comment]
pretty sure it is ok like that. I ran into this issue while trying external converters one time not sure why.

**Comment by cloutierjo** [comment]
@MattL0 Thanks for the support with homeseer666, just to be sure your yet to be open pr will include those change? I can close this request?

**Comment by MattL0** [comment]
Yes it is merged. You can close this one :p

**Pull request closed without merging**
