### PR TITLE
Added support for OpenLumi Router

### PR DESCRIPTION
**Pull request by igo-r**
Added support for OpenLumi Router JN5169

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you link me instructions on how to build this device?

**Comment by igo-r** [comment]
> Can you link me instructions on how to build this device?
> 
> Note to self: after this merge https://github.com/Koenkk/zigbee2mqtt.io/pull/567/files

In the process of writing. Later, it will appear on GitHub at the link in the description.

**Comment by Koenkk** [comment]
Good, please let me know when it's ready. Then I will merge this.

**Comment by igo-r** [comment]
> Good, please let me know when it's ready. Then I will merge this.

Done

**Comment by Koenkk** [comment]
Can you link it? Cannot find it in the github repo

**Comment by igo-r** [comment]
> Can you link it? Cannot find it in the github repo

https://github.com/igo-r/Lumi-Router-JN5169

**Comment by Koenkk** [comment]
Sorry, but that's not enough information to me on how to setup this. Please provide a list of required hardware, how to flash and pair. Without this I don't think it's useful for anyone else and I cannot merge this. Alternatively you can provide an external configuration instead: https://www.zigbee2mqtt.io/information/configuration.html#external-converters-configuration

**Comment by igo-r** [comment]
> Sorry, but that's not enough information to me on how to setup this. Please provide a list of required hardware, how to flash and pair. Without this I don't think it's useful for anyone else and I cannot merge this. Alternatively you can provide an external configuration instead: https://www.zigbee2mqtt.io/information/configuration.html#external-converters-configuration and put it in your repo.

I updated the information to make it even more clear!
https://github.com/igo-r/Lumi-Router-JN5169/blob/master/README.md

This is an alternative firmware for the zigbee module installed in the Xiaomi Gateway DGNWG05LM.
In the future, new functionality will appear in it, we will allow light control and receiving information about pressing a button and a light sensor.

So that you understand that this firmware is needed, you can visit the telegram channel for customization Xiaomi Gateway DGNWG05LM, where there are 953 participants.
https://t.me/xiaomi_gw_hack

**Comment by Koenkk** [comment]
I don't see instructions on how to flash here: https://github.com/igo-r/Lumi-Router-JN5169/blob/master/README.md . I would expect stuff like how to connect cables etc.

**Comment by igo-r** [comment]
> I don't see instructions on how to flash here: https://github.com/igo-r/Lumi-Router-JN5169/blob/master/README.md . I would expect stuff like how to connect cables etc.

No cables need to be connected, everything is done via ssh. Here you do not need any direct connections to the zigbee module. It is already connected to the processor of the device, the firmware is carried out by ssh.

**Pull request merged**
