### PR TITLE
Refactor Thermostat Part of code

### PR DESCRIPTION
**Pull request by MattL0**
Easier to read and work with

### CODE REVIEW

**Review by MattL0 — COMMENTED** [review]
fix space

**Comment by Koenkk** [comment]
Are these only cosmetic changes?

**Comment by MattL0** [comment]
Yes,

You can reject these if you think it is not necessary. The aim was to get something more standardized.


I also added a unnocupied_setpoint to expose
________________________________
De : Koen Kanters ***@***.***>
Envoyé : Monday, November 21, 2022 1:36:14 PM
À : Koenkk/zigbee-herdsman-converters ***@***.***>
Cc : MattL0 ***@***.***>; Author ***@***.***>
Objet : Re: [Koenkk/zigbee-herdsman-converters] Refactor Thermostat Part of code (PR #4986)


Are these only cosmetic changes?

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
