### PR TITLE
#771 Basic actions for Aqara Opple WXCJKG11LM, WXCJKG12LM and WXCJKG13LM

### PR DESCRIPTION
**Pull request by kirovilya**

### CODE REVIEW

**Comment by Koenkk** [comment]
As this device has no icons on the button, I think it will be more logical to provide actions like: `{action: 'left_top'}`, `{action: 'left_bottom}`, `{action: 'right_middle'}`, etc. (for this new converters have to be added).

**Comment by kirovilya** [comment]
:) I do not think so
there is such a picture. it corresponds to actions
image

**Comment by Koenkk** [comment]
Thanks, I didn't know about this picture, but still it might not directly be clear, `top_left` etc. feel more logical to me??

**Comment by uncle-fed** [comment]
I have this swith and about to use it in vertical position to control 2 different lights as a simple on/off switch (and maybe more with double clicks and hold).
So I woudn't be a fan of using top/left/right/bottom labels.
How about just numbering them clockwise starting with the one that has LED light?
I.e. button_1, button_2, etc... ?

**Comment by uncle-fed** [comment]
I understand that this issue is titled as 'basic actions', so I suppose the current commits only enable single click actions. What about the 'double press' and 'hold' actions? Can those be included as well or is some extra investigative work required for those? Cause with the current pull request merged it sort of makes the other actions not visible.

Also, currently each button press generates 4 identical messages sent to the topic.

**Comment by kirovilya** [comment]
surprisingly, so far I have not been able to catch the events of double and long press. also did not see events about the battery.
if such events are detected, then we can rename the action to btn_1: click, btn_2: dbl_click, etc.

**Comment by Koenkk** [comment]
@uncle-fed thanks for your responses.

I think it would be most logical now to name the actions like   `{"action": "button_1_single"}`, if in the future we discover more events (hold, double, etc) we could easily add this without breaking.

**Comment by kirovilya** [comment]
Ok. I change this moments today...

**Comment by kirovilya** [comment]
found double click events for 3 and 4 buttons... but need fix https://github.com/Koenkk/zigbee-herdsman/pull/99

button 3 double click
```type 'raw', cluster 'lightingColorCtrl', data '{"type":"Buffer","data":[17,71,76,1,69,0,7,0,0,0,0,0,0,0]}' from endpoint 1 with groupID 0```

button 4 double click
```type 'raw', cluster 'lightingColorCtrl', data '{"type":"Buffer","data":[17,73,76,3,69,0,7,0,0,0,0,0,0,0]}' from endpoint 1 with groupID 0```

almost match to single clicks on buttons 5 and 6... very strange...

**Comment by Koenkk** [comment]
I've merged the herdsman pr, is there anything left before this can be merged?

**Comment by kirovilya** [comment]
will change after https://github.com/Koenkk/zigbee-herdsman/compare/master...kirovilya:patch-2

**Comment by kirovilya** [comment]
we can merge with Koenkk/zigbee-herdsman#100

so... 
I have not WXCJKG11LM and can't check.
WXCJKG12LM can single click for all buttons and double click for 3 and 4.
WXCJKG13LM can single click for all buttons and long click/hold for 3, 4, 5, 6.

**Comment by Koenkk** [comment]
Great, thanks!!

**Comment by liftylol** [comment]
hey, i just commented it below the commit but realized it would fit better here so just c&p:

i have the 3 bar version and the last 2 buttons do not work with this for me. i wrote the code for those myself, just saw that you already did so, replaced mine with yours because it looked a lot cleaner than mine, but like i said, bottom buttons dont work.

i can upload the stuff i wrote in the fromZigbee.js if you want - when i was troubleshooting the bottom buttons, i noticed that i only get 'raw' data from the device. so i looked at everything there (hold/release/click) and wrote the data down:

> left click:				"data":[17,218,76,1,69,0,7,0,0,0,0,0,0,0]
> right click:			"data":[17,219,76,3,69,0,7,0,0,0,0,0,0,0]
> left hold:				"data":[17,237,75,1,15,0,0,0,0,0,0,0]}
> right hold:				"data":[17,235,75,3,15,0,0,0,0,0,0,0]}
> left release:			"data":[17,238,75,0,15,0,0,0,0,0,0,0]
> right release:			"data":[17,236,75,0,15,0,0,0,0,0,0,0]

and googled around a little until i found something were similar and re-used it.


```
	WXCJKG13LM_bottomrow_raw: {
		cluster: 'lightingColorCtrl',
		type: 'raw',
		convert: (model, msg, publish, options) => {
			// i dont know yet what all the numbers do, the ones i know are below. other ones are not neccesary imo?
			// #2 is a counter that increments with each click
			// #4 is the button, 1 is left and 3 is right
			// #5 is the action, 69 as single click and 15 as hold.
			// if #5 is 15 and the button is 0 it means the last button was released 
			const deviceID = msg.device.ieeeAddr;
			const btn_lookup = {
				0: 'btn_rls',
				1: 'btn_bl',
				3: 'btn_br', 
				},
				act_lookup = {
				69: 'click',
				15: 'hold',
				},
			bbutton = btn_lookup[msg.data[3]],
			action = act_lookup[msg.data[4]];
				  
			
			if (bbutton && action) {
				// Save last button for release event if action is hold, but not if its released
				if (action == 'hold' && bbutton != 'btn_rls'){
					if (!store[deviceID]) {
						store[deviceID] = {};
					}
					store[deviceID].bbutton = bbutton;
				}
				if (bbutton == 'btn_rls'){
					if (!store[deviceID]) {
						return null;
					}
					return {'button': store[deviceID].bbutton, 'action': 'release'};
				}
				return {'button': bbutton, 'action': action};
			}
		}, 
	},
```

i have more stuff from the debugging still copied if you want to see it, just let me know :)
thanks for the great work guys!

**Comment by uncle-fed** [comment]
If it is possible to catch a "release button" event, that is really really useful!
It would be then possible to set up a "dimmer" function for the lights.
Because with a single "hold" and without the "released button" it is not possible to realise gradual dimming of lights. It would be super cool if we could get "button hold / button released" events published to be used in automation.

**Comment by kirovilya** [comment]
@liftylol @uncle-fed can you check last converters and last herdsman? there should no longer be a raw cluster

**Comment by liftylol** [comment]
@kirovilya i checked and apparently thats the problem... whats the correct way to update those in a zigbee2mqtt environment? i just ran everything under the 'update' section of zigbee2mqtt and was expecting that to update to the latest herdsman aswell :x

**Comment by kirovilya** [comment]
https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

**Comment by dedors** [comment]
> WXCJKG13LM can single click for all buttons and long click/hold for 3, 4, 5, 6.

I'm running hassio-z2m 1.8 with a WXCJKG13LM (6 button).
I can single click every one, but hold only works on 3 and 4. No hold on 5 and 6.

Is there for sure no double click with the 13LM? 
Because they advert it explicit with "each button can be clicked, double-clicked and long-pressed":
https://imgaz.staticbg.com/images/oaupload/ser1/banggood/images/29/0F/a1c78b15-c354-4733-b84f-5dc24093e38d.jpg
They also show example with the 6-button-switch where they double press it.

**Comment by addellll** [comment]
I can confirm that the 4 button version + the 6 button version works with both single press, double press and long press on ALL buttons if using an Aqara Hub (2 button version not tested).

**Comment by verybadsoldier** [comment]
I am also having a WXCJKG13LM 6-button and all buttons do only single press with version 1.8.0. No double press possible.
Hold & Release does only work with buttons 3 + 4, but not with 1,2, 5 and 6.

**Comment by iz3man** [comment]
What do you guys think? Is this some strange  proprietary behaviour of Aqara, or is this missing implementation in herdsman? So can this be solved? Or are we doomed w/o a genuine Aqara hub?

**Comment by uncle-fed** [comment]
In the end, even if it is proprietary behaviour, the data sent out by the switch should contain information that differentiates single/double click and hold. The question is how much effort is to reverse engineer the raw bytes. Perhaps the main maintainers / contributors to the herdsman code (@kirovilya / @Koenkk) don't have enough time / incentive to poke around on the very low level in order to make this work 100%. I wish I could help (I have Zigbee sniffer and some free time due to holiday season) but I lack very basic understanding of how it works on low level with raw bytes.

**Comment by kirovilya** [comment]
@uncle-fed If you have an Aqara hub and sniffer, write down the logs of pairing, double-clicking on the buttons, holding (preferably in separate files) and attach it here.

Without the sniffing of working with the original gateway, we can’t find out what commands it sends to remote control and which ones it receives from the remote control.

I don’t have a Aqara hub, so I can’t do this.

**Comment by kirovilya** [comment]
and YES, I have not free time now

**Comment by uncle-fed** [comment]
I'd love to help but unfortunately I do not have Aqara hub. Perhaps @liftylol or @dedors or others who are following this issue have one and could contribute?

**Comment by razvanmdobre** [comment]
Hi guys. 
I have a CC2531 sniffer. Do I need to flash it with Zigbee 3.0 firmware in order to use all the gestures?

**Comment by grostim** [comment]
Hi ! Am i the only one to have  this weird behavior ? I have paired a WXCJKG11LM to zigbee2mqtt 
hassio zigbee2mqtt-dev Version of Zigbee2Mqtt: 1.8.0-dev
Coordinator version: 20190608

At this stage, the switch is not recognized yet (log filled with message "Received message from unsupported device with Zigbee model 'undefined' )
However the switch actuate ALL the lights connected to zigbee2mqtt. the action is instant, so i guess that by default the switch is binded with a "General" light group.
- left click: all light switched off
- right click: all light switched on
- left double click: all light dim down (by 33% step)
- right double click: all light dim up (by 33% step)
- long left click: all light in warm white
- long right click: all light  in cold white


This rise several questions:
- I had no idea there was such a general group. What is its ID if i want to bind other switches to this group ?
- How to unbind from this group ?

**Comment by iz3man** [comment]
https://zigbee2mqtt.discourse.group/t/new-aqara-opple-switches/600?page=2

**Comment by iz3man** [comment]
And it's not only lights. It also switches power plug etc

**Comment by grostim** [comment]
> https://zigbee2mqtt.discourse.group/t/new-aqara-opple-switches/600?page=2

Yes, see my message above. You need to unbind the switch from "coordinator"

**Comment by rs-development** [comment]
_Having two problems with this device.

@grostim How to unpair from "coordinator", isnt the zigbee2mqtt device the coordinator and needs to be paired to forward to home assistant?

I have paired to z2m with all devices of, after turning the devices on the xiaumi button still controls them directly. How can i disable the behaviour?

The other problem is that each message is send 4 times. I have disabled all light bulbs acting as router or similar and repaired but still the same.

    info  2020-01-10 21:41:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":76,"battery":"100.00","voltage":3000,"action":"button_3_single"}'
    info  2020-01-10 21:41:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":76,"battery":"100.00","voltage":3000,"action":""}'
    info  2020-01-10 21:41:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":76,"battery":"100.00","voltage":3000,"action":"button_3_single"}'
    info  2020-01-10 21:41:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":76,"battery":"100.00","voltage":3000,"action":""}'
    info  2020-01-10 21:41:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":76,"battery":"100.00","voltage":3000,"action":"button_3_single"}'
    info  2020-01-10 21:41:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":76,"battery":"100.00","voltage":3000,"action":""}'
    info  2020-01-10 21:41:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":76,"battery":"100.00","voltage":3000,"action":"button_3_single"}'
    info  2020-01-10 21:41:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":76,"battery":"100.00","voltage":3000,"action":""}'
    info  2020-01-10 21:41:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":70,"battery":"100.00","voltage":3000,"action":"button_1_single"}'
    info  2020-01-10 21:41:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":70,"battery":"100.00","voltage":3000,"action":""}'
    info  2020-01-10 21:41:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":70,"battery":"100.00","voltage":3000,"action":"button_1_single"}'
    info  2020-01-10 21:41:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":70,"battery":"100.00","voltage":3000,"action":""}'
    info  2020-01-10 21:41:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":70,"battery":"100.00","voltage":3000,"action":"button_1_single"}'
    info  2020-01-10 21:41:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":70,"battery":"100.00","voltage":3000,"action":""}'
    info  2020-01-10 21:41:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":70,"battery":"100.00","voltage":3000,"action":"button_1_single"}'
    info  2020-01-10 21:41:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75bac6', payload '{"linkquality":70,"battery":"100.00","voltage":3000,"action":""}'

**Comment by grostim** [comment]
> @grostim How to unpair from "coordinator", isnt the zigbee2mqtt device the coordinator and needs to be paired to forward to home assistant?
as described here:
you need to post to the following topic zigbee2mqtt/bridge/unbind/[SOURCE_DEVICE_FRIENDLY_NAME] with payload "Coordinator".
binding and pairing is 2 different subjects:
pairing is joining a network.
binding is the process of setting up a source device to send command directly to a target device, without any intervention of the coordinator or you home automation gateway.

**Comment by rs-development** [comment]
Thanks, that is understandable!

**Comment by hdo** [comment]
> Thanks, that is understandable!

@rs-development  Did you managed to successfully unbind the opple switch? I still do have the same problems with messages being sent 4 times and button 1/2 directly controlling all my switches :-(

`zigbee2mqtt:info  2020-01-20 14:28:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b91d', payload '{"linkquality":48,"action":"button_2_single"}'
zigbee2mqtt:info  2020-01-20 14:28:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b91d', payload '{"linkquality":48,"action":"button_2_single"}'
zigbee2mqtt:info  2020-01-20 14:28:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b91d', payload '{"linkquality":48,"action":"button_2_single"}'
zigbee2mqtt:info  2020-01-20 14:28:31: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b91d', payload '{"linkquality":48,"action":"button_2_single"}'
zigbee2mqtt:info  2020-01-20 14:28:31: MQTT publish: topic 'zigbee2mqtt/0x84182600000ee830', payload '{"state":"ON","linkquality":78}'
zigbee2mqtt:info  2020-01-20 14:28:31: MQTT publish: topic 'zigbee2mqtt/0x7cb03eaa00ae5f34', payload '{"state":"ON","linkquality":21}'
zigbee2mqtt:info  2020-01-20 14:28:31: MQTT publish: topic 'zigbee2mqtt/0x7cb03eaa00ae6af7', payload '{"state":"ON","linkquality":21}'
zigbee2mqtt:info  2020-01-20 14:28:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b91d', payload '{"linkquality":69,"action":"button_1_single"}'
zigbee2mqtt:info  2020-01-20 14:28:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b91d', payload '{"linkquality":69,"action":"button_1_single"}'
zigbee2mqtt:info  2020-01-20 14:28:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b91d', payload '{"linkquality":69,"action":"button_1_single"}'
zigbee2mqtt:info  2020-01-20 14:28:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b91d', payload '{"linkquality":69,"action":"button_1_single"}'
zigbee2mqtt:info  2020-01-20 14:28:32: MQTT publish: topic 'zigbee2mqtt/0x84182600000ee830', payload '{"state":"OFF","linkquality":72}'
zigbee2mqtt:info  2020-01-20 14:28:32: MQTT publish: topic 'zigbee2mqtt/0x7cb03eaa00ae5f34', payload '{"state":"OFF","linkquality":15}'
zigbee2mqtt:info  2020-01-20 14:28:32: MQTT publish: topic 'zigbee2mqtt/0x7cb03eaa00ae6af7', payload '{"state":"OFF","linkquality":24}'
`

**Comment by rs-development** [comment]
If i remember correctly, i turned off all my devices expect from the CC stick, i removed the switch from the device list and reset it with the reset button on the back.

> you need to post to the following topic zigbee2mqtt/bridge/unbind/[SOURCE_DEVICE_FRIENDLY_NAME] with payload "Coordinator".

I think i have not done this, but its worth a try.

**Comment by socialstijn** [comment]
Using Hassio I still get the message that the device is unsupported. Has anyone been able to pair it successfully?

**Comment by hdo** [comment]
> Using Hassio I still get the message that the device is unsupported. Has anyone been able to pair it successfully?

You may need to use the latest-dev branch instead of 'master'. However i don't know how to switch that with Hassio

**Comment by iz3man** [comment]
I wish I also knew how to switch to dev branch in hassio. I can use zigbee2mqtt-edge which is 1.9.0 at the moment, but it seems there is an even "more" dev branch than that, correct?

**Pull request merged**
