### PR TITLE
Add LINKIND ZS130000078 Keypad

### PR DESCRIPTION
**Pull request by stefangries**
Thanks to alle the contributors in [this thread](https://github.com/Koenkk/zigbee2mqtt/issues/6242) who made this integration possible.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Koenkk** [comment]
Thanks!

**Comment by mon3y78** [comment]
i tried to install the keypad.  zigbee2mqtt sees it however I only have access to battery and signal information.  the connection led remains red and the keyboard locked

**Comment by stefangries** [comment]
Please do not post your request in several forums at the same time. It creates chaos.
Let's continue here: https://github.com/Koenkk/zigbee2mqtt/issues/6242

**Pull request merged**
