### PR TITLE
Bug fixes, and new schedule for TV02-Zigbee.

### PR DESCRIPTION
**Pull request by vladi1234**
Bug Fixes:
setState is used correctly for TV02-Zigbee.md .
ValueMin is set to 5.
Small cosmetic things adapted.
I will create `system_mode`. And heating_stop remains for compatibility reasons.

### CODE REVIEW

**Comment by Koenkk** [comment]
Because this pr modifies `fz. tvtwo_thermostat` which is completely removed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/4750

**Comment by vladi1234** [comment]
> Because this pr modifies `fz. tvtwo_thermostat` which is completely removed in #4750

How can this be solved? This must not be deleted.

**Comment by Koenkk** [comment]
These changes should be integrated into https://github.com/Koenkk/zigbee-herdsman-converters/pull/4750 , @vladyspavlov  could you merge this with your branch?

**Comment by vladi1234** [comment]
> Because this pr modifies `fz. tvtwo_thermostat` which is completely removed in #4750

I think @vladyspavlov needs to undo.

**Comment by vladyspavlov** [comment]
> This was agreed with @vladyspavlov.

No, it's not true

> These changes should be integrated into #4750 , @vladyspavlov could you merge this with your branch?

These changes are exactly a part of what I did in my PR. Looks like @vladi1234 pulled parts from code before migration to new tuya format and created a new one PR.

**Comment by vladi1234** [comment]
That's what you @vladyspavlov wrote:

> Could you explain more please? I don't see errors on your screenshot. As I see there are some differences with code that commited here, could you show your version? Maybe it will help to find issues. Or try using the current version of the code.

That's what you wrote:
if you like, I delete your schedule from my PR and you are not allowed to change or delete my code.

**Comment by vladi1234** [comment]
@Koenkk  lesen Sie unsere kommunikation in #4750 und Sie werden verstehen, dass jeder komunikation mit user vladyspavlov  sehr problematisch nervig ist.

Ich bitte Sie dieses problem lösen.

**Comment by vladyspavlov** [comment]
> That's what you wrote:

I wrote it to determine what the problem do you have. So we could discuss it and find a joint decision.

> if you like, I delete your schedule from my PR and you are not allowed to change or delete my code.

It's a public repository there is no private parts of code. I can make a PR to suggest my changes and it can be accepted or declined. It's up to the community

**Comment by vladi1234** [comment]
> > Das hast du geschrieben:
> 
> Ich habe es geschrieben, um festzustellen, was das Problem ist, das Sie haben. So könnten wir darüber diskutieren und eine gemeinsame Entscheidung finden.
> 
> > Wenn Sie möchten, lösche ich Ihren Zeitplan aus meiner PR und Sie dürfen meinen Code nicht ändern oder löschen.
> 
> Es ist ein öffentliches Repository, es gibt keine privaten Teile des Codes. Ich kann eine PR erstellen, um meine Änderungen vorzuschlagen, und sie kann akzeptiert oder abgelehnt werden. Es liegt an der Gemeinde

You need to create a new thermostat.

TV02-Zigbee is working with community for about a year.

**Comment by rotilho** [comment]
It always annoyed me not have the `system_mode`. It works but it could be better.

**Comment by Koenkk** [comment]
> it may take some time, but now there is a problem with a user vladyspavlov who wants to completely remove all thermostat modules and replace them with others.

This is not true, it migrates to the new TuYa format which is more clear and results in less code.

Since these changes will be included in https://github.com/Koenkk/zigbee-herdsman-converters/pull/4750 this can be closed.

**Pull request closed without merging**
