### PR TITLE
Support Philips Hue Bluetooth White & Color Ambiance Spot Centris with 4 Spots

### PR DESCRIPTION
**Pull request by copystring**
See https://github.com/Koenkk/zigbee-herdsman-converters/issues/1573

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide the `data/database.db` entry of these devices?

**Comment by copystring** [comment]
https://drive.google.com/file/d/17HQhlE-OqvrV3Dt3zatV1hPYdZ1Kp7aM/view?usp=drivesdk

**Comment by Koenkk** [comment]
If I correctly understand, this is a single device (with 4 spots) that pairs as 4 separate devices? If so, I think it makes more sense to merge all the zigbeeModels (`zigbeeModel: ['5060730P7_01', '5060730P7_02', etc...],`) and change the model to `5060730P7` so that we only have 1 definition.

**Comment by copystring** [comment]
Yes it is one device with spots but it also has one panel making it 5 in total.
Sure can make it one model instead.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
