### PR TITLE
Lixee : explode STGE into sub-values

### PR DESCRIPTION
**Pull request by mildis**
No need to expose these values are they are computed and STGE is already exposed by itself.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by ALaDoffe** [comment]
Hello, 
Just test and "status_register_tempo_jour" reports "UNDEF" instead of "BLANC"
Not yet test "status_register_tempo_demain" as it publishes at 08:00PM

thx

**Comment by mildis** [comment]
Hi @ALaDoffe, PR #6997 solves this.
status_register is sent as a String representing an hex value but I didn't managed to convert it to true hex before parsing.

**Comment by ALaDoffe** [comment]
Thank you @mildis.

In fact, I already done a custom sensor to decode status register in HA for "status_register_tempo_demain".
But I get an error on each HA restart that is why I am interrested in your component.
For information, during dev of this sensor I realize that values are not equal as described in documentation.
Indeed, Status_register for "couleur lendemain contrat tempo"  (bit 26-27) never take value 1 for "BLEU" it always keep value 0.
Here below what i do and it works for a while:

      {%- if today_at("06:00") < now() < today_at("20:00") -%}
            Not Yet Defined
      {%- else -%}
        {%- if TC == 2 -%}
            Jour BLANC
        {%- elif TC == 3 -%}
            Jour ROUGE
        {%- else -%}
            Jour BLEU
        {%- endif -%}
      {%- endif -%}

**Pull request merged**
