### PR TITLE
Add Zeeflora DIY Soil Moisture 

### PR DESCRIPTION
**Pull request by TrimVa**
Add Zeeflora DIY Soil Moisture

### CODE REVIEW

**Comment by TrimVa** [comment]
Add Zeeflora DIY Soil Moisture

**Comment by TrimVa** [comment]
Flower sensor with rechargeable battery

**Comment by Koenkk** [comment]
Do you have instructions on how to create this device? This is mandatory for DiY devices.

**Comment by TrimVa** [comment]
> Do you have instructions on how to create this device? This is mandatory for DiY devices.

the firmware and pcb sources are available on my github

**Comment by TrimVa** [comment]
https://github.com/TrimVa/zeeflora

**Comment by Koenkk** [comment]
Cool, could you move it to: `zigbee-herdsman-converters/devices/custom_devices_diy.js `

**Comment by TrimVa** [comment]
Good now ? :)

**Comment by TrimVa** [comment]
I deleted my zeeflora.js is added at the end of custom_devices_diy.js :)

**Comment by Koenkk** [comment]
Thanks, could you also create a device page with a link to your github?

**Comment by TrimVa** [comment]
Ok, i will try, i never did... 😅
--
Girard Sylvain samedi, 03 juillet 2021, 02:59PM +02:00 de Koen Kanters  ***@***.*** :

**Pull request merged**
