### PR TITLE
Add support for b-parasite

### PR DESCRIPTION
**Pull request by ginkel**
This PR adds support for the [b-parasite](https://github.com/rbaron/b-parasite), a capacitive open-source soil moisture sensor.

### CODE REVIEW

**Comment by ginkel** [comment]
If you need a photo of the device: https://photos.app.goo.gl/327GQrApUqDRtpDFA

**Comment by Koenkk** [comment]
This looks like a DiY device, can you move it to https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/custom_devices_diy.js ?

**Comment by ginkel** [comment]
Done. I appended it to the end of the list as the devices don't really seem to be sorted.

**Comment by ginkel** [comment]
> Thanks, do you have a picture with a white background?

I have edited the white balance of the picture I linked above, will this work?

**Comment by Koenkk** [comment]
yes, thanks!

**Pull request merged**
