### PR TITLE
Added Woox R7052 to tuya whitelabel

### PR DESCRIPTION
**Pull request by NebzHB**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by NebzHB** [comment]
I just read the new release changelog, not installed yet but couldn't it be a conflict with this : https://github.com/Koenkk/zigbee2mqtt/discussions/20496

**Comment by Koenkk** [comment]
Pushed a fix!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by NebzHB** [comment]
It's not a duplicate ?

image

**Comment by Koenkk** [comment]
It's not indeed, reverted again, is all ok with 1.35.1?

**Comment by NebzHB** [comment]
Yes it is and it's my version that is discovered. So maybe the second one is an useful duplicate ?

**Comment by Koenkk** [comment]
Yes, but I already reverted it (or do I misunderstand you?)

**Comment by NebzHB** [comment]
for me its nice that way, i was just afraid that there may be a duplicate somewhere ;) thank you

**Pull request merged**
