### PR TITLE
Improves OTA images related tests

### PR DESCRIPTION
**Pull request by PedroLamas**
Adds a new test image for Ubisys and improves the way these tests are run with jest.

This also includes some minor changes in the handling of the indexes on for `otaHeaderFieldControl`

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by felixstorm** [comment]
@PedroLamas, @Koenkk Are you sure that the changes to `common.js` do not break parsing of optional header fields? As far as I read the ZigBee docs, `otaHeaderFieldControl` is a bit field that is not limited to single bits being set. If my understanding is correct then trying to read all optional values starting from the fixed position 56 could therefore fail if multiple bits are set...

**Comment by PedroLamas** [comment]
@felixstorm You are correct, and it seems I have screwed this up... 🙁 Thanks for bringing this to attention!

@Koenkk I'll make a quick fix and submit a PR in the next few minutes.

**Comment by PedroLamas** [comment]
PR added, it is a full revert to the previous state of "common.js", but would be great if you can take a look @felixstorm

**Pull request merged**
