### PR TITLE
Add support for Tuya TV02-Zigbee '_TZE200_hue3yfsn' thermostat radiator valve

### PR DESCRIPTION
**Pull request by vladi1234**

### CODE REVIEW

**Review by vladi1234 — COMMENTED** [review]
TV02-Zigbee '_TZE200_hue3yfsn'

image

**Comment by handfreezer** [comment]
Just to tell you that : 
the week planning conversion is strange:
image

Also, I do not understand the holidaye mode date format:
image

Refreshing manually local_temperature is giving an error:
image

Also, is it possible to get on top le current_heating_setpoint, local_temperature and preset mode ?

**Comment by kalmatthew** [comment]
Is this not just a duplicate of TuYa TS0601_thermostat_1 (https://www.zigbee2mqtt.io/devices/TS0601_thermostat_1.html) with a different Manufacturer ID?

**Comment by handfreezer** [comment]
@kalmatthew : it seems not as, when adding finger print to thermostat_1, I got a lot of error.
I'll try to send you a debug trace of that case.

**Comment by vladi1234** [comment]
> Is this not just a duplicate of TuYa TS0601_thermostat_1 (https://www.zigbee2mqtt.io/devices/TS0601_thermostat_1.html) with a different Manufacturer ID?

This is a different thermostat and works differently, but just apparently looks the same. Therefore make too many mistakes.

**Comment by Koenkk** [comment]
@vladi1234 please fix the tests (you can run them locally by running `npm tst`)

**Comment by vladi1234** [comment]
@Koenkk 

pi@raspberrypi:/opt/zigbee2mqtt$ npm tst

> zigbee2mqtt@1.22.0-dev test
> jest test

 PASS  test/bridge.test.js (16.74 s)
 PASS  test/homeassistant.test.js (30.57 s)
 PASS  test/logger.test.js (16.305 s)
 PASS  test/bind.test.js (9.709 s)
 PASS  test/frontend.test.js (12.488 s)
 PASS  test/externalExtension.test.js (7.81 s)
 PASS  test/publish.test.js (8.618 s)
 PASS  test/controller.test.js (58.037 s)
 PASS  test/availability.test.js (7.432 s)
 PASS  test/configure.test.js (7.011 s)
 PASS  test/receive.test.js (5.936 s)
 PASS  test/group.test.js (6.644 s)
 PASS  test/legacy/bridgeLegacy.test.js (7.847 s)
 PASS  test/onEvent.test.js (5.621 s)
 PASS  test/legacy/report.test.js (5.642 s)
 PASS  test/otaUpdate.test.js (5.729 s)
 PASS  test/settings.test.js
 PASS  test/utils.test.js
 PASS  test/networkMap.test.js
 PASS  test/data.test.js
 PASS  test/externalConverters.test.js (5.042 s)

Test Suites: 21 passed, 21 total
Tests:       584 passed, 584 total
Snapshots:   0 total
Time:        76.203 s
Ran all test suites matching /test/i.

**Comment by vladi1234** [comment]
Here is another error, cannot be carried out.

pi@raspberrypi:/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters$ npm tst

zigbee-herdsman-converters@14.0.309 test
ZHC_TEST=true jest test

No tests found, exiting with code 1
Run with --passWithNoTests to exit with code 0
No files found in /opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: https://jestjs.io/docs/configuration
Pattern: test - 0 matches

**Comment by vladi1234** [comment]
@Koenkk I have a general question for the future. Can you structure "fingerprint" differently, as in the example, which includes "modelID" and "vendor" in figerprint. That makes a lot more sense because every device has its own "modelID", "vendor", "model" and "manufacturerName".
```
fingerprint: [{model: 'TV02-Zigbee', vendor: 'TuYa', modelID: 'TS0601', manufacturerName: '_TZE200_hue3yfsn'}],
```

**Comment by Koenkk** [comment]
@vladi1234 you can already include the modelID in the fingerprint, e.g. https://github.com/Koenkk/zigbee-herdsman-converters/blob/54af10436c47c0097e0a41f69f3c718956188638/devices/awox.js#L13 . I don't understand what you mean with `model` and `vendor`, these are not things send by the device (we can check everything that is in data/database.db).

Can I merge this?

**Comment by vladi1234** [comment]
Please make a marge.

**Comment by Koenkk** [comment]
Thanks!

**Comment by vladi1234** [comment]
Thanks!

**Comment by piars777** [comment]
Hello,
I have an issue with this device. I can set negative value to `local_temperature_calibration `:

`nov. 11 22:26:03 samso npm[24554]: Zigbee2MQTT:debug 2021-11-11 22:26:03: RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 255. Received 4076
nov. 11 22:26:03 samso npm[24554]:     at writeU_Int8 (internal/buffer.js:734:11)
nov. 11 22:26:03 samso npm[24554]:     at Buffer.writeUInt8 (internal/buffer.js:744:10)
nov. 11 22:26:03 samso npm[24554]:     at BuffaloZcl.writeUInt8 (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/buffalo/buffalo.ts:41:21)
nov. 11 22:26:03 samso npm[24554]:     at BuffaloZcl.writeListUInt8 (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/buffalo/buffalo.ts:169:18)
nov. 11 22:26:03 samso npm[24554]:     at BuffaloZcl.write (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/buffalo/buffalo.ts:266:18)
nov. 11 22:26:03 samso npm[24554]:     at BuffaloZcl.write (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/zcl/buffaloZcl.ts:376:26)
nov. 11 22:26:03 samso npm[24554]:     at ZclFrame.writePayloadCluster (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/zcl/zclFrame.ts:158:21)
nov. 11 22:26:03 samso npm[24554]:     at ZclFrame.toBuffer (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/zcl/zclFrame.ts:78:18)
nov. 11 22:26:03 samso npm[24554]:     at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:364:22)
nov. 11 22:26:03 samso npm[24554]:     at Object.func (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:332:25)
nov. 11 22:26:03 samso npm[24554]: Zigbee2MQTT:info  2021-11-11 22:26:03: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'local_temperature_calibration' to 'Radiateur de la chambre de Kyllan' failed: 'RangeError [ERR_OUT_OF_RANGE]: Command 0x2c1165fffec80a61/1 manuSpecificTuya.setData({\"status\":0,\"transid\":4,\"dp\":27,\"datatype\":2,\"length_hi\":0,\"length_lo\":4,\"data\":[159,255,255,4076]}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (The value of \"value\" is out of range. It must be >= 0 and <= 255. Received 4076)'","meta":{"friendly_name":"Radiateur de la chambre de Kyllan"},"type":"zigbee_publish_error"}'`

**Comment by vladi1234** [comment]
I just did fix. It can take a while until it comes in.
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3331

**Comment by igorbujaroski** [comment]
Hi,
Not sure how to read through this, does this mean the TZE200_hue3yfsn can be fully integrated in HA?
I have installed a few and I can't find a way to turn it on on-demand. Neither I can change the target heating temperature.
However, I can update the attribute's value (the 500 in the pic is 5 degrees) using the manage option for the TRV:

image

Anything anyone could share so I can follow a guide or understand how to fix this?

Thanks in advance,

**Pull request merged**
