### PR TITLE
Added support for Mercator Ikuu 6 gang device

### PR DESCRIPTION
**Pull request by SeanoNET**

### CODE REVIEW

**Comment by Koenkk** [comment]
Please merge with `TS0601_switch_6_gang` in `tuya.ts`, you can use the `tuya.whitelabel` for correct detection.

**Comment by SeanoNET** [comment]
Something like this?

tuya.ts
```javascript
{
        fingerprint: tuya.fingerprint('TS0601', ['_TZE200_mwvfvw8g']),
        model: 'TS0601_switch_6_gang',
        vendor: 'TuYa',
        description: '6 gang switch',
        fromZigbee: [tuya.fz.datapoints],
        toZigbee: [tuya.tz.datapoints],
        configure: tuya.configureMagicPacket,
        exposes: [
            tuya.exposes.switch().withEndpoint('l1'),
            tuya.exposes.switch().withEndpoint('l2'),
            tuya.exposes.switch().withEndpoint('l3'),
            tuya.exposes.switch().withEndpoint('l4'),
            tuya.exposes.switch().withEndpoint('l5'),
            tuya.exposes.switch().withEndpoint('l6'),
        ],
        endpoint: (device) => {
            return {'l1': 1, 'l2': 1, 'l3': 1, 'l4': 1, 'l5': 1, 'l6': 1};
        },
        meta: {
            multiEndpoint: true,
            tuyaDatapoints: [
                [1, 'state_l1', tuya.valueConverter.onOff],
                [2, 'state_l2', tuya.valueConverter.onOff],
                [3, 'state_l3', tuya.valueConverter.onOff],
                [4, 'state_l4', tuya.valueConverter.onOff],
                [5, 'state_l5', tuya.valueConverter.onOff],
                [6, 'state_l6', tuya.valueConverter.onOff],
            ],
        },
    },
```

mercator.ts
```javascript
 {
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_wnp4d4va'}],
        model: 'SSW06G',
        vendor: 'Mercator Ikuü',
        description: '6 Gang switch',
        fromZigbee: [tuya.fz.datapoints],
        toZigbee: [tuya.tz.datapoints],
        whiteLabel: [{vendor: 'TuYa', model: 'TS0601_switch_6_gang'}],
        exposes: [
            e.switch().withEndpoint('l1').setAccess('state', ea.STATE_SET),
            e.switch().withEndpoint('l2').setAccess('state', ea.STATE_SET),
            e.switch().withEndpoint('l3').setAccess('state', ea.STATE_SET),
            e.switch().withEndpoint('l4').setAccess('state', ea.STATE_SET),
            e.switch().withEndpoint('l5').setAccess('state', ea.STATE_SET),
            e.switch().withEndpoint('l6').setAccess('state', ea.STATE_SET),
        ],
        configure: async (device, coordinatorEndpoint, logger) => {
            await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            device.powerSource = 'Mains (single phase)';
            device.save();
        },
    },
```

**Comment by Koenkk** [comment]
I mean removing it from `mecrator.ts` and changing:


```js
fingerprint: tuya.fingerprint('TS0601', ['_TZE200_mwvfvw8g']),
```

to 

```js
fingerprint: tuya.fingerprint('TS0601', ['_TZE200_mwvfvw8g', '_TZE200_wnp4d4va']),
```

and add a `tuya.whitelabel` for proper detection (search in `tuya.ts` for examples)

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
