### PR TITLE
support for  T2037 ikea STOFTMOLN 37

### PR DESCRIPTION
**Pull request by mastertape**
my first try - to share a working code to the community

### CODE REVIEW

**Comment by mastertape** [comment]
but its working fine on my system... what did i wrong?

**Comment by EXP-Carthage** [comment]
You create a new file to integrate your device without Z2M knowing where to look...
You have to add your definition to the existing `devices\ikea.js` file, namely :
``` javascript
{
    zigbeeModel: ['STOFTMOLN ceiling/wall lamp WW37'], 
    model: 'T2037', 
    vendor: 'IKEA of Sweden', 
    description: 'LED Downlight', 
    supports: 'Dimming',
    extend: extend.light_onoff_brightness(),
}
```

**Comment by mastertape** [comment]
try it again - but the test failed again.. and i get not smarter after reading the log :(

**Comment by EXP-Carthage** [comment]
Delete your file `devices/T2037_Ikea_STOFTMOLN_37.js`.
f you keep it in your commits, it is normal that the test fails every time.

**Comment by mastertape** [comment]
now it works and all tests are passed

**Comment by EXP-Carthage** [comment]
Sure, but what happened with those lines ?
* `vendor: 'IKEA of Sweden'` which becomes `vendor: 'IKEA'`
* `supports: 'Dimming'` which has completely disappeared

**Comment by mastertape** [comment]
> Sure, but what happened with those lines ?
> 
> * `vendor: 'IKEA of Sweden'` which becomes `vendor: 'IKEA'`
> * `supports: 'Dimming'` which has completely disappeared

I change it because when you take a look in ikea.js not 1 device have the full vendor name..
Also  the support tag is not use in all other devices... so i thougt better to change it like the other devices...
https://github.com/Koenkk/zigbee-herdsman-converters/pull/4597/commits/ad0997b6442c573d16769083f55cd3d21b7c2514

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
