### PR TITLE
Update Sonoff TRV to move superfluous entities from sensors device category

### PR DESCRIPTION
**Pull request by blacknell**
There are a number of entities that are created with the default `entity category` - meaning they appear in dashboards when they really shouldn't and therefore clog up appearance. Some of these are diagnostic (interesting for some people) and a couple of others are used to set up the device (eg. child lock) and should be configuration type

So:-

- Idle steps is now `diagnostic`
- Closing steps is now `diagnostic`
- Valve closing limit voltage is now `diagnostic`
- Valve motor running voltage is now `diagnostic`
- Valve opening limit voltage is now `diagnostic`
- Child lock is now `config`
- Open window detection is now `config`
- Frost protection temperature is now `config`

For some reason (I can't work it out) frost protection temperature appears both as a writeable entity but also as a read-only but disabled diagnostic, so I've just set this to configuration.

Relates #7573

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by blacknell** [comment]
@Koenkk - I just installed the update and removed the TRV from my HA instance. Then paired it. The `entity_category` is not coming through on MQTT in the config payload for *some* of these entities.

Some of these have the `access: 'STATE_GET'` included (which I didn't change) but I don't see anything obvious.

eg. idle_steps it does not (should be `diagnostic`)

```
availability:
  - topic: zigbee2mqtt/bridge/state
  - topic: zigbee2mqtt/Office Radiator/availability
availability_mode: all
device:
  identifiers:
    - zigbee2mqtt_0x0cae5ffffeaa24ca
  manufacturer: SONOFF
  model: Zigbee thermostatic radiator valve (TRVZB)
  sw_version: 1.1.5
  via_device: zigbee2mqtt_bridge_0x00124b0024c04f51
  name: Office Radiator
enabled_by_default: true
json_attributes_topic: zigbee2mqtt/Office Radiator
object_id: office_radiator_idle_steps
origin:
  support_url: https://www.zigbee2mqtt.io
  name: Zigbee2MQTT
  sw_version: 1.39.1
state_topic: zigbee2mqtt/Office Radiator
unique_id: 0x0cae5ffffeaa24ca_idle_steps_zigbee2mqtt
value_template: '{{ value_json.idle_steps }}'
name: Idle steps
platform: mqtt
```

But on child_lock it does (this one's `config`)

```
availability:
  - topic: zigbee2mqtt/bridge/state
  - topic: zigbee2mqtt/Office Radiator/availability
availability_mode: all
command_topic: zigbee2mqtt/Office Radiator/set/child_lock
device:
  identifiers:
    - zigbee2mqtt_0x0cae5ffffeaa24ca
  manufacturer: SONOFF
  model: Zigbee thermostatic radiator valve (TRVZB)
  sw_version: 1.1.5
  via_device: zigbee2mqtt_bridge_0x00124b0024c04f51
  name: Office Radiator
entity_category: config
icon: mdi:account-lock
json_attributes_topic: zigbee2mqtt/Office Radiator
object_id: office_radiator_child_lock
origin:
  support_url: https://www.zigbee2mqtt.io
  name: Zigbee2MQTT
  sw_version: 1.39.1
payload_off: UNLOCK
payload_on: LOCK
state_topic: zigbee2mqtt/Office Radiator
unique_id: 0x0cae5ffffeaa24ca_switch_child_lock_zigbee2mqtt
value_template: '{{ value_json.child_lock }}'
name: Child lock
platform: mqtt
```

**Comment by Koenkk** [comment]
Mystery solved: https://github.com/Koenkk/zigbee2mqtt/pull/23494 !

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by blacknell** [comment]
I'll need to leave this until master. I think you release in a cycle? Can you remind. 

I've realised a couple more entities are in the wrong section so will raise a PR when I'm back from Paris 🇬🇧

**Comment by Koenkk** [comment]
Yes, release is every 1st of the month.

**Pull request merged**
