### PR TITLE
fix: Cluster with key 'draytonDeviceInfo' does not exist

### PR DESCRIPTION
**Pull request by mgrom**

### CODE REVIEW

**Comment by Koenkk** [comment]
This is related to https://github.com/Koenkk/zigbee-herdsman-converters/pull/939

I believe this PR will only fix a part of the problem as the attributes `ALG`, `ADC` and `boost` also have to be added here in order for this configure to work: https://github.com/Koenkk/zigbee-herdsman/blob/master/src/zcl/definition/cluster.ts#L3616

**Comment by sjorge** [comment]
Yes, but I have no idea what those value should be. I think the original other might have forgotten them in one of the patches.

**Comment by mgrom** [comment]
> This is related to #939 (@sjorge)
> 
> I believe this PR will only fix a part of the problem as the attributes `ALG`, `ADC` and `boost` also have to be added here in order for this configure to work: https://github.com/Koenkk/zigbee-herdsman/blob/master/src/zcl/definition/cluster.ts#L3616

Yeah, but without it valve is failing to update occupied_heating_setpoint. I'll dig into it little bit

**Comment by sjorge** [comment]
With it it we are hitting an error though, @Koenkk maybe for #939 I can just dorp the whole
```            await endpoint.configureReporting('wiserDeviceInfo', wiserDeviceConfig);``` line as the other changes are still good.

Then once @mgrom figures out what the proper values should be (as with just that change we hit the other error) we can add it back?

**Comment by mgrom** [comment]
@sjorge I'll try :) I've just started reading ZCL documentation, to better understand what I'm dealing with. It's new subject for me, but looks very interesting

**Comment by mgrom** [comment]
In the meantime I've made some analysis of ALG values:
"ALG":"10,1,230,224,6,54,363,2,363,60,100"

ALG means Application Layer Gateway, so I imagine this is used to communicate with hub
1 - some kind of counter... 
2 - always "1" (?)
3 - heating setpoint (*10)
4 - current temp (*10)
5 - diff between heating setpoint and current temp, but sometimes became "0" or not exactly correct value maybe because of some measurments that are not reported, then again get's correct value
6 - it's related to heating, when below zero means target temp is lower than current one, when above means target > current
7 - greater than 0 when heating, but can't find proper meaning
8 - some kind of counter... 
9 - equals 7
10 - heating demand (0-100)
11 - always "100" (?)



BTW. What's your battery consumption?

**Comment by sjorge** [comment]
With my other PR applied I lost 4% in a month, which is not too bad. The eurotronic is about the same.

**Comment by sjorge** [comment]
Do we know the field ID of the ALG value? I think that is the one we need to add to the file koen linked in the other PR.

**Comment by mgrom** [comment]
I've just realized that some of my problems with forcing TRV to change target temp are coming from TRV connected with IKEA Bulb/IKEA Driver... I don't know why, but when TRV was connected directly to Coordinator there were no problems with this.

@sjorge 4% is realy great, could you link this PR? 
I will look for ID of ALG.

**Comment by sjorge** [comment]
It’s the one linked by koen above #939 

I had the same fix as you have here + some reporting tweaks. But then hit the undefined error that is blocking the merge.

**Comment by sjorge** [comment]
Some more data, I happened to be debugging something when the TRV came by:
```
zigbee2mqtt:debug 2020-03-03 17:05:19: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ADC,1384,1382,1387,215,-32768,2350,0,310,100,222,223,221"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-03 17:05:19: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ALG,3,1,235,215,20,0,310,2,790,45100"}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-03-03 17:05:20: MQTT publish: topic 'zigbee2mqtt/0x086bd7fffe7ecd67', payload '{"battery":100,"voltage":3.1,"linkquality":52,"ADC":"1384,1382,1387,215,-32768,2350,0,310,100,222,223,221","ALG":"3,1,235,215,20,0,310,2,790,45100","local_temperature":21.5,"pi_heating_demand":45,"boost":"Up","occupied_heating_setpoint":23.5}'
```

My ALG seems to have less fields?
45100 might just be PIHeatingDemand but in higher persission?

**Comment by sjorge** [comment]
Also of interest, we can swap out `fz.wister_thermostat` for `fz.thermostat_att_report` and everything seems fine!

**Comment by mgrom** [comment]
yours ALG looks like you were heating: 235 vs 215, so mine and yours were heating during the report. Last three values in mine were:
363,60,100
yours last two:
790,45100

I have a feeling that it should be 60100 in mine, or 45, 100 in yours... seems stupid, but as far it looks reasonable maybe it's not stupid explanation ;)

**Comment by sjorge** [comment]
I wonder if there is also a flag in there somehwere to derrive a system_mode, as currently we don't have one. The device seems to have an 'off', 'schedule', 'manual' so i guess that maps to off, auto, heat... but it's not in the expected system_mode attribute.

**Comment by mgrom** [comment]
>The device seems to have an 'off', 'schedule', 'manual' 

How do you know?

**Comment by sjorge** [comment]
I was unable to find a technical spec sheet for the device, but I did find all the other manuals.
You can use the room thermostat (linked to the TRV) to switch between schedule, manual or off.

Where manual takes it out of the scheduled mode and off, well turns it off I guess.
https://www.se.com/ww/en/product/CCTFR6100/se---wiser-radiator-thermostat/
https://www.se.com/ww/en/product/MEG5935-0000/merten---wiser-radiator-thermostat/?range=65635-wiser&parent-category-id=2200&parent-subcategory-id=88815

These are both the same device, Schneider makes it and sells it under a few brands.
In addition to the main scheinder one there are :
- Merten
- Drayton
- Eberle

**Comment by mgrom** [comment]
I hope you're right, but things that you've listed could be the feature of wall thermostat, or wall thermostat together with hub. 
TRV itself can be dummy, and only have reporting with setting target temp. Schedule defined in other device can only force TRV to change target temp when the schedule needs it. Same thing with manual

**Comment by mgrom** [comment]
> Do we know the field ID of the ALG value?

I've sniffed zigbee traffic and it seems it's the same for all messages... 
image

**Comment by mgrom** [comment]
It will be great to have one heathub, to sniff messages between hub and trv. Without it I think we will not be able to understand full potential of standalone trv.

**Comment by mgrom** [comment]
There is one thing that TRV is reporting and it's manufacturer specific:
image
No idea what is it.. but seems to be static

**Comment by sjorge** [comment]
@mgrom good news, over in my PR I fixed the pairing issues... well aside from a warning about undefined model.

I had to do packet captures to figure out the issues but to summerize them for you:
- some binds failed due to full table, so don't bind them
  - genIdentify
  - genPollCtrl
  - hvacUserInterfaceCfg (this one is intersting, as we do setup reporting for it and get those published wrt the lock state of the controlles!)
- `wiserDeviceInfo` cluster only has 1 attribute `deviceInfo` so we setup reporting for that instead of `ALG`, `ADC`, and `boost` as they do not exist.

I also got some wiserDeviceInfo message fromthe log that might help in the future with extracting data from them:
```
zigbee2mqtt:debug 2020-03-15 17:33:49: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"BAT,3.10,Full"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 17:33:51: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ADC,1386,1378,1384,221,-32768,2000,0,0,100,222,225,222"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 17:33:51: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ALG,1,0,200,221,-21,0,0,0,0,0100"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 17:34:50: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"BAT,3.10,Full"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 17:34:51: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ADC,1384,1377,1382,221,-32768,2000,0,0,100,222,225,223"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 17:34:51: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ALG,1,0,200,221,-21,0,0,0,0,0100"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:08:56: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"NWK,WiserHeatUserJoin,2259155,6ab9"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:09:06: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"BAT,3.10,Full"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:09:08: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ADC,1367,1348,1367,221,-32768,2000,0,0,100,229,236,229"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:09:08: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ALG,2,0,200,221,-21,0,0,0,0,0100"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:10:07: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"BAT,3.10,Full"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:10:09: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ADC,1364,1347,1360,224,-32768,2000,0,0,100,230,236,231"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:11:07: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"BAT,3.10,Full"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:11:09: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ALG,2,0,200,221,-21,0,0,0,0,0100"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:12:07: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"BAT,3.10,Full"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:12:09: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ADC,1359,1350,1358,224,-32768,2000,0,0,100,232,235,232"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:12:09: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ALG,2,0,200,221,-21,0,0,0,0,0100"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:13:08: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"BAT,3.10,Full"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:13:09: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ADC,1358,1349,1358,224,-32768,2000,0,0,100,232,235,232"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:13:10: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ALG,2,0,200,221,-21,0,0,0,0,0100"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:14:02: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"MOT,CloseValve"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:14:10: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ADC,1358,1350,1358,224,-32768,2000,0,0,100,232,235,232"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:14:10: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ALG,3,0,200,224,-42,0,0,0,0,0100"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:14:11: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"MOT,Stall"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:15:08: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"BAT,3.00,Full"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:15:10: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ADC,1359,1350,1358,224,-32768,2000,0,0,100,232,235,232"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:15:10: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ALG,3,1,200,224,-42,0,0,0,0,0100"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:16:08: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"BAT,3.00,Full"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:16:10: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ADC,1359,1353,1360,224,-32768,2000,0,0,100,232,234,231"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-03-15 18:16:10: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ALG,3,1,200,224,-42,0,0,0,0,0100"}' from endpoint 1 with groupID 0
```

Especially this one seems interesting:
```
zigbee2mqtt:debug 2020-03-15 18:14:11: Received Zigbee message from '0x086bd7fffe7ecd67', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"MOT,Stall"}' from endpoint 1 with groupID 0
```

As I had it on my desk for debugging, this error makes sense and we should probably capture it and publish it as `wiser_motor` with value `stalled`... well if we can figure out the reverse message when it unstalls ideally...

**Comment by mgrom** [comment]
@sjorge Good job. I'll test it in few days - waiting for delivery of one more CC2531  ;)

**Comment by sjorge** [comment]
@koenkk I think this is fixed now, well atleast the draytonDeviceInfo error, we could probably still eventually parse more data from this. But I think that is hard without having the gateway.

**Comment by Koenkk** [comment]
Yes, lets close it for now

**Pull request closed without merging**
