### PR TITLE
Update samotech.ts

### PR DESCRIPTION
**Pull request by alexeiw123**
Added device support for SM325-ZG

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by alexeiw123** [comment]
@Koenkk (I thinkk) your commits removed the options that disable effects and power on behaviour, which didn't work in my testing of the device. I was just working on another PR that would tidy this code of mine up a lot, but yours is much more concise.

suggest replacing
`extend: [light({configureReporting: true})],`
with
`exposes: extend.light_onoff_brightness({disablePowerOnBehavior: true, disableEffect: true}).exposes,`

I'm not sure if `configureReporting: true` is also required or not, I don't understand the options well enough.

**Comment by alexeiw123** [comment]
@Koenkk yes, after updating dev channel, these two non functional options have returned.

image

**Comment by alexeiw123** [comment]
I have attempted to fix this here https://github.com/Koenkk/zigbee-herdsman-converters/pull/7095

Testing in my local converter is a bit different to the way it's done in this git though.

**Pull request merged**
