### PR TITLE
disablePowerOnBehavior:true for https://www.moeshouse.com/collections/smart-light/products/zb-td5-rcw-gu10-ms

### PR DESCRIPTION
**Pull request by Hadatko**
Signed-off-by: Dusan Cervenka <cervenka.dusan@gmail.com>

### CODE REVIEW

**Comment by Hadatko** [comment]
Hi, as mentioned here https://github.com/Koenkk/zigbee2mqtt/issues/15451 i have different device than is already supported. It looks like it is almost same, but i had to turn off `disablePowerOnBehavior:true` option as it was throwing error with unsupported option. If i remove my config file, then device is recognized like  https://www.zigbee2mqtt.io/devices/ZLD-RCW.html but i have https://www.moeshouse.com/collections/smart-light/products/zb-td5-rcw-gu10-ms

How can i distuingish between these two devices? I am curious if i can remove existing support somehow from code to maybe get more reliable information about product (something specific).

**Comment by Hadatko** [comment]
I see previously it was edited exiting model: https://github.com/Koenkk/zigbee2mqtt/issues/12919
Should i add disable attribute to existing configuration and remove new one?

**Comment by Koenkk** [comment]
Please edit the existing definition.

**Comment by Hadatko** [comment]
@Koenkk Done.

**Comment by Koenkk** [comment]
Thanks!

**Comment by Hadatko** [comment]
Thank you too ;)

**Pull request merged**
