### PR TITLE
Add support for Xiaomi Temperature and Humidity sensor with display

### PR DESCRIPTION
**Pull request by Woodpeckercz**
Please add support for this device made by Xiaomi Aqara.

HTB1poCldlWD3KVjSZFsq6AqkpXaz

My entry in devices.js looks like this.

     {
        zigbeeModel: ['TS0201'],
        model: 'TS0201',
        vendor: 'Xiaomi',
        description: 'Aqara temperature & humidity sensor with display',
        supports: 'temperature and humidity',
        fromZigbee: [
            fz.xiaomi_battery_3v, fz.xiaomi_temperature, fz.humidity,
        ],
        toZigbee: [],
     },

### CODE REVIEW

**Comment by Koenkk** [comment]
added, thanks!

**Comment by Woodpeckercz** [comment]
I see, here it is now

**Comment by Woodpeckercz** [comment]
Thanks

**Comment by Koenkk** [comment]
Does the battery reporting work?

**Pull request closed without merging**
