### PR TITLE
Add xiaomi aqara H1 switches WS-EUK01 and WS-EUK02

### PR DESCRIPTION
**Pull request by korzenek**
Add support for xiaomi aqara H1 EU wired switches (no neutral)

### CODE REVIEW

**Comment by kirovilya** [comment]
Is there a "command mode" there (for binding)?
Is there current and load monitoring?

**Comment by korzenek** [comment]
There is no load and current monitoring in no neutral version 
https://www.aqara.com/eu/product/smart-wall-switch-h1-no-neutral
I've tested operation_mode and power_outage_memory and it is working

I don't know what you mean by command mode, but without setting "event mode" Im not receiving events on switch manual click

**Comment by kirovilya** [comment]
ok about load without neutral, i am agree...

but for "command mode"... 
did you try to set it?:
```
await endpoint1.write('aqaraOpple', {'mode': 0}, {manufacturerCode: 0x115f});
await endpoint1.write('aqaraOpple', {0x0125: {value: 0x01, type: 0x20}}, {manufacturerCode: 0x115f});
```

no toggleCommand in logs?

**Comment by kirovilya** [comment]
look in configure notes for 'WRS-R02' model

**Comment by korzenek** [comment]
I've tried it, it only works with `{'mode': 1}` with ` {'mode': 0}` I receive no events on manual switch click.
```
await endpoint1.write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f, disableDefaultResponse: true, disableResponse: true});
```

changing value in 

```
await endpoint1.write('aqaraOpple', {0x0125: {value: 0x01, type: 0x20}}, {manufacturerCode: 0x115f, disableDefaultResponse: true, disableResponse: true}
```
doesn't seem to change anything. double clicks are still working

Also no logs for `grep -ir toggleCommand  /opt/zigbee2mqtt/data/log/`

**Comment by kirovilya** [comment]
hmm, strange. I really hoped that there would be a possibility of binding

**Comment by Koenkk** [comment]
@kirovilya @korzenek ready for merge?

**Comment by kirovilya** [comment]
yes

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
