### PR TITLE
Added Hue Ensis (black) 929003052501

### PR DESCRIPTION
**Pull request by chewyf5**
Maybe Philips changed the model nummer of Hue Ensis. This is the model nummer of my Ensis newly bought one week ago. The lamp reports itself as 929003052501_01 (facing the ceiling ) and 929003052501_02 (facing the table/ground).

### CODE REVIEW

**Comment by chewyf5** [comment]
Theoretically its possible to add an other Ensis: Hue Ensis (white) - should! report as 929003053301_01 and 929003053301_02 - but i don't have the lamp - so i have no device for verification

**Comment by Koenkk** [comment]
Hue uses different model numbers (I believe product vs SKU), I've merged it with the existing entry.

**Comment by chewyf5** [comment]
Cool - thanks :-) (this was my frist accepted pull request on github)

**Comment by Koenkk** [comment]
> Cool - thanks :-) (this was my frist accepted pull request on github)

Congrats!

**Pull request merged**
