### PR TITLE
Update tuya.ts

### PR DESCRIPTION
**Pull request by sdbldn**
Hello, we have added a 'Fan Coil ZIGBEE Thermostat' that complies with the tuya protocol. This is edited based on the 'tuya. ts' file and is suitable for external converters. Do I need to add any additional content to complete the update?

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `HHST001.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by sdbldn** [comment]
这是来自QQ邮箱的自动回复邮件。你好。已收到你的邮件，我会在看到邮件后尽快处理。

**Comment by sdbldn** [comment]
Hello, thank you for your guidance. 
I will submit images that meet the specifications for the document. I would like to inquire, is it only necessary to add images that meet the specifications, as well as titles/descriptions? Do I need to add any other files?

**Comment by Koenkk** [comment]
Image is enough!

**Comment by pcrednet** [comment]
hy @sdbldn.
I would like to try this thermostat; where can we buy it?
We have a company dedicated to building climate control and we are looking for a zigbee thermostat that works well.
We need it to have hot/cold control.

**Comment by sdbldn** [comment]
@luismipr Hi, dear, we are glad that you are interested in our ZigBee Air-Conditioning thermostat, if you want to purchase it, please kindly contact us~
Contact  information:
email address: fiona@morning-e.com
WhatsApp/WeChat: 0086 18658755756

**Pull request merged**
