### PR TITLE
Correct lixee.ts logging

### PR DESCRIPTION
**Pull request by qp68**
With Logger = console, debug log "zlinky config: ..." are spamming the console

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you fix the failing checks?

**Comment by qp68** [comment]
Done, hope it's the right way

**Comment by Koenkk** [comment]
Thanks!

**Comment by qp68** [comment]
@Koenkk There is an issue when starting Z2M due to my addition.

`Zigbee2MQTT:error 2023-12-10 21:52:01: Failed to call 'Bridge' 'start' (TypeError: Cannot read properties of undefined (reading 'debug')
    at getCurrentConfig (/app/node_modules/zigbee-herdsman-converters/src/devices/lixee.ts:724:12)
    at Object.exposes (/app/node_modules/zigbee-herdsman-converters/src/devices/lixee.ts:800:27)
    at Device.exposes (/app/lib/model/device.ts:34:36)
    at Bridge.getDefinitionPayload (/app/lib/extension/bridge.ts:703:29)
    at /app/lib/extension/bridge.ts:657:34
    at Array.map (<anonymous>)
    at Bridge.publishDevices (/app/lib/extension/bridge.ts:616:47)
    at Bridge.start (/app/lib/extension/bridge.ts:114:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Controller.callExtensions (/app/lib/controller.ts:319:17)) `

I don’t know how to fix it so maybe it’s simpler to revert the commit.

Sorry

**Pull request merged**
