### PR TITLE
Add support for innr SP 222 smart plug

### PR DESCRIPTION
**Pull request by lpomfrey**
homeassistant integration to go with this is in https://github.com/Koenkk/zigbee2mqtt/pull/2230

### CODE REVIEW

**Comment by Koenkk** [comment]
According to https://github.com/Koenkk/zigbee2mqtt/issues/2228 it also support power measurements. Can you try with

```js
    {
        zigbeeModel: ['SP 222'],
        model: 'SP 222',
        vendor: 'Innr',
        description: 'Smart plug',
        supports: 'on/off',
        fromZigbee: [fz.on_off, fz.electrical_measurement],
        toZigbee: [tz.on_off],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement']);
            await endpoint.read('haElectricalMeasurement', [
                'acVoltageMultiplier', 'acVoltageDivisor', 'acCurrentMultiplier',
                'acCurrentDivisor', 'acPowerMultiplier', 'acPowerDivisor',
            ]);
            await configureReporting.onOff(endpoint);
            await configureReporting.rmsVoltage(endpoint);
            await configureReporting.rmsCurrent(endpoint);
            await configureReporting.activePower(endpoint);
        },
    },
```

**Comment by lpomfrey** [comment]
I thought that too initially, and tried using that configuration, the configuration for the innr SP 120, and a few combinations of both but couldn't get it to report any power information. `current` was present in the payload from `rmsCurrent` but it was always `null`. So I'm not sure if it actually supports power measurements, if I have an issue with my particular smart plug, or if it's reporting it in some other non-standard way.

**Comment by lpomfrey** [comment]
Saying that, I had `configureKey: 2` rather than `configureKey: 1`, I'm not sure if that would have made a difference?

**Comment by Koenkk** [comment]
From the article on their site I can't find that it does support it:

image

@jameswarner62 where did you got this from?

**Comment by lpomfrey** [comment]
I can't find anything about it supporting power measurement, and that configuration doesn't work either. 

I can rebase this against master again if you'd rather not have the revert commit in git history?

**Comment by Koenkk** [comment]
Don't worry about the commit history; I will squash merge this anyway. Waiting for a response from @jameswarner62 now.

**Comment by jameswarner62** [comment]
> From the article on their site I can't find that it does support it:
> 
> image
> 
> @jameswarner62 where did you got this from?

Hi Koenkk - many thanks for taking a look - Amazon UK have them available:

https://www.amazon.co.uk/Zigbee-Smart-Philips-Google-Required/dp/B07SGG1BS5/ref=sr_1_5?keywords=innr+smart+plug&qid=1572426483&sr=8-5

**Comment by lpomfrey** [comment]
Actually on the Amazon link someone has asked if it supports power measurement and someone has answered that it doesn't.

**Comment by Koenkk** [comment]
Ok, thanks!

**Pull request merged**
