### PR TITLE
Add OTA support for Xiaomi `MCCGQ12LM`

### PR DESCRIPTION
**Pull request by Otnow**
OTA file added with https://github.com/Koenkk/zigbee-OTA/pull/268

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by torandreroland** [comment]
@Otnow: Have you gotten OTA to work with MCCGQ12LM? Mine doesn't seem to support this cluster.

**Comment by Otnow** [comment]
@torandreroland, I don't have this device, so unfortunately I can't check OTA.
You can try searching in issues or opening a new one with this problem.

**Comment by torandreroland** [comment]
@Otnow: Can you recall the reason for opening this issue in the first place? Was it only done because we found the OTA file?

I'm thinking of removing the genOta cluster again since my hypothesis is that the device don't support it, but just trying to make sure.

**Comment by Otnow** [comment]
@torandreroland, yes, that's right, only based on the OTA file.

**Pull request merged**
