### PR TITLE
adding futurehome smart thermostat

### PR DESCRIPTION
**Pull request by talisker77**
Adding futurehome thermostat to converters, it is a connecte copy. resuing code
https://www.futurehome.io/no/shop/thermostat-hvit
--
I'm getting some unknown DP values: but will work in HA and zigbee2mqtt.
2023-10-13 16:46:36zigbee-herdsman-converters:connecte_thermostat: Unrecognized DP #121 with data {"dp":121,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,241]}}
2023-10-13 16:46:36zigbee-herdsman-converters:connecte_thermostat: Unrecognized DP #120 with data {"dp":120,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,0]}}
2023-10-13 16:46:36zigbee-herdsman-converters:connecte_thermostat: Unrecognized DP #122 with data {"dp":122,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,0]}}
2023-10-13 16:46:36zigbee-herdsman-converters:connecte_thermostat: Unrecognized DP #123 with data {"dp":123,"datatype":2,"data":{"type":"Buffer","data":[0,0,2,208]}}
2023-10-13 16:46:58zigbee-herdsman-converters:connecte_thermostat: Unrecognized DP #121 with data {"dp":121,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,239]}}
2023-10-13 16:46:58zigbee-herdsman-converters:connecte_thermostat: Unrecognized DP #120 with data {"dp":120,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,0]}}
2023-10-13 16:46:58zigbee-herdsman-converters:connecte_thermostat: Unrecognized DP #122 with data {"dp":122,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,0]}}
2023-10-13 16:46:58zigbee-herdsman-converters:connecte_thermostat: Unrecognized DP #123 with data {"dp":123,"datatype":2,"data":{"type":"Buffer","data":[0,0,4,54]}}

### CODE REVIEW

**Comment by talisker77** [comment]
corrected ci error

**Comment by talisker77** [comment]
Hope all is ok now, and looking forward to remove my external converter

**Comment by Koenkk** [comment]
Please merge with https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/connecte.ts#L10, you can use the whitelabel to separately identify the device, example: 

https://github.com/Koenkk/zigbee-herdsman-converters/blob/d19daaef69687dc66738c627e03fa1dc7be5852c/src/devices/tuya.ts#L565

**Comment by talisker77** [comment]
Thanks for the guide.
I've merged code, and hopefully made the correct adjustment for both devices to work fine.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
