### PR TITLE
add _TZE204_sxm7l9xa as presence sensor

### PR DESCRIPTION
**Pull request by richardwonka**
(sorry for the mess)

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you confirm the manufacturerName should not be `_TZE204_sxm7l9xa`?

**Comment by richardwonka** [comment]
Pasting directly from Z2M:_TZE204_sxm7l9xaRichard Wonka —Throw off the bow lines! Dream! Discover! On 8. May 2023, at 20:25, Koen Kanters ***@***.***> wrote:﻿
Can you confirm the manufacturerName should not be _TZE204_sxm7l9xa?

**Comment by Koenkk** [comment]
Thanks!

**Comment by tothgergely92** [comment]
Unfortunately in the code it is NOT ..._SXm... but ..._XSm... which looks misspelled, the good one is the ..._SXm...

**Pull request merged**
