### PR TITLE
philips: set colorTempRange for LTW013

### PR DESCRIPTION
**Pull request by zegl**
Fixes https://github.com/Koenkk/zigbee2mqtt/issues/15929

### CODE REVIEW

**Comment by sjorge** [comment]
Is this actually what the device reports as supported? All hue lights i got my hands on report the same value when reading the color cluster.

You can check these by reading lightingColorCtrl.colorTempPhysicalMin and lightingColorCtrl.colorTempPhysicalMax.

**Comment by zegl** [comment]
@sjorge I didn't check with a physical device, as I don't have one, but the claims made in the original issue seems to be true. I double checked it against [some documentation](Example: https://www.bauhaus.se/media/pdf/2008840B.pdf) that I found online, which claims a temperature range between 2200 and 6500 K.

**Comment by zegl** [comment]
I'll update the PR to also include the LTG002.

**Comment by sjorge** [comment]
Ideally we verify it on the actual hardware but since there is usually little variance with Hue and my ws also returns the same range/have matching info on the site. It’s indeed probably OK to do both.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
