### PR TITLE
Add support for Ledvance Outdoor Plug, compact version

### PR DESCRIPTION
**Pull request by rkallensee**
In addition to the recently added [Ledvance Outdoor Plug](https://shop.ledvance.com/products/smart-outdoor-plug-eu) (white, with cord) there is a [new, compact version](https://www.ledvance.com/consumer/products/smart-home/smart-home-products-with-zigbee-technology/smart-home-components/smart-compact-outdoor-plug-c141283) (anthracite, only a plug without power cord) with type `AC31266`.

### CODE REVIEW

**Comment by rkallensee** [comment]
I'm sorry but I'm not sure about how to fix the duplicate Zigbee model issue raised in the tests. 😅 This is the `database.db` entry of the plug:

```
{"id":36,"type":"Router","ieeeAddr":"0xf0d1b800001a6380","nwkAddr":13843,"manufId":4489,"manufName":"LEDVANCE","powerSource":"Unknown","modelId":"Plug Value","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"Plug Value","manufacturerName":"LEDVANCE","powerSource":0,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":2,"swBuildId":"00203045"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc42f9","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":2,"swBuildId":"00203045","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1466202208},"lastSeen":1624908730441}
```

**Comment by Koenkk** [comment]
Since the modelID is the same, we cannot distinguish these devices. I propose to change https://github.com/Koenkk/zigbee-herdsman-converters/blob/d153fbc97fdcddc13a5d0d4ced4a55097dd8ac95/devices/ledvance.js#L7 to `'AC26940/AC31266'` instead.

**Comment by rkallensee** [comment]
Makes sense, done!

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
