### PR TITLE
Added Zigbee to RS485 controller support

### PR DESCRIPTION
**Pull request by xsp1989**
Added Zigbee to RS485 controller support

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `MODEL.png`, e.g. `ZB-PM01.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by xsp1989** [comment]
I have submitted all the product images and modified the names according to the modelID.Can you help me merge them?
[https://github.com/Koenkk/zigbee2mqtt.io/pull/3167](url)
[https://github.com/Koenkk/zigbee2mqtt.io/pull/3162](url)

**Comment by Koenkk** [comment]
Thanks!

**Comment by stefangries** [comment]
@xsp1989 The ZB-WB08 looks like a nice device. Where did you buy it?

**Comment by xsp1989** [comment]
> @xsp1989 The ZB-WB08 looks like a nice device. Where did you buy it?

You can send an email to sales@easyiot.tech for consultation.

**Pull request merged**
