### PR TITLE
Update Device.js GL-MC-001

### PR DESCRIPTION
**Pull request by MathiasAntunes**
Added meta for better support of GL-MC-001 led strip.

### CODE REVIEW

**Comment by Koenkk** [comment]
Removed the configureKey part, it's only used when the device has a `configure()` which this device hasn't. Thanks!

**Comment by MathiasAntunes** [comment]
Thank you for the amazing work on this project !

**Comment by MathiasAntunes** [comment]
Hi @Koenkk,

I've been using the Hass.io addon zigbee2mqtt-edge, and I would like to know how to pull request this code on the repo https://github.com/danielwelch/hassio-zigbee2mqtt. Is the add-on using code from this repo ?
I am also using docker images so I may need to recreate images. 
The problem is on each reboot, the image is pulled and created from the repo and the small modif I made disappear. Really anoying.
Thx !

**Comment by Koenkk** [comment]
Yes the addon is using code form this repo. As I've already merged your changes you should be good by just using the edge version of the addon (this will use these changes).

**Pull request merged**
