### PR TITLE
Created ozsmartthings.js

### PR DESCRIPTION
**Pull request by Scales82**
Created ozsmartthings.js for new OZ SMART RGBW ZIGBEE DOWNLIGHT.
https://www.ozsmartthings.com.au/products/oz-smart-rgbw-zigbee-downlight

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Scales82** [comment]
My pleasure. My first PR. Hope it works okay!

**Comment by Deblen** [comment]
Hi,  I purshased someof these Downlights, and having trouble trying to control them with HA and Zigbee2mqtt.
I have tried to follow instructions usung a converter but  no luck.

Latestest version HA as of 06/06/2023
Skyconnect dongle.
Installed Zigbee2mqtt.

I have attached 6 files which show a snapshot of the following:
js file calledOzSmart
Zigbee2mqtt yaml file
Log of Zigbee2mqtt on startup normal
Log of Downlight  when paired zigbee2mqtt
Showing in Zigbee2mqtt 
Showing result when clicking on Downlight

Am  I missing details in other yaml files.
Zig2mtt_2
Zig2mtt_1
Zig2mtt_6
Zig2mtt_5
Zig2mtt_4
Zig2mtt_3


In the.js  file I feel that there are commands missing from th to and from statements.

Hoping you can help.

Thanks Deblen

**Comment by Deblen** [comment]
Hi Scales82,
Thank you for the reply.
When I paired the Downlight, I got the following when I opened Zigbee2mqtt
Zig2mtt_1
I was unable tocontrol the light at all.

I then looked at the Zigbee2mqtt log, which displayed the followingwarning;
Zig2mtt_6
As it showed unsupported device, I followed the link dispayed, for , how to support new devices,  then searched for adding unsupported devices, which made mention of creating the .js file.

Hoping I can get them working
Thanks  Deblen

**Comment by Deblen** [comment]
Hi,

Thanks for the headsup on having a old version.

After researching on the Web, I wasabletofigure it out.

The key to upgradewastorestart HA, then install,via:  " https://github.com/zigbee2mqtt/hassio-zigbee2mqtt:.

Then wait awhile , ie walk away, the latest version then installed.

I now have it working.

Deblen

**Comment by Scales82** [comment]
> Hi, I am someone new to this and was linked to this by support at ozsmartthings. Where is the readme file so I can install this. My understanding is I can use this to update the firmware via HA.

There is no readme file. I added this JS file to the zigbee2mqtt project to support the ozsmartthings downlights. You need to refer to that project if you want more information. If you dont know what zigbee2mqtt's purpose is, or how to use it... You'll need to refer to their site or github for more information.

No this has nothing to do with firmware. Anyone who suggested otherwise is misleading you. I only added the support for the downlights, I am not the manufacturer nor the supplier. Just an enthusiast.

**Pull request merged**
