### PR TITLE
Add device HK-ZCC-A Sunricher Zigbee Curtain Motor Controller

### PR DESCRIPTION
**Pull request by tomamplius**

### CODE REVIEW

**Comment by Koenkk** [comment]
Updated the code a bit, can you check if it is still OK?

**Comment by Koenkk** [comment]
Note to self: after this merge https://github.com/Koenkk/zigbee2mqtt.io/pull/714

**Comment by tomamplius** [comment]
I'm sorry i'm lost on the invertion zigbee => ZIGBEE2MQTT ==> domoticz invert widget
With the current commit on ZIGBEE2MQTT log 
~~~
Apr 24 19:35:50 zigbee2mqtt npm[4764]: #033[34mZigbee2MQTT:debug#033[39m 2021-04-24 19:35:50: Received MQTT message on 'zigbee2mqtt/Salon : Volet roulant/set' with data '{"position": 86}'
~~~
my store is 14% close and 86% open
i think is good.
Just one widget is create on domoticz. I don't know if it need to expose button open/stop/close

**Comment by Koenkk** [comment]
@tomamplius looks good, 100 should be fully open. Can I merge this?

**Comment by tomamplius** [comment]
Yes

**Pull request merged**
