### PR TITLE
Update tuya.ts

### PR DESCRIPTION
**Pull request by Giexperience**
Please delete line 13333, which contains an incorrect 'Battery' DPID

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Giexperience** [comment]
Hello,

I apologize for bothering you. This is my first time adding a device to Zigbee2MQTT, and I was wondering if I could ask for your guidance.

I followed the tutorial and wrote the code for the device in the .ts file (it has been tested successfully locally). I also uploaded the images and created a .md file. These have already been successfully pulled by you. However, my device is still not supported by Zigbee2MQTT.

Does it take some time for Zigbee2MQTT to update before the device becomes supported? I need to determine the cause of the issue so I can fix any errors.

If you could reply, I would greatly appreciate it. Your help would be very valuable to me.

Best regards,
Raul

**Comment by Koenkk** [comment]
Device is support in the dev branch and will be supported in the next release (every 1st of the month)

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198

**Comment by Giexperience** [comment]
Hello,Koenkk. I’m very sorry to bother you again. As I mentioned earlier, this is my first time attempting to add a new device to Zigbee2MQTT, and I would greatly appreciate your help. In December 2024, I added a Tuya TS0601 Zigbee device, model GX03. I have already added the corresponding code to zigbee-herdsman-converters/src/devices/tuya.ts, as well as the images and MD files. Last time I asked you, you mentioned that the update would be made on the 1st of every month. I noticed that the MD file is indeed visible on the website now. However, when I try to pair this device with Zigbee2MQTT, it still cannot be recognized. The error message is:

z2m: Device '0xb43522fffe533ddb' with Zigbee model 'TS0601' and manufacturer name '_TZE284_8zizsafo' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new_devices/01_support_new_devices.html

I’m really at a loss on what went wrong, and I would be truly grateful for any guidance you can provide to help resolve this issue.

Thank you so much for your time and assistance!
Best regards
GIEXSMART

**Pull request merged**
