### PR TITLE
Add low battery alert for Tuya Thermostatic valve 

### PR DESCRIPTION
**Pull request by insipiens**
As per testing in [https://github.com/Koenkk/zigbee2mqtt/issues/3821](https://github.com/Koenkk/zigbee2mqtt/issues/3821)

homeassistant.js PR to follow later today/tonight

### CODE REVIEW

**Comment by insipiens** [comment]
I can't seem to get my zigbee2mqtt (homeassistant.js) to fork correctly.

@Koenkk: I have the following configuration change to add: **cfg.binary_sensor_battery_low**  if this could be done manually. Apologies again! 😻

    'TS0601_thermostat': [
        cfg.lock_child_lock,
        cfg.switch_window_detection,
        cfg.switch_valve_detection,
        cfg.sensor_battery,
        cfg.binary_sensor_battery_low,
        climate(5, 30, 'current_heating_setpoint', 0.5, [], [],
            ['schedule', 'manual', 'away', 'boost', 'complex', 'comfort', 'eco']),
    ],

**Comment by Koenkk** [comment]
Updating homeassistant.js is not needed anymore with the latest dev branch. Home Assistant devices are now discovered through the `exposes` in `devices.js`. 

In https://github.com/Koenkk/zigbee-herdsman-converters/pull/1742 there was a TuYa rework which also affects this pr, please update it accordingly.

**Comment by insipiens** [comment]
The impressive change is a bit out of my comfort zone, perhaps @drzony can advise to reach a quick resolutions? 

> 
> 
> Updating homeassistant.js is not needed anymore with the latest dev branch. Home Assistant devices are now discovered through the `exposes` in `devices.js`.
> 
> In #1742 there was a TuYa rework which also affects this pr, please update it accordingly.

The impressive change is a bit out of my comfort zone, perhaps @drzony can advise to reach a quick resolution?

**Comment by drzony** [comment]
Tuya data points were separated into 2 parts, data point and data type. Data type is the high byte, so in your case 1 (this means bool), and your data point is (366 - 1 * 256) = 110. So the thing to do is to add 110 to common.TuyaDataPoints between those two lines:
```js
    valvePos: 109,
    weekFormat: 111,
```
for example:
```js
    valvePos: 109,
    batteryLow: 110,
    weekFormat: 111,
```
and then change what you added to:
```js
case common.TuyaDataPoints:
    return {battery_low: value}
```
The data type is handled automatically, so if you have bool data point, then tuyaGetDataValue will return bool
Hope that helps, if not, feel free to ask again

**Comment by insipiens** [comment]
Closing, replaced by new PR #1745

**Pull request closed without merging**
