### PR TITLE
Add Silver Crest HG06335 device (LIDL)

### PR DESCRIPTION
**Pull request by paulomanuelp**
Add Silver Crest HG06335 device (LIDL) 

Model website: https://www.lidl.pt/pt/p/smart-home/silvercrest-sensor-de-movimentos-zigbee/p77012

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you also share the `data/database.db` entry of this device?

**Comment by paulomanuelp** [comment]
Yes sure:
{"id":16,"type":"EndDevice","ieeeAddr":"{{XX}}","nwkAddr":48768,"manufId":4619,"manufName":"_TZ1800_fcdjzz3s","powerSource":"Battery","modelId":"TY0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"TY0202","manufacturerName":"_TZ1800_fcdjzz3s","powerSource":3,"zclVersion":1,"appVersion":65,"stackVersion":2,"hwVersion":1,"dateCode":"2019.12.12"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b00194a1a7c","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[],"meta":{}}},"appVersion":65,"stackVersion":2,"hwVersion":1,"dateCode":"2019.12.12","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1605888204927}

**Comment by Koenkk** [comment]
Thanks!

**Comment by PedroQ** [comment]
This is the same device as the one added in this pull request: https://github.com/Koenkk/zigbee-herdsman-converters/pull/1748
How should these devices be added? Should these be a new device or their own or should we add them using the _whiteLabel_ property, keeping the vendor and model to TuYa? I'm planning on adding support (for other Lidl (Silvercrest) devices and I'm not sure what is the best approach.

**Comment by Koenkk** [comment]
I've already merged them together under: https://github.com/Koenkk/zigbee-herdsman-converters/blob/fc0273c5d1d338df5e972b6a9e7ffabd5f2da525/devices.js#L14937 , you can add new silvercrest devices there.

**Comment by rubenkr** [comment]
Absolutely awesome that the Lidl/Silvercrest motion sensors work out of the box with ZHA. So I wanted to thank you very much for your efforts. 

What is kind of annoying of this device is that it flushes red when motion is detected, green when it is gone. Has anyone an idea how to simply turn off all LEDs of the motion device?

Thank you all !

**Pull request merged**
