### PR TITLE
TuYa TS0121, add support power_outage_memory

### PR DESCRIPTION
**Pull request by artem-sedykh**
Hello!

In TuyaSmart application found support for "Restart status"

image

Using [this tutorial](https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html) received the following data:

**off**
image

**on**
image

**save_chanel_staus**
image

To set this option publish to zigbee2mqtt/FRIENDLY_NAME/set payload {"power_outage_memory": "on"} (or "off", "restore").

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by septillion-git** [comment]
Is it also possible to set this using device type specific configuration?

**Comment by Koenkk** [comment]
@septillion-git no

**Comment by shirou93** [comment]
@Koenkk @artem-sedykh   powerstrip TS0115 have this same feature in tuya app. How check it in z2m?

**Pull request merged**
