### PR TITLE
Update tuya.ts

### PR DESCRIPTION
**Pull request by dams74**
Update with new device
https://github.com/Koenkk/zigbee2mqtt/issues/18419

### CODE REVIEW

**Review by dams74 — COMMENTED** [review]
update [Tuya TS0601 TZE204_81yrt3lo](https://github.com/Koenkk/zigbee2mqtt/issues/18419#top)
#18419

**Review by dams74 — COMMENTED** [review]
sorry an other update

**Review by dams74 — COMMENTED** [review]
other update

**Review by dams74 — COMMENTED** [review]
update

**Review by dams74 — COMMENTED** [review]
update

**Review by dams74 — COMMENTED** [review]
update

**Review by dams74 — COMMENTED** [review]
the last i hope

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
