### PR TITLE
Add Acova Taffetas2

### PR DESCRIPTION
**Pull request by molusk**
Add Acova Taffetas2 heater support by copying Percale2 configuration as those have similar functions.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by sven337** [comment]
@molusk would you please take a look at https://github.com/Koenkk/zigbee2mqtt/issues/16961#issuecomment-1615738365, see if you see the same thing as I do?
namely when you set "heat", the device actually enters frost protection at 7°.

**Comment by molusk** [comment]
@sven337 I replied in your issue. Same thing here, don’t know how to fix it...

**Comment by daxter62** [comment]
i have the same issue with percale 2

**Pull request merged**
