### PR TITLE
Added support for Zemismart Curtain switch - Garage controller TS0003

### PR DESCRIPTION
**Pull request by dinhchinh82**
This is an universal curtain switch which can be used to control the curtain or garage (open/stop/close).
Product page:
1. Zemismart curtain switch (garage opener):
https://www.alibaba.com/product-detail/Zigbee-EU-Curtain-Wall-Switch-Compatible_62192599668.html

### CODE REVIEW

**Comment by dinhchinh82** [comment]
It's also needed to add the following configuration into the homeassistant.js file but I don't know the related repo:
   'TS0003_curtain': [cfg.cover_position],

**Comment by dinhchinh82** [comment]
@Koenkk could you please check this PR?
This one also related to the following PR:
https://github.com/Koenkk/zigbee2mqtt/pull/4506

Thank you.

**Comment by Koenkk** [comment]
- I've made some changes, please test if all devices still work as expected
- Please provide links for all 3 devices

Note to self: after this merge https://github.com/Koenkk/zigbee2mqtt/pull/4506

**Comment by dinhchinh82** [comment]
Product page:

1. Zemismart curtain switch (garage opener):
https://www.alibaba.com/product-detail/Zigbee-EU-Curtain-Wall-Switch-Compatible_62192599668.html
2. Larkkey dimmer:
http://order.larkkey.com/gooddetail.html?id=63
2. Larkkey curtain switch:
http://order.larkkey.com/gooddetail.html?id=64

**Pull request merged**
