### PR TITLE
Return brightness percent along with brightness value and state

### PR DESCRIPTION
**Pull request by YehorFedorov**

### CODE REVIEW

**Comment by Koenkk** [comment]
I'm fine with this however I feel we should only return `brightness_percent` when the users use or has previously used this. This in order to avoid having this value for many users who don't use it.

This means only add it when `meta.state.hasOwnProperty('brightness_percent') || key === 'brightness_percent'` is true.

**Comment by sjorge** [comment]
@Koenkk or maybe a toggle to include calculated values that would toggle including this. IIRC it has also been requested to include things like r,g,b values for color and others. So having a global toggle to enable this for people who want calculated/derived values might work too.

**Comment by YehorFedorov** [comment]
So, @Koenkk, should I add this flag? I can pass this flag in `meta` and add an additional logic for all of the convertors.

**Comment by Koenkk** [comment]
Not sure yet, want to avoid introducing an option for everything.

@sjorge what would be the use case of returning this value without ever setting it via `brightness_percent`?

**Comment by sjorge** [comment]
Personally I don't think it should be included in the default output, but it would be nice to toggle it for automation that use it.
If you're setting it via brightness_percent, you probably also want to read it via brightness_percent, so having a simple toggle to enable it would be nice.

We have other calculated values too which we are not returning currently, would be nice to have those also the toggle is set.

**Comment by Koenkk** [comment]
@sjorge yes I agree with that, in https://github.com/Koenkk/zigbee-herdsman-converters/pull/1409#issuecomment-660544627 I proposed to only return it when the user has previously used `brightness_percent` to control the brightness. @YehorFedorov could you add that?

**Comment by sjorge** [comment]
How will that interact with the state cache?

If you set it to day 50% once using the _percent variant... will it keep doing the conversion from them on? Will it only do it once? If it only does it once, it might end up in the state cache and get out of sync. If we always do it from them on, how do we disable it? (Reverse of the non converted one is also true)


~ sjorge (using phone)

**Comment by Koenkk** [comment]
After setting it once, it should always recalculate it when `brightness` is adjusted (so keep them in sync).

**Comment by sjorge** [comment]
Have a payload if ‘false’ could the disable it?

~ sjorge

**Comment by YehorFedorov** [comment]
@Koenkk yes, I can add that

**Comment by YehorFedorov** [comment]
@Koenkk I looked through all the convertors and I think that I need to add the same logic for convertors that depend on each other. For example, convertor `light_colortemp` returns only `color_temp` and `light_brightness` returns only `brightness`

I can repeat the same logic for this converts as for `light_onoff_brightness`. What do you think?

**Comment by YehorFedorov** [comment]
I guess it's easier for me to use a fork of this library.
Thanks for help!)

Closing this request

**Pull request closed without merging**
