### PR TITLE
Add new model tuya TA0601 "_TZE200_atpwqgml"

### PR DESCRIPTION
**Pull request by alesoft73**
Add a new model manufacturer 3 gang swicth.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by alesoft73** [comment]
> Thanks!

Thanks yopu for you big work for community!!!

I think the same 1/2/3 gang models should also be added.
What do you say ?

**Comment by Koenkk** [comment]
> I think the same 1/2/3 gang models should also be added.


What are the manufacturer names of these?

**Comment by alesoft73** [comment]
> > I think the same 1/2/3 gang models should also be added.
> 
> What are the manufacturer names of these?
This is in aliexpress..
https://it.aliexpress.com/item/1005001622518790.html

I think the name for 1..2 and 4 gang is the same "[TA0601 "_TZE200_atpwqgml"]

**Comment by alesoft73** [comment]
> > I think the same 1/2/3 gang models should also be added.
> 
> What are the manufacturer names of these?
This is in aliexpress..
https://it.aliexpress.com/item/1005001622518790.html

I think the name for 1..2 and 4 gang is the same "[TA0601 "_TZE200_atpwqgml"]

**Comment by Koenkk** [comment]
@alesoft73 they will have a different manufacturer name

**Comment by alesoft73** [comment]
@Koenkk I don't known, attend when arrive another switch and in case I add the devices ;)
Thanks another for your attention !

**Pull request merged**
