### PR TITLE
Adding support for Danfoss Icon floor heating thermostat and regulator

### PR DESCRIPTION
**Pull request by nagydavid**
Adding support for Danfoss Icon floor heating thermostat and regulator.

### CODE REVIEW

**Comment by nagydavid** [comment]
Hi All, 

So after testing the devices for a week, I encountered the following issue.:

- It is a bit struggling to pair the device. It has to be done multiple times, because the device gets disconnected and leaving the network. 
- So multiple non exiting entities are exposed due to the 15 setting of multiple device. I wonder cannot be sent through the UI how much entity we would like to expose. 
- The biggest problem is, that I am unable to control the device through home assistant. Even though I have multiple climate entities, when ever I am trying to set the a new temperature temperature for one of the climate entities only the first climate entity will be changed.

**Comment by nagydavid** [comment]
So this the output, if I am sending set_temperature from HA. Even though I am sending the request to endpoint 5, home assistant sends it to endpoint 1. As you can see the topic is not including the endpoint name.
```
Zigbee2MQTT:debug 2021-11-08 14:54:43: Received MQTT message on 'zigbee2mqtt/Heating System/set/occupied_heating_setpoint' with data '25.5'
Zigbee2MQTT:debug 2021-11-08 14:54:43: Publishing 'set' 'occupied_heating_setpoint' to 'Heating System'
Zigbee2MQTT:debug 2021-11-08 14:54:43: Received Zigbee message from 'Heating System', type 'attributeReport', cluster 'hvacThermostat', data '{"occupiedHeatingSetpoint":2550}' from endpoint 1 with groupID 0
```

**Comment by robertalexa** [comment]
@Koenkk Could you please help with the above?

If this related to what you did for the Hive SLR2 recently? See commit here https://github.com/Koenkk/zigbee2mqtt/commit/a41c00faea66cb14cb7002ca30c66245c0b76218

**Comment by Koenkk** [comment]
I think I've fixed the issue (it was not related to that commit).

@nagydavid could you check?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by nagydavid** [comment]
Hi @Koenkk and @robertalexa 

After the changes in the edge, everything works as it should

**Pull request merged**
