### PR TITLE
Update reporting for SPZB0001

### PR DESCRIPTION
**Pull request by sjorge**
- Configure existing reproting according to manual
- Add reporting for a few missing options

https://eurotronic.org/wp-content/uploads/2019/11/Spirit_ZigBee_BAL_web_DE_Okt.-2019.pdf

### CODE REVIEW

**Comment by sjorge** [comment]
@sti0 @allofmex this needs more testing, I just applied it but didn't notice a real change...

But I am not the one with the fancy graphs :)

**Comment by sjorge** [comment]
Should have checked the full log, that was because I fudged the devices.js and nothing got applied.

**Comment by sjorge** [comment]
So far so good, the 4 configured items localTemp, pIHeatingDemand, occupiedHeatingSetpoint, and unoccupiedHeating seem to now get published together!
```
zigbee2mqtt:debug 2019-12-27 12:45:57: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2200,"pIHeatingDemand":17,"occupiedHeatingSetpoint":2200,"unoccupiedHeatingSetpoint":1600}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 12:50:04: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"pIHeatingDemand":42}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 12:51:47: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"occupiedHeatingSetpoint":2200}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 12:51:47: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"unoccupiedHeatingSetpoint":1600}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 12:51:47: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"16387":2200}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 12:52:05: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2200}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 12:59:25: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"16386":0}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 13:00:07: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"pIHeatingDemand":34}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 13:01:50: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"occupiedHeatingSetpoint":2200}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 13:01:50: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"unoccupiedHeatingSetpoint":1600}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 13:01:50: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"16387":2200}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 13:02:08: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2200}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 13:10:10: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"pIHeatingDemand":34}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 13:11:53: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"occupiedHeatingSetpoint":2200}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 13:11:53: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"unoccupiedHeatingSetpoint":1600}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 13:11:53: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"16387":2200}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-27 13:12:11: Received Zigbee message from 'bedroom/radiator', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2200}' from endpoint 1 with groupID 0
```

There do seem to be ~10 min between each reporting unless a value got changed in between that triggered a report... so that's good I think.

I wonder if the 'report' interval restarts everytime it sends a message early due to a change...

**Comment by allofmex** [comment]
> tz.thermostat_local_temperature

`tz.thermostat_local_temperature` should be removed, you cannot WRITE the temperature TO device

> configureReporting.thermostatPIHeatingDemand
configureReporting.thermostatOccupiedHeatingSetpoint
configureReporting.thermostatUnoccupiedHeatingSetpoint

According to [eurotronic docs](https://eurotronic.org/wp-content/uploads/2019/01/Spirit_ZigBee_BAL_web_DE_view_V9.pdf) are all 3 not report-able but get reported every 600s automatically by device itself. Please try the 3 configure settings with lower max value, just to see if there is a difference.
But I guess that it will not change anything, so the 3 configure lines can be removed.

**Comment by sti0** [comment]
> According to [eurotronic docs](https://eurotronic.org/wp-content/uploads/2019/01/Spirit_ZigBee_BAL_web_DE_view_V9.pdf) are all 3 not report-able but get reported every 600s automatically by device itself. Please try the 3 configure settings with lower max value, just to see if there is a difference.
> But I guess that it will not change anything, so the 3 configure lines can be removed.

According to the docs the "Pre-Configured Reporting Interval" is 1200 sec. Recommended is 600sec. So that makes sense.

**Comment by Koenkk** [comment]
@sjorge please let me know when this is ready for merge.

**Comment by allofmex** [comment]
> "Pre-Configured Reporting Interval" is 1200 sec. 

I'm sorry, you are right. My fault.
Can someone explain to me what they mean by `Reportable N`? Doesn't make sense to me if it says on other page `Pre-Configured != Recommended`, wich would require reporting to be configureable.

**Comment by sti0** [comment]
On the functional docs from Eurotronic (which I'm not supposed to share) the following attributes are `Reportable Y`:

- Local Temperature
- Pi Heating Demand(valve position %)
- Occupied Heating Setpoint
- Unoccupied Heating Setpoint
- Set Valve Position
- Error Code
- Current Temperature Setpoint

I think it's simply an error in the official docs you linked above.

**Comment by sjorge** [comment]
> `tz.thermostat_local_temperature` should be removed, you cannot WRITE the temperature TO device

Correct, it is not writable, tz.thermostat_local_temperature also does not have a convertSet as can be seen here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/edd4ce980975e76792b153c1df8d4e2c2b04e0e4/converters/toZigbee.js#L490

This seems to be needed for https://github.com/Koenkk/zigbee2mqtt/issues/2359 though, as the convertGet is used to poll the localTemp attribute. I believe this is required to fix the previous mentioned issue, I included it here because it's such a small change a separate PR doesn't make sense. (Some other fix in zigbee2mqtt will also be needed though, as the c.key.includes() call behaves works on string and array so it has some weird results still.

> On the functional docs from Eurotronic (which I'm not supposed to share) the following attributes are `Reportable Y`:

@allofmex I was working of the 600s recomentation in the published doc and the info @sti0 mentioned, with the changes here I do seem to get reports at every 600s, sometimes sooner if a change is triggered... I am uncertain if a change trigger also results the reporting interval timer or not. But at least I seem to be getting more frequent updates now.

**Comment by sti0** [comment]
@sjorge The reporting is now more frequent on all of my three thermostats as you can see at the following graphs:
image *"Raumthermostat" (orange line) is a Xiaomi Bluetooth thermometer which not reports this frequent.
image
image

For a better monitoring for this one I set the offset to 0 and disabled my offset adjustment.

Just fyi, I returned my two devices with the "old" firmware and replaced them with two devices with the newest firmware. So this reporting test is done with devices of - I think - newest firmware ("softwareBuildID":"22190930","dateCode":"20191014")

**Comment by sjorge** [comment]
Nice, shame they are not providing firmware upgrades though. But good to see it is working better now. @Koenkk i think this is good to go.

**Comment by allofmex** [comment]
@sjorge 
Please change
`configureReporting.thermostatPIHeatingDemand(endpoint, 0, repInterval.MINUTES_10, 25);`
to 
`configureReporting.thermostatPIHeatingDemand(endpoint, 0, repInterval.MINUTES_10, 1);`
Else valve position will be reported only in >25% steps! (as visilbe in sti0's last screenshot (blue))

I'm ok with the other changes

**Comment by sjorge** [comment]
I can’t change it now, traveling. But @koenkk can before merging if he merges before I am back.

~ sjorge

**Comment by sjorge** [comment]
Updated, was a bit of a pain on my phone.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
