### PR TITLE
Fix FP1 Firmware Version Display

### PR DESCRIPTION
**Pull request by Nixon506E**

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you give some more context to this?

**Comment by Nixon506E** [comment]
Previously the OTA screen showed no value for the firmware version of the FP1

**Comment by Koenkk** [comment]
I see, thanks for the fix!

**Comment by ajunio3** [comment]
There's one firmware update available for Aqara FP1 (version 58) in Aqara home. How can we have it on OTA in Z2M?
FP1 New Firmware

**Pull request merged**
