### PR TITLE
Invert position _TZE200_gubdgai2

### PR DESCRIPTION
**Pull request by leroyloren**
https://github.com/Koenkk/zigbee-herdsman-converters/issues/4040#issuecomment-1100924941

### CODE REVIEW

**Comment by leroyloren** [comment]
@Koenkk yes, true.

obrazek

**Comment by Koenkk** [comment]
Then it is already correct, so no need to invert.

**Comment by leroyloren** [comment]
I don't know if we understand each other, but according to the attached picture it is 0 = state CLOSED, but the blind is open at that moment

In the used automations it is necessary to use the inverted state.

**Comment by Koenkk** [comment]
I see, thanks for double checking.

**Comment by leroyloren** [comment]
Thanks 👍

**Pull request merged**
