### PR TITLE
Update müller_licht.js

### PR DESCRIPTION
**Pull request by copystring**
Fix to make it work with https://github.com/o0shojo0o/ioBroker.zigbee2mqtt

### CODE REVIEW

**Comment by Koenkk** [comment]
Removing the legacy converters creates a breaking change. You can disable the legacy behaviour by passing `legacy: false` to the converter options.

**Comment by copystring** [comment]
Okay. With legacy: false the problem is that the exposed is wrong. For example one exposed is color_wheel which changes to color_move. https://github.com/o0shojo0o/ioBroker.zigbee2mqtt doesn't know about this change when connecting via websocket. Where or how would it get the correct exposed data?

**Comment by copystring** [comment]
Right. I forgot exposed don't matter with legacy so I changed the pull request. Is this ok now? The exposed data was wrong but is working now.

**Comment by Koenkk** [comment]
Perfect, thanks!

**Pull request merged**
