### PR TITLE
[Lixee] Add Standard Rate and Fix Standard HCHP Rate

### PR DESCRIPTION
**Pull request by SilentT-FR**
FIX
Add EASD02 for Standard HCHP Rate

NEW
Add STANDARD BASE rate

@vk496 Its OK ?

### CODE REVIEW

**Comment by Koenkk** [comment]
@vk496 could you check this?

**Comment by vk496** [comment]
@Koenkk already reviewed. Just one breaking change in varname I think

**Comment by vk496** [comment]
@Koenkk please check my annotation in the PR. I suspect that there is a typo in the code you merged

**Comment by Koenkk** [comment]
Ah, I think you forgot to submit the review , we cannot see your comments.

**Comment by vk496** [comment]
Weird, I don't know how to make it public. Is line 229, variable `fname` changed to `name`

**Comment by Koenkk** [comment]
@vk496 fixed, next time use "Add single comment"


Screenshot 2022-04-10 at 09 54 33

**Comment by vk496** [comment]
@Koenkk sorry, did from the mobile app and didn't provide me any option. Just "send" 😓

**Comment by SilentT-FR** [comment]
Sorry for this mistake https://github.com/Koenkk/zigbee-herdsman-converters/commit/9ecc677c49d76ab1cf7ad41647f9f085f8708f04

**Pull request merged**
