### PR TITLE
Update vesternet VES-ZB-SWI-015

### PR DESCRIPTION
**Pull request by devildant**
fix the impl, the measurement are provide on endpoint11 not 1

proof : 
paper documentation : 
image

result on Z2M:
image

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by chris-1243** [comment]
I don't know if it is the right place but it seems the fix is not present on 1.34.0-dev commit: 87f6b9e.

I am exactly facing the same issue and the binding is not correct.

Any work around until the issue is solved ?
[sunricher_error.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/13649969/sunricher_error.txt)
[Zigbee-herdsman.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/13649970/Zigbee-herdsman.txt)

I have added some log file if it helps

**Comment by martyn-vesternet** [comment]
@chris-1243 if you're using the VES-ZB-SWI-015 device from Vesternet then there's an external converter at https://github.com/vesternet/zigbee2mqtt-herdsman-converters which should fix this issue now. It should hopefully configure the device correctly during pairing based on its reported firmware version.

It seems to work OK for me on the two versions of test device that I have here, perhaps you can check it on yours?

**Comment by chris-1243** [comment]
I just had a try on the latest-dev and it is not implemented.

Using your file as an external converter, the pairing went successful and the endpoints were ALL corrects even the reporting (endpoint 11 based on my firmware).

It seems to be perdectly working on my side.

Many thanks for your effort

**Pull request merged**
