### PR TITLE
Additional whiteLabel Gledopto Multi-mode LED controllers

### PR DESCRIPTION
**Pull request by pjxturner**
Gledopto 5-in-1, 3-in-1 or 2-in-1 LED controllers have a physical button that allows them to switch between up to 5 different modes of operation.  Each of these modes result in the controller being identified by z2m as a different `modelId`.
Either `GL-C-008P` -> RGBCCT, `GL-C-007P` -> RGBW, `GL-C-003P` -> RGB, `GL-C-006P` -> CCT or `GL-C-009P` -> DIMMER.

The precedent for dealing with these devices, established for GL-C-001P [here](https://github.com/Koenkk/zigbee-herdsman-converters/issues/3016#issuecomment-1032881922), and followed for GL-C-002P [here](https://github.com/Koenkk/zigbee-herdsman-converters/pull/4318), is to add each Multi-mode controller as a `whiteLabel` device of the "most capable" or somewhat arbitrarily "default" mode it supports. _(I assume this is because you can't add a whiteLabel model to multiple base devices)._

This PR adds the Gledopto Multi-mode LED controllers that have subsequently been released, so that they can be referenced, and picked up by the z2m documentation.

I have added the 5-in-1 and 3-in-1 controllers to `GL-C-008` as these all support RGBCCT (as one of their modes), and I've added the 2-in-1 controllers to `GL-C-006P` as they support CCT (in addition to DIMMER).  The other modes can then be referenced from the documentation.

I've referred to the Model GL-C-003P 2in1 as `model: 'GL-C-003P_1'` to distinguish from `model/modelId: 'GL-C-003P'`

For completeness, I have also added the mini versions of the single-mode controllers as whiteLabel versions of their original models.

### CODE REVIEW

**Comment by pjxturner** [comment]
For posterity's sake, here's my workings.
Gledopto LED Controller Matrix

**Comment by Koenkk** [comment]
Thanks!

**Comment by Ltek** [comment]
@pjxturner @Koenkk do you know if any of these controllers (or any others from another manufacturer) can have the RGB and CCT on at the same time to maximize the brightness when wanting 'white' color?  I searched all over the docs and dont find anything that says any of them can, and I bought/tested 201Pand dont see any way (in the web UI device properties) to have the RGB on when the Cool White and/or Warm White chip is on?

thx for the help!

**Comment by pjxturner** [comment]
Hi @Ltek,

As you've experienced, the controllers I listed above control the colour and the white channels separately.

But, a couple of years ago, Gledopto produced a GL-C-007(MIX) and a GL-C-008(MIX) which I believe does what you are looking for.  I asked them about this when they launched and they answered [here](https://www.reddit.com/r/Gledopto/comments/z8lw0v/comment/j4iwwbp/?context=3).

The RGBCCT version (GL-C-008(MIX)) seems to still be [available](https://www.aliexpress.com/item/1005009147866590.html).

I never went ahead and purchased one, so can't comment on the Z2M converter support, although I typically run external converters for my Gledopto devices.

Back in the day, Gledopto did make 1ID and 2ID controllers which had the same effect of either mixing both channels or controlling them separately through either one or two endpoints.  A discussion of this issue is [here](https://github.com/Koenkk/zigbee2mqtt/issues/3436), so I can't see why these wouldn't be able to be supported, if they aren't already.

Good luck.

**Pull request merged**
