### PR TITLE
CR Home TS0204 Gas Sensor Remove battery

### PR DESCRIPTION
**Pull request by robertalexa**
Just removing the battery related exposes.

Battery_low in my case reports False
Battery reports Null

The device gets powered via mains, no internal battery advertised by the sellers, idk why this exposed battery.

Looking at previous PRs i couldn't find anything for this device. Looking at git log, the code shows up first time when the code base was split by device file, but i can't find any history older than that, although I have not done serious digging into the original file.

When you unplug the device from the mains, the device powers off, sign of no internal battery.

Also the device shows as mains powered in z2m - DC Source
image

### CODE REVIEW

**Comment by Koenkk** [comment]
@robertalexa is your device labeled as CR Smart home? Otherwise I also propose to move this device to tuya.js en change the vendor to tuya

**Comment by robertalexa** [comment]
@Koenkk Not sure to be honest. It appears the CR Smart Home website is now dead, so I have no reference of what the original product looks like? http://crsmarthome.nl/

My device looks identical to the image on z2m.io Here is the link to the device listing
https://www.aliexpress.com/item/1005001692323775.html

image

Not sure what to say about the best approach?

**Comment by robertalexa** [comment]
I was just trying to provide the device from database file and weirdly, the file is not available in Studio Code?

**Comment by Koenkk** [comment]
CR smart home looks dead indeed, might be better to move everything to tuya.js.

Not sure why vscode doens't show if, if your file browser shows it vscode should also show it, nothing has been changed there.

**Comment by robertalexa** [comment]
I can try to have a look and move it to tuya one of these days. Leave my PR open for now.

As with VS code, turns out is has a File Exclude `**/*.db` hence.... yeah... All good, PEBKAC

**Comment by robertalexa** [comment]
Hi @Koenkk 

Apologies for the delay, had some personal situations and didn't get a chance to work on this.

I can see that as of last release you have already migrated all CR Home devices to Tuya as a result of someone else doing a PR on z2m.io https://github.com/Koenkk/zigbee2mqtt.io/pull/1252

As a result, I have brought this branch back in line with master, and replicated the work in the tuya.js file instead of the original CR.

Thanks

**Comment by Koenkk** [comment]
> Apologies for the delay, had some personal situations and didn't get a chance to work on this.

No problem! Hope everything is well, thanks as always!

**Pull request merged**
