### PR TITLE
UNSUPPORTED_ATTRIBUTE

### PR DESCRIPTION
**Pull request by ashottonoyan**
Keeps throwing error and spamming the network

### CODE REVIEW

**Comment by Koenkk** [comment]
Is it also removed from the exposes?

**Comment by ashottonoyan** [comment]
Actually no, I'm assuming since it's extending xiaomi, needs to be disabled explicitly. Not sure how to do that.

**Comment by Koenkk** [comment]
Use `extend: xiaomiExtend.light_onoff_brightness_colortemp({disableSwitchPowerOutageMemory: true}),`

**Comment by ashottonoyan** [comment]
I think it's rather `disablePowerOnBehavior: true`. Pushed.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
