### PR TITLE
Add support for Müller Licht 45727 Amela 42cm

### PR DESCRIPTION
**Pull request by Pferdebockwurst**
This adds support für the ceiling lamp "Amela" made by "Müller Licht". The manufacturers model number is 45727.

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by Pferdebockwurst** [comment]
Sure, can you tell me how?

**Comment by Pferdebockwurst** [comment]
{"id":66,"type":"Router","ieeeAddr":"0xa4c13800ab3b0fe7","nwkAddr":17480,"manufId":4635,"manufName":"MLI","powerSource":"Mains (single phase)","modelId":"Bulb white","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,4111,65376],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"Bulb white","manufacturerName":"MLI","powerSource":1,"zclVersion":3,"appVersion":0,"stackVersion":2,"hwVersion":0,"swBuildId":"MDA60332"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":555,"colorMode":2,"currentX":30295,"currentY":27192,"colorTemperature":454,"startUpColorTemperature":65535}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":0,"swBuildId":"MDA60332","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1667642752633,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
