### PR TITLE
fix(inovelli): add missing param 121 FanTimerMode

### PR DESCRIPTION
**Pull request by JefeDavis**
fanTimerMode was implemented on herdsman in https://github.com/Koenkk/zigbee-herdsman/pull/881

new params were introduced in #6936 but fanTimerMode was missed, this PR adds that missing parameter

### CODE REVIEW

**Comment by Koenkk** [comment]
@InovelliUSA could you review this?

**Comment by JefeDavis** [comment]
@Koenkk any chance we can get this change in before the release?
@InovelliUSA do you have a sec to review?

**Comment by InovelliUSA** [comment]
Yes, this looks good to be merged.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
