### PR TITLE
Added Moes Human presence sensor

### PR DESCRIPTION
**Pull request by Burki24**
A new launched Radar-Sensor, using 12V.

### CODE REVIEW

**Comment by Burki24** [comment]
double work. :-(

**Comment by prokudin07** [comment]
yes, but you have DP 6
image

I'll add tomorrow

**Comment by Burki24** [comment]
I'm adding it right now, if it's okay for you.

**Comment by Burki24** [comment]
I'm adding it right now, if it's okay for you.

**Comment by Burki24** [comment]
I'm adding it right now, if it's okay for you.

**Comment by Koenkk** [comment]
@prokudin07 already made a pr for this: https://github.com/Koenkk/zigbee-herdsman-converters/pull/4179

**Comment by prokudin07** [comment]
Yes, of course! Exclelent

**Pull request closed without merging**
