### PR TITLE
Update WB-MSW v.3 converter

### PR DESCRIPTION
**Pull request by wb-adegtyarev**
Added a converter for IR commands, new settings and OTA.

This is one of three pull requests:
https://github.com/Koenkk/zigbee2mqtt.io/pull/1157
https://github.com/Koenkk/zigbee-herdsman/pull/497

### CODE REVIEW

**Comment by wb-adegtyarev** [comment]
@Koenkk Please help with validation error.

**Comment by Koenkk** [comment]
thanks!

**Comment by wb-adegtyarev** [comment]
> thanks!
@Koenkk Hi, I added a `occupancy_timeout` to the converter, due to the fact that the value was written to the wrong endpoint.
Now, after removing the `occupancy_timeout` from the converter, I get an error when writing the attribute.

The reason, I think, is that once, in order to bypass the error, we made `default: '4'`: https://github.com/Koenkk/zigbee-herdsman-converters/pull/3529#discussion_r771823624

```
Zigbee2MQTT:error 2022-01-24 09:12:32: Publish 'set' 'occupancy_timeout' to '0x842e14fffe8b184e' failed: 'Error: Write 0x842e14fffe8b184e/4 msOccupancySensing({"pirOToUDelay":35}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
```

**Comment by Koenkk** [comment]
ah sorry, could you make a pr to fix this?

**Comment by wb-adegtyarev** [comment]
> ah sorry, could you make a pr to fix this?
Oh sure: https://github.com/Koenkk/zigbee-herdsman-converters/pull/3733

**Pull request merged**
