### PR TITLE
Livolo Dimmer and Switch bug fixes

### PR DESCRIPTION
**Pull request by Piscator74**
Already commented on these bugs quite a while back and finally found some time to commit the fixes.
See discussions:
* https://github.com/Koenkk/zigbee2mqtt/issues/5516#issuecomment-811482988
* https://github.com/Koenkk/zigbee2mqtt.io/pull/607#issuecomment-812860097

For the update in fromZigbee.js:
I left the original code (msg.data[10] === 7), but that does not work for me.

For the updates in devices.js:
That fixes exceptions related to endpoints (and actually makes the dimmer work in combination with the fix above).

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by resh1309** [comment]
Can I ask a question regarding the Livolo switch. Will this fix be working only with zigbee2mqtt or do you need the Livolo gateway to connect to zigbee2mqtt?

**Comment by Piscator74** [comment]
The livolo dimmer needs to pair one time with the original livolo gateway. After that, you can pair it with zigbee2mqtt and you do not need the livolo gateway anymore. This is an open issue and is discussed in the links above.

The livolo 2-gang switch should work flawlessly.

Note that you cannot connect a Livolo gateway to zigbee2mqtt. That works only with the Livolo app and is proprietary.

**Comment by resh1309** [comment]
Thank you for your reply! 

I bought the following livolo switch
https://www.livolo.nl/a-64026688/modules-sr-touchschakelaar/livolo-module-sr-zwart-dimmer-universeel-zigbee-wifi-livolo-app/#description

Any experience on this one? 

When the livolo switch is paired with the livolo hub, you say that it is possible after that to pair with zigbee2mqtt. Is that only on channel 26 or is that then not necessary anymore to add in yml script? 

You also refer to the open issue 1 time registration on luvolo hub,  those are still in discussion? Do you mean you are still aiming to get livolo switches up and running without 1 time registration on livolo hub?

**Comment by Piscator74** [comment]
I have a similar dimmer and it works great. 

For all the livolo devices you need to configure the 'advanced' settings it as is on the man pages. It will take you some time to set it up when you are trying it for the first time.

This is an open source project, so anyone who has time and the inclination, can fix it.

```
advanced:
  log_level: info
  ext_pan_id:
    - 33
    - 117
    - 141
    - 25
    - 0
    - 75
    - 18
    - 0
  channel: 26
```

**Pull request merged**
