### PR TITLE
Update `inovelli.ts` with new parameters exposed in new VZM35 firmware

### PR DESCRIPTION
**Pull request by futurexdesign**
Related update to cluster definitions: https://github.com/Koenkk/zigbee-herdsman/pull/881

### CODE REVIEW

**Comment by Koenkk** [comment]
@InovelliUSA could you review this?

**Comment by Koenkk** [comment]
Thanks!

**Comment by blubaru14** [comment]
@futurexdesign is `fanTimerMode` missing from this PR or I am just missing something obvious. thanks!

**Comment by JefeDavis** [comment]
@blubaru14 it seems to have been added to herdsman but did not make it's way into the converter

**Comment by futurexdesign** [comment]
Thanks @JefeDavis , I completely missed that one.

**Pull request merged**
