### PR TITLE
Improves OTA image sub-element parsing

### PR DESCRIPTION
**Pull request by PedroLamas**
From what I can see, there are a few issues with the current implementation, specifically it will always parse the first sub-element only (as the offset is always set to `headerLength`)

This ensures proper parsing of sub-elements as expected.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks, do you have an OTA file to test again? I think we can add that as a test case then.

**Comment by PedroLamas** [comment]
I haven't found an OTA image with multiple sub-elements yes (though I've only checked 2 from IKEA and 1 from Salus), but I will see if I can find one and then add some test cases.

On a side note and in case you are interested, I've had considerable success parsing the EBL from the sub-elements! Here's my hacky code: https://github.com/PedroLamas/ebl-parser/blob/master/index.js

**Comment by PedroLamas** [comment]
Ok, got a few of them from [ledvance](https://update.ledvance.com/firmware-overview?submit=all) that fail with the current implementation but pass with my changes!

Now to write some tests...

**Comment by PedroLamas** [comment]
@Koenkk tests added!

Be aware, I've added a few files on this (~800Kb of data)!

**Comment by Koenkk** [comment]
Big thanks! 🏅

**Pull request merged**
