### PR TITLE
Added Salus thermostat fc600 (#917)

### PR DESCRIPTION
**Pull request by frozenwave11**
Adding changes for fc600 thermostat.

Big thanks to Chrischi- for involving.

### CODE REVIEW

**Comment by frozenwave11** [comment]
@Koenkk I'm trying to add thermostat but it fails because of line limits 
/home/travis/build/Koenkk/zigbee-shepherd-converters/devices.js
  2284:1  error  Line 2284 exceeds the maximum line length of 120  max-len
  2296:1  error  Line 2296 exceeds the maximum line length of 120  max-len

**Comment by Chrischi-** [comment]
@frozenwave11 
look here what i did in this case:
https://github.com/Koenkk/zigbee-shepherd-converters/blob/80c781b142e0f97a3bc48bcfa260e5d4e1a27501/converters/fromZigbee.js#L204

**Comment by frozenwave11** [comment]
@Chrischi-  Thanks, I fix it now, but still can't pass due to the line limit

**Comment by Chrischi-** [comment]
> @Chrischi- Thanks, I fix it now, but still can't pass due to the line limit

That‘s because you have to do it with the devuces.js. My link was only an example how to fix the issue.

**Comment by frozenwave11** [comment]
@Chrischi-  Omg I see, haven't read errors correctly, now I will fix it

**Comment by frozenwave11** [comment]
Hi @Koenkk 
When I try to get local temperature for first time it works, 
https://pastebin.com/yGTAwvAW

but when I second time try to get local_temperature, I don't get result.
this is the output. 
https://pastebin.com/LY09xWSP

Maybe you can help solve this ?

**Comment by Koenkk** [comment]
@frozenwave11 this is a non issue which will be fixed (see https://github.com/Koenkk/zigbee2mqtt/issues/518#issuecomment-436392746)

**Comment by Chrischi-** [comment]
@frozenwave11 
do you need some additional help?

**Pull request closed without merging**
