### PR TITLE
plugwise tom: support valve position

### PR DESCRIPTION
**Pull request by vhdirk**
This devices looks somewhat similar to a eurotronics thermostatic valve, but this could just be a coincidence. I wonder if the valve position command could/should therefore be generalized.

I can control the valve motor but feedback would be appreciated. @JanJaapKo you also have such a device I believe?

### CODE REVIEW

**Comment by JanJaapKo** [comment]
@vhdirk  Yes I've got one but still need to build it in (haven't gotten to draining the heating system since the radiator now only has a manual valve so it requires some old school plumbing). The valve doesn't seem to be controllable when it's just lying on my desk. I did get the impression I could get feedback on the position (for Domoticz I already created a PR on zigbee2mqtt plugin to have it supported there on the front end). Using the developer console I was playing around a bit but did not yet see how I could send a position to the valve (although that probably should be possible).

The Plugwise documentation suggests that they follow the Zigbee protocol standard which I downloaded from [here](https://zigbeealliance.org/wp-content/uploads/2019/12/07-5123-06-zigbee-cluster-library-specification.pdf), see section 6.3

**Comment by vhdirk** [comment]
I only found out how to drive the motor by sniffing traffic between the Tom and Adam. Then, after seeing the command was 0x4001, I searched around in herdsman for similar devices. The implementation in this MR is a fairly direct copy of the eurotronics valve. That works although it will only reliably drive to either 0% or 100%. Anything in between will not always drive the motor. I'm also not sure if there's an 'auto' mode to let the Tom drive the motor based on the temperature set point.

**Comment by JanJaapKo** [comment]
Ok, I've placed the Tom plus the actual valve together in my desk, will run some test tonight. BTW I found the frontend of z2m very helpful, the developers pane allows you to read and write to the device, helps you play around and find out what works and what not.

**Comment by vhdirk** [comment]
Yes that's what I did. Using the developer console I was able to set the motor to fully open or fully closed. But in my case, everything in between was not that reliable. Perhaps a calibration is needed. I'll have to sniff again to see how that is done and how it should be implemented in z2m.

**Comment by JanJaapKo** [comment]
OK, I've been playing around a bit with the Tom using the z2m dev console. I can send values for: 
- SystemMode (0 for off, 1 for auto)
- occupiedHeatingSetpoint (set point in deg Celcius * 100)

Sending any other attribute leads to an error (the zigbee spec also mentioned that PiHeatingDemand is read-only). Point is that the valve doesn't seem to move (at least it is not reporting any movement on PiHeatingDemand).

Interestingly, z2m also reports now and then the following:
`Received Zigbee message from 'Radiator badkamer', type 'attributeReport', cluster 'hvacThermostat', data '{"16392":12}' from endpoint 1 with groupID null` which moves a bit up and down between 12 and 15
Which I do not really understand. Apparently it is sending information outside the standard zigbee attributes......

Small annoyence: when sending occupiedHeatingSetpoint there is no reply to acknowledge the reception of the new setpoint (which does work for SystemMode).

Did you get any further?

**Comment by vhdirk** [comment]
I got that too. Since the valve position command is 0x4001, I've been looking at the eurotronics valve implementation as it uses the same command (is that in the zb spec?). 
For the eurotronics valve, 16392 (0x4008) is bit field with flags. Perhaps Plugwise is doing something similar?

I haven't been able to move the valve without sending the 0x4001 command. That's also the only way I've noticed it working in combination with the Adam.

What does system mode do? I have limited knowledge of zb attributes, I mainly looked at other trv devices in z2m and been sniffing the Plugwise system.

**Comment by JanJaapKo** [comment]
Well the way I was expecting it to work is to send a temperature setpoint and let the thing sort it out for itself (I do not want to control the valve position myself......) There seems to be also some weekly schedule thing, perhaps that is the way in....

**Comment by vhdirk** [comment]
I don't really know. I have had an Adam and a couple of Toms in use for over a year now. In that time I can't say I have seen any other valve position than 0 or 100%. The Adam is always fully in control. It won't even activate the motors if you haven't attached it to a boiler.

**Comment by JanJaapKo** [comment]
I've dug through the logging a bit, I see the Tom also publish 0x4008/16392, 0x4002/16386 and 0x400c/16396. I created an fromZigbee thingy for that to get it logged in Domoticz as well, hope to make some sense out of it.......

**Comment by vhdirk** [comment]
Do you mind sharing that thingy? As far as this PR goes, I think it does what I set out to do. Perhaps the Tom has more tricks up its sleeve, but for now I don't think there's much to add.
I'll be looking at the Lisa next.

**Comment by JanJaapKo** [comment]
OK, hthe above looks like crap bit can't get it fixed, sorry for that

**Comment by vhdirk** [comment]
My goal is to reverse engineer the plugwise Adam using only open-source bits (either standalone or as a Home Assistant module, not sure yet). The Adam does control the valve position, even when no other temperature sensor is present, so I guess that's just how they work.

I haven't been able to invest much time since creating this MR. I hope to do some more digging this week. Starting from a clone of the eurotronics valve, I just removed everything that did not work. So what's left didn't yield an error in the console. Whether the Tom accepted it or not is another question.

I did see a number of responses with code 0x4008. I don't know what these mean. Again, the only other device that sends messages with that identifier is the eurotronics valve, where these are a set of bitflags. The other updates are also pretty much unknown to me.

I also haven't done any long-running tests yet but I did see 0x4002 and 0x400c pass by. If you get these at regular intervals I would also assume these are status messages of sorts.

**Comment by JanJaapKo** [comment]
Hey,

I've received feedback from the Plugwise helpdesk: they indeed only control the valve position and do not send a temperature setpoint to it. I've asked them for explanation of the other attributes, awaiting reply now...(first answer took a week.....)

Their reply (assuming you're Dutch too:

> <html>
<body>
<div dir="ltr" style="color: rgb(34, 34, 34); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Beste Jan-Jaap,<br>Wat leuk dat je aan een zigbee2mqtt integratie werkt. Bij de Tom sturen we alleen aan op valve position:</div><span style="color: rgb(34, 34, 34); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> </span>

Attribute | Attribute Id | Default | Data | Read/Write (R/W) | Mandatory/ | Manufacturer Specific | Reportable
-- | -- | -- | -- | -- | -- | -- | --
Value | type | Optional (M/O) | (Y/N) | (Y/N)
Set Valve Position | 0x4001 | (min=0x00, max=0x64) | 0x20 (int8u) | RW | O | Y | N

<div dir="ltr" style="color: rgb(34, 34, 34); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div dir="ltr" style="color: rgb(34, 34, 34); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Is dit zo voldoende?</div>
</body>
</html>

**Comment by vhdirk** [comment]
Cool, I wasn't sure if they would even like third-party integrations like this. (I'm Belgian btw).

From what I can tell, going from 0 to 255 seems to be akin to calibration. It seems to run for a long time when I do that.
I'll have another go at it tomorrow. Thanks for your help already. My practical knowledge of both zigbee and mqtt is pretty limited.

**Comment by Koenkk** [comment]
@JanJaapKo you are missing a `[`, sholud be `mosquitto_pub -h localhost -t 'zigbee2mqtt/Radiator badkamer/set' -m '{"read":{"attributes":[16385,16386,16392,16396],"cluster":"hvacThermostat","options":{"manufacturerCode":4466}}}'`

**Comment by JanJaapKo** [comment]
@Koenkk  it wasn't the mosquitto_pub styatement that is causing issues but the below fragment from `toZigbee.js`:
```
    plugwise_valve_position: {
        key: ['plugwise_valve_position', 'valve_position'],
        convertSet: async (entity, key, value, meta) => {
            const payload = {0x4001: {value, type: 0x20}};
            await entity.write('hvacThermostat', payload, manufacturerOptions.plugwise);
        },
        convertGet: async (entity, key, meta) => {
            await entity.read('hvacThermostat', [0x4001], manufacturerOptions.plugwise);
        },
    },
```
Where I expect that the ```convertGet/entity.read``` part would trigger a read back over zigbee network of the value that was written to the device, as a sort of acknowledgement. But that does not seem to happen. I do not see anything in the logfiles on a read command and also no errors, I only see the write command. See logfile extract below:

I send an update of valve position at 20:22:16, nicely sent out over zigbee (valve is moving). Some data comes back but not for attribute 0x4001/16385 unless I explicitly ask for it via MQTT (at 20:23:50)

```
debug 2022-04-05 20:22:16: Received MQTT message on 'zigbee2mqtt/Radiator badkamer/set' with data '{"valve_position":25}'
debug 2022-04-05 20:22:16: Publishing 'set' 'valve_position' to 'Radiator badkamer'
debug 2022-04-05 20:22:27: Received Zigbee message from 'Radiator badkamer', type 'attributeReport', cluster 'hvacThermostat', data '{"pIHeatingDemand":26}' from endpoint 1 with groupID null
info  2022-04-05 20:22:27: MQTT publish: topic 'zigbee2mqtt/Radiator badkamer', payload '{"battery":100,"control_sequence_of_operation":"heating_only","data_16386":0,"data_16392":16,"data_16396":8961,"linkquality":255,"local_temperature":19.28,"local_temperature_calibration":0.1,"occupied_heating_setpoint":24,"pi_heating_demand":10,"programming_operation_mode":"setpoint","remote_sensing":{"local_temperature":"internally","occupancy":"remotely","outdoor_temperature":"internally"},"running_state":"heat","system_mode":"off","valve_position":2}'
debug 2022-04-05 20:23:30: Received Zigbee message from 'Radiator badkamer', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":1987}' from endpoint 1 with groupID null
info  2022-04-05 20:23:30: MQTT publish: topic 'zigbee2mqtt/Radiator badkamer', payload '{"battery":100,"control_sequence_of_operation":"heating_only","data_16386":0,"data_16392":16,"data_16396":8961,"linkquality":255,"local_temperature":19.87,"local_temperature_calibration":0.1,"occupied_heating_setpoint":24,"pi_heating_demand":10,"programming_operation_mode":"setpoint","remote_sensing":{"local_temperature":"internally","occupancy":"remotely","outdoor_temperature":"internally"},"running_state":"heat","system_mode":"off","valve_position":2}'
debug 2022-04-05 20:23:30: Received Zigbee message from 'Radiator badkamer', type 'attributeReport', cluster 'hvacThermostat', data '{"16392":11}' from endpoint 1 with groupID null
info  2022-04-05 20:23:30: MQTT publish: topic 'zigbee2mqtt/Radiator badkamer', payload '{"battery":100,"control_sequence_of_operation":"heating_only","data_16386":0,"data_16392":11,"data_16396":8961,"linkquality":255,"local_temperature":19.87,"local_temperature_calibration":0.1,"occupied_heating_setpoint":24,"pi_heating_demand":10,"programming_operation_mode":"setpoint","remote_sensing":{"local_temperature":"internally","occupancy":"remotely","outdoor_temperature":"internally"},"running_state":"heat","system_mode":"off","valve_position":2}'
debug 2022-04-05 20:23:50: Received MQTT message on 'zigbee2mqtt/Radiator badkamer/set' with data '{"read":{"attributes":[16385,16386,16392,16396],"cluster":"hvacThermostat","options":{"manufacturerCode":4466}}}'
debug 2022-04-05 20:23:50: Publishing 'set' 'read' to 'Radiator badkamer'
debug 2022-04-05 20:23:57: Received Zigbee message from 'Radiator badkamer', type 'readResponse', cluster 'hvacThermostat', data '{"16385":25,"16386":0,"16392":11,"16396":8961}' from endpoint 1 with groupID null
info  2022-04-05 20:23:57: MQTT publish: topic 'zigbee2mqtt/Radiator badkamer', payload '{"battery":100,"control_sequence_of_operation":"heating_only","data_16386":0,"data_16392":11,"data_16396":8961,"linkquality":255,"local_temperature":19.87,"local_temperature_calibration":0.1,"occupied_heating_setpoint":24,"pi_heating_demand":10,"programming_operation_mode":"setpoint","remote_sensing":{"local_temperature":"internally","occupancy":"remotely","outdoor_temperature":"internally"},"running_state":"heat","system_mode":"off","valve_position":25}'
info  2022-04-05 20:23:57: Read result of 'hvacThermostat': {"16385":25,"16386":0,"16392":11,"16396":8961}
```

**Comment by Koenkk** [comment]
To trigger that converter you have to send to `zigbee2mqtt/Radiator badkamer/set` payload `{"valve_position":""}` (I don't see that in your log)

**Comment by vhdirk** [comment]
@JanJaapKo After some more sniffing I haven't really found anything super interesting.
I did find:

*Push force*:
attribute: 0x4012
values: [0, 0x60000, 0x70000]

*Radio strength*:
attribute: 0x4014
values: [false, true]

*Calibrate*:
command: 0x0a

I can also clearly see that the Adam never sends valve positions higher than 100 (0x64). If I send values between 100 and 254 it doesn't respond reliably but at 255 it starts opening up all the way. Not sure why that is. 
So I still need to fix the piHeatingDemand response mapping so it uses decimal 0 - 100.

I'm hoping you still get a reaction from Plugwise so we can have this more complete. I'm not sure yet how to map these 3 new things I found.

@Koenkk is there some way we can post all of the unknown commands to mqtt without having to create specific fields like @JanJaapKo did here? https://github.com/Koenkk/zigbee-herdsman-converters/pull/4046#issuecomment-1085017293.

**Comment by JanJaapKo** [comment]
Yep, one step further:

<html>
<body>
<div dir="ltr" style="color: rgb(34, 34, 34); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Attribute | Attribute Id | Default | Data | Read/Write (R/W) | Mandatory/ | Manufacturer Specific | Reportable
-- | -- | -- | -- | -- | -- | -- | --
Value | type | Optional (M/O) | (Y/N) | (Y/N)
Status | 0x4002 | Read from MSP Status | 0x20 (int8u) | R | O | Y | N
T_Diff | 0x4008 | Read from MSP Status | 0x28 (int8s) | R | O | Y | N

</div><div dir="ltr" style="color: rgb(34, 34, 34); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div>​<br></div><div dir="ltr">Status: This read-only manufacturer specific attribute represents the MSP Status byte </div><div dir="ltr">T_diff: This read-only manufacturer specific attribute represents the 8-bit T_diff value returned in the MSP Status request. </div><span class="im" style="color: rgb(80, 0, 80);"><div> </div></span></div>
</body>
</html>

I've asked for the explanation of the status bits (or to send me the complete doc set ;) )

The t_diff suggests that some kind of setpoint should be able to be used but no info on that so far.

**Comment by vhdirk** [comment]
Thanks for the update!
I've just pushed some changes to use piHeatingDemand and valve position between 0 and 100. I'm just going to ignore that it can take values up to 255.

Do you know what they mean with MSP Status? I would assume that MSP is just an abbreviation for Manufacturer SPecific, which tells us exactly nothing.

I'll try to get these responses and the other discovered attributes in as well.

As far as the legacy stuff is concerned: I don't need that at all. In fact, I don't even know what the difference is between the 'normal' track and legacy. I just implemented that for completeness' sake.

**Comment by vhdirk** [comment]
@JanJaapKo I've added controls for push force and radio strength.

@Koenkk How do I send a custom command (other than attribute read/write) without payload? Calibration seems triggered with a command 0xa0.

**Comment by Koenkk** [comment]
@vhdirk it first has to be added to the clusters commands in https://github.com/Koenkk/zigbee-herdsman/blob/master/src/zcl/definition/cluster.ts . You can find this file locally under `ZIGBEE2MQTTDIR/node_modules/zigbee-herdsman/dist/zcl/definition/cluster.js`

**Comment by JanJaapKo** [comment]
I've been trying to read out all attributes from 4000 to 4016 (assuming all usefull stuff would be around that range) and found the below:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/nljkos/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/nljkos/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Attribute   [hex] | Attribute [dec] | read result |  
-- | -- | -- | --
4000 | 16384 | unsupported |  
4001 | 16385 | 250 | valve position
4002 | 16386 | 0 | MSP status
4003 | 16387 | unsupported |  
4004 | 16388 | unsupported |  
4005 | 16389 | 20 | local temp?
4006 | 16390 | unsupported |  
4007 | 16391 | unsupported |  
4008 | 16392 | 11 | t_diff
4009 | 16393 | unsupported |  
400a | 16394 | unsupported |  
400b | 16395 | unsupported |  
400c | 16396 | 8961 | ?
400d | 16397 | unsupported |  
400e | 16398 | unsupported |  
400f | 16399 | unsupported |  
4010 | 16400 | unsupported |  
4011 | 16401 | 100 | battery?
4012 | 16402 | 0 | push force
4013 | 16403 | 1 | radio strength?
4014 | 16404 | unsupported |  
4015 | 16405 | unsupported |  
4016 | 16406 | unsupported |  



</body>

</html>

**Comment by JanJaapKo** [comment]
@vhdirk You can send a command without data the same way as with data but have to set the datatype to 0x00 for no data (see page 85 of https://zigbeealliance.org/wp-content/uploads/2019/12/07-5123-06-zigbee-cluster-library-specification.pdf

**Comment by vhdirk** [comment]
@JanJaapKo I still have to verify the radio strength command. Other than that, I think we're done here.

**Comment by Koenkk** [comment]
@vhdirk let me know once it is ready for merge.

**Comment by vhdirk** [comment]
@JanJaapKo I checked again: push force is indeed 0x4012, not 0x4014. I even had it written down as such.

**Comment by vhdirk** [comment]
@JanJaapKo I also tried with battery power just now. Stil 0x4014

**Comment by JanJaapKo** [comment]
OK so I've received the functional specification of the Tom. The helpdesk guy already mentioned that it may be out dated (makes one wonder about the internal processes at Plugwise, but OK. Get the feeling that SW development has been outsourced there). It describes the Zigbee clusters, but in the mail they state that the internal PID control of the valve using a temperature setpoint did not work properly so is no longer supported. The below figure is quite interesting though:

image

So the t_diff could be between water temperature and room temperature or something? Could be interesting in a self-built controller to asses if there is actually heat in the system.

Another interesting thing in the document is the fact that it describes that OTA updates are supported but when using z2m frontend all attributes I try to query return 'UNSUPPORTED_ATTRIBUTE'. The z2m front end indicates for me a firmware date of 28-07-2015.......

I've asked them to try to find out the meaning of the MSP status bits, as that seems the most missing part for now.....

btw @vhdirk can you update toZigbee.js to the below? It makes z2m to read back the valve position on 4001 after it has been sent. In Domoticz this acknowledgement is needed to have the front end updated.

```
    plugwise_valve_position: {
        key: ['plugwise_valve_position', 'valve_position'],
        convertSet: async (entity, key, value, meta) => {
            const payload = {0x4001: {value, type: 0x20}};
            await entity.write('hvacThermostat', payload, manufacturerOptions.plugwise);
			// Tom does not automatically sends beack updated value so ask for it
            await entity.read('hvacThermostat', [0x4001], manufacturerOptions.plugwise);
        },
        convertGet: async (entity, key, meta) => {
            await entity.read('hvacThermostat', [0x4001], manufacturerOptions.plugwise);
        },
    },

```

**Comment by JanJaapKo** [comment]
Well, latest mail from Plugwise:

> Beste Jan-Jaap,
De MSP status wordt intern gebruikt voor debugging en heeft voor jou geen nut om uit te lezen.

Right, I'll be the judge of that...... Anyway, don't count on any info, let's ignore the MSP status and stick to the fields found so far.

**Comment by vhdirk** [comment]
@JanJaapKo Thanks for all the info.
I've added the reporting bits to toZigbee.js. 
The only thing that's still weird to me is that you found radio_strength to be a different attribute than I have?

**Comment by JanJaapKo** [comment]
@vhdirk As far as I can see this PR is working. Shall it be merged? I haven't gotten the time yet to figure out the radio strength, but I consider that as beyond nice to have ;)

**Comment by vhdirk** [comment]
@Koenkk ready for merging! Finally!

**Comment by Koenkk** [comment]
@vhdirk great, I've merged everything into the `plugwise.js` file and removed the legacy since converter (since we don't want to add any new legacy converters). Could you do a final check?

**Comment by vhdirk** [comment]
Thanks! I haven't had much time lately. Looks good to me!

**Comment by Koenkk** [comment]
great, thanks!

**Pull request merged**
