### PR TITLE
State mapping change - for TZE200_dv8abrrz thermostat

### PR DESCRIPTION
**Pull request by kowalczykrafal**
My proposed change to "Add system mode support for TZE200_dv8abrrz thermostat # 4861."
In Home Assitant, when using the schedule plugin (https://github.com/nielsfaber/scheduler-card), when the automatic mode is selected, there is no temperature setting, which makes it difficult to use this plugin.
My change is to add state_mode -> emergency_heating.
Now:
- mapping 'heat' system mode to manual (same as preset 'MANUAL')
- mapping 'auto' system mode to auto (same as preset 'AUTO')
- mapping 'off' system mode to off (same as preset 'OFF')
- mapping 'emergency_heating' system mode to on (same as preset 'ON')

### CODE REVIEW

**Comment by kowalczykrafal** [comment]
@muddy79 what do you think about it?

**Comment by muddy79** [comment]
@kowalczykrafal I'm not a decision maker, just my two cents... 

It's hard for me to judge, since I'm not using Scheduler plugin. However, my previous change was to make this device functionally compatible with other TuYa thermostat: as far as I noticed, all others map "HEAT" system mode to 100% heating, so it made sense to map this  to preset "ON" of this device. I was not even aware of the "EMERGENCY HEATING" system mode before and I am not sure it's visible in the standard lovelace thermostat entity as a button.

We can discuss if "AUTO" system mode should be mapped to "MANUAL" preset or "AUTO" preset. I've decided to propose "MANUAL", since it's the only one which is usable at the moment, since "AUTO" preset means the device uses it's internal schedule (and - I guess - it's a different one which is defined using the plugin you've mentioned above), while it's not yet possible to set it up from HA/Z2M (fix me if I'm wrong). But, I guess, it's not relevant to your issue.

Anyway, we need @Koenkk  to step in and make a final decision , maybe your fix makes sense, but probably it means we should fix all other thermostats and change the meaning of mode HEAT to the "manual" temperature setting, "EMERGENCY HEATING" to 100% heating and AUTO to use internal schedule...  Or maybe the scheduler plugin should be adjusted to allow the temperature setting for AUTO mode / or PRESET selection mode? 

PS. I've just installed Scheduler plugin and played a bit with both: TZE200_dv8abrrz and _TZE200_ckud7u2l. The behavior is the same: if you schedule HEAT and set the temperature, the actual action is to enable 100% heating on both at the moment...

**Comment by kowalczykrafal** [comment]
@muddy79 below is my external_converters:
`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const haozee_thermostat_dev = {
       cluster: 'manuSpecificTuya',
       type: ['commandDataResponse', 'commandDataReport'],
       convert: (model, msg, publish, options, meta) => {
           const dpValue = tuya.firstDpValue(msg, meta, 'haozee_thermostat');
           const dp = dpValue.dp; // First we get the data point ID
           const value = tuya.getDataValue(dpValue);
           const presetLookup = {0: 'auto', 1: 'manual', 2: 'off', 3: 'on'};
           const systemModeLookup = {0: 'auto', 1: 'heat', 2: 'off', 3: 'emergency_heating'};
           switch (dp) {
           case tuya.dataPoints.haozeeSystemMode:
               return {preset: presetLookup[value], system_mode: systemModeLookup[value]};
           case tuya.dataPoints.haozeeHeatingSetpoint:
               return {current_heating_setpoint: (value / 10).toFixed(1)};
           case tuya.dataPoints.haozeeLocalTemp:
               return {local_temperature: (value / 10).toFixed(1)};
           case tuya.dataPoints.haozeeBoostHeatingCountdown:
               // quick heating countdown - not supported by this device
               return {boost_heating_countdown: value};
           case tuya.dataPoints.haozeeWindowDetection:
               // window check
               return {window_detection: value ? 'ON' : 'OFF'};
           case tuya.dataPoints.haozeeWindowState:
               // window state
               return {window: value ? 'OPEN' : 'CLOSED'};
           case tuya.dataPoints.haozeeChildLock:
               return {child_lock: value ? 'LOCK' : 'UNLOCK'};
           case tuya.dataPoints.haozeeBattery:
               // battery
               return {battery: value};
           case tuya.dataPoints.haozeeFaultAlarm:
               return {error: value ? 'ON': 'OFF'};
           case tuya.dataPoints.haozeeScheduleMonday:
               // Monday
               return {
                   'monday_schedule': ' ' + value[1] + 'h:' + value[2] + 'm ' + value[4] / 10 + '°C' +
                       ',  ' + value[5] + 'h:' + value[6] + 'm ' + value[8] / 10 + '°C' +
                       ',  ' + value[9] + 'h:' + value[10] + 'm ' + value[12] / 10 + '°C' +
                       ',  ' + value[13] + 'h:' + value[14] + 'm ' + value[16] / 10 + '°C ',
               };
           case tuya.dataPoints.haozeeScheduleTuesday:
               // Tuesday
               return {
                   'tuesday_schedule': ' ' + value[1] + 'h:' + value[2] + 'm ' + value[4] / 10 + '°C' +
                       ',  ' + value[5] + 'h:' + value[6] + 'm ' + value[8] / 10 + '°C' +
                       ',  ' + value[9] + 'h:' + value[10] + 'm ' + value[12] / 10 + '°C' +
                       ',  ' + value[13] + 'h:' + value[14] + 'm ' + value[16] / 10 + '°C ',
               };
           case tuya.dataPoints.haozeeScheduleWednesday:
               // wednesday
               return {
                   'wednesday_schedule': ' ' + value[1] + 'h:' + value[2] + 'm ' + value[4] / 10 + '°C' +
                       ',  ' + value[5] + 'h:' + value[6] + 'm ' + value[8] / 10 + '°C' +
                       ',  ' + value[9] + 'h:' + value[10] + 'm ' + value[12] / 10 + '°C' +
                       ',  ' + value[13] + 'h:' + value[14] + 'm ' + value[16] / 10 + '°C ',
               };
           case tuya.dataPoints.haozeeScheduleThursday:
               // Thursday
               return {
                   'thursday_schedule': ' ' + value[1] + 'h:' + value[2] + 'm ' + value[4] / 10 + '°C' +
                       ',  ' + value[5] + 'h:' + value[6] + 'm ' + value[8] / 10 + '°C' +
                       ',  ' + value[9] + 'h:' + value[10] + 'm ' + value[12] / 10 + '°C' +
                       ',  ' + value[13] + 'h:' + value[14] + 'm ' + value[16] / 10 + '°C ',
               };
           case tuya.dataPoints.haozeeScheduleFriday:
               // Friday
               return {
                   'friday_schedule': ' ' + value[1] + 'h:' + value[2] + 'm ' + value[4] / 10 + '°C' +
                       ',  ' + value[5] + 'h:' + value[6] + 'm ' + value[8] / 10 + '°C' +
                       ',  ' + value[9] + 'h:' + value[10] + 'm ' + value[12] / 10 + '°C' +
                       ',  ' + value[13] + 'h:' + value[14] + 'm ' + value[16] / 10 + '°C ',
               };
           case tuya.dataPoints.haozeeScheduleSaturday:
               // Saturday
               return {
                   'saturday_schedule': ' ' + value[1] + 'h:' + value[2] + 'm ' + value[4] / 10 + '°C' +
                       ',  ' + value[5] + 'h:' + value[6] + 'm ' + value[8] / 10 + '°C' +
                       ',  ' + value[9] + 'h:' + value[10] + 'm ' + value[12] / 10 + '°C' +
                       ',  ' + value[13] + 'h:' + value[14] + 'm ' + value[16] / 10 + '°C ',
               };
           case tuya.dataPoints.haozeeScheduleSunday:

               // Sunday
               return {
                   'sunday_schedule': ' ' + value[1] + 'h:' + value[2] + 'm ' + value[4] / 10 + '°C' +
                       ',  ' + value[5] + 'h:' + value[6] + 'm ' + value[8] / 10 + '°C' +
                       ',  ' + value[9] + 'h:' + value[10] + 'm ' + value[12] / 10 + '°C' +
                       ',  ' + value[13] + 'h:' + value[14] + 'm ' + value[16] / 10 + '°C ',
               };

           case tuya.dataPoints.haozeeRunningState:
               // working status 0 - pause 1 -working
               return {'heating': value ? 'ON' : 'OFF'};
           case tuya.dataPoints.haozeeBoostHeating:
               // rapid heating -> boolean - not supported by this device
               return {'boost_heating': value ? 'ON' : 'OFF'};
           case tuya.dataPoints.haozeeTempCalibration:
               // temperature calibration
               return {'local_temperature_calibration': ( value/10 ).toFixed(1)};
           case tuya.dataPoints.haozeeValvePosition:
               // valve position
               return {'position': ( value/10 ).toFixed(1)};
           case tuya.dataPoints.haozeeMinTemp:
               // lower limit temperature
               return {'min_temperature': ( value/10 ).toFixed(1)};
           case tuya.dataPoints.haozeeMaxTemp:
               // max limit temperature
               return {'max_temperature': ( value/10 ).toFixed(1)};
           case tuya.dataPoints.haozeeSoftVersion:
               // software
               break;
           default:
               meta.logger.warn(`zigbee-herdsman-converters:haozee: NOT RECOGNIZED DP #${
                   dp} with data ${JSON.stringify(dpValue)}`);
           }
       },
   };

module.exports = haozee_thermostat_dev;

const haozee_thermostat_preset_dev = {
       key: ['preset'],
       convertSet: async (entity, key, value, meta) => {
          const lookup = {'auto': 0, 'manual': 1, 'off': 2, 'on': 3};
           await tuya.sendDataPointEnum(entity, tuya.dataPoints.haozeeSystemMode, lookup[value]);
       },
   };

module.exports = haozee_thermostat_preset_dev;

const haozee_thermostat_system_mode_dev = {
        key: ['system_mode'],
        convertSet: async (entity, key, value, meta) => {
            // mapping 'heat' system mode to manual (same as preset 'MANUAL')
            // mapping 'auto' system mode to auto (same as preset 'AUTO')
            // mapping 'off' system mode to off (same as preset 'OFF')
            const lookup = {'auto': 0, 'heat': 1, 'off': 2, 'emergency_heating': 3};
            await tuya.sendDataPointEnum(entity, tuya.dataPoints.haozeeSystemMode, lookup[value]);
        },
    };

module.exports = haozee_thermostat_system_mode_dev;

const mytehrmostat =
{
      fingerprint: [
    {modelID: 'TS0601', manufacturerName: '_TZE200_a4bpgplm'},
    {modelID: 'TS0601', manufacturerName: '_TZE200_dv8abrrz'},
  ],
      model: 'TS0601_thermostat_1',
      vendor: 'TuYa',
      description: 'Thermostatic radiator valve',
      whiteLabel: [
          {vendor: 'Unknown/id3.pl', model: 'GTZ06'},
      ],
      onEvent: tuya.onEventSetLocalTime,
      fromZigbee: [fz.ignore_basic_report, fz.ignore_tuya_set_time, haozee_thermostat_dev],
      toZigbee: [
          haozee_thermostat_system_mode_dev, tz.haozee_thermostat_current_heating_setpoint, tz.haozee_thermostat_boost_heating,
          tz.haozee_thermostat_boost_heating_countdown, tz.haozee_thermostat_window_detection,
          tz.haozee_thermostat_child_lock, tz.haozee_thermostat_temperature_calibration, tz.haozee_thermostat_max_temperature,
          tz.haozee_thermostat_min_temperature,haozee_thermostat_preset_dev
      ],
      exposes: [
          e.battery(), e.child_lock(), e.max_temperature(), e.min_temperature(),
          e.position(), e.window_detection(),
          exposes.binary('window', ea.STATE, 'CLOSED', 'OPEN').withDescription('Window status closed or open '),
          exposes.binary('heating', ea.STATE, 'ON', 'OFF').withDescription('Device valve is open or closed (heating or not)'),
          exposes.climate()
              .withLocalTemperature(ea.STATE).withSetpoint('current_heating_setpoint', 5, 35, 0.5, ea.STATE_SET)
              .withLocalTemperatureCalibration(-30, 30, 0.1, ea.STATE_SET).withPreset(['auto', 'manual', 'off', 'on'],
                  'MANUAL MODE ☝ - In this mode, the device executes manual temperature setting. ' +
                  'When the set temperature is lower than the "minimum temperature", the valve is closed (forced closed). ' +
                  'AUTO MODE ⏱ - In this mode, the device executes a preset week programming temperature time and temperature. ' +
                  'ON - In this mode, the thermostat stays open ' +
                  'OFF - In this mode, the thermostat stays closed')
              .withSystemMode(['auto', 'heat', 'off', 'emergency_heating'], ea.STATE_SET),
          exposes.composite('programming_mode').withDescription('Auto MODE ⏱ - In this mode, ' +
                  'the device executes a preset week programming temperature time and temperature. ')
              .withFeature(exposes.text('monday_schedule', ea.STATE))
              .withFeature(exposes.text('tuesday_schedule', ea.STATE))
              .withFeature(exposes.text('wednesday_schedule', ea.STATE))
              .withFeature(exposes.text('thursday_schedule', ea.STATE))
              .withFeature(exposes.text('friday_schedule', ea.STATE))
              .withFeature(exposes.text('saturday_schedule', ea.STATE))
              .withFeature(exposes.text('sunday_schedule', ea.STATE)),
          exposes.binary('boost_heating', ea.STATE_SET, 'ON', 'OFF').withDescription('Boost Heating: press and hold "+" for 3 seconds, ' +
              'the device will enter the boost heating mode, and the ▷╵◁ will flash. The countdown will be displayed in the APP'),
          exposes.numeric('boost_heating_countdown', ea.STATE_SET).withUnit('min').withDescription('Countdown in minutes')
              .withValueMin(0).withValueMax(1000),
      ],
  };

module.exports = mytehrmostat;
`
You can try it. You are right that in "EMERGENCY HEAT" mode it is not mapped correctly in HA. In the standard lovelace thermostat is not visible as a button. But in the Scheduler plugin there is. ;)

**Comment by Koenkk** [comment]
Is this a breaking change?

**Comment by muddy79** [comment]
@Koenkk in my opinion, it "breaks" the compatibility with the standard HA lovelace Thermostat card and makes the device "different" than other TuYa thermostats (by changing meaning of HEAT mode from 100% heat to manually set temperature), but it makes it usable for the schedule plugin (while other thermostats are still not really usable). My proposal is to rather contact schedule plugin maintainer, to allow setting the desired temperature for AUTO mode. But, as I said before, I'm not an expert...

**Comment by Koenkk** [comment]
> My proposal is to rather contact schedule plugin maintainer, to allow setting the desired temperature for AUTO mode

I agree with this. The impact is too big to justify fixing this just for a specific HA plugin.

**Comment by kowalczykrafal** [comment]
Thanks guys  ;)
I add Feature request.
https://github.com/nielsfaber/scheduler-card/issues/617

**Comment by kowalczykrafal** [comment]
Hi,
Guys is the answer on https://github.com/nielsfaber/scheduler-card/issues/617.
If @Koenkk you think that is too big impact - close this pull request.
My suggestion is that it is worth thinking about it in the future and doing something about it.

**Comment by kowalczykrafal** [comment]
Let's think about it again. My opinion:
Auto - scheduler in the thermostat without the influence of external automation,
Heat - heating to a set temperature - e.g. from external automatics,
On - 100% valve opening - set temperature has no effect
Off - is off.
In system_mode we only have 3 options.
I'm not an expert but mapping system_mode auto to preset manual seems to be wrong. System_mode Heat is preset on as well.
Regardless of everything, at the moment I use my solution as external_converters.
I hope this problem will be solved and I will be able to return to the standard configuration.

**Comment by muddy79** [comment]
I only have experience with TuYa TS0601 and - now this new device, which I bought to replace one of my broken TS0601, so I just followed what I am aware of. If this is not compatible with the HA rulebook, it should probably be changed for all TuYa devices.
PS. Following the HA docs, EMERGENCY_HEAT mode is also not allowed, since system modes are strictly pre-defined…

**Comment by kowalczykrafal** [comment]
I have now purchased all TuYa TS0601s and have noticed strange behavior. I thought it was supposed to be like that, but something did not work for me, so I decided to propose something.
@ muddy79 you are right about the EMERGENCY_HEAT mode. As I wrote above, mode 4 is missing in simple_mode. Adding this mode to simply_mode in TuYa TS0601 is just a loose suggestion.
At the moment, EMERGENCY_HEAT is not used in my home automation.

**Pull request closed without merging**
